### ISSUE TITLE
Deploy Your First SAPUI5 App

### ISSUE THREAD

**Issue by whdinata** [sap-tutorials/Tutorials#13947]
Tutorials: https://developers.sap.com/tutorials/appstudio-sapui5-create.html
--------------------------

I have found the tutorial is not quite accurate. Step 4 can't be done because the deployment config is not generated even after following Step 3. Running npm run deploy-config is needed to generate the config file.

**Comment by cjbernal** [comment]
Hi there,

Sorry to hear that you are having an issue. I am currently reaching out to a member of  the product team to further assist you. Thank you for your patience. 

Kind regards,
Conrad (SAP UX Engineering)

**Comment by longieirl** [comment]
Hi,
Can you please re-run the steps again ensuring you have selected `Yes` to `Add deployment configuration`. This step generates the mta.yaml to allow you deploy the application to CF. This flow calls the same logic as the deploy-config command. 
Assuming you are on Business Application Studio, when repeating the steps, ensure you enable the output tab by selecting View - Output - Application Wizard.Templates. If there is any issue with the generation of the application or the mta.yaml it should output here.
Please let me know how you get.
Thanks.
John

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
