### ISSUE TITLE
Create A New Welcome Card - The Registration in Mobile app is failing after creating welcome card

### ISSUE THREAD

**Issue by FarozanFarman** [sap-tutorials/Tutorials#17985]
Tutorials: https://developers.sap.com/tutorials/cp-mobile-cards-welcome.html
--------------------------

Hello,

Step 3: View card on your mobile device:
7. Enter your SAP BTP credentials and tag Log On:
The registration of the mobile application is failing after creating the First Mobile card in both US and AP Region
After scanning the QR generated for registering the mobile device, and entering credentials,it gives the error: Registration Failed
Please refer to the screenshot:
![image](https://user-images.githubusercontent.com/71028764/148911980-1a1f84c7-aaff-4e26-9bfc-0b39ad9ec6a6.png)
Labels to be attached:
Sprint Label: SCPTest-2201A
Prio: high-prio
Scenario label: SCPTest-mcard
Landcape Label: trial2, trial3, 

Thanks,
Farozan

**Comment by SamiLechner** [comment]
Hi @FarozanFarman 
We have fixed the issue. The Fix should be in production by EoD today. please retest and let us know the results
