### ISSUE TITLE
Configure Business Rules, Workflow and Process Visibility

### ISSUE THREAD

**Issue by I559299** [sap-tutorials/Tutorials#17987]
Tutorials: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-2-configure.html
--------------------------

Step 4: Deploy business rules : Step 3: After clicking on deploy getting below error and its unable to deploy rule services

<img width="657" alt="image" src="https://user-images.githubusercontent.com/95752943/148909459-843e6337-2cff-45ea-8bd4-e57d993058ed.png">

Labels to be added:
Scenario label:SCPTest-eboard
Sprint Label: SCPTest-2201A
Landscape Label: trial2, trial3

**Comment by BaskarThambiayah** [comment]
Hi Colleagues,
Greetings!
This scenario is part of Global SAP D-kom Live Coding Space which is planned on 18th, 19th and 20th of Jan 2022. Currently this issue is the blocker to execute this scenario. So kindly request you to take it as very high priority and resolve this issue and make the system ready as soon as possible.

Many thanks & regards,
Baskar

**Comment by ArchanaShukla** [comment]
Hello Baskar, 
This is was due to recent changes in the product which was not informed upfront. I will make the changes and upload the new version in API  Hub by today. Will keep you informed.

**Comment by BaskarThambiayah** [comment]
Hi Archana,
Thank you so much for your swift response and the timely action you have taken to resolve this issue.

**Comment by ArchanaShukla** [comment]
Hello Baskar, 
An update: there are some minor issues in publishing the package to API Hub. API Hub team is working on the fix, we have  plans to publish the updated package by today.

**Comment by ArchanaShukla** [comment]
Hello Baskar,
The changes are published now. Please run the scenario and check.

**Comment by BaskarThambiayah** [comment]
Hi Archana,
Many thanks for your effort in bringing this scenario to work. I have done the retest now and the scenario is working fine. I could able to complete this scenario successfully. Thanks again.
Kind regards,
Baskar
