### ISSUE TITLE
Configure Your AppGyver Application to Open your Device Camera

### ISSUE THREAD

**Issue by gopalanand333** [sap-tutorials/Tutorials#17983]
Tutorials: https://developers.sap.com/tutorials/appgyver-configure-camera.html
--------------------------

Write here how you think we can improve the tutorial ...
The tutorial asks for scan a barcode, where Is the barcode?

**Comment by heytombeck** [comment]
Hello - sorry for the delay here, appreciate you've been waiting a long time for a response. The barcode is something you need to supply yourself - it should work for any barcode printed on food or drink packaging. In my example, I scanned the barcode for some chocolate that I'd bought.
