### ISSUE TITLE
Get an Account on SAP BTP to Try Out Free Tier Service Plans

### ISSUE THREAD

**Issue by dsimov** [sap-tutorials/Tutorials#18001]
Tutorials: https://developers.sap.com/tutorials/btp-free-tier-account.html
--------------------------

Step 3: Add personal details is advising users to select the Purchase as an individual option. Note that this option works in a limited number of countries. For example, when I am located in Bulgaria, I cannot register as an individual. I get a message that says "This solution is not currently available for individual purchase in your country/region." 

See my detailed report on trying free tier https://sap-my.sharepoint.com/:w:/p/dimiter_simov/EfrTNxssDpJAmdqvlrjpz9sBnlKfgjiz8Jcf5y7MJY3fyA, section Part1: Signing Up > SAP Store > Company Details.

**Comment by AnnikaGonnermann** [comment]
Dear @dsimov - thanks very much for your feedback which I have forwarded to the respective colleagues. They will have a very detailed look at it and apply wherever possible your recommendations for improvement! 

Thanks once again,
Annika
