### ISSUE TITLE
Use SAP HANA as the Database for a CAP Java Application

### ISSUE THREAD

**Issue by Nil300** [sap-tutorials/Tutorials#18008]
Tutorials: https://developers.sap.com/tutorials/cp-cap-java-hana-db.html
--------------------------

I am stuck on Step 3: Deploy database artifacts to SAP HANA. I am getting an error when creating service Hana hdi-shared bookstore-Hana. it says The plan hdi-shared could not be found for service hanatrial.

![image](https://user-images.githubusercontent.com/48037687/149422848-d7e2c83b-ef74-44d7-a853-af0ff9909373.png)

do you have any idea how I can fix this error?

you can reach me at niravkumar.surti@sap.com

**Comment by dhirschbach** [comment]
Hi all,
Manual creation of SAP HANA database in SAP BTP cockpit could solve the issue, capable to complete this [tutorial](https://developers.sap.com/tutorials/cap-service-deploy.html) yesterday:

1. Logon to SAP BTP Cockpit trial account
2. Click on Subaccount "trial"
3. Click on Spaces "dev"
4. Click on "SAP HANA Cloud"
5. Click on "Create"
6. Click on "SAP HANA database"
7. Click on "SAP HANA Cloud, SAP HANA Database" (other data lake possible too, not tested in this scenario)
8. Click on "Next step"
9. Choose Instance name, e.g. "<trialaccountname>hub"
10. Choose SAP HANA Database Password
11. Click on "Next step", click on "Next step", click on "Review and Create", confirm last button before creation db
12. Wait for database status "running"
13. Execute on local environment: `cf create-service hana hdi-shared my-bookshop-db` -> worked for me

**Comment by dhirschbach** [comment]
Hi all,
Manual creation of SAP HANA database in SAP BTP cockpit could solve "no database available", faced and capable to fix in tutorial **Business Application Using CAP for Node.js** https://developers.sap.com/tutorials/cap-service-deploy.html yesterday:

1. Logon to SAP BTP Cockpit trial account
2. Click on Subaccount "trial"
3. Click on Spaces "dev"
4. Click on "SAP HANA Cloud"
5. Click on "Create"
6. Click on "SAP HANA database"
7. Click on "SAP HANA Cloud, SAP HANA Database" (please test data lake too)
8. Click on "Next step"
9. Choose Instance name, e.g. "<trialaccountname>hub"
10. Choose SAP HANA Database Password
11. Click on "Next step", click on "Next step", click on "Review and Create", confirm last button before creation db
12. Wait for database status "running"
13. Execute on local environment: `cf create-service hana hdi-shared my-bookshop-db`
14. Proceed tutorial

**Comment by beckermarc** [comment]
Are you using a SAP BTP Trial account as described in the first part of the tutorial: https://developers.sap.com/tutorials/appstudio-onboarding.html ?

You can also try to create your own HANA trial instance in your `dev` space as described here: https://developers.sap.com/tutorials/hana-cloud-mission-trial-2.html
After that you should be able to create HDI containers with the hana service, like `cf create-service hana hdi-shared bookstore-hana`.

**Comment by beckermarc** [comment]
I just checked and also for me the hanatrial hdi-shared service is no longer offered for a newly created trial account on the US landscape. Looks like creating your own HANA instance is now a prerequisite to create HDI containers in a trial account.
Please try to follow the second tutorial link that I provided and confirm that after following these steps you can run the `cds deploy --to hana:bookstore-hana` command successfully.

**Comment by Nil300** [comment]
> I just checked and also for me the hanatrial hdi-shared service is no longer offered for a newly created trial account on the US landscape. Looks like creating your own HANA instance is now a prerequisite to create HDI containers in a trial account. Please try to follow the second tutorial link that I provided and confirm that after following these steps you can run the `cds deploy --to hana:bookstore-hana` command successfully.

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/48037687/150516213-a0087d9c-a243-483c-9e78-eb6bf6490f89.png)

yes, this is working but with that also getting error which can be solved to give with a different name "cds deploy --to hana:bookstore-hana1"
