### ISSUE TITLE
Create Calculation View and Expose via CAP (SAP HANA Cloud)

### ISSUE THREAD

**Issue by ahmedkhan29789** [sap-tutorials/Tutorials#18007]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-cap-calc-view.html
--------------------------

After creating calculation view when i am trying to get the entity already defined in my schema.cds I am getting below error, I also relogin multiple times to BAS but still same error.

![image](https://user-images.githubusercontent.com/22063881/149391027-a5bd5bbf-e26f-4f48-b157-545b7dbdb4a8.png)

**Comment by jung-thomas** [comment]
You need to login in again to Cloud Foundry.  This was step 2 of an earlier tutorial in this mission:
https://developers.sap.com/tutorials/hana-cloud-cap-create-project.html#77f7b1f9-8ac0-4f21-a25d-f942cd7ac044

Your login is only good for one day and has to be repeated each day.  So if you don't complete the mission in a single day you do need to login again at whatever point you cross over into a new day.

**Comment by ahmedkhan29789** [comment]
Did you mean, I need to login via terminal using "cf login"?

I will try this and let you know

**Comment by jung-thomas** [comment]
You certainly can log via the terminal and the cf login command. But you can also use the steps in the link provided and login via the Cloud Foundry Targets UI in BAS from the earlier tutorial.

**Comment by ahmedkhan29789** [comment]
Ok So I have tried after relogin to my cloud foundry, Now the chages to this
![image](https://user-images.githubusercontent.com/22063881/149421693-13df43dd-2036-4e77-a70b-d7603d82bde7.png)

**Comment by jung-thomas** [comment]
That error indicates that already logged into cf, it isn't returning an organization. You are successfully logged into cf and targeting an organization?  
Perhaps try doing a "cf target" from the command line to make sure that an org is returned from the cli.

**Comment by ahmedkhan29789** [comment]
yes cf target gives me right result and still i have this error
![image](https://user-images.githubusercontent.com/22063881/149566567-bd7e1fff-b398-4d4a-8c78-a08d73bdc4a9.png)

**Comment by jung-thomas** [comment]
I'm assuming you've both closed and re-opened the Calculation View editor and perhaps even reloaded the BAS window in total after doing the cf login?  Those are the only troubleshooting I can suggest - that perhaps it's not picking up the fresh login totally. 

I just tested the whole tutorial now and it worked fine. 
![image](https://user-images.githubusercontent.com/12159356/149575301-7330a2f9-8367-40a5-bb1e-428a44854ede.png)

I suggest entering a support ticket then. I really don't believe there is anything wrong in the tutorial itself. You seem to be encountering some sort of bug in the Calculation View editor itself which I couldn't replicate.
