### ISSUE TITLE
Deploy Your Business Application to Cloud Foundry

### ISSUE THREAD

**Issue by vgup** [sap-tutorials/Tutorials#18013]
Tutorials: https://developers.sap.com/tutorials/appstudio-cap-deploy-app.html
--------------------------

Write here how you think we can improve the tutorial ...

In the bind hana instance step..

Deployment ended at 2022-01-16 16:39:26

Error: invalid schema name: USR_26MQ3N9IPYOIE8ATU6SILMLJA#DI: line 1 col 37 (at pos 36)

(0s 769ms)

[ERROR] [cds.deploy] - HDI deployment failed with exit code 1

**Comment by Paolaufer** [comment]
Hi,
It seems the deployment has failed. This is probably something with the instance they you using (if you followed all the other steps). You can use another clean instance. 
Please take a look at this troubleshooting guide: https://cap.cloud.sap/docs/advanced/troubleshooting#how-do-i-resolve-deployment-errors

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
