### ISSUE TITLE
Create a Directory for Development

### ISSUE THREAD

**Issue by mattj239** [sap-tutorials/Tutorials#18010]
Tutorials: https://developers.sap.com/tutorials/btp-app-create-directory.html
--------------------------

Step 5.5
cp -r .gitignore $(ls -1A | grep -v .git) ../cpapp is giving me an error: 

grep : The term 'grep' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included,     
verify that the path is correct and try again.
At line:1 char:29
+ cp -r .gitignore $(ls -1A | grep -v .git) ../cpapp
+                             ~~~~

**Comment by slavipande** [comment]
Hi @mattj239 ,

Thanks for your feedback!

We've found that this error can occur when using PowerShell as your command line interpreter. Could you please try executing the command in Git BASH and let us know if it works? 
For more info on most suitable command line interpreters with the tutorials, please refer to [Command Line Interpreters](https://developers.sap.com/tutorials/btp-app-set-up-local-development.html#70a28cd2-5cd4-41ee-a428-16e8a5274c49).

Hope this helps!

Best regards,
Svetoslav

**Comment by iwonahahn** [comment]
Related to this [issue](https://github.com/SAP-samples/cloud-cap-risk-management/issues/13).

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
