### ISSUE TITLE
Add Views and Define Routes to Access Them

### ISSUE THREAD

**Issue by zlob2k** [sap-tutorials/Tutorials#18011]
Tutorials: https://developers.sap.com/tutorials/sapui5-101-add-routing.html
--------------------------
After creating file "List.view.xml" there are some errors.
It requires to add the attribute "ID" for the screen elements such as
&lt;StandardListItem type="Navigation" press="handleListItemPress" title="{ProductName}"/&gt;
My example:
&lt;StandardListItem type="Navigation" press="handleListItemPress" title="{ProductName}" id="list_item1"/&gt;

**Comment by zlob2k** [comment]
Hi, Conrad. 
Yes, it is a challenge for beginner to find where ID should be created. 
Best regards, Yurii пятница, 14 января 2022г., 18:52 +03:00 от Conrad Bernal  ***@***.*** :

**Comment by cjbernal** [comment]
Hi Yurii,

Thank you for getting back to me. I will reach out to the team to see if we can get this updated for future learners. 

Kind regards,
Conrad

**Comment by zlob2k** [comment]
Hello, Conrad. 
Thanks for excellent tutorial and quick answers
Best regards, Yurii
--
С уважением, 
Юрий Злобин.  вторник, 18 января 2022г., 19:36 +03:00 от Conrad Bernal  ***@***.*** :

**Comment by longieirl** [comment]
@zlob2k I'm working on the Fiori Tools development team and I've taken a look at the referenced tutorial. I was able to complete the tutorial, generating a SAPUI5 app and then extending the routing without any issues. The tutorial that you referenced expects that you already have a SAPUI5 project generated which will have created the `webapp/view/View1.view.xml` file already for you. There should be no need to create this file, the expectations is that you are changing it to allow a different view type to handle the data.
This is the group of tutorials https://developers.sap.com/group.cp-frontend-ui5-1.html which details how to create a SAPUI5 application.
I can review your project for you. Please attach `ffproject.zip` to this ticket, by running;
```
zip -r ffproject.zip ./your-project-name/ -x */\.* *.git* \.* *.zip *.mta *.rb *.bak *.swp *.back *.merge *.txt *.sh **/resources/\* **/gen/\* **/node_modules/\* **/mta_archives/\* **/dist/\*
```
Replace `your-project-name` with the name of your project folder and ensure this is executed outside of your actual project folder.
Please let me know if this resolves your issue?
John

**Comment by cjbernal** [comment]
@zlob2k Do you still require assistance here? My colleague @longieirl has offered to help troubleshoot above. If not, we can close this ticket.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
