### ISSUE TITLE
npm cds-dk including 3 high severity vulnerabilites

### ISSUE THREAD

**Issue by KRANIG** [sap-tutorials/Tutorials#18029]
Tutorials: https://developers.sap.com/tutorials/cp-apm-nodejs-create-service.html
--------------------------
Command

npm i -g @sap/cds-dk

returns warning on

3 high severity vulnerabilities

**Comment by iwonahahn** [comment]
Hi @KRANIG,

Thank you for this feedback. The dev colleagues are already working on it. It should be fixed asap.

Best regards,
Iwona
