### ISSUE TITLE
Create an SAP BTP ABAP Environment Trial User

### ISSUE THREAD

**Issue by jdees** [sap-tutorials/Tutorials#18021]
Tutorials: https://developers.sap.com/tutorials/abap-environment-trial-onboarding.html
--------------------------

This point:
Enter your connection settings:

Region: choose your SAP BTP Cloud Foundry Environment region, for e.g. US East (VA)
Email: your email address
Password: your password

I don't have a E-Mail/Password Login. I only login with client certificate and two-factor authentication. This step is therefore missleading / not possible for all users.
Please also write about the option to use a service key.

**Comment by mervey45** [comment]
Hi @jdees ,

thank you for your feedback. We'll update this information.

Best regards, 
Merve
