### ISSUE TITLE
Deploy Commerce Mock Application in the Kyma Runtime

### ISSUE THREAD

**Issue by iwonahahn** [sap-tutorials/Tutorials#18022]
Tutorials: https://developers.sap.com/tutorials/cp-kyma-mocks.html
--------------------------

Write here how you think we can improve the tutorial ...

Step 2.3.

Only minor thing to change for the navigation:

![2022-01-18_10-51-34](https://user-images.githubusercontent.com/22098308/149913637-26ad973b-5b6e-4329-8441-4d530c292ded.png)

Step 2.4.

For a better understanding please change:

Apply the `APIRule` of the mock application to the `dev` Namespace by choosing the **Deploy new workload** option, using the **Browse** option to choose the `kyma.yaml` file.

to:

Apply the `APIRule` of the mock application to the `dev` Namespace by choosing again the **Deploy new workload** > **Upload YAML** option, using the **Browse** option to choose the `kyma.yaml` file.

**Comment by jcawley5** [comment]
Thank you for the feedback. Due to the change in Kyma 2.0 the language has been changed, awaiting PR approval for release. Please submit a new issue if you feel any changes are necessary.
