### ISSUE TITLE
Add an API Proxy to a Product

### ISSUE THREAD

**Issue by RomanM-ops** [sap-tutorials/Tutorials#18027]
Tutorials: https://developers.sap.com/tutorials/hcp-apim-create-product.html
--------------------------

During Product activation error occurred: Unable to publish Product, not any detail information provided, just Error window.

**Comment by kulkarnir** [comment]
Hello Roman, 

Could you please check, if you have enabled API Business Hub Enterprise? 

In the [Set Up Integration Suite Trial](https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html)

In step 3,  you have to select the checkbox " Select the Enable API Business Hub Enterprise checkbox. Choose Next "

You can also check this from the APIPortal,  click on icon button **Navigation Links** (available on top right corner) and select **API Business Hub Enterprise** 

If this is enabled and still not working please let me know 

Sorry for the inconvinience 

Regards, 
Raghavendra

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
