### ISSUE TITLE
Enable SAP BTP, Kyma Runtime

### ISSUE THREAD

**Issue by redwoodca** [sap-tutorials/Tutorials#18037]
Tutorials: https://developers.sap.com/tutorials/cp-kyma-getting-started.html
--------------------------

Write here how you think we can improve the tutorial ...

I do not see the Application Runtime available under Entitlements

**Comment by KevinMuessig** [comment]
Hi @redwoodca ,

are you using trial or free tier for SAP BTP? If yes, you should see the Kyma runtime when searching for _Kyma_  in the entitlements of your Subaccount. Even if the entitlements are already set you should see the runtime appear. 
If that is not the case, maybe you can give me more information or open a ticket with the SAP BTP support team.
Thanks for reaching out and I wish you a happy weekend.

Best KM
