### ISSUE TITLE
Connect to Third-Party Services Using Integration Suite

### ISSUE THREAD

**Issue by MMZPERS** [sap-tutorials/Tutorials#18032]
Mission: https://developers.sap.com/mission.apim-open-connectors.html
--------------------------

Link: https://developers.sap.com/tutorials/cp-apim-openconnectors-common-resources.html

Tutorial 3 of 4 does not work properly.
Section: **Map Fields Between Open Connectors and HubSpot**
Step 1: **Common Resource Templates**

The common Resource Templates are not loaded, and the tutorial can't  be completed

**Comment by MMZPERS** [comment]
I'm attaching two screenshots so you can understand better:

![Common Resource Templates](https://user-images.githubusercontent.com/75525447/150333468-e4ef7594-4c71-4b51-ad82-1ec408147e37.PNG)

![Common Resource Templates 2](https://user-images.githubusercontent.com/75525447/150333515-b7137031-7247-48aa-a040-80614f0db455.PNG)

**Comment by MMZPERS** [comment]
Some more helpful information:

- I have tried to clear the cache and accessing with different browsers, same result.
- I have also have found and old issue from another user, describing the behavior:
  https://gitmetadata.com/repo/SAPDocuments/Tutorials/issues/7115

Thanks in advance

**Comment by MMZTECH** [comment]
No Basic-Companies Common Resource Template showing:

The tutorial says to search for the "basic-companies" tile:

![image](https://user-images.githubusercontent.com/75474544/158803567-9001046e-0782-4925-9546-4b965d9badbd.png)

But that template is not showing

![image](https://user-images.githubusercontent.com/75474544/158802675-c7c9e73e-23a6-4c45-8d1f-e20c5ddc1ad0.png)

Thanks

**Comment by jmmargo** [comment]
This tutorial will soon be deprecated.  Thank you.
