### ISSUE TITLE
View the SAP BTP from 10,000 Meters

### ISSUE THREAD

**Issue by workoffset** [sap-tutorials/Tutorials#18043]
Tutorials: https://developers.sap.com/tutorials/cp-explore-cloud-platform.html
--------------------------

IMHO, the quiz after step 2 should be moved below step 3.  Thank you for providing the space for feedback!

**Comment by qmacro** [comment]
Given the opening sentence of Step 3, combined with the last paragraph of that step, I can understand why your view is this way. However the answer to this question is also available in Step 1. So I would say that while it would also make sense to ask this question after Step 3, it also makes sense to have it where it is too, i.e. after Step 2. But thanks for the feedback! Keep it coming! :-)
