### ISSUE TITLE
Take a Tour of SAP BTP Trial

### ISSUE THREAD

**Issue by workoffset** [sap-tutorials/Tutorials#18044]
Tutorials: https://developers.sap.com/tutorials/cp-trial-quick-onboarding.html
--------------------------

Last line, step 3:
If you run into problems regarding entitlements and quotas, can check out the Guided Answers.

Should be written:
If you run into problems regarding entitlements and quotas, you can check out the Guided Answers.

Thank you.

**Comment by AnjaNicoleKretz** [comment]
Thank you for your feedback!
I have fixed the typo and uploaded a new version of the tutorial. It might take 1-2 days until changes are visible.
