### ISSUE TITLE
Set Up and Generate a New SAP Fiori App Project

### ISSUE THREAD

**Issue by mperrrin** [sap-tutorials/Tutorials#18041]
Tutorials: https://developers.sap.com/tutorials/fiori-tools-generate-project.html
--------------------------
Step 2 : Select a template
--------------------------
Hello,

I was in touch with Conrad.
I'm always lock at this step : ntohing happens when I select command 'Fiori: Open Application Generator'.

Thanks for any help, Marc PERRIN

**Comment by cjbernal** [comment]
Hi Marc,

Happy new year! In last year's incident, we left off with trying to get a video recording of the error: https://github.com/sap-tutorials/Tutorials/issues/7252#issuecomment-985536843

Is it possible for you to capture a screen recording of you using the `Fiori: Open Application Generator` command? If possible, please try to attach it as a GIF using github in the browser. 

**In the meantime, a potential workaround:** Are you able to use the `Open Template Wizard` command? This is another way for you to get into the application generator. 

![image](https://user-images.githubusercontent.com/43248032/150571118-6427ade2-1369-4c5e-aa4e-b4a1cb46451d.png)

Kind regards,
Conrad (SAP UX Engineering)

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
