### ISSUE TITLE
Access a Classic Schema from SAP Business Application Studio - Step 6 Question

### ISSUE THREAD

**Issue by ASRHARDING** [sap-tutorials/Tutorials#18047]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-access-cross-container-schema.html
--------------------------
At the end of Step 6 there is a question answer box with no question.

Having watched the video link at the start of the tutorial it appears that you are supposed to copy the SQL statement from the last action in the step, and paste it into the answer box. Unfortunately, even removing tabs and carriage returns from the SQL statement produced on my trial account does not result in a correct answer. Is the SQL below correct?

SELECT TOP 1000 "REGION", "DESCRIPTION" FROM "PLAIN"."REGIONS"

Thanks, Andrew

**Comment by jung-thomas** [comment]
The question is just above in the last sub-step:

Right-click on the view and choose Open Data. **Paste the generated SQL statement in the box below to complete the validation.**

No that wouldn't be the correct answer for this question.  Have a closer look at the screenshot and this step.  We are not working with REGIONS in this step.

**Comment by ASRHARDING** [comment]
Thanks for the clue, problem solved. I had to copy the screenshot into Paint and zoom in to see the view title properly. My screen is probably a lot smaller than the ones you are used to working with.
