### ISSUE TITLE
Send and Receive Test SAP Event Mesh

### ISSUE THREAD

**Issue by gman77** [sap-tutorials/Tutorials#18059]
Tutorials: https://developers.sap.com/tutorials/cp-enterprisemessaging-test-queue-sendreceive.html
--------------------------

Doesnt work with trial account. The posting of a message always comes back Unauthorized.

**Comment by MichaelCzcz** [comment]
![image](https://user-images.githubusercontent.com/57144076/151127566-62aa292e-c5cb-4395-a7c7-fbf9eca4b5c3.png)

Thank you for your feedback. For this tutorial you need a licence.

**Comment by gman77** [comment]
Please update the tutorial that it does not work with trial account. Thank you.
