### ISSUE TITLE
Installing SAP HANA, express edition Server + Apps, with Docker

### ISSUE THREAD

**Issue by hohmsen** [sap-tutorials/Tutorials#18052]
Tutorials: https://developers.sap.com/tutorials/hxe-ua-install-using-docker-xsa.html
--------------------------

One should note, that the hostname has to be "hxehost". This should be a variable and the run_hana script should be updated accordingly, because changing the hostname in docker afterwards is very complicated.

**Comment by JCurrie27** [comment]
Many thanks for the note - our team will add this to the tutorial.
