### ISSUE TITLE
Enhance Behavior With Action and Validation

### ISSUE THREAD

**Issue by rohitsap27** [sap-tutorials/Tutorials#18058]
While adding the Action,  new button  code needs to added at the Consumption view for displaying it UI screen . Step is missing in the tutorial, Kindly add that step as well 

{ type: #FOR_ACTION , dataAction: 'acceptTravel', label:'Accept'}],

**Comment by MichaelCzcz** [comment]
@rohitsap27 What's the name of the tutorial?

**Comment by mervey45** [comment]
Hi @rohitsap27 ,

thank you for your feedback. We will have a look at it.

Best regards, 
Merve
