### ISSUE TITLE
Deploy Commerce Mock Application in the Kyma Runtime

### ISSUE THREAD

**Issue by DanSchlachter** [sap-tutorials/Tutorials#18064]
Tutorials: https://developers.sap.com/tutorials/cp-kyma-mocks.html
--------------------------

Hello,

in step 2 of the tutorial a namespace "dev" is to be created. 
_Open the Kyma console and create the dev Namespace by choosing Add new namespace, providing the name dev, and choosing Create._

It would be great to mention here, that if the namespace is called any different than dev, the apps will not work / environment variables have to be adjusted.

Thanks
Daniel

**Comment by jcawley5** [comment]
Hi Daniel,

Thanks for the feedback. Can you help me understand why you didn't use the name dev as listed in the instructions? 

Regards,
Jamie

**Comment by DanSchlachter** [comment]
Hi Jamie,

we share a kyma environment for the team, so after one colleague has done
the tutorial, the namespace is already taken and can not be done by another
person.
Also, usually in such tutorials the naming is not so important meaning I
don't need to name artefacts exactly similar to the tutorial. I expected
the name of the space to be similar to e.g. a project name as I didn't know
this influences the URLs later.

Thanks
Daniel

Am Fr., 4. Feb. 2022 um 15:27 Uhr schrieb Jamie Cawley <
***@***.***>:

**Comment by jcawley5** [comment]
Ok, I'll enter some text to indicate so. It will be made available in the next few weeks.
