### ISSUE TITLE
Tour the SAP API Business Hub

### ISSUE THREAD

**Issue by gitbenedict** [sap-tutorials/Tutorials#18065]
Tutorials: https://developers.sap.com/tutorials/hcp-abh-getting-started.html
--------------------------

Write here how you think we can improve the tutorial ...

Is the question on Step 5 correct? I am not able to find any user name field when I browsed the Campaign API.

**Comment by qmacro** [comment]
Hi @gitbenedict thanks - looks like the data has changed since the tutorial was first authored. I've changed the validation question and it will hopefully have a better chance at standing the test of time! :-)
