### ISSUE TITLE
Map Fields Between Open Connectors and HubSpot

### ISSUE THREAD

**Issue by Oneyedzoro** [sap-tutorials/Tutorials#18067]
Tutorials: https://developers.sap.com/tutorials/cp-apim-openconnectors-common-resources.html
--------------------------

Write here how you think we can improve the tutorial ...

On the open connectors common resources templates there I have no tiles. So either the tutorial is missing some steps, I did something wrong or the tutorial is outdated.

**Comment by jmmargo** [comment]
This tutorial will soon be deprecated.  Thank you.
