### ISSUE TITLE
Test SAP API Business Hub APIs with Curl

### ISSUE THREAD

**Issue by gitbenedict** [sap-tutorials/Tutorials#18068]
Tutorials: https://developers.sap.com/tutorials/hcp-abh-test-locally.html
--------------------------

Hi, I am unable to complete the Tutorial 2 of 2. Step 5 since my output does not match with the expected result in Step5
Please check and let me know what is wrong. I am interested to know.

-------------------INPUT-----------------------
C:\Users\xxxxx>curl --request GET  --url "https://sandbox.api.sap.com/sap/c4c/odata/v1/c4codataapi/CampaignCollection?%24top=3&%24select=Status%2CStatusText"  --header "APIKey: xxxx"  --header "Accept: application/json"  --header "DataServiceVersion: 2.0"

-------------------OUTPUT-----------------------
{"d":{"results":[{"__metadata":{"uri":"https://sandbox.api.sap.com/sap/c4c/odata/v1/c4codataapi/CampaignCollection('00163E03A0701ED28B9EB2A63189D226')","type":"c4codata.Campaign","etag":"W/\"datetimeoffset'2012-11-12T18%3A20%3A06.8114710Z'\""},"Status":"2","StatusText":"Active"},{"__metadata":{"uri":"https://sandbox.api.sap.com/sap/c4c/odata/v1/c4codataapi/CampaignCollection('00163E03A0701ED28B9EB2A63189F226')","type":"c4codata.Campaign","etag":"W/\"datetimeoffset'2012-11-12T18%3A20%3A06.8114710Z'\""},"Status":"2","StatusText":"Active"},{"__metadata":{"uri":"https://sandbox.api.sap.com/sap/c4c/odata/v1/c4codataapi/CampaignCollection('00163E03A0701ED28B9EB2A6318A1226')","type":"c4codata.Campaign","etag":"W/\"datetimeoffset'2012-11-12T18%3A20%3A06.8114710Z'\""},"Status":"2","StatusText":"Active"}]}}

**Comment by qmacro** [comment]
Hi @gitbenedict - you have indeed successfully completed this step - while some details of the output may differ (this is sandbox data and IDs may change over time) the core of what you're looking for is there: the list of campaigns is limited to 3, and in each case the only data fields returned are Status and StatusText. Good work! 👍
