### ISSUE TITLE
Design and Deploy Your First Integration Flow

### ISSUE THREAD

**Issue by veeraa83** [sap-tutorials/Tutorials#18069]
Tutorials: https://developers.sap.com/tutorials/cp-starter-integration-cpi-design-iflow.html
--------------------------

Write here how you think we can improve the tutorial ...

**Comment by veeraa83** [comment]
in  Step 4: Add JSON to XML converter
<<< 2. Connect the converter to the message path by clicking on the message path.

TIP: When you place your cursor on the message processing path, you see it change to green color. >>>
 
The message processing path is never changing to green color,eve after correctly placing the converter on the path

**Comment by Karunaharan** [comment]
@veeraa83 - thanks for noticing the issue and letting us know.

With the recent enhancement, the color changing scheme is removed. I'll update the tutorial accordingly. All that you have to do now is to place the connector in the message path.

Regards,
Karuna
