### ISSUE TITLE
Implement Roles and Authorization Checks In CAP

### ISSUE THREAD

**Issue by guwerner** [sap-tutorials/Tutorials#18066]
Tutorials: https://developers.sap.com/tutorials/btp-app-cap-roles.html
--------------------------

Hello , 
thanks for that tutorial. 
The login pop-up does not come up. I have had installed the  passport module and made the changes in the code. If I try to load the risks I got a Forbidden popup.

**Comment by guwerner** [comment]
Ok if I clean my Browser cache, it works now!

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
