### ISSUE TITLE
Create an Anonymized View Using L-Diversity

### ISSUE THREAD

**Issue by aaloka-anant** [sap-tutorials/Tutorials#18079]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-data-anonymization-4.html
--------------------------

The self test has the fourth option written with a worng spelling. 
It would have been fine, except if it was right. 

Option below should be reworded.
Current: L-Diversity is at its best when used in combination with K-diversity.
Correct: L-Diversity is at its best when used in combination with K-anonymity.

**Comment by thomashammerSAP** [comment]
Dear @aaloka-anant,

you are right. This is a spelling mistake.
We will fixe the response as soon as possible.

Thanks for pointing that out.

BR
Thomas
