### ISSUE TITLE
Perform Actions On Cards To Support Your Business Case

### ISSUE THREAD

**Issue by VanitaDhanagar** [sap-tutorials/Tutorials#18093]
Tutorials: https://developers.sap.com/tutorials/cp-mobile-cards-booster-starter.html
--------------------------

Step 3 : Its good to add steps like "Step 3: View card on your mobile device(1 to 11) in 
https://developers.sap.com/tutorials/cp-mobile-cards-welcome.html ,Which are missing here.

Step 4 :View sales order approval card on your mobile device

- Point 7 : After approving the order the **LifeCycleStatus**  is not changing to accepted 
- Point 8 : After rejecting a order The value for **LifeCycleStatus**  is not changing to Rejected: Invalid Amount.

One more notice,after performing the above actions the specific customer names are not visible in the list .

Ex:If i perform approve order action for customer :carlene Mc later the customer is not visible in the list  to check **LifeCycleStatus** status change .

Thanks and Regards,
Vanita 

Labels to be attached:
Sprint Label: SCPTest-2202A
Prio: high-prio
Scenario label: SCPTest-mcard
Landcape Label: SCPTest-trail3

**Comment by LalithManokar** [comment]
Hi @SamiLechner and @MichaelCzcz ,

Please check the issue and provide your comments.

Thanks & Regards,
Lalith. S

**Comment by SamiLechner** [comment]
I retested can not reproduce this. The tuorial works for me
