### ISSUE TITLE
Enable SAP BTP, Kyma Runtime

### ISSUE THREAD

**Issue by MarcusSchiffer** [sap-tutorials/Tutorials#18091]
Tutorials: https://developers.sap.com/tutorials/cp-kyma-getting-started.html
--------------------------

Hi,

when accessing my trial this morning I got the message I need to create a new account due to cancellation of the Frankfurt based environment. I recreated my trial and enabled Kyma, assigned the role collections to my user but I am not able to access the dashboard.
I get this message:
Internal Server Error
Failed to authenticate: xsuaa: failed to get token: oauth2: cannot fetch token: 401 Unauthorized Response: {"error":"unauthorized","error_description":"Bad credentials"}

Any help is appreciated.

Regards
Marcus

**Comment by KevinMuessig** [comment]
Hi @MarcusSchiffer ,

thank you for reaching out! We are aware of the issue and it is been investigated internally at the moment.
Please see the following thread on community.sap.com for your reference:
https://answers.sap.com/questions/13578477/kyma-dashboard-failed-to-authenticate.html

I am sorry I can't help you at the moment. 

Best,
KM
