### ISSUE TITLE
Design and Deploy Your First Integration Flow

### ISSUE THREAD

**Issue by Askullu** [sap-tutorials/Tutorials#18099]
Tutorials: https://developers.sap.com/tutorials/cp-starter-integration-cpi-design-iflow.html
--------------------------

Issue: at step 8.1 the deployment is failing.
Screenshot:
![MicrosoftTeams-image (31)](https://user-images.githubusercontent.com/75372983/153229742-078e29d0-dbcc-4edd-b784-b9911ea42980.png)

Labels:
SCPTest-cloudin
SCPTest-2202A
trail2 , trail3
Priority- High

**Comment by Karunaharan** [comment]
@Askullu - the issue is resolved now
