### ISSUE TITLE
Create Data Model and Lock Object in SAP BTP, ABAP Environment

### ISSUE THREAD

**Issue by tyalgr** [sap-tutorials/Tutorials#18097]
Tutorials: https://developers.sap.com/tutorials/abap-environment-lock-object.html
--------------------------

Hi
2 errors found

1 very small one:
no description for the data element, 

1 more critical:

there is an error when I want to create the data definition.
Here is the error message:
Description	Resource	Path	Location	Type
Use of CDS Entity I_BusinessUserBasic is not permitted.	z_i_room_099.asddls	/TRL_EN/.adt/ddic/ddlsources/z_i_room_099/z_i_room_099.asddls	line 9	ABAP Syntax Check Problem

By the way I need to modify the data definition, but I do not know what will be the impact.
I have comented the association.

**Comment by mervey45** [comment]
Hi @tyalgr ,

in which system are you trying to do this tutorial?
It is only availabe for licensed systems. If you are trying to do it in the trial system, you will get error messages.

Best regards, 
Merve

**Comment by mervey45** [comment]
Hi @tyalgr  ,

we are closing this issue. If you still have any issues, please open a new github issue for that. 

Best regards, 
Merve
