### ISSUE TITLE
Create A New Welcome Card

### ISSUE THREAD

**Issue by VanitaDhanagar** [sap-tutorials/Tutorials#18095]
Tutorials: https://developers.sap.com/tutorials/cp-mobile-cards-welcome.html
--------------------------
Trial US East (VA) (AWS) 

Android device to start registration Is failing to register 

![Screenshot_2022-02-09-11-16-12-175_com sap content2go](https://user-images.githubusercontent.com/80330660/153129889-70a698c1-d14e-4a3a-930c-d3e72055ce8d.jpg)

Labels to be attached:
Sprint Label: SCPTest-2202A
Prio: high-prio
Scenario label: SCPTest-mcard
Landcape Label: SCPTest-trail2 

Thanks and Regards,
Vanita

**Comment by LalithManokar** [comment]
Hi @SamiLechner and @MichaelCzcz  ,

Please check the issue and Provide your Comments.

Regards,
Lalith. S

**Comment by SamiLechner** [comment]
Can you please retest as there was issues with the IDP we fixed mean while
