### ISSUE TITLE
Set Up Your Java Development Environment

### ISSUE THREAD

**Issue by ExternalMe** [sap-tutorials/Tutorials#18100]
Tutorials: https://developers.sap.com/tutorials/cp-java-reference-app-setup.html
--------------------------

As of today (20220209) Step 5 does not work. There is no SAP > Java Web Tomcat 8 available.

![image](https://user-images.githubusercontent.com/43265555/153299330-250f2a51-5eee-4c0a-9aaf-4150624ee7c1.png)

**Comment by YogithaC** [comment]
Hi,
@shankarigr is looking into this.
Regards,
Yogitha

**Comment by YogithaC** [comment]
Hi,
The support for Java Tools for Eclipse has ended.

Notice - https://help.sap.com/doc/43b304f99a8145809c78f292bfc0bc58/Cloud/en-US/98bf747111574187a7c76f8ced51cfeb.html?sel1=SAP%20BTP%20SDK%20for%20the%20Neo%20Environment&from=2021-03-10&to=2021-06-10

This tutorial along with GitHub samples have been deprecated as the tools are no longer supported.
Regards,
Yogitha
