### ISSUE TITLE
Design and Deploy Your First Integration Flow

### ISSUE THREAD

**Issue by MrMengT** [sap-tutorials/Tutorials#18104]
Tutorials: https://developers.sap.com/tutorials/cp-starter-integration-cpi-design-iflow.html
--------------------------

![fe7691bd98ff2566ca2380bcf887327](https://user-images.githubusercontent.com/99397140/153384135-dfe78d06-9092-4c4f-bb11-7cafd9b6271d.png)

When I followed this blog, I got this error, I don't know where is the problem, can you please help me

**Comment by Karunaharan** [comment]
@MrMengT - the issue is resolved now
