### ISSUE TITLE
Expose a Standard Core Data Service for ABAP Environment

### ISSUE THREAD

**Issue by nickpan-fioneer** [sap-tutorials/Tutorials#18116]
Tutorials: https://developers.sap.com/tutorials/abap-environment-business-service-provisioning.html
--------------------------

For the "Test yourself", may I suggest changing the wording to "Where do you define your exposed **entities**?" (or perhaps "views", or even "business objects", per [this diagram](https://help.sap.com/viewer/fc4c71aa50014fd1b43721701471913d/202009.001/en-US/289477a81eec4d4e84c0302fb6835035.html)).
The answer ("service definition") implies that what got exposed was `I_Currency`, which is a view and not a service (please correct if wrong).

It may seem nit-picky, but accurate terminology goes a long way in helping those using tutorials to learn.

**Comment by niloofar-flothkoetter** [comment]
you are right, I will edit and push it asap.
