### ISSUE TITLE
Add the SAP Launchpad Service

### ISSUE THREAD

**Issue by austinkloske22** [sap-tutorials/Tutorials#18111]
Tutorials: https://developers.sap.com/tutorials/btp-app-launchpad-service.html
--------------------------

I'm currently stuck on install MTA package as global package. I am running a 2020 mac (M1 chip). It looks like an issue was created for [this issue](https://github.com/SAP/cloud-mta/issues/228) in August 2021. Is there any work-around?

**Comment by iwonahahn** [comment]
@manjuX please also have a look at this question here in the community https://answers.sap.com/questions/13585338/cap-mta-deployment-with-launchpad-service.html

**Comment by iwonahahn** [comment]
Hi @austinkloske22,

 The issue seems to be resolved, so I am closing the issue. If you still have questions, feel free to reopen the issue.

Best regards,
Iwona
