### ISSUE TITLE
Create an SAP Fiori Elements-Based UI

### ISSUE THREAD

**Issue by davidsonnenschein** [sap-tutorials/Tutorials#18114]
Tutorials: https://developers.sap.com/tutorials/btp-app-create-ui-fiori-elements.html
--------------------------

Write here how you think we can improve the tutorial ...
At Step 3 when I went to add a risk, it did not insert a black risk, it gave an error saying use a GUID. Not fatal, but confusing.

**Comment by slavipande** [comment]
Hi @davidsonnenschein ,

Sorry for the delayed response.

[Step 3](https://developers.sap.com/tutorials/btp-app-create-ui-fiori-elements.html#49b3edfd-af45-4c23-a6bf-cc95cf36ebb7) in the mentioned tutorial does not include creating a risk. Did you mean [Step 4](https://developers.sap.com/tutorials/btp-app-create-ui-fiori-elements.html#530d411e-298e-48d5-93d8-1712af771f85) or something else? Could you share more details about your progress through the tutorial when the error occurs? Also, a screenshot of the error would be useful. :)

We'll be looking forward to your kind reply.

Best regards,
Svetoslav

**Comment by iwonahahn** [comment]
Hi @davidsonnenschein,

We haven't heard from you in a while and the issue seems to be resolved, so I am closing the issue. If you still have questions, feel free to open a new issue. 

Best regards,
Iwona
