### ISSUE TITLE
Subscribe to the Low-Code / No-Code Service in SAP BTP

### ISSUE THREAD

**Issue by rnl-work** [sap-tutorials/Tutorials#18117]
Tutorials: https://developers.sap.com/tutorials/appgyver-subscribe-service.html
--------------------------
Hi,

the prerequisites for the tutorial: a BTP account in EU10 ist no longer possible with a Trial account, as announced here:
https://help.sap.com/doc/43b304f99a8145809c78f292bfc0bc58/Cloud/en-US/98bf747111574187a7c76f8ced51cfeb.html?from=2021-10-14&to=2021-10-14&search=SAP%2520BTP%2520Trial%2520Subaccounts%2520on%2520eu10

Only cf-us10 and cf-ap21 are possible. So, how can we test appgyver in the BTP trial account now?

Thank you, René

**Comment by heytombeck** [comment]
Hello - unfortunately the AppGyver service is not available with a trial account, it is a paid service. To test the same features and complete the other tutorials in this mission, you can sign up for free at www.appgyver.com. The color scheme and button locations change at times, but the steps should still be possible.
