### ISSUE TITLE
Use Redis in the Kyma Runtime to Store and Retrieve Data

### ISSUE THREAD

**Issue by davidloufd** [sap-tutorials/Tutorials#18112]
Tutorials: https://developers.sap.com/tutorials/cp-kyma-redis-function.html
--------------------------

I can't find the place to check the gateway_url as an environment variable in Step 9: Adjust function code. Could you please help to provide more explanations, many thanks!

**Comment by jcawley5** [comment]
Hi David,

In step 8 you add a service instance to the function which creates a few environment variables. The variables will be shown on the Code tab under the actual code. You will need to scroll down the page to see them. The name of your variable will not match what the tutorial shows, but should be ending in **gateway_url**.

Regards,
Jamie
