### ISSUE TITLE
Deploy Your First SAPUI5 App

### ISSUE THREAD

**Issue by Sachinart** [sap-tutorials/Tutorials#18115]
Tutorials: https://developers.sap.com/tutorials/appstudio-sapui5-create.html
--------------------------

Hey,

Thanks for the nice tutorial. I have few points which needs update in the tutorial as they are failing.

Step 4: Build the application is not working. I got two errors when building MTA project -

1. Failed to read configuration for project sapui5 at "ui5-deploy.yaml". Error: ENOENT: no such file or directory
This error was resolved by explicitly running the script - "deploy-config" by command - npm run deploy-config in the terminal. This command is present in manifest.json file. I think this happened because on clicking - Build MTA Project, it ran deploy script which have some other command to run.
2. ERROR the xs-security.json path does not exist in the MTA project location
This error was resolved by parameter key from "path" to "config_path" holding the value "./xs-security.json" in mta.yaml file.

Step 5: Deploy the archive to Cloud Foundry. I found one error -

1. 403 Forbidden (status 403) when tried to deploy MTA archive.
The reason being that the Space Developer role was missing from Dev space. I was able to fix the issue by navigating to Cockpit > Cloud Foundry > Spaces > Select dev Space > click on Member on left menu items > Edit member and add Space Developer role.

Please fix those errors so that if someone else try to go through the tutorial, he/she does not face these issues.

**Comment by quiggs1001** [comment]
Hello @Sachinart ,

Thank you for reaching out and reporting your issues.  I've tried to replicate the problem you have, and I'm having a little difficultly at the moment :(.

After generating the application, can you please confirm that you didn't switch workspace until the application had successfully finished, and you saw the following prompt:

![image](https://user-images.githubusercontent.com/17096912/153911913-251b4a7c-a031-4035-b912-b03bf5f6c943.png)

From the errors above, it looks like some files were missing, and perhaps that's because you switched workspace before generation completed.  The deployment files you mention are the last to get created.  If you could confirm this that would help with the investigation.

Thanks,
Ian

**Comment by Sachinart** [comment]
Hi @quiggs1001 ,

Thanks for the quick response. I do not remember the prompt, but I will try to replicate the issue tomorrow and let you know. As far as I remember, I did not switch the workspace, but still I'll give it a try and let you know.

Thanks,
Sachin

**Comment by Sachinart** [comment]
Hi Ian,

Thank you for replicaing the issue and figuring out the exact cause. You are absolutely right about switching the workspaces. It caused the deployment files not getting generated.
It happened with me for the first time because in step 3 (Create a new single-module-project) poiny 7, when we finish all template steps, the next point suggests to switch on seeing success message but what exactly is the success message it's not mentioned and that confused me.
The message - "Installing dependencies..." is very small, faded and static for atleat 20 seconds that I ignored it and moved to the next step and the blunder happened. 😅

Could you please specify the success message in point 8 or better if you show the success page (i.e. Application Information page) appears after application is created successfully. And then put the next steps, it would be great.

Thanks for your efforts. 👍
Sachin

**Comment by quiggs1001** [comment]
Thanks Sachin,

That all makes sense, I agree that the generation success message is a little small.  We will update accordingly.  Thanks again for your feedback.

Regards,
Ian

**Comment by Sachinart** [comment]
That's great 😊
