### ISSUE TITLE
Embed an SAP Analytics Cloud Story in a Simple Web App

### ISSUE THREAD

**Issue by Kiemes** [sap-tutorials/Tutorials#18128]
Tutorials: https://developers.sap.com/tutorials/sac-embed-story.html
--------------------------

Write here how you think we can improve the tutorial ...
Hello colleagues,
the tutorial mentions that we should enable `Allow all origins` on SAC.
This option apparently got removed from SAC.
This [SAP note](https://launchpad.support.sap.com/#/notes/0003017131) even talks about the intended removal, but does not give the alternative or any reason for the removal.
Also the [official SAC documentation](https://help.sap.com/viewer/a4406994704e4af5a8559a640b496468/release/en-US/9e147121f2254300b308c21b968a77f2.html) still talks about the `Allow all origin` checkbox. That should also be changed.
How should we proceed now?
Thanks and best regards, Tom

**Comment by jmmargo** [comment]
This tutorial has been removed.
