### ISSUE TITLE
Create Service Instance for Document Translation

### ISSUE THREAD

**Issue by mchcn2018** [sap-tutorials/Tutorials#18124]
Tutorials: https://developers.sap.com/tutorials/sth-enable-document-translation.html
--------------------------

Service "Document Translation" is available in NEO only? How can I switch from Cloud Foundry to Cloud Neo?

**Comment by beapasch** [comment]
The Document translation service is not available on SAP BTP neo but on SAP BTP multi-cloud environment (see documentation: https://help.sap.com/viewer/9f73362817cd48339dd8a6acba160f7f/Cloud/en-US/100d41cc6ea94876ae95d6a6a584e9f7.html) . 
The other APIs from SAP Translation Hub are only available on SAP BTP neo and we are planning the migration (see roadmap item for Q4 2022: https://roadmaps.sap.com/board?PRODUCT=73555000100800000086&range=FIRST-2022Q4#Q4%202022).
I hope this answers your question.
