### ISSUE TITLE
Deploy Your Business Application to Cloud Foundry - ESlinnt Pop-up

### ISSUE THREAD

**Issue by i353590** [sap-tutorials/Tutorials#18137]
Tutorials: https://developers.sap.com/tutorials/appstudio-cap-deploy-app.html
--------------------------

After creating the CAP project from the template, we get a Pop-up for ESLint whether you want to allow or not.
Please add a step for this also whether to say 'Allow' or 'Don't allow'

Also, in the package.json, ESlint config also gets added. Please update that as well in the screenshots accordingly

<img width="371" alt="image" src="https://user-images.githubusercontent.com/66831161/155020305-1baacfba-4758-43d8-a5d8-58dfc7fd638e.png">

Thanks,
Shubham

**Comment by Paolaufer** [comment]
Hi,
Thank you for your feedback.
We will look into this and update you as soon as possible.
REgards,
Pao

**Comment by Paolaufer** [comment]
HI,
I have added the change. It actually belongs to the previous tutorial in the series: https://developers.sap.com/tutorials/appstudio-cap-app.html

Thank you for helping us improve our tutorials.

Regards,
Pao
