### ISSUE TITLE
Deploy Your Business Application to Cloud Foundry - Step missing

### ISSUE THREAD

**Issue by i353590** [sap-tutorials/Tutorials#18135]
Tutorials: https://developers.sap.com/tutorials/appstudio-cap-deploy-app.html
--------------------------

Hello,
Link:
https://developers.sap.com/tutorials/appstudio-cap-deploy-app.html#:~:text=Click%20the%20green%20arrow%20on%20the%20right%20of%20the%20configuration%20name%20to%20run%20the%20application

At (Step 9), we are asked to click on the app, but we were in SQL Config. tab.
Please add a step to Navigate back to "Run configurations" tab.

Thanks,
Shubham Agarwal

**Comment by Paolaufer** [comment]
Hi,
Thank you for your feedback.
We will look into this and update you as soon as possible.
REgards,
Pao

**Comment by Paolaufer** [comment]
I've added the missing step. Thank you for your contribution.
