### ISSUE TITLE
Set Up SAP Business Application Studio for Development with 'real' Global Account (no trial)

### ISSUE THREAD

**Issue by abap-weasel** [sap-tutorials/Tutorials#18139]
Tutorials: https://developers.sap.com/tutorials/appstudio-onboarding.html
--------------------------

Hi SAP Team, 

while the guide looks great and we already used it for initial testing of BAS in scope of trial, we fail to use it to enable BAS in our company global account. Can you add details for use case with company global account, please? -- Thank you!

**Comment by Paolaufer** [comment]
Hi,
Thank you for your feedback.
We will look into this and update you as soon as possible.
REgards,
Pao

**Comment by raz-korn** [comment]
Hi @abap-weasel ,

I apologize for the late response.

The tutorials are created and maintained with the trial environment in mind.
For productive (enterprise) accounts, one should refer to the product's [documentation](https://help.sap.com/viewer/9d1db9835307451daa8c930fbd9ab264/Cloud/en-US/19611ddbe82f4bf2b493283e0ed602e5.html).

Regards - Raz
