### ISSUE TITLE
Map Fields Between Open Connectors and HubSpot

### ISSUE THREAD

**Issue by EoinW95** [sap-tutorials/Tutorials#18140]
Tutorials: https://developers.sap.com/tutorials/cp-apim-openconnectors-common-resources.html
--------------------------

Hi,

When trying to add common resource template no templates appear to be loading. Screenshot attached for reference.

Thanks

<img width="716" alt="Common Resource 1" src="https://user-images.githubusercontent.com/98608051/155115797-a63278af-a996-49ac-9abc-3ef1777b69fd.PNG">
<img width="384" alt="Common Resource 2" src="https://user-images.githubusercontent.com/98608051/155115809-1a93cc73-661a-422b-a501-53829b521152.PNG">

**Comment by jmmargo** [comment]
This tutorial will soon be deprecated.  Thank you.
