### ISSUE TITLE
Tutorial Page iot-edge-enable.md Issue. PROD

### ISSUE THREAD

**Issue by SAPDocs** [sap-tutorials/Tutorials#18141]
Tutorial issue found: [https://github.com/sap-tutorials/Tutorials/blob/master/tutorials/iot-edge-enable/iot-edge-enable.md](https://github.com/sap-tutorials/Tutorials/blob/master/tutorials/iot-edge-enable/iot-edge-enable.md) contains invalid tags. Even though your tutorial was created, the invalid tags listed below were disregarded. Please double-check the following tags:
- software-product>sap-btp

 Affected server: PROD

**Comment by marco-porru** [comment]
created pull request:

https://github.com/sap-tutorials/Tutorials/pull/18142

**Comment by marco-porru** [comment]
fix merged
