### ISSUE TITLE
Debug Your SAPUI5 App with SAP Business Application Studio

### ISSUE THREAD

**Issue by JTR7** [sap-tutorials/Tutorials#18149]
Tutorials: https://developers.sap.com/tutorials/appstudio-sapui5-debug.html
--------------------------

Hello,

I've followed the tutorial but when i run the app it is not showing the same image. Instead it's trying to open a launchpad with several tiles in the background and with the following error

"Title: ErrorMessage: App could not be opened because the SAP UI5 component of the application could not be loaded.Details: {	"info": "Failed to load UI5 component for navigation intent \"#sapbtpproject7-display\"",	"technicalMessage": "failed to load 'sap/btp/sapui5/controller/View1.controller.js' from ../resources/sap/btp/sapui5/controller/View1.controller.js: script load error\nModuleError: failed to load 'sap/btp/sapui5/controller/View1.controller.js' from ../resources/sap/btp/sapui5/controller/View1.controller.js: script load error\n    at p1 (https://workspaces-ws-6mjnd-app1.cry10.int.applicationstudio.cloud.sap/resources/sap-ui-core.js:53:213)\n    at j1.failWith (https://workspaces-ws-6mjnd-app1.cry10.int.applicationstudio.cloud.sap/resources/sap-ui-core.js:40:43)\n    at HTMLScriptElement.p (https://workspaces-ws-6mjnd-app1.cry10.int.applicationstudio.cloud.sap/resources/sap-ui-core.js:60:468)\nCaused by: Error: script load error\n    at HTMLScriptElement.p (https://workspaces-ws-6mjnd-app1.cry10.int.applicationstudio.cloud.sap/resources/sap-ui-core.js:60:510)"}

![Uploading 2022-02-25_16-52-57.png…]()

**Comment by JTR7** [comment]
When adding the message page, the view.controller.js indicates there is an error in the following line

<MessagePage showHeader="false" description="More content to come" text="Stay tuned!" icon="sap-icon://home"/>

Recommendation from BAS is to generate an ID but after applying, still does not work. Same error as above.

**Comment by cjbernal** [comment]
Hi there,

Sorry to hear that you're having an issue. Just to be sure I'm understanding correctly, are you getting this error during _Step 5: Run the web app_? If so, could you do 3 things for me to help us try and troubleshoot it? 

1. Could you please share a few more details about what you're doing leading up to the error?
2. Could you tell me if the launchpad has a tile for your application on it? 
3. Could you please attach a zipped version of your project with the `node_modules` folder removed here? This will make it easier for the team to look into details if needed.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
