### ISSUE TITLE
Create Your First Application with SAP Cloud SDK for JavaScript

### ISSUE THREAD

**Issue by junkukaka** [sap-tutorials/Tutorials#18159]
Tutorials: https://developers.sap.com/tutorials/s4sdkjs-odata-service-cloud-foundry.html
--------------------------
### In step 4
**The attribute "requestBuilder" does not exist on type "Typeof BusinessPartner".**

![image](https://user-images.githubusercontent.com/19967633/156303747-0c1a894d-5913-4153-bec5-51f22aa74dcb.png)

**Comment by artemkovalyov** [comment]
Hi @junkukaka,

We've released a new major version update recently which might make the tutorials temporary outdated. We plan to migrate them to our documentation in the nearest future. In the meanwhile, I'd recommend looking at our getting started guide here: https://sap.github.io/cloud-sdk/docs/js/getting-started
You can also check our sample apps here:
https://github.com/SAP-samples/cloud-sdk-js

I'll be closing this issue for now as it's 19 days old. Don't hesitate to get back to us if you still have any questions.
In case you have already developed with the SDK, you can find support in our official GitHub repository: https://github.com/SAP/cloud-sdk-js/issues
