### ISSUE TITLE
Using ABAP with the SAP API Business Hub

### ISSUE THREAD

**Issue by AlexMFrank** [sap-tutorials/Tutorials#18156]
Tutorials: https://developers.sap.com/tutorials/hcp-abh-abap.html
--------------------------

The screenshots in the tutorial shows that you should download the api.github.com certificate. However, you need the https://sandbox.api.sap.com/ certificate instead.
Perhaps the screenshots of the tutorial should also be updated to the current API Business Hub UI.

**Comment by rich-heilman** [comment]
This tutorial has been archived.
