### ISSUE TITLE
Get an Account on SAP BTP to Try Out Free Tier Service Plans

### ISSUE THREAD

**Issue by jchirk** [sap-tutorials/Tutorials#18162]
Tutorials: https://developers.sap.com/tutorials/btp-free-tier-account.html
--------------------------

For the "Step 9: Enable Cloud Foundry environment", I couldn't find the free plan for cloud foundry. I had to go to "Entitlements" and add it to my entitlements. I could then use the free plan.

**Comment by jchirk** [comment]
Hello @AnnikaGonnermann,

I created the subaccount on eu20 (it seems like CF free tier is only available on this region for Europe).

Thank you !

**Comment by AnnikaGonnermann** [comment]
Hey @jchirk - thanks again for your feedback. We've changed the tutorial!
Best
Annika
