### ISSUE TITLE
Add User Authentication to Your Application (SAP HANA Cloud)

### ISSUE THREAD

**Issue by Kopylov-aa** [sap-tutorials/Tutorials#18164]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-cap-add-authentication.html
--------------------------

Step 3; You shows how to create role collection. But previously (as I think) we need deploy xs-securety.json roles description.
How to do it?

**Comment by jung-thomas** [comment]
That is done in Step 1 part 4.  When you create the XSUAA you supply the xs-security.json.  
![image](https://user-images.githubusercontent.com/12159356/156370296-ac087d1f-f8ed-4e0b-845b-7194d7f8aee7.png)
