### ISSUE TITLE
Build an Automation for Orders Management

### ISSUE THREAD

**Issue by ghrotceh** [sap-tutorials/Tutorials#18165]
Tutorials: https://developers.sap.com/tutorials/irpa-order-management-2-automation.html
--------------------------

Write here how you think we can improve the tutorial ...

The function "Set Navigator" doesn't work fine. The browser doesn't stand up. I have had changed it to "Start Screen".

**Comment by eshitamahajansap** [comment]
Hello, 
Thanks for your feedback! We did test the automation using "Set Navigator" and it worked fine. 
It will be great if you could share the details of the issue you are facing with the browser while using "Set Navigator" activity. 
Kind Regards, Eshita

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
