### ISSUE TITLE
Deploy an App to SAP BTP, Cloud Foundry runtime

### ISSUE THREAD

**Issue by anandraichura** [sap-tutorials/Tutorials#18166]
Tutorials: https://developers.sap.com/tutorials/cp-cf-dev-02-deploy-app.html
--------------------------

Step 4: Explore the deployed app - Point#2 - In the Application Routes section, choose the URL to open the application you’ve just deployed. 

This step and point is showing URL but it is not matching with the URL in the actual step. I am aware host name and server will be different but even details after that is totally different for example:-

My deployed app URL: https://myhosthk123.apps.internal/
Tutorial app URL: myhost1508.cfapps.eu10.hana.ondemand.com

When I am clicking on my deployed app URL as mentioned on step#4 I am getting message as **'This site can’t be reached - myhosthk123.apps.internal’s server IP address could not be found.'**

Kindly help to resolve the same or guide if I am not any step correctly.

Regards,
Anand

**Comment by qmacro** [comment]
Hi @anandraichura - can you please share some more information - e.g. a screenshot of the Application Overview page in the BTP Cockpit (a small section of this is shown in Step 4 of the tutorial). I'd like to understand where the `.apps.internal` is coming from.

**Comment by anandraichura** [comment]
Hi @qmacro - Please find attached requested screen shot. 
![image](https://user-images.githubusercontent.com/100823665/156531932-e889786c-f589-44cb-9671-b5024c7ea153.png)

**Comment by anandraichura** [comment]
Hi @qmacro 

Please find below details:-

---
applications:
- name: cf-nodejs
  memory: 192M
  instances: 1
  random-route: false
  host: myhosthk123

Regards,
Anand Raichura

**Comment by qmacro** [comment]
That should be fine. I have something for you to try, which is to not use the manifest file, but instead uncheck the "Use manifest" checkbox, and instead fill in information, like this:

<img width="725" alt="screenshot 2022-03-03 at 10 54 06" src="https://user-images.githubusercontent.com/73068/156550993-95c7e519-03f2-443a-8880-a930ebc5b0b3.png">

While you're there, please report back what the possible values are in the selection for the "Domain" field. Thanks.

**Comment by anandraichura** [comment]
Hi @qmacro Please find below  details of possible value from domain field.

![image](https://user-images.githubusercontent.com/100823665/156552231-bc8373b8-49f3-4544-9b85-b3f0e24450cd.png)

**Comment by anandraichura** [comment]
hi @qmacro it is working as per the step 4 now.. Thanks a lot for your help.

**Comment by qmacro** [comment]
ok, it was a little odd, right? But glad you're over the issue, and thank you for the update. Cheers!
