### ISSUE TITLE
Create Business Configuration for Factory Calendar

### ISSUE THREAD

**Issue by dimebg** [sap-tutorials/Tutorials#18170]
Tutorials: https://developers.sap.com/tutorials/abap-environment-service-binding.html
--------------------------

When trying to publish the local service endpoint on step 10 I get an exception pop-up in ADT. I opened an incident hoping SAP could help with the error in my landscape and tools but was told to go this route.

**Comment by mervey45** [comment]
Hi @dimebg ,

are you doing this tutorial in a licensed system?
If yes, can you send me the error message?

Thank you.

Best regards, 
Merve

**Comment by dimebg** [comment]
I am doing this on our S/4 system I'm not sure which license you're looking for. The error message is:
Publishing local service endpoint of Service Binding "XXXX" has encountered a problem.
Local Publish of XXXX failed
As second pop says "An exception was raised"

According to SAP support you are are the only way of getting support for this error and I hope they're right.

**Comment by mervey45** [comment]
Hi @dimebg ,

did you change the XXX with your own ID everywhere? Please make sure you did. You can press CTRL + F to search replace everywhere. If you still have any issues, please get in contact with me again. 

![image](https://user-images.githubusercontent.com/27953324/158147687-b93a172a-bfa9-412f-8775-b453f402260b.png)


Best regards, 
Merve

**Comment by mervey45** [comment]
Hi @dimebg ,

we are closing this issue. If you still have any issues, please open a new github issue for that. 

Thank you. 

Best regards, 
Merve
