### ISSUE TITLE
Define and Expose a CDS-Based Travel Data Model

### ISSUE THREAD

**Issue by shivakumar-p12-sap** [sap-tutorials/Tutorials#18186]
Tutorials: https://developers.sap.com/tutorials/abap-environment-data-model.html
--------------------------
Suggestion: 

In the last step "Step 4: Create service binding" and sub step 4
Please add step with a screenshot as mentioned in this tutorial (https://developers.sap.com/tutorials/abap-environment-behavior.html) from Step 2: Create behavior definition for projection view and sub step 7.Double-click on TravelProcessor to start your preview to justify the sentence "Therefore you are able to see the travel booking application on the UI."

Lables :
SCPTest-2203A
SCPTest-trial2
Low-Prio
SCPTest-fabap

Regards
Shivakumar P

**Comment by mervey45** [comment]
Hi @MamathaKH , 

this is updated. We are closing this issue.

Best regards, 
Merve
