### ISSUE TITLE
Train Execution of ML Model (AI API Client SDK)

### ISSUE THREAD

**Issue by karimmohraz** [sap-tutorials/Tutorials#18182]
Tutorials: https://developers.sap.com/tutorials/ai-core-aiapi-clientsdk-train.html
--------------------------

Write here how you think we can improve the tutorial ...
plz rename the title to "Train ML Model (AI API Client SDK)
"Execution" is a technical AI Core term referring to both training workflows and deployments.

**Comment by LunaticMaestro** [comment]
Thanks @karimmohraz  for highlighting the issue.
The changes will soon be made.

**Comment by MichaelCzcz** [comment]
@LunaticMaestro has this issue been resolved?

**Comment by LunaticMaestro** [comment]
It will be resolved by 15th May, the tutorials with tag `beginner` are in QA which shall address the usage of this technical term `Execution`

**Comment by MichaelCzcz** [comment]
@LunaticMaestro If this has this been solved as promised, please close this issue. Thank you.

**Comment by LunaticMaestro** [comment]
Hi @karimmohraz ,

The following PR fixes this issue:
https://github.com/sap-tutorials/Tutorials/pull/18450

available in the following tutorial.
https://developers.sap.com/tutorials/ai-core-helloworld.html

Very soon (within next week) another tutorial (completed only push to PROD remaining) will provided extended usage (logs and details) and simplification on the term "Execution".
