### ISSUE TITLE
Get Started with SAP Rapid Application Development by Mendix

### ISSUE THREAD

**Issue by miteshjpatel** [sap-tutorials/Tutorials#18189]
Tutorials: https://developers.sap.com/tutorials/mendix-onboarding.html
--------------------------

Cannot leave License Model blank

**Comment by Paolaufer** [comment]
Hi,
Could you please tell me in which step of the tutorial you are having trouble?
THank you.

**Comment by Paolaufer** [comment]
I will update the Tutorial to show you must select "Subscription".
THank you for the feedback.
