### ISSUE TITLE
Create an SAP Fiori App Using SAP Business Application Studio

### ISSUE THREAD

**Issue by Askullu** [sap-tutorials/Tutorials#18193]
Tutorials: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html
--------------------------

In step 3.6 new parameter "Minimum SAPUI5 version" has been added to the template. So the screenshot needs to be updated and also the new parameter has to be added in the table.

**Expected:**
![1](https://user-images.githubusercontent.com/75372983/157678420-8c75c6fb-cdb4-44d7-94cf-fc6a62214b6b.png)

**Actual:**
<img width="926" alt="1_1" src="https://user-images.githubusercontent.com/75372983/157678450-2724435e-7957-4a9d-8acc-f25771e13440.png">

Scenario Label: SCPTest-fbizapp
Sprint Label: SCPTest-2203A
Landscape Label: trail3, trail2
Priority: Medium

**Comment by raz-korn** [comment]
Fixed and PR created.
