### ISSUE TITLE
Help Thomas Get Started with SAP HANA Cloud

### ISSUE THREAD

**Issue by Cornellini** [sap-tutorials/Tutorials#18191]
Tutorials: https://developers.sap.com/tutorials/hana-trial-advanced-analytics.html
--------------------------

Write here how you think we can improve the tutorial ...

Hi Not able to complete step no 7 (substep 4) - I'm getting after "service instance creation failed" error. Not sure if it's only for me. Can you help me to debug it somehow?

**Comment by jung-thomas** [comment]
Are there any more details in the log besides just service instance creation failed?  Are you sure you HANA instance is running?  HANA Cloud on trial/free tier does shut down every night and hast to manually be restarted.

**Comment by Cornellini** [comment]
That was it. SAP HANA Instance shut down overnight and I have not checked it. Thank you so much for your reply, I can continue tutorial now.
