### ISSUE TITLE
Use SAP HANA as the Database for a CAP Java Application

### ISSUE THREAD

**Issue by dongtianxiaozi** [sap-tutorials/Tutorials#18190]
Tutorials: https://developers.sap.com/tutorials/cp-cap-java-hana-db.html
--------------------------

There is error “**[ERROR] CF-ResourceNotFound: Creation of service key failed (10010)**” when process step 3/point 4 "Create an SAP HANA service instance and implicitly push all artifacts to the database“

Detail error from BTP space instance as below:
Failed to open connection to the database, because of: Failed to get connection for database 'XXX' (XXX.hana.trial-us10.hanacloud.ondemand.com:443), because of: SAP DBTech JDBC: Cannot connect to jdbc:sap://XXX.hana.trial-us10.hanacloud.ondemand.com:443 [Object is closed: com.sap.db.jdbc.SecureChannelSession@716bdd4c XXX.hana.trial-us10.hanacloud.ondemand.com:443 ConnectionID:0 SessionID:0 on sun.nio.ch.UnixAsynchronousSocketChannelImpl[connected local=/XXX:55610 remote=XXX.hana.trial-us10.hanacloud.ondemand.com/34.202.189.140:443]].

Could you pls check if there is any issue from your side with Trial account?

Write here how you think we can improve the tutorial ...

**Comment by iwonahahn** [comment]
Hi @dongtianxiaozi,

Sorry for the late reply, I was ooo. 

It seems to be a technical problem with the HANA broker on SAP BTP. We can't really recommend anything other than "please try again". Let us know if the error still occures.

Thank you and best regards,
Iwona

**Comment by dongtianxiaozi** [comment]
> Hi @dongtianxiaozi,
> 
> Sorry for the late reply, I was ooo.
> 
> It seems to be a technical problem with the HANA broker on SAP BTP. We can't really recommend anything other than "please try again". Let us know if the error still occures.
> 
> Thank you and best regards, Iwona

The issue is resolved after start the HANA cloud server. And remove the failed service key.
