### ISSUE TITLE
Create a Python Application via Cloud Foundry Command Line Interface

### ISSUE THREAD

**Issue by alldantas** [sap-tutorials/Tutorials#18194]
Tutorials: https://developers.sap.com/tutorials/btp-cf-buildpacks-python-create.html
--------------------------

Hi, I am afraid that the python-3.9.6 (@ runtime.txt) is no longer available. When trying to do the "`cf push`" I got blocked with message "_BuildpackCompileFailed - App staging failed in the buildpack compile phase_". 

I checked on https://github.com/cloudfoundry/python-buildpack/releases and used the 3.9.9 (it worked), but I am not sure whether all versions listed there would be available at SAP BTP CF.

I think you should write a "notice" in that step (of the runtime.txt creation) pointing that version needs to be checked.

**Comment by Joysie** [comment]
Hi @alldantas,

Thanks you for your valuable feedback! You are right. I tested the tutorial again with 3.9.6 and I got the same error message. 
It works fine with **3.9.9**, **3.9.***, and **3.10.1**.  I updated the tutorial accordingly.

Best regards,
Gergana
