### ISSUE TITLE
Remote Table Replication

### ISSUE THREAD

**Issue by condamoor-sap** [sap-tutorials/Tutorials#18204]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-mission-extend-09.html
--------------------------
create virtual table <VIRTUALTABLENAME> refresh definition;

should be

ALTER virtual table <VIRTUALTABLENAME> refresh definition;

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
