### ISSUE TITLE
Create an SAP Fiori Elements-Based UI

### ISSUE THREAD

**Issue by tobiaswild** [sap-tutorials/Tutorials#18215]
Tutorials: https://developers.sap.com/tutorials/btp-app-create-ui-fiori-elements.html
--------------------------

Hello. I was trying to complete the tutorial above. But in Step 4 when you should try to create a risk by yourself, in the image shown what you can enter 'Embargo violation: …' But in my case it says that I have to enter a GUID in the '12345678-90AB-CDEF-1234-567890ABCDEF' format. And then when I copy this example GUID is gives me the error 'Reference integrity violated for association "miti"'. And even when I change to GUID and follow the format, it still returns me this value. 

I even tried to do the exact same thing in a copy of the 'create-ui-fiori-elements' [branch](https://github.com/SAP-samples/cloud-cap-risk-management/tree/create-ui-fiori-elements) of the repository of this tutorial.

What can I do to fix this error?

**Comment by tobiaswild** [comment]
Ah, I got it.
I did not see the little icon in the Mitigation input field. I don't understand why it creates an error when I try to enter the Mitigation myself. But now it works. 
So it was my fault. But it would be nice if there were an information about this in the tutorial.

**Comment by iwonahahn** [comment]
Hi @tobiaswild,

Thank you for your feedback. We will have a look and if required we will add a note for a better user experience.

Best regards,
Iwona

**Comment by iwonahahn** [comment]
Hi @tobiaswild,

The update in the tutorial is now [public](https://developers.sap.com/tutorials/btp-app-create-ui-fiori-elements.html#ca60f491-166a-4c5d-a830-f9189593ba2a). So we can close this issue. Again thank you for your feedback.

Best regards,
Iwona
