### ISSUE TITLE
Access the SAP Screen Personas Training System

### ISSUE THREAD

**Issue by hounshac** [sap-tutorials/Tutorials#18211]
Tutorials: https://developers.sap.com/tutorials/personas-access-learning-sys.html
--------------------------

Unable to access the training system http://link.personas.help/opensap/userrequest

Getting the attached error message

![Screenshot 2022-03-16 113405](https://user-images.githubusercontent.com/101714275/158581195-f8aace78-8eb0-4fbd-a8bf-0c90711a1252.png)

**Comment by cjbernal** [comment]
Hi @hounshac,

Sorry to see you're having an issue. The system is currently available for me. Would you mind trying again and letting us know if there is still a problem accessing the page?

Thanks and regards,
Conrad

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
