### ISSUE TITLE
Get a store package from SAP Intelligent RPA Store.

### ISSUE THREAD

**Issue by ghrotceh** [sap-tutorials/Tutorials#18225]
Tutorials: https://developers.sap.com/tutorials/irpa-bot-download-store.html
--------------------------

Write here how you think we can improve the tutorial ...

The question 2 is not working. The answer would be "sucess" but you can check whatever you want and it always say "Sorry, that's incorrect. Please try again"

**Comment by chaitanya-priya-puvvada** [comment]
I guess this has been discussed and closed as well.Not sure why is it open status.
