### ISSUE TITLE
Create Rule Services and Rulesets

### ISSUE THREAD

**Issue by vipinvijay1986** [sap-tutorials/Tutorials#18221]
Tutorials: https://developers.sap.com/tutorials/cp-cf-businessrules07-ruleservice-ruleset.html
--------------------------
According to images , Policy should be Aggregation but system by default populate "Orchestration" as policy. 
So same information can be added in text .
Write here how you think we can improve the tutorial ...

**Comment by VandanaVasudevan** [comment]
Thanks a lot for the feedback! We will look into it and improvise the tutorials.
