### ISSUE TITLE
Get Started with SAP API Management

### ISSUE THREAD

**Issue by MMZTECH** [sap-tutorials/Tutorials#18224]
Group: https://developers.sap.com/group.cp-apim-code-1.html
--------------------------

There is an error when provisioning the API Management capability.
I get this error when entering the API Portal:

![image](https://user-images.githubusercontent.com/75474544/158800078-a4f2f0e4-88dc-4c5b-b12f-7a019a2bd640.png)

Account ID: bc372369trial

Thanks in advance.

**Comment by MMZTECH** [comment]
After a while, I´ve capable of accessing the API Portal, but there are still problems when trying to complete the exercise:

Issue 1: Not able to fetch OData Metadata from ES5.
![image](https://user-images.githubusercontent.com/75474544/158804105-41cf84f8-6285-4b96-b895-b52091a25215.png)

Issue 2: Not able to fecth its own Host Alias:
![image](https://user-images.githubusercontent.com/75474544/158804275-e1b45341-a581-47da-94e5-43dd748cfa2d.png)
This ends up with an error when saving the API proxy:
![image](https://user-images.githubusercontent.com/75474544/158804386-c75f22a8-c479-429d-b217-bc029387e7bf.png)

The following post states that not being able to get the virtual host is a provisioning issue:
https://answers.sap.com/questions/12702450/missing-configurations-please-contact-support-team.html

Thanks

**Comment by MichaelCzcz** [comment]
@MMZTECH Thank you for your feedback. You have posted an issue for a tutorial group. Which tutorial is the one you are haven problems with?

**Comment by MMZTECH** [comment]
With this one:
https://developers.sap.com/group.cp-apim-code-1.html

First I had issues with step 1 of the Mission (provisioning the API Manager Capability)
- When provisioning it returned and error (first post of this issue)

Then I was able to access the API Portal, but I han an error with step 3 (Create an API Proxy)
- When saving the API PRoxy it returned and error (second post of this issue)

I´ve looking into it, and both of them seem related to issues during the provisioning of the capability.
Links in the previous post.

**Comment by MichaelCzcz** [comment]
@MMZTECH The link points to a group of tutorials. Please navigate to the tutorial in question and C&P the URL. Thank you.

**Comment by MMZTECH** [comment]
I solved the issue by creating a new trial instance.
Thanks
