### ISSUE TITLE
Subscribe to the Low-Code / No-Code Service in SAP BTP

### ISSUE THREAD

**Issue by danku73dv** [sap-tutorials/Tutorials#18249]
Tutorials: https://developers.sap.com/tutorials/appgyver-subscribe-service.html
--------------------------
Prerequisites:
Access to an SAP BTP account in EU10 with Low-Code / No-Code entitlements
Conflict: 
The region Europe (Frankfurt) is no longer available on SAP BTP Trial. See[What's New for SAP BTP.](https://help.sap.com/doc/43b304f99a8145809c78f292bfc0bc58/Cloud/en-US/98bf747111574187a7c76f8ced51cfeb.html?from=2021-10-14&to=2021-10-14&search=SAP%2520BTP%2520Trial%2520Subaccounts%2520on%2520eu10)

**Comment by heytombeck** [comment]
Hello - Sorry for the extremely slow response here, I didn't see a notification for this ticket. 

SAP AppGyver is a paid service, enabled via sufficient entitlements in your SAP BTP global account. You can use SAP AppGyver’s free Community Edition instead though, which includes the same features needed to complete the rest of the mission. You can sign up here: https://www.appgyver.com

Sorry again.

Tom
