### ISSUE TITLE
Create Business Configuration for Factory Calendar - continued

### ISSUE THREAD

**Issue by dimebg** [sap-tutorials/Tutorials#18252]
I opened issue #18170 but didn't get a resolution. Last comment I got was surrounding putting my initials in the place of ### which I had already done. I'm eclipse 2012-12 currently and I believe that the configuration of my S/4 client is the culprit to the issue. I opened a ticket with SAP and was told that the author of the tutorial had previous experience with the error I was encountering and that this was my only way to get resolution to my issue. At this time I cannot publish OData V4 - UI services on my S/4 system. 

Please help.

**Comment by mervey45** [comment]
Hi @dimebg ,

can you please send me a screenshot of your error message.

Thank you.

Best regards, 
Merve

**Comment by dimebg** [comment]
![image](https://user-images.githubusercontent.com/73665642/159534451-3e2129eb-462f-4e10-b0cf-1efc38f18f5a.png)
