### ISSUE TITLE
Get a store package from SAP Intelligent RPA Store.

### ISSUE THREAD

**Issue by thecodester** [sap-tutorials/Tutorials#18260]
Tutorials: https://developers.sap.com/tutorials/irpa-bot-download-store.html
--------------------------

Write here how you think we can improve the tutorial ...

- Title has a period at end and the title should be capitalized
- Prerequisites should have bullets
- MIssing space in Step 2, substep 1 
- - Why is the answer to Step 2 also "Job Completed"?

**Comment by MichaelCzcz** [comment]
![image](https://user-images.githubusercontent.com/57144076/159653937-09283c61-1b3f-433b-851b-b84a024f80f9.png)

**Comment by thecodester** [comment]
Job Completed AND Success must be selected. Success is correct but Job completed I cannot find.

**Comment by chaitanya-priya-puvvada** [comment]
https://github.com/sap-tutorials/Tutorials/pull/18264.
Implemented the changes mentioned  and the answer the question is only Success

**Comment by chaitanya-priya-puvvada** [comment]
https://github.com/sap-tutorials/Tutorials/pull/18264.
Implemented the changes mentioned  and the answer the question is only Success
