### ISSUE TITLE
Add an API Proxy to a Product

### ISSUE THREAD

**Issue by JuergenMair** [sap-tutorials/Tutorials#18266]
Tutorials: https://developers.sap.com/tutorials/hcp-apim-create-product.html
--------------------------

In the last step when publishing the Product there is a error "Unable to publish Product" without any further details. See Screenshot. I tried several times, even with a new Trial account, always the same error. 

![Capture](https://user-images.githubusercontent.com/64806044/159784535-0738c4a7-77ee-4e52-87d7-ef8882756191.PNG)

**Comment by kulkarnir** [comment]
Hello, 

Sorry for the delay in reply,  

Have you launched API Business Hub Enterprise( old name developer portal) ?

Looks like API Business Hub Enterprise( developer portal) is not set up.

Please click on the **Navigation Links** on the top right corner of API Portal and select **API Business Hub Enterprise**


![image](https://user-images.githubusercontent.com/26405634/167664761-36f2e826-8b67-40c2-bf7b-04873f275432.png)

It should launch **API Business Hub Enterprise**, , now try to publish the product

Please let us know if this did not work 

Regards, Raghu

**Comment by JuergenMair** [comment]
Hi Raghu, 

many thanks - this solved my problem! 

Kind regards, 
Juergen

**Comment by JuergenMair** [comment]
I close this issue as it is solved.
