### ISSUE TITLE
Steps title confusing in Tutorial "Enhance Behavior With Action and Validation" 

### ISSUE THREAD

**Issue by yaseenabaper** [sap-tutorials/Tutorials#18267]
Tutorials: https://developers.sap.com/tutorials/abap-environment-behavior-action.html
--------------------------

Inside Tutorial "Enhance Behavior With Action and Validation" of group "SAP BTP ABAP Environment: Create and Expose a CDS-Based Data Model", I believe title for steps 6 & 7 should be interchanged. Currently for creating method for action, step title says DETERMINATION and similarly for creating determination method for TRAVEL_ID, step title says ACTION. I think it is confusing for the members who practise tutorials.

**Comment by mervey45** [comment]
Hi @yaseenabaper ,

thank you for your messag, we will update this as soon as possible.

Best regards, 
Merve
