### ISSUE TITLE
Create A New Welcome Card

### ISSUE THREAD

**Issue by JuergenMair** [sap-tutorials/Tutorials#18271]
Tutorials: https://developers.sap.com/tutorials/cp-mobile-cards-welcome.html
--------------------------

The Screenshots and also the process was different when I tried it - it seems the description does not fit to how the workflow is in reality. 

Also, since a while there is an issue when trying the tutorial as an SAP employee - on the Mobile App a Logon is not possible, see screenshot. 
![Capture](https://user-images.githubusercontent.com/64806044/160107871-d63f5b58-02d8-4b46-b6d4-de56c8cbd637.PNG)

**Comment by SamiLechner** [comment]
can you please give more details what does not seem to work.
and yes the tutorial will not work out of the box for SAP managed devices with Single Sign on
