### ISSUE TITLE
Create Behavior and Service in SAP BTP, ABAP Environment

### ISSUE THREAD

**Issue by tyalgr** [sap-tutorials/Tutorials#18272]
Tutorials: https://developers.sap.com/tutorials/abap-environment-behavior-definition.html
--------------------------

Write here how you think we can improve the tutorial ...
Replace (read only)
by  (readonly)

**Comment by mervey45** [comment]
Hi @tyalgr ,

thank you for your message. We'll update this as soon as possible.

Best regards, 
Merve
