### ISSUE TITLE
Set Up SAP Business Application Studio for CAP Java

### ISSUE THREAD

**Issue by VanitaDhanagar** [sap-tutorials/Tutorials#18273]
Tutorials: https://developers.sap.com/tutorials/cp-cap-java-app-studio.html
--------------------------

Step 2: Create application skeleton

The steps have been chaged ,update the navigation steps and screenshot as below

![image](https://user-images.githubusercontent.com/80330660/160331633-a5b1137b-b98c-408c-8939-327c0b211f4d.png)

Thanks and Regards,
Vanita

**Comment by iwonahahn** [comment]
Hi @VanitaDhanagar,

Thank you for your feedback. We are still updating the tutorials and will get back to you asap.

Best regards,
Iwona

**Comment by iwonahahn** [comment]
Hi @VanitaDhanagar,

The content was updated and therefore we closed the issue see mentioned pull request.

Best regards,
Iwona
