### ISSUE TITLE
Train ML Model with Execution in SAP AI Core (Postman)

### ISSUE THREAD

**Issue by karimmohraz** [sap-tutorials/Tutorials#18283]
Tutorials: https://developers.sap.com/tutorials/ai-core-aiapi-postman-train.html
--------------------------

plz check the screenshots in Step 5.
1) executions endpoint needs the execution id to show the latest status and potential error message.
2) plz add logs endpoint here, or point to different tutorial for trouble-shooting.

In aif support slack channel, people report more and more issues when trying out the tutorials, which is great, because it shows they are a great way to get started with the AI Core monster.
However, they usually don't know how to get the logs.

**Comment by dhrubpaul** [comment]
This tutorial is about to be deprecated.
New Tutorials contains the suggestions provided
