### ISSUE TITLE
Map Fields Between Open Connectors and HubSpot

### ISSUE THREAD

**Issue by gitbenedict** [sap-tutorials/Tutorials#18288]
Tutorials: https://developers.sap.com/tutorials/cp-apim-openconnectors-common-resources.html
--------------------------

Write here how you think we can improve the tutorial ...
![integrationSuite_CommonResources](https://user-images.githubusercontent.com/14294991/161197612-4500f839-8a14-4d90-8022-5264ff1155aa.jpg)
Please see attached image. I do not see any available templates under Common Resources. I rechecked all the steps but didnt find anything different between the tutorial and what I have done. Please assist.

**Comment by jmmargo** [comment]
This tutorial will soon be deprecated.  Thank you.
