### ISSUE TITLE
Build an SAP Fiori App that Consumes Data from an On-Premise System

### ISSUE THREAD

**Issue by MartinNorverto** [sap-tutorials/Tutorials#18295]
Group: https://developers.sap.com/group.appstudio-fiori.html
--------------------------

Hello, I'm having difficulty starting these exercises mostly because I've found an issue that won't let me continue which is when I'm trying to connect a server from USA or Singapour, it fails and it won't let me continue to create my DEV space in B.A.S

![image](https://user-images.githubusercontent.com/75043084/161637963-96317448-da00-4c42-9a86-dc7d36d5150d.png)
![image](https://user-images.githubusercontent.com/75043084/161638082-e5508f52-4ae7-4f65-97d2-72a68a9e1fcb.png)

I need to finish these exercises before tomorrow because I'm in interview sessions currently and they need them by tomorrow midday.

Thank you in advance,
Regards, Martin Alejandro Norverto.

**Comment by raz-korn** [comment]
Hi @MartinNorverto ,

I asked my colleagues to take a look.
As a workaround, and also current recommendation, there's the option to use SAP BTP Free-Tier.

- [Get an Account on SAP BTP to Try Out Free Tier Service Plans](https://developers.sap.com/tutorials/btp-free-tier-account.html)
- [SAP Business Application Studio Free Tier Model Onboarding](https://www.youtube.com/watch?v=-g7LZHqcbDQ)

Regards - Raz
