### ISSUE TITLE
Create Stored Procedures

### ISSUE THREAD

**Issue by hoffmannst** [sap-tutorials/Tutorials#18298]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-sqlscript-stored-proc.html
--------------------------
In the tutorial in step 1: Import Tables & Data a reference to the data.zip file from [here](https://github.com/SAP-samples/hana-opensap-cloud-2020/raw/main/tutorial/data.zip) is included, as in the tutorial the audience will use predefined tables with sample data for all of the SQLScript tutorials in the tutorial. Unfortunately the file doesn't contain all related table definitions, that's why a simple build isn#T possible without adjustments.

**Comment by jung-thomas** [comment]
You said something was missing from the zip file.  Can you please share the build log with the errors because I don't see anything missing in the zip file.

**Comment by hoffmannst** [comment]
Error: The file requires "db://OPENSAP_MD_BUSINESSPARTNERS" which is not provided by any file [8212001]
      at "src/Tutorial/OPENSAP_MD_PRODUCTS.hdbtable$OPENSAP_MD_PRODUCTS.validate" (32:11-40)
     Expanded from "src/Tutorial/OPENSAP_MD_PRODUCTS.hdbtable" 
    Error: The file requires "db://OPENSAP_MD_BUSINESSPARTNERS" which is not provided by any file [8212001]
      at "src/Tutorial/OPENSAP_PURCHASEORDER_HEADERS.hdbtable$OPENSAP_PURCHASEORDER_HEADERS.validate" (2:709-738)
     Expanded from "src/Tutorial/OPENSAP_PURCHASEORDER_HEADERS.hdbtable" 
    Error: The file requires "db://OPENSAP_MD_EMPLOYEES" which is not provided by any file [8212001]
      at "src/Tutorial/OPENSAP_MD_PRODUCTS.hdbtable$OPENSAP_MD_PRODUCTS.validate" (27:11-33)
     Expanded from "src/Tutorial/OPENSAP_MD_PRODUCTS.hdbtable" 
    Error: The file requires "db://OPENSAP_MD_EMPLOYEES" which is not provided by any file [8212001]
      at "src/Tutorial/OPENSAP_PURCHASEORDER_HEADERS.hdbtable$OPENSAP_PURCHASEORDER_HEADERS.validate" (2:372-394)
     Expanded from "src/Tutorial/OPENSAP_PURCHASEORDER_HEADERS.hdbtable" 
    Error: The file requires "db://OPENSAP_MD_PRODUCTIMAGES" which is not provided by any file [8212001]
      at "src/Tutorial/OPENSAP_MD_PRODUCTS.hdbtable$OPENSAP_MD_PRODUCTS.validate" (29:11-37)
     Expanded from "src/Tutorial/OPENSAP_MD_PRODUCTS.hdbtable" 
    Error: The file requires "db://OPENSAP_MD_PRODUCTS_TEXTS" which is not provided by any file [8212001]
      at "src/Tutorial/OPENSAP_MD_PRODUCTS.hdbtable$OPENSAP_MD_PRODUCTS.validate" (30:11-38)
     Expanded from "src/Tutorial/OPENSAP_MD_PRODUCTS.hdbtable" 
    Error: The file requires "db://SAP_COMMON_CURRENCIES" which is not provided by any file [8212001]
      at "src/Tutorial/OPENSAP_MD_PRODUCTS.hdbtable$OPENSAP_MD_PRODUCTS.validate" (28:11-34)
     Expanded from "src/Tutorial/OPENSAP_MD_PRODUCTS.hdbtable" 
    Error: The file requires "db://SAP_COMMON_CURRENCIES" which is not provided by any file [8212001]
      at "src/Tutorial/OPENSAP_PURCHASEORDER_HEADERS.hdbtable$OPENSAP_PURCHASEORDER_HEADERS.validate" (2:464-487)
     Expanded from "src/Tutorial/OPENSAP_PURCHASEORDER_HEADERS.hdbtable" 
    Error: The file requires "db://SAP_COMMON_CURRENCIES" which is not provided by any file [8212001]
      at "src/Tutorial/OPENSAP_PURCHASEORDER_ITEMS.hdbtable$OPENSAP_PURCHASEORDER_ITEMS.validate" (2:325-348)
     Expanded from "src/Tutorial/OPENSAP_PURCHASEORDER_ITEMS.hdbtable" 
    Error: Could not compose a consistent make graph [8212012]

**Comment by hoffmannst** [comment]
OPENSAP_MD_PRODUCTS has some dependencies that are not reflected in the zip file


COLUMN TABLE  "OPENSAP_MD_PRODUCTS" (
    "CREATEDAT" LONGDATE, 
    "CREATEDBY" NVARCHAR(255), 
    "MODIFIEDAT" LONGDATE, 
    "MODIFIEDBY" NVARCHAR(255), 
    "QUANTITY" DECIMAL(13,3), 
    "QUANTITYUNIT" NVARCHAR(3), 
    "PRODUCTID" NVARCHAR(10) NOT NULL, 
    "TYPECODE" NVARCHAR(2), 
    "CATEGORY" NVARCHAR(40), 
    "NAME" NVARCHAR(5000), 
    "DESC" NVARCHAR(5000), 
    "WEIGHTMEASURE" DECIMAL(13,3), 
    "WEIGHTUNIT" NVARCHAR(3), 
    "PRICE" DECIMAL(15,2), 
    "WIDTH" DECIMAL(13,3), 
    "DEPTH" DECIMAL(13,3), 
    "HEIGHT" DECIMAL(13,3), 
    "DIMENSIONUNIT" NVARCHAR(3), 
    "IMAGEURL" NVARCHAR(5000), 
    "PARTNER_ID" NVARCHAR(36), 
    "CURRENCY_CODE" NVARCHAR(3), 
    "IMAGE_PRODUCT_PRODUCTID" NVARCHAR(10), 
    PRIMARY KEY ("PRODUCTID"))
    WITH ASSOCIATIONS
    ( 
    JOIN  "OPENSAP_MD_EMPLOYEES" AS "CREATEDBYEMPLOYEE" ON createdByEmployee.email = createdBy, 
    JOIN  "SAP_COMMON_CURRENCIES" AS "CURRENCY" ON currency.code = currency_code, 
    JOIN  "OPENSAP_MD_PRODUCTIMAGES" AS "IMAGE" ON image.product_productId = image_product_productId, 
    JOIN  "OPENSAP_MD_PRODUCTS_TEXTS" AS "LOCALIZED" ON localized.productId = productId AND localized.locale = SESSION_CONTEXT('LOCALE'), 
    JOIN  "OPENSAP_MD_EMPLOYEES" AS "MODIFIEDBYEMPLOYEE" ON modifiedByEmployee.email = modifiedBy, 
    JOIN  "OPENSAP_MD_BUSINESSPARTNERS" AS "PARTNER" ON partner.ID = partner_ID, 
    JOIN  "OPENSAP_MD_PRODUCTS_TEXTS" AS "TEXTS" ON texts.productId = productId) 
    UNLOAD PRIORITY 5  AUTO MERGE ;

**Comment by jung-thomas** [comment]
I looked in the zip file and all those items from your log are in there.  
![image](https://user-images.githubusercontent.com/12159356/161760581-342f6ec4-78ea-4830-a022-8375354ed345.png)

I suspect that you unzipped the file into the incorrect folder. You seem to have everything in a Tutorial subfolder instead of the /src/data as was expected by the tutorial/sample.

**Comment by hoffmannst** [comment]
My mistake as I found out. Thanks Thomas and sorry for causing additional workload on your side
