### ISSUE TITLE
hana-cloud-mission-trial-9 - Grant Access to Calculation Views

### ISSUE THREAD

**Issue by JuBerndt** [sap-tutorials/Tutorials#18297]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-mission-trial-9.html
--------------------------
ERROR: Error: (dberror) [258]: insufficient privilege

i could not execute Step 4 on this tutorial.

1. User Managment

    A error message appears with the following text:
    Could not execute 'CREATE USER report PASSWORD <mypassword> NO FORCE_FIRST_PASSWORD_CHANGE set usergroup default'
    Error: (dberror) [258]: insufficient privilege: Detailed info for this error can be found with guid 
    '5FDD8805A3CD7B49807519B96E168578'

    Due to the error on SQL console, i created the user REPORT via the HANA Cockpit - UserManagement area with DBAdmin user.
    It works and i could see the user via the screen and via a select statement at the database explorer. 
     
2.  Grant the user access to the role
    Same error message pops up:
    
    Could not execute 'GRANT <SCHEMA_NAME>."PublicAccessSchema" to report'
    Error: (dberror) [258]: insufficient privilege: Detailed info for this error can be found with guid
    'B94B0CA8660B094EB7B7D4B0E40F211C'
    
    I tried to assig the role to the user via the Role Management at the HANA Cockpit, but here i got the same error with
    insufficient privileges.
      
What can i do or how to solve this issue ? Is it an environment issue ?
How could i found more informations for this errors ? I didn't find a info how to use this guid's to do a deep dive.

Kind regards
Jürgen

**Comment by D026523** [comment]
Hi Jürgen,
please open a connection with the DBADMIN user in database explorer to execute the statements.
Best,
Jan

**Comment by JuBerndt** [comment]
Thanks Jan,
I solved it but the screenshot is misleading.
I was able to run the commands after connecting to the HANA DB with the DBAdmin user.
In my opinion, the screenshot suggests that the commands should be executed at the SharedKeyDB level. Even when connected as DBAdmin this doesn't work.
Regards
Jürgen

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
