### ISSUE TITLE
Create HANA Stored Procedure and Expose as CAP Service Function (SAP HANA Cloud)

### ISSUE THREAD

**Issue by I501000** [sap-tutorials/Tutorials#18291]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-cap-stored-proc.html
--------------------------

Write here how you think we can improve the tutorial ...

I had done the successfull test for all the steps . But when  I tried to build the MTA project  , it ends with the following error .

user: MyCapMta1 $ mbt build  
[2022-04-03 13:13:29]  INFO Cloud MTA Build Tool version 1.2.7
[2022-04-03 13:13:29]  INFO generating the "Makefile_20220403131329.mta" file...
[2022-04-03 13:13:29]  INFO done
[2022-04-03 13:13:29]  INFO executing the "make -f Makefile_20220403131329.mta p=cf mtar= strict=true mode=" command...
[2022-04-03 13:13:29]  INFO validating the MTA project
[2022-04-03 13:13:29]  INFO running the "before-all" build...
[2022-04-03 13:13:29]  INFO executing the "npm ci" command...
.npm WARN prepare removing existing node_modules/ before installation
............................................npm WARN lifecycle The node binary used for scripts is /extbin/bin/node but npm is using /opt/nodejs/node-v14.17.6-linux-x64/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> sqlite3@5.0.2 install /home/user/projects/MyCapMta1/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
.[sqlite3] Success: "/home/user/projects/MyCapMta1/node_modules/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node" is installed via remote
.
> @sap/hana-client@2.11.20 install /home/user/projects/MyCapMta1/node_modules/sap-hdbext-promisfied/node_modules/@sap/hdbext/node_modules/@sap/hana-client
> node checkbuild.js

> @sap/hana-client@2.11.20 install /home/user/projects/MyCapMta1/node_modules/@sap/hdbext/node_modules/@sap/hana-client
> node checkbuild.js

.
> @sap-cloud-sdk/core@1.54.0 postinstall /home/user/projects/MyCapMta1/node_modules/@sap-cloud-sdk/core
> node postinstall.js

.
============================================
🚀 SAP Cloud SDK Announcement

The SAP Cloud SDK will release new major versions regularly starting in 2022.
A beta version for version 2 is expected to be released in November 2021.
We will ensure that upgrading takes less than one day of effort when using our upgrade guide.
Read more in our announcement post: https://sap.github.io/cloud-sdk/docs/js/announcing-version-2

Set environment variable SAP_CLOUD_SDK_SILENT to hide this and future announcements.
============================================

> @sap/cds-compiler@2.13.8 postinstall /home/user/projects/MyCapMta1/node_modules/@sap/cds-compiler
> node lib/fix_antlr4-8_warning.js

postinstall cds-compiler: Successfully fixed Antlr's circular dependency
added 395 packages in 48.512s
[2022-04-03 13:14:19]  INFO executing the "npx -p @sap/cds-dk cds build --production" command...
..............postinstall cds-compiler: Successfully fixed Antlr's circular dependency
..[cds] - determining build tasks for project [/home/user/projects/MyCapMta1].
[cds] - the following build tasks will be executed
[cds] -    {
     "build": {
       "target": ".",
       "tasks": [
         {"for":"hana", "src":"db", "options":{"model":["db","srv","app"]}},
         {"for":"node-cf", "src":"srv", "options":{"model":["db","srv","app"]}}
       ]
     }
   }

[cds] - building project [/home/user/projects/MyCapMta1], clean [true]
[cds] - cds [5.9.1], compiler [2.13.8], home [/home/user/projects/MyCapMta1/node_modules/@sap/cds]

[cds] - done > wrote output to:
   db/src/gen/.hdiconfig
   db/src/gen/.hdinamespace
   db/src/gen/CatalogService.Countries.hdbview
   db/src/gen/CatalogService.Countries_texts.hdbview
   db/src/gen/CatalogService.Interactions_Header.hdbview
   db/src/gen/CatalogService.Interactions_Items.hdbview
   db/src/gen/CatalogService.V_Interaction.hdbview
   db/src/gen/app.interactions.Interactions_Header.hdbtable
   db/src/gen/app.interactions.Interactions_Items.hdbtable
   db/src/gen/localized.CatalogService.Countries.hdbview
   db/src/gen/localized.CatalogService.Interactions_Header.hdbview
   db/src/gen/localized.CatalogService.Interactions_Items.hdbview
   db/src/gen/localized.app.interactions.Interactions_Header.hdbview
   db/src/gen/localized.app.interactions.Interactions_Items.hdbview
   db/src/gen/localized.sap.common.Countries.hdbview
   db/src/gen/sap.common.Countries.hdbtable
   db/src/gen/sap.common.Countries_texts.hdbtable
   srv/gen/_i18n/i18n.json
   srv/gen/csn.json

[cds] - build completed in 485 ms

..[2022-04-03 13:14:37]  INFO validating the MTA project
[2022-04-03 13:14:37]  INFO building the "MyCapMta1-srv" module...
[2022-04-03 13:14:37]  INFO executing the "npm clean-install --production" command...
npm WARN prepare removing existing node_modules/ before installation
..................npm WARN lifecycle The node binary used for scripts is /extbin/bin/node but npm is using /opt/nodejs/node-v14.17.6-linux-x64/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> @sap/hana-client@2.11.20 install /home/user/projects/MyCapMta1/node_modules/sap-hdbext-promisfied/node_modules/@sap/hdbext/node_modules/@sap/hana-client
> node checkbuild.js

> @sap/hana-client@2.11.20 install /home/user/projects/MyCapMta1/node_modules/@sap/hdbext/node_modules/@sap/hana-client
> node checkbuild.js

.
> @sap-cloud-sdk/core@1.54.0 postinstall /home/user/projects/MyCapMta1/node_modules/@sap-cloud-sdk/core
> node postinstall.js

.
============================================
🚀 SAP Cloud SDK Announcement

The SAP Cloud SDK will release new major versions regularly starting in 2022.
A beta version for version 2 is expected to be released in November 2021.
We will ensure that upgrading takes less than one day of effort when using our upgrade guide.
Read more in our announcement post: https://sap.github.io/cloud-sdk/docs/js/announcing-version-2

Set environment variable SAP_CLOUD_SDK_SILENT to hide this and future announcements.
============================================

> @sap/cds-compiler@2.13.8 postinstall /home/user/projects/MyCapMta1/node_modules/@sap/cds-compiler
> node lib/fix_antlr4-8_warning.js

postinstall cds-compiler: Successfully fixed Antlr's circular dependency
added 281 packages in 19.627s
[2022-04-03 13:14:58]  INFO the build results of the "MyCapMta1-srv" module will be packaged and saved in the "/home/user/projects/MyCapMta1/.MyCapMta1_mta_build_tmp/MyCapMta1-srv" folder
[2022-04-03 13:14:58]  INFO finished building the "MyCapMta1-srv" module
[2022-04-03 13:14:58]  INFO building the "MyCapMta1-db-deployer" module...
[2022-04-03 13:14:58]  INFO executing the "npm install --production" command...
npm WARN deploy@ No description
npm WARN deploy@ No repository field.
npm WARN deploy@ No license field.

npm notice Beginning October 4, 2021, all connections to the npm registry - including for package installation - must use TLS 1.2 or higher. You are currently using plaintext http to connect. Please visit the GitHub blog for more information: https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/
up to date in 0.276s

1 package is looking for funding
  run `npm fund` for details

.[2022-04-03 13:14:59]  INFO the build results of the "MyCapMta1-db-deployer" module will be packaged and saved in the "/home/user/projects/MyCapMta1/.MyCapMta1_mta_build_tmp/MyCapMta1-db-deployer" folder
[2022-04-03 13:15:05]  INFO finished building the "MyCapMta1-db-deployer" module
[2022-04-03 13:15:05]  INFO building the "app" module...
[2022-04-03 13:15:05]  INFO executing the "npm install --production" command...
..npm notice Beginning October 4, 2021, all connections to the npm registry - including for package installation - must use TLS 1.2 or higher. You are currently using plaintext http to connect. Please visit the GitHub blog for more information: https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/
npm WARN approuter@ No repository field.
npm WARN approuter@ No license field.

up to date in 2.349s
.
3 packages are looking for funding
  run `npm fund` for details

[2022-04-03 13:15:09]  INFO the build results of the "app" module will be packaged and saved in the "/home/user/projects/MyCapMta1/.MyCapMta1_mta_build_tmp/app" folder
[2022-04-03 13:15:19]  INFO finished building the "app" module
[2022-04-03 13:15:19]  INFO building the "MyCapMta1_ui_deployer" module...
[2022-04-03 13:15:19]  INFO the build results of the "MyCapMta1_ui_deployer" module will be packaged and saved in the "/home/user/projects/MyCapMta1/.MyCapMta1_mta_build_tmp/MyCapMta1_ui_deployer" folder
[2022-04-03 13:15:40] ERROR could not package the "MyCapMta1_ui_deployer" module when archiving: could not read the "/home/user/projects/MyCapMta1/node_modules/.bin/detect-libc" symbolic link: stat /home/user/projects/MyCapMta1/node_modules/detect-libc/bin/detect-libc.js: no such file or directory
make: *** [Makefile_20220403131329.mta:37: MyCapMta1_ui_deployer] Error 1
Error: could not build the MTA project: could not execute the "make -f Makefile_20220403131329.mta p=cf mtar= strict=true mode=" command: exit status 2

**Comment by jung-thomas** [comment]
Building the MTA and deploying to Cloud Foundry is not included in this scope of this tutorial. There is no mention of those steps in this tutorial. For general support for a topic outside the scope of the content of the tutorial, please consider asking a question in the SAP Community.  

There are completely separate steps required to adjust any CAP/HANA project before it can be deployed as an MTA.  There is a separate tutorial for these steps. I'd recommend starting there. https://developers.sap.com/tutorials/hana-cloud-cap-deploy-mta.html

**Comment by I501000** [comment]
Hi, Thomas,

I can deploy the MTA applicaiton in CF . But when I click on the deployed APP url  . There is another error .

![image](https://user-images.githubusercontent.com/74337345/161673350-590a66fc-1ba0-4a6e-9ce4-e123aed941bb.png)

**Comment by jung-thomas** [comment]
That looks a little like your XSUAA isn't configured properly for the Org/Space you are running the service within. The allow list of the XSUAA isn't approving the backend service url for redirect.  Did you remove the allow list extra settings from the xs-security.json before you built the MTA?  

But we are way outside the scope of this tutorial at this point.  I can see from the URLs you are an SAP employee running against internal landscapes and these tutorials are for BTP Free Trial or Free Tier.  For the specifics of your internal landscape or security configuration, I can't help you. Nor should that be discussed in a public forum.
