### ISSUE TITLE
Help! The Tutorials page cannot be opened!

### ISSUE THREAD

**Issue by evaZhangben** [sap-tutorials/Tutorials#18308]
Tutorials: https://developers.sap.com/tutorials/cp-cap-java-service-reuse.html
--------------------------

Help! The page cannot be opened!
The page for this Tutorials won't open! Hope it gets fixed soon! Please!

**Comment by MichaelCzcz** [comment]
It opens, but "closes" immediately.

**Comment by evaZhangben** [comment]
I'm sorry my English is not good. It is closed immediately, please fix it quickly, otherwise we will not be able to continue learning the following content..

**Comment by jmmargo** [comment]
The fix has been applied to production and tutorials are now accessible again.

**Comment by jmmargo** [comment]
Hot Fix was applied on 4/8/2022 to production.
