### ISSUE TITLE
Load Data into Standalone Data Lake in SAP HANA Cloud

### ISSUE THREAD

**Issue by VolkerSaggau** [sap-tutorials/Tutorials#18313]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-hdl-getting-started-3.html
--------------------------

Write here how you think we can improve the tutorial ...
C_PHONE              char(15)                       not null, 

and other char(99) commands are not allowed in HDL

The script has several errors. The below one works.

must be:
     /*==============================================================*/
     /* Table: CUSTOMER                                              */
     /*==============================================================*/
     create table TPCH.CUSTOMER (
       C_CUSTKEY            integer                        not null iq unique (150000),
       C_NAME               varchar(25)                    not null,
       C_ADDRESS            varchar(40)                    not null,
       C_NATIONKEY          integer                        not null iq unique (25),
       C_PHONE              varchar(15)                       not null,
       C_ACCTBAL            decimal(15,2)                  not null,
       C_MKTSEGMENT         varchar(10)                       not null,
       C_COMMENT            varchar(117)                   not null,
       constraint PK_CUSTOMER primary key (C_CUSTKEY)
     );

     /*==============================================================*/
     /* Table: NATION                                                */
     /*==============================================================*/
     create table TPCH.NATION (
       N_NATIONKEY          integer                        not null iq unique (25),
       N_NAME               varchar(25)                       not null,
       N_REGIONKEY          integer                        not null iq unique (5),
       N_COMMENT            varchar(152)                   not null,
       constraint PK_NATION primary key (N_NATIONKEY)
     );

     /*==============================================================*/
     /* Table: REGION                                                */
     /*==============================================================*/
     create table TPCH.REGION (
       R_REGIONKEY          integer                        not null iq unique (5),
       R_NAME               varchar(25)                       not null,
       R_COMMENT            varchar(152)                   not null,
       constraint PK_REGION primary key (R_REGIONKEY)
     );
     /*==============================================================*/
     /* Table: SUPPLIER                                              */
     /*==============================================================*/
     create table TPCH.SUPPLIER (
       S_SUPPKEY            integer                        not null iq unique (10000),
       S_NAME               varchar(25)                       not null,
       S_ADDRESS            varchar(40)                    not null,
       S_NATIONKEY          integer                        not null iq unique (25),
       S_PHONE              varchar(15)                       not null,
       S_ACCTBAL            decimal(15,2)                  not null,
       S_COMMENT            varchar(101)                   not null,
       constraint PK_SUPPLIER primary key (S_SUPPKEY)
     );

**Comment by saphinsperg** [comment]
This tutorial was originally designed to target on-premise IQ users moving to HDL who would create a standalone data lake instance with IQ compatibility enabled.  The char type is supported when the user specifies 'IQ compatibility' when creating the HDL instance, and the script works when executed in an instance provisioned this way.  The comment following this block indicates the types must be changed if the instance was created with HANA db compatibility.
