### ISSUE TITLE
Unable to log into API URL

### ISSUE THREAD

**Issue by amoolyaajmera** [sap-tutorials/Tutorials#18315]
unable to log into the API URL using the credentials used to create the trial account.

URL   -   https://api.cf.us10.hana.ondemand.com

ERROR  -    Authentication failed: API endpoint: https://api.cf.us10.hana.ondemand.com Authenticating... Password: API endpoint: https://api.cf.us10.hana.ondemand.com API version: 3.113.0 Not logged in. Use 'cf login' or 'cf login --sso' to log in. FAILED

**Comment by MichaelCzcz** [comment]
Hello,
what's the name of the tutorials where you are facing this issue?

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
