### ISSUE TITLE
SAP HANA Cloud, Data Lake Client Interfaces Overview

### ISSUE THREAD

**Issue by JCurrie27** [sap-tutorials/Tutorials#18312]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-dl-clients-overview.html
--------------------------

Hi Dan - Noticed a small typo at the start of the tutorial: 
"...Learn about the SAP **HAN** Cloud, data lake, how to create ..."

**Comment by danielva** [comment]
Thanks for leaving the feedback.  I will correct this in the next update.
