### ISSUE TITLE
Deploy a CAP Business Service to SAP Business Technology Platform

### ISSUE THREAD

**Issue by VanitaDhanagar** [sap-tutorials/Tutorials#18316]
Tutorials: https://developers.sap.com/tutorials/cap-service-deploy.html
--------------------------

In US region , the cf push is failing with below error,**"cf push -f gen/srv --random-route"**

![passport](https://user-images.githubusercontent.com/80330660/162678641-6b86ab4f-da63-4d7c-891f-21864869d38b.JPG)

Need to include passport dependecies

More info https://cap.cloud.sap/docs/node.js/authentication

Labels:
Sprint Label: SCPTest-2204A
SCPTest-banode
Landscape Labels: trail2
Priority label: High-prio
Label : Defect

Thanks and Regards,
Vanita

**Comment by iwonahahn** [comment]
Hi @VanitaDhanagar,

We are still updating the tutorial to use the new way to [deploy](https://cap.cloud.sap/docs/guides/deployment/to-cf). I will get back to you here asap and also answer the question in the [community](https://answers.sap.com/questions/13631264/unable-to-require-required-packagefile-passport-wh.html).

Best regards,
Iwona

**Comment by iwonahahn** [comment]
Hi @VanitaDhanagar,

In the meanwhile also the community raised this issue, see the answer in the [community](https://answers.sap.com/answers/13627421/view.html). Nevertheless, we will update the tutorial as mentioned above.

Best regards,
Iwona
