### ISSUE TITLE
Load Data into Standalone Data Lake in SAP HANA Cloud

### ISSUE THREAD

**Issue by VolkerSaggau** [sap-tutorials/Tutorials#18314]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-hdl-getting-started-3.html
--------------------------

Write here how you think we can improve the tutorial ...
Capter 2 What is "service_instance" now? I assume another HDL. This is confusing.

To my previous one: Why adding a section that the script has errors rather to fix ist?

**Comment by saphinsperg** [comment]
This tutorial was originally designed to target on-premise IQ users moving to HDL who would create a standalone data lake instance with IQ compatibility enabled.  The char type is supported when the user specifies 'IQ compatibility' when creating the HDL instance, and the script works when executed in an instance provisioned this way.  The comment following this block is meant to explain this fact and that the types must be changed if using the tutorial with an instance provisioned with maximum HANA db compatibility.
