### ISSUE TITLE
Use abapGit to Transfer Your On-Premise ABAP Source Code to the Cloud

### ISSUE THREAD

**Issue by TheFakeStefan** [sap-tutorials/Tutorials#18317]
Tutorials: https://developers.sap.com/tutorials/abap-environment-abapgit.html

--------------------------

Good day,

the screenshot https://developers.sap.com/tutorials/abap-environment-abapgit/jcr:content.github-proxy.1618556101.file/github2.png suggests that a `Public` repository should be used which is a bad default from the security perspective. In my standpoint, the default repository visibility should be `Private`.

Thanks!

**Comment by TheFakeStefan** [comment]
I have created a pull request for this issue.

https://github.com/sap-tutorials/Tutorials/pull/18326

Thanks
Stefan

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
