### ISSUE TITLE
Set Up Integration Suite Trial - Booster is failing - US region 

### ISSUE THREAD

**Issue by i353590** [sap-tutorials/Tutorials#18319]
Tutorials: https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html
-------------------------

Hello,

Step 4: Automatically assign roles and create service instances using Booster
In this step, the booster is failing in the US region saying the Integration suite service is not subscribed.
Even though the service is subscribed and capabilities are also added.

please check the issue.

<img width="1315" alt="image" src="https://user-images.githubusercontent.com/66831161/162703058-ea8fe4d6-e027-4f2b-8dc4-7e7021955aa7.png">

<img width="595" alt="image" src="https://user-images.githubusercontent.com/66831161/162703397-e31b19d1-03b0-4625-b10a-aa7c67019b4d.png">

Thanks,
Shubham

Labels to be added:
prior - HIGH-prio
Sprint Label: SCPTest-2204A
Scenario label: SCPTest-cloudin
Landscape: trial2 (US)

**Comment by Karunaharan** [comment]
Hello @i353590 , @MamathaKH , @AnnikaGonnermann 
Thanks for the patience and apologies for the long delay. There were issues in the Integration Suite trial offerings which are resolved now. You shouldn't be facing this issue anymore.

Regards,
Karuna
