### ISSUE TITLE
Use Machine Learning to Extract Information from Documents with Document Information Extraction Trial UI - Screenshot update for Account explorer

### ISSUE THREAD

**Issue by i353590** [sap-tutorials/Tutorials#18327]
Tutorials: https://developers.sap.com/tutorials/cp-aibus-dox-booster-app.html
--------------------------

Hello,
Step 4.2
https://developers.sap.com/tutorials/cp-aibus-dox-booster-app.html#:~:text=From%20your%20global%20account%20page%2C%20choose%20the%20trial%20tile%20to%20access%20your%20subaccount.
-> From your global account page, choose the trial tile to access your subaccount.
Issue: the Account explorer screenshot has to be changed with the latest one. now the subaccount are listed in a different way. 

![image](https://user-images.githubusercontent.com/66831161/162886363-9e17b287-5697-4673-ac41-5532c30f9b04.png)

Please update the same to avoid confusion.

Thanks,
Shubham

labels to be added:
prio - Mid-prio
Sprint Label: SCPTest-2204A
Landscape: trial2 (US)
Scenario label: SCPTest-docinfo

**Comment by Juliana-Morais** [comment]
Image updated and PR sent (https://github.com/sap-tutorials/Tutorials/pull/18340).
