### ISSUE TITLE
Request Product Details with an Integration Scenario - Capabilities Screenshot update needed

### ISSUE THREAD

**Issue by i353590** [sap-tutorials/Tutorials#18321]
Mission: https://developers.sap.com/mission.cp-starter-integration-cpi.html
Step 3: https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html#:~:text=APIs%20click%20capabilities.-,Choose%20Next,-.

While selecting the capabilities to activate, a screenshot update is needed as one more capability is now listed. (after fixing the [old issue,](https://github.com/sap-tutorials/Tutorials/issues/18199) one more capability is added now.

Latest screenshot:

![image](https://user-images.githubusercontent.com/66831161/162704007-b681a2f6-a3c7-4eb8-a118-a3674b7565ad.png)

please update the same.

Thanks,
Shubham

Labels to be added:
prior - Low-prio
Sprint Label: SCPTest-2204A
Scenario label: SCPTest-cloudin
Landscape: trial2, trial3

**Comment by Karunaharan** [comment]
This is fixed now, @i353590 
Will publish soon. Thanks
