### ISSUE TITLE
Request Product Details with an Integration Scenario - Role collection to be added

### ISSUE THREAD

**Issue by i353590** [sap-tutorials/Tutorials#18322]
Mission: https://developers.sap.com/mission.cp-starter-integration-cpi.html
--------

Hello,
Step 2: https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html#:~:text=You%20are%20subscribed%20to%20the%20service%20now.%20Click%20Go%20to%20Application%20in%20the%20Integration%20Suite%20overview%20page.%20Now%20you%20are%20directed%20to%20the%20Integration%20Suite%20Launchpad.

After subscribing the app, the default role (Integration_Provisioner) is not added by default sometimes.
Please add steps to add the roles, or mention it as a note to make sure the role bas been assigned and how to assign if not already done automatically.

![image](https://user-images.githubusercontent.com/66831161/162724204-62a06b7e-0a8f-4905-93bb-ca9478ea3455.png)

Thanks,
Shubham

Labels to be added:
prior - high-prio
Sprint Label: SCPTest-2204A
Scenario label: SCPTest-cloudin
Landscape: trial2, trial3

**Comment by Karunaharan** [comment]
This issue is fixed now, @i353590 
Will publish soon. Thanks.
