### ISSUE TITLE
Use Pre-Trained Tensorflow Models with a GPU in SAP AI Core

### ISSUE THREAD

**Issue by kemperd** [sap-tutorials/Tutorials#18323]
Tutorials: https://developers.sap.com/tutorials/ai-core-tensorflow-byod.html
--------------------------

Hello,

I am trying to follow your new tutorial on deploying a TensorFlow model to SAP AI core, however I am blocked in a quite early stage.
The top part of the tutorial lists a prerequisite on creating an SAP AI Core-enabled BTP account which is not explained well. The linked document on creating a trial account is clear, however I am not able to see "SAP AI Core" in both the Serivice Marketplace and the Entitlements screens. I have tried both the US East (AWS) and Signapore (Azure) regions.

Regards, Dirk [dirk.kemper@expertum.net]

**Comment by LunaticMaestro** [comment]
@kemperd Thanks for reaching out.
The tutorial is maked that it **cannot be performed on Trial Account**. Hence the requires license tag (highlighted yellow in screenshot below).
![image](https://user-images.githubusercontent.com/38010046/165039403-5cf13493-e9ff-4e88-8238-6e3b0e05cf7c.png)

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
