### ISSUE TITLE
Create a Sample Application on Cloud Foundry Using SAP Cloud SDK

### ISSUE THREAD

**Issue by bmccarron01** [sap-tutorials/Tutorials#18330]
Tutorials: https://developers.sap.com/tutorials/s4sdk-cloud-foundry-sample-application.html
--------------------------

Step 2 Generate project from archetype does not work.

The following command produces multiple errors and results in BUILD FAILURE.
mvn archetype:generate "-DarchetypeGroupId=com.sap.cloud.sdk.archetypes" "-DarchetypeArtifactId=scp-cf-tomee" "-DarchetypeVersion=RELEASE"

[ERROR] No plugin found for prefix 'archetype' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (C:\Users\xxxxxxx\.m2\repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
