### ISSUE TITLE
Create and Configure Forms

### ISSUE THREAD

**Issue by audrey-j07** [sap-tutorials/Tutorials#18346]
Tutorials: https://developers.sap.com/tutorials/spa-create-forms.html
--------------------------

hi Chaitanya,
Thank you for making this tutorial, I'm BTP presales based in Singapore and want to use this tutorial for workshop deep dive session on SPA. However I realize some tables in this particular tutorial series are not displaying properly, also screenshots (e.g. form builder - text area is no longer available) are outdated due to product update. Can you help to update the tutorial so it would be nice to share with the customer?

Appreciate your help on the update.

Regards,
Audrey

![Capture1](https://user-images.githubusercontent.com/100930555/164190398-3c65ab6a-740a-406e-a639-c0476661029f.PNG)
![Capture](https://user-images.githubusercontent.com/100930555/164190374-d7c4b05f-0754-4227-8170-8c3fd169c5fa.PNG)

**Comment by ArchanaShukla** [comment]
The tutorial formats are fixed now
