### ISSUE TITLE
Add a User Task to Your Workflow and Deploy

### ISSUE THREAD

**Issue by msyamsunder** [sap-tutorials/Tutorials#18355]
Tutorials: https://developers.sap.com/tutorials/cp-workflow-3-add-usertask-cf.html
--------------------------

As part of this tutorial, after building the workflow form, when i try to build the MTA project from yaml file, i get an error as below. 

Problems loading reference 'vscode://schemas/workspaceConfig': Unable to load schema from 'vscode://schemas/workspaceConfig': A resource provider for 'vscode://schemas/workspaceConfig' is not registered.

Please help to resolve this

**Comment by AstridHerbst** [comment]
Hi there,
These tutorials have been discontinued as the prerequisites are no longer given. Generally, the workflow capability of SAP Workflow Management service has moved to SAP Build Process Automation. 
Thanks and best regards,
Astrid
