### ISSUE TITLE
Create and Configure Forms

### ISSUE THREAD

**Issue by rbrainey** [sap-tutorials/Tutorials#18353]
Tutorials: https://developers.sap.com/tutorials/spa-create-forms.html
--------------------------

Hi,

There's a few spots in the Tutorial where markdown tables are not rendering properly.  Here's an example:

Design the Approval Form in the form builder by simply dragging-and-dropping fields onto the form editor and configuring respective field settings.

| Form Fields | Field Settings with Label | :————- | :————- | Headline 1 | Approve Sales Order | Paragraph | A new order has been received. Please review and confirm whether the requirements can be met or not. | Paragraph | Sales Order Details:

**Comment by ArchanaShukla** [comment]
Tutorial formats are fixed now
