### ISSUE TITLE
Create and Configure Forms

### ISSUE THREAD

**Issue by eshitamahajansap** [sap-tutorials/Tutorials#18350]
Tutorials: https://developers.sap.com/tutorials/spa-create-forms.html
--------------------------

Thanks for the tutorial. I noticed that Step2 and Step 3 have multiple formatting issues. It is even difficult to follow the tutorial due to these issues. Can you please make the necessary changes?

Regards,
Eshita

**Comment by ArchanaShukla** [comment]
Tutorial formats are fixed now
