### ISSUE TITLE
Installing SAP HANA, express edition with Docker

### ISSUE THREAD

**Issue by abap-weasel** [sap-tutorials/Tutorials#18351]
Tutorials: https://developers.sap.com/tutorials/hxe-ua-install-using-docker.html
--------------------------

HANA container have a note "Deprecation notice
This product is no longer maintained on this page, and will be removed in the future. The publisher may offer a more recent version elsewhere in Docker Hub." on https://hub.docker.com. 

* Is that guide still valid / advised to use as installation option? 
* Is it possible to get docker support again for HANA Express?

**Comment by abap-weasel** [comment]
Any news on this by now? 😕

**Comment by JCurrie27** [comment]
Thanks for your comment. We're going to (temporarily) remove the Docker tutorial while the Docker unavailability is under investigation.
