### ISSUE TITLE
Deleted data appearing in List report (CAP Project) columns

### ISSUE THREAD

**Issue by anilsapfiori** [sap-tutorials/Tutorials#18363]
How to avoid deleted still data showing in the List report smart table column, please help me.

**Comment by MichaelCzcz** [comment]
What's the name of the tutorial?

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
