### ISSUE TITLE
Create and Configure Forms

### ISSUE THREAD

**Issue by miffels** [sap-tutorials/Tutorials#18366]
Tutorials: https://developers.sap.com/tutorials/spa-create-forms.html
--------------------------

Thanks for providing the SPA tutorials! Have been eagerly waiting for them. A minor thing in this one:

In step 1.2, one creates a form.
In step 1.3, one edits the form.

The issue is that after creating the form in step 1.2, it is not automatically opened for editing and the instructions on how to open it are missing, so I am being left a little confused between those steps. Fix would be to explain how to open the newly created form for editing, i.e. to click the feature overflow in the flow item (three stacked dots) and then select "Open Editor":

<img width="519" alt="image" src="https://user-images.githubusercontent.com/1126941/165268616-178122c6-873e-424c-8382-369ee8c8acd9.png">

Feel free to use that screenshot if it suits your needs.

Cheers,
Michael

**Comment by ArchanaShukla** [comment]
The step to open the form is now added in the tutorial
