### ISSUE TITLE
Start Your MDK Application in the Editor

### ISSUE THREAD

**Issue by dongtianxiaozi** [sap-tutorials/Tutorials#18371]
Tutorials: https://developers.sap.com/tutorials/cp-mobile-dev-kit-offline-app.html
--------------------------

After step 5 and following all steps, the application can't be displayed in IPhone or web.

Below error is raised:
404 Not Found: Requested route ('XXXXX-dev-nsdemosampleapp-approuter.cfapps.ap21.hana.ondemand.com') does not exist.

Could you please guide how to resolve it?

**Comment by jitendrakansal** [comment]
@dongtianxiaozi can you please just make sure that the highlighted applications are in started state  in your space cockpit

<img width="1038" alt="image" src="https://user-images.githubusercontent.com/31536700/165458866-139721cc-6e63-429b-bb43-6fe52b2db318.png">

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
