### ISSUE TITLE
Create Application and Device Model

### ISSUE THREAD

**Issue by ClemensBlum** [sap-tutorials/Tutorials#18374]
Tutorials: https://developers.sap.com/tutorials/iot-model-create.html
--------------------------

At step 3 the code is called "cd sap-iot-samples/iot-bootstrap-scripts". When I download the file and look at the folder, the path for me is "sap-iot-samples-main\iot-bootstrap-scripts". 

Thanks

**Comment by marcuscbehrens** [comment]
this depends on how you download the repository. if you download it with git then "main" will not be appended to the directory name. if you downloaded it as a zip file and extract the zip file with the default folder name then it will be this.
