### ISSUE TITLE
Create A New Welcome Card

### ISSUE THREAD

**Issue by RanjishPR** [sap-tutorials/Tutorials#18408]
Tutorials: https://developers.sap.com/tutorials/cp-mobile-cards-welcome.html
--------------------------

Creation of a Welcome card failed. 
---------------------------------------

An error message says 'A mobile card with the same name already exists', even though an unique name was provided to the card during the creation process.

Please follow steps under 'STEP 2' in the above mentioned link. The error appears at the 14th step under STEP 2

Please find the screen shot attached as well.

Thank You.

Best Regards,
Ranjish
![Welcome card Bug](https://user-images.githubusercontent.com/105277535/167767037-568ac2bd-e84d-49b1-a031-f00cc96314c9.jpg)

**Comment by RanjishPR** [comment]
Hello,

Please note that the issue is the same while creating other cards as well.

Thanks & Best Regards,
Ranjish

**Comment by SamiLechner** [comment]
As the error clearly states you have already a card like this. This means you already ran this tutorial before and the service detected this.
