### ISSUE TITLE
Configure Object Pages Using SAP Fiori Tools

### ISSUE THREAD

**Issue by Gunduran** [sap-tutorials/Tutorials#18407]
Tutorials: https://developers.sap.com/tutorials/fiori-tools-configure-object-pages.html
--------------------------

Hello,
I know, that it might be a recurring job to be scheduled. But it is very annoying if you are in Configure Object Pages Using SAP Fiori Tools 
 (and even in the lesson before) when there is no sales data available.
I selected 10 or more products, but no sales data. SO the graph and the details will not contain any data...

Could you tell me a product, where sales data is available? (Or do I have to create my own application to search for it :-))

Best wishes,
Detlev

**Comment by Gunduran** [comment]
Hmm, I switched to the **mock data...** That is also fine... Sorry :-)

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
