### ISSUE TITLE
Run the Employee Onboarding Sample Scenario

### ISSUE THREAD

**Issue by MurkuteNidhi** [sap-tutorials/Tutorials#18400]
Tutorials: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-5-run.html
--------------------------

Step 4 : Execute the workflow sample application
Substep 4: After starting new instance, the instance is not coming in Running status instead its in 'Erroneous' status in both AP and US region.
<img width="959" alt="image" src="https://user-images.githubusercontent.com/95752943/167367439-a945b3ec-eadd-441c-b04d-23d650a105b5.png">

Labels to be added:
Scenario label: SCPTest-eboard
Sprint Label: SCPTest-2204A
Landscape Label: trail2(Trial US East (VA) (AWS) ) & trail3 (AP21 Azure)
Priority: High

**Comment by ArchanaShukla** [comment]
Hello @MurkuteNidhi ,
Can you confirm if  you have run the Booster? Is yes, can you sent me the screenshot for service  instance  in  cockpit

**Comment by MurkuteNidhi** [comment]
Hi @ArchanaShukla ,  
I used Booster! 
below is the screenshot for service instances in BTP
<img width="797" alt="image" src="https://user-images.githubusercontent.com/95752943/167584948-bd9735bf-33ee-4a33-a603-7c2388500ee2.png">

**Comment by ArchanaShukla** [comment]
I ran this exercise on fresh US10 account and I did not get this error. Could be some temporary issue. Please reopen if issue occurs again
