### ISSUE TITLE
Prepare the Local Development Environment

### ISSUE THREAD

**Issue by ramadasupuli** [sap-tutorials/Tutorials#18409]
Tutorials: https://developers.sap.com/tutorials/cp-prepare-local-dev.html
--------------------------

When I try to use following command, Its giving following error
C:\Windows\system32>@powershell -NoProfile -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"
**Access is denied.**

Please let us know how to resolved this

**Comment by qmacro** [comment]
Hi there - I'm afraid these issues are for problems with the tutorial flow or general content, and to contribute improvements. Please ask this question on [SAP Community Q&A](https://answers.sap.com). That said, it may just be that you require administrative privileges and don't have them on your machine.
