### ISSUE TITLE
Set Up Integration Suite Trial

### ISSUE THREAD

**Issue by Askullu** [sap-tutorials/Tutorials#18413]
Tutorials: https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html
--------------------------

**Issue** 1: In step 4.4 the booster is failing. Even though the subaccount has Integration suite subscribed.
Below is the screenshot with error:
<img width="875" alt="image" src="https://user-images.githubusercontent.com/75372983/168027132-1cf79f81-dee2-4ac6-ac78-1ea0e772acd6.png">

So performed the booster steps manually and continued.

**Labels**:
Scenario Label: SCPTest-cloudin
Sprint Label: SCPTest-2203A
Landscape Label: trail2
Priority - High

**Comment by Karunaharan** [comment]
Hello @PriyankaShivakumar, @Askullu, @AnnikaGonnermann 
Thanks for the patience and apologies for the long delay. There were issues in the Integration Suite trial offerings which are resolved now. You shouldn't be facing this issue anymore.

Regards,
Karuna
