### ISSUE TITLE
Expose Integration Flow Endpoint as API and Test the Flow

### ISSUE THREAD

**Issue by Askullu** [sap-tutorials/Tutorials#18412]
Tutorials: https://developers.sap.com/tutorials/cp-starter-isuite-api-management.html
--------------------------

**Issue**: In step 2.3 the API portal is not loading. The screenshot has been attached:
**Expected**:
![image](https://user-images.githubusercontent.com/75372983/167998251-757da4f9-9639-4f07-9ff7-b7f27fa8c4eb.png)

**Actual**:
![Integration suit 2](https://user-images.githubusercontent.com/75372983/167998187-dadc7258-eddf-4e0f-8adf-2bb68ad7cbf2.jpg)

**Labels:**
Scenario Label: SCPTest-cloudin
Sprint Label: SCPTest-2203A
Landscape Label: trail2
Priority - High

**Comment by Karunaharan** [comment]
The issue is resolved now. Could you please check?
