### ISSUE TITLE
Subscribe to the Low-Code / No-Code Service in SAP BTP - no Subscription available

### ISSUE THREAD

**Issue by JuBerndt** [sap-tutorials/Tutorials#18416]
Tutorials: https://developers.sap.com/tutorials/appgyver-subscribe-service.html
--------------------------
i use a Cloud Foundry trail account on US East(VA) - cf-us10.
(The region Europe (Frankfurt) is no longer available on SAP BTP Trial. )

On Boosters the tile for Prepare an Account for Low-Code is not available in this environment.
Therefore i could not use the tutorial and the app.

How can i get this environment ?

Kind regards
Jürgen

**Comment by heytombeck** [comment]
Hello - unfortunately this service is only available as a paid service in Europe currently. The good news is that you can complete the remaining tutorials in the mission using AppGyver's free community edition. To access this, sign up for an account at https://platform.appgyver.com/users/sign_up

**Comment by JuBerndt** [comment]
Hi,
yes i have done it before, and try it actually.
But i dont know if any other integrations are missing.

Thanks for now.
Regards
Jürgen

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
