### ISSUE TITLE
Create an API Proxy

### ISSUE THREAD

**Issue by spcbbt** [sap-tutorials/Tutorials#18418]
Tutorials: https://developers.sap.com/tutorials/hcp-apim-create-api.html
--------------------------

I have the following error when creating the proxy with the trial account, API_PORTAL_DEST_NOT_FOUND

![image](https://user-images.githubusercontent.com/105505231/168308213-40b7dff5-2bfa-4e67-accb-eafb3d8d6f90.png)

Regards

**Comment by kulkarnir** [comment]
Hello, 

It appears like there is some issue with the setup of API Management..

Did you face any issue when you setup API Management 

Regards, Raghu

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
