### ISSUE TITLE
Move Data from a Free Tier Model or Trial Instance to a Production Instance

### ISSUE THREAD

**Issue by Paolaufer** [sap-tutorials/Tutorials#18429]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-trial-2-production.html
--------------------------

Hi,
Trial will be sunset very soon.
Could you please update the tutorial so that it does not mention trial?

Thank you

**Comment by mikepaola** [comment]
We cannot remove this reference yet - especially since there are delays with the trial sunset.  In addition, when trial does eventually sunset, we want to have this tutorial to show how people can export their contents from their trial instance so that they do not lose their data.

**Comment by Paolaufer** [comment]
OK, I see your point :)
Thanks
