### ISSUE TITLE
Run Employee Onboarding Tutorial Error

### ISSUE THREAD

**Issue by elenaylz** [sap-tutorials/Tutorials#18427]
Hi, I came across a problem when i was trying to follow the tutorial.

- Tutorial Link: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-5-run.html
- Problem Existence: Step 4.4
- Details: After I start the new instance and want to see how it is running, always get the error message, see in picture.
I have already followed the tutorials step by step and also use the Boosters to add the service.
<img width="691" alt="Problem" src="https://user-images.githubusercontent.com/77970036/168977816-d5281767-dd3a-4678-86df-73f113c16ba0.png">

**Comment by ArchanaShukla** [comment]
I ran this exercise on fresh US10 account and I did not get this error. Could be some temporary issue. Please reopen if issue occurs again
