### ISSUE TITLE
Get an Account on SAP BTP to Try Out Free Tier Service Plans

### ISSUE THREAD

**Issue by RaphaelReply** [sap-tutorials/Tutorials#18421]
Tutorials: https://developers.sap.com/tutorials/btp-free-tier-account.html
--------------------------

Dear all,

I was trying to ramp up a BTP free tier account today. However I was not able to get it done with the tutorial as the link for the SAP Store there is "https://storefront.s1.store.net.sap/dcp/en/product/display-9999951781_live_v1/Pay-As-You-Go%20for%20SAP%20BTP". The registration was somehow buggy and I was not able to place the order. However when doing the same thing in the SAP Store with the link "https://store.sap.com/dcp/en/" it worked like a charm. Can you please explain what the issue here is and please remove also my data from the other store? Thanks

Best regards,
Raphael

**Comment by AnnikaGonnermann** [comment]
Dear @RaphaelReply - thanks for pointing out issues with the tutorial. It should be fixed now!

Best
Annika
