### ISSUE TITLE
Set Up SAP Business Application Studio for Development

### ISSUE THREAD

**Issue by Paolaufer** [sap-tutorials/Tutorials#18431]
Tutorials: https://developers.sap.com/tutorials/appstudio-onboarding.html
--------------------------

Hi,
Trial will be sunset very soon.
Could you please update the tutorial so that it does not mention trial? We could update it to fit the Free plan.

Thank you

**Comment by raz-korn** [comment]
Hi @Paolaufer ,

Should the tutorial be sunset and for free-tier users will be referred to the following [tutorial](https://developers.sap.com/group.btp-setup.html)?

Regards - Raz

**Comment by Paolaufer** [comment]
I think we could, since we already have everything we need in the Free tier tutorial.

**Comment by MichaelCzcz** [comment]
@Paolaufer @raz-korn What's the status here? If you want to retire this tutorial, please contact @jmmargo with the details. Also please make sure that this tutorial is not referenced in other places/tutorials.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
