### ISSUE TITLE
Create a Business Configuration App for Factory Calendar Using the ABAP RESTful Application Programming Model

### ISSUE THREAD

**Issue by RPK-GIT** [sap-tutorials/Tutorials#18460]
Mission: https://developers.sap.com/mission.abap-dev-factory-calendar.html
--------------------------

Hi,

The original tutorial describing step by step approach to how to build RAP BO for the factory calendar is missing. It was there till 23rd May 2022, since today it is missing. Now, where can I find the original tutorial?

**Comment by mervey45** [comment]
Hi @RPK-GIT ,

we have update this mission. Unfortunately the first tutorial is missing, but it will be published as soon as posisble as well.

Best regards, 
Merve
