### ISSUE TITLE
Create an Application with SAP AppGyver

### ISSUE THREAD

**Issue by mpredolim** [sap-tutorials/Tutorials#18467]
Mission: https://developers.sap.com/mission.appgyver-low-code.html
--------------------------

Subscription into BTP for AppGyver Boosters is not permitted with Trial accounts.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. There is no issue with the tutorial. You can see from the key symbol in the mission's and tutorials' titles that a parter/customer licence is required.

![image](https://user-images.githubusercontent.com/57144076/170641230-6a014956-9718-47f0-af1d-1b3481ba7f9a.png)
