### ISSUE TITLE
Get an Account on SAP BTP to Try Out Free Tier Service Plans

### ISSUE THREAD

**Issue by ajmaradiaga** [sap-tutorials/Tutorials#18468]
Tutorials: https://developers.sap.com/tutorials/btp-free-tier-account.html
--------------------------

_if you do not own a credit card, you can create a trial account which allows you to try out BTP services in a separated environment but without the free tier model on SAP BTP: [Get a Free Account on SAP BTP Trial](https://developers.sap.com/tutorials/hcp-create-trial-account.html))_

In the prerequisites sections it is suggested to use the trial environment if the users doesn't own a credit card. This can cause some confusion as there are services that are not available on trial but are available as free tier in the productive environment, e.g. SAP Process Automation. Can we please add some additional text explaining that not all free tier services are available in the trial environment and encourage the user to check if the service(s), that they are interested, is available in the trial environment. Note: This is possible via Discovery Center.

Thanks!

**Comment by AnnikaGonnermann** [comment]
Thanks @ajmaradiaga for your suggestion, I appreciate you taking the time to reach out. I will incorporate your feedback with the next update!

Best
Annika
