### ISSUE TITLE
Create a Dev Space for SAP Fiori Apps

### ISSUE THREAD

**Issue by phkulla** [sap-tutorials/Tutorials#18476]
Tutorials: https://developers.sap.com/tutorials/appstudio-devspace-fiori-create.html
--------------------------

Hi,

I followed the tutorial "Build an SAP Fiori App that Consumes Data from an On-Premise System" (https://developers.sap.com/group.appstudio-fiori.html) but in Sub-Tutorial "Create an SAP Fiori App Using SAP Business Application Studio" (https://developers.sap.com/tutorials/appstudio-fioriapps-create.html) Step 3.4 Data Source and Service Selection the ES5 System is not shown in the drop down list.

![pic1](https://user-images.githubusercontent.com/106671342/171398978-f115c832-6e57-453d-a602-2086921ee98b.PNG)

Are there some configuration steps missing in the previous steps?

I have 2 entries in Connectivity - Destinations in the BTP Cockpit

![pic2](https://user-images.githubusercontent.com/106671342/171399326-90d737e5-c470-4865-9bfa-e08d01fdfd96.PNG)

Can someone help me here?

Regards,
Philipp

**Comment by raz-korn** [comment]
Hi @phkulla ,

Can you share a screenshot of the full ES5 destination configuration, including the "additional properties"?

Regards - Raz

**Comment by phkulla** [comment]
Hi,
I found the issue. I had a spelling mistake in one of the parameters.
Thank you
