### ISSUE TITLE
Subscribe to the Low-Code / No-Code Service in SAP BTP

### ISSUE THREAD

**Issue by funnygerman** [sap-tutorials/Tutorials#18478]
Tutorials: https://developers.sap.com/tutorials/appgyver-subscribe-service.html
--------------------------

1. Maybe it's worth to mention in tutorial, that AppGyver isn't available yet on the BTP Trial. 

I was looking for that in there and asked someone from your team and got this answer:
Since AppGyver isn't available yet on the Free Tier of BTP I'd suggest using the Community Edition, which is free and includes the same core functionality: https://appgyver.com/

2. What are then the requirements of the BTP instance so that subscription to the low/no-code service would be possible? I totally missed that.

**Comment by heytombeck** [comment]
Hi - thanks for your feedback. There is only a paid service available on SAP BTP currently, so the tutorial includes a 'Customer / partner license' required tag and mentions the entitlements in the prerequisites. I'll make this more visible though and offer the alternative. 

To purchase the service, see the SAP Discovery Center for more information: https://discovery-center.cloud.sap/serviceCatalog/sap-appgyver?region=europe(frankfurt)&service_plan=standard&tab=feature
