### ISSUE TITLE
Prepare Your Development Environment for SAP Fiori Elements

### ISSUE THREAD

**Issue by ssimsekler** [sap-tutorials/Tutorials#18471]
Tutorials: https://developers.sap.com/tutorials/fiori-tools-cap-prepare-dev-env.html
--------------------------

Hi
The "Test Yourself" question at the end of the tutorial seems to have an old version of dev space types. This may be confusing for people who recently started learning.
Thanks

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
