### ISSUE TITLE
Capture Orders Management Web Application

### ISSUE THREAD

**Issue by Bilaal-ac** [sap-tutorials/Tutorials#18475]
Tutorials: https://developers.sap.com/tutorials/irpa-orders-management-1-capture.html
--------------------------

i am stuck in step 4 and step 5 of this tutorial, the fields i see are different from that of the tutorial, screenshots below. 

![image](https://user-images.githubusercontent.com/106663201/171388467-033d56dd-172e-470a-bfa8-1cfdd87a5471.png)

![image](https://user-images.githubusercontent.com/106663201/171389132-862fc4e7-2209-4a48-83c4-7cd595b0e842.png)

**Comment by celineaudinsap** [comment]
We have updated the tutorial to enable users to explicitly select web in the Filter option and then capture the application:
https://developers.sap.com/tutorials/irpa-orders-management-1-capture.html
