### ISSUE TITLE
Create an SAP Fiori App Using SAP Business Application Studio

### ISSUE THREAD

**Issue by GertSchneider** [sap-tutorials/Tutorials#18488]
Tutorials: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html
--------------------------

In Step 4 (Run the App Locally in the Dev Space) the new tab shows an empty screen instead of the title suppliers:
![image](https://user-images.githubusercontent.com/45477872/172041691-5f34aec5-bf09-49c5-a2e9-2fa090a681e8.png)

There are also a lot of errors in the console:
![image](https://user-images.githubusercontent.com/45477872/172041756-2128d308-4e4c-4975-acd7-7c883f996b31.png)

**Comment by raz-korn** [comment]
Hi @GertSchneider ,

A fix was deployed.
Please re-check - You need to re-do the tutorial from the start.

Regards - Raz

**Comment by GertSchneider** [comment]
Hi @raz-korn ,
the tutorial works now fine completely. Thanks for your help!
Best regards, Gert
