### ISSUE TITLE
Issue while executing Employee Onboarding Sample Scenario

### ISSUE THREAD

**Issue by BaskarThambiayah** [sap-tutorials/Tutorials#18502]
Issue: Error while running the Boosters for Set up account for Workflow Management.

Steps to reproduce this issue:
Tutorial 1: Set Up Workflow Management in Cloud Cockpit (https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-1-setup.html)
 
Step  2: Set up your account using Booster
 
1.	From your global account page, choose the **Boosters** from left-hand navigation. Among the available options, click **Start** of **Set up account for Workflow Management.**

Screenshot of the error:
![image](https://user-images.githubusercontent.com/60343237/172993950-e9e3c8a3-2679-4a7d-ab4b-04f143716391.png)

Observation: 
When we have only one subaccount, the start of Boosters is throwing this error for Set up account for Workflow Management.
If we add one more subaccount in our trial account, it is working fine. 

Kindly look into this issue.

Labels to be added:
Scenario label: SCPTest-eboard
Sprint Label: SCPTest-2206A
Landscape Label: trail2(Trial US East (VA) (AWS) ) & trail3 (AP21 Azure)
Priority: High

Thanks & regards,
Baskar

**Comment by ArchanaShukla** [comment]
I tried this in fresh account in trial account, but I did not see this problem. Please reopen if the issue still exists
