### ISSUE TITLE
Automate  SAP S/4 HANA Cloud Applications using SAP UI5 Recorder

### ISSUE THREAD

**Issue by SAPNickYang** [sap-tutorials/Tutorials#18510]
Tutorials: https://developers.sap.com/tutorials/irpa-recorder-s4hana-cloudapplications-create.html
--------------------------

I encounter error "Cancelling the recording failed. Please relaunch the recorder." in step 6 "Export the recording". The only way to export is to close the recorder and click "Export & Close".

**Comment by celineaudinsap** [comment]
Hello, we are currently checking this problem. Expect an answer next week. Best, Céline

**Comment by celineaudinsap** [comment]
Dear Nick Yank,
Can you send me a screenshot of your error please so I can better assess the issue?
Many thanks,
Céline

**Comment by SAPNickYang** [comment]
Hi Celine,
This error is same as this one 
https://github.com/sap-tutorials/Tutorials/issues/18509
I think this one can be closed or merged to the above one.
