### ISSUE TITLE
Create an SAP Fiori Elements-Based UI

### ISSUE THREAD

**Issue by OJ75** [sap-tutorials/Tutorials#18516]
Tutorials: https://developers.sap.com/tutorials/btp-app-create-ui-fiori-elements.html
--------------------------

Step 3 Modify the UI with OData annotations
Section 3, On the launch page that now comes up, choose the Risks tile:
Expected according to tutorial: A launch page with a Risks tile inside
![image](https://user-images.githubusercontent.com/107467794/173538009-c6a79a79-8ca4-4eec-a8cf-43efc94cb102.png)

What really shows up: The webapp application index.html directly
![image](https://user-images.githubusercontent.com/107467794/173538185-74a3c9c0-dc4b-401b-8d84-c01a78100fd1.png)

**Comment by iwonahahn** [comment]
Thank you so much for taking the time to contribute to this tutorial. We will get back to you asap.
