### ISSUE TITLE
Implement Roles and Authorization Checks In CAP

### ISSUE THREAD

**Issue by OJ75** [sap-tutorials/Tutorials#18518]
Tutorials: https://developers.sap.com/tutorials/btp-app-cap-roles.html
--------------------------

Step 4 is the first section of the page, should be last section

**Comment by iwonahahn** [comment]
Hi @OJ75,

Thank you for reporting it. I will fix it and get back here to close the issue.

Best regards,
Iwona

**Comment by iwonahahn** [comment]
This is fixed now :).
