### ISSUE TITLE
Set Up the SAP HANA Cloud Service

### ISSUE THREAD

**Issue by OJ75** [sap-tutorials/Tutorials#18519]
Tutorials: https://developers.sap.com/tutorials/btp-app-hana-cloud-setup.html
--------------------------

Step 1
Section 1, Add SAP HANA support to your project by running.
The result of the package.json after executing the command looks like:
![image](https://user-images.githubusercontent.com/107467794/173581318-7fc604c3-b3ef-4171-8566-41d2cdd45dc4.png)

According to the tutorial, it should look like:
![image](https://user-images.githubusercontent.com/107467794/173581447-96e2b8d4-d9a2-40a9-b2dc-c9b5373e296e.png)

When you do not update the package.json manually so that it looks like in the tutorial (kind: sql), cds watch failes:
![image](https://user-images.githubusercontent.com/107467794/173582586-0e11df13-f4ee-415c-9844-b65636eab28d.png)

**Comment by iwonahahn** [comment]
Thank you so much for taking the time to contribute to this tutorial. We will get back to you asap.

**Comment by iwonahahn** [comment]
Hi @OJ75,

We have updated the [tutorial](https://developers.sap.com/tutorials/btp-app-hana-cloud-setup.html#8eea9b9b-23f6-457b-88dc-d07890639472) based on your feedback and therefore we close this issue.

Best regards,
Iwona
