### ISSUE TITLE
Add More Than One Application to the Launch Page

### ISSUE THREAD

**Issue by OJ75** [sap-tutorials/Tutorials#18517]
Tutorials: https://developers.sap.com/tutorials/btp-app-launchpage.html
--------------------------

Step 2, Implementation
Section 3, Open the file index.html in an editor and change the following lines:
Expected: The script block mentioned has to be added to the existing html page, not changed.

Furthermore, the bootstrap ui5 script block is missing

And, finally, the "placeAt" script block is also missing in the tutorial.

![image](https://user-images.githubusercontent.com/107467794/173576990-81b8ce93-e3a9-4c37-897b-3f785a378003.png)

**Comment by iwonahahn** [comment]
Thank you so much for taking the time to contribute to this tutorial. We will get back to you asap.

**Comment by manjuX** [comment]
Hi @OJ75,

The tutorial is updated and we now have different instructions for the launchpad due to changes in the generator. We now have instructions to instead add a launch-page from the templates.

Thanks for raising the issue.

Best regards,
Manju
