### ISSUE TITLE
Deploy Your Multi-Target Application (MTA)

### ISSUE THREAD

**Issue by OJ75** [sap-tutorials/Tutorials#18521]
Tutorials: https://developers.sap.com/tutorials/btp-app-cap-mta-deployment.html
--------------------------

Step 6, Exclude CSV files from deployment
"Add the following line to the mta.yaml file:"
You have to add two lines, not only one like mentioned.
The original mta.yaml only contains:
![image](https://user-images.githubusercontent.com/107467794/173586739-729e7dc3-ccdb-46cf-b56b-57a25e4717ba.png)

But it should in the end according to the tutorial contain three lines:
![image](https://user-images.githubusercontent.com/107467794/173586885-d37bc383-b84f-4157-a686-c2e3a5cdde4e.png)

`npm install --production` is missing in the generated yaml-file

**Comment by iwonahahn** [comment]
Thank you so much for taking the time to contribute to this tutorial. We will get back to you asap.

**Comment by iwonahahn** [comment]
Hi @OJ75,

We have updated the [tutorial](https://developers.sap.com/tutorials/btp-app-cap-mta-deployment.html#c8c6134b-2cec-478e-ab67-b978d9f50845) based on your feedback and therefore we close this issue.

Best regards,
Iwona
