### ISSUE TITLE
Set Up Account for Document Information Extraction and Go to Application

### ISSUE THREAD

**Issue by user220621** [sap-tutorials/Tutorials#18538]
Tutorials: https://developers.sap.com/tutorials/cp-aibus-dox-booster-app.html
--------------------------

The booster run into an error. Manual subscription to the service "Document Information Extraction Trial UI" is not possible.

![image](https://user-images.githubusercontent.com/107916521/174750041-bcb3267b-6966-46cb-a4d5-04370d1c1397.png)
![image](https://user-images.githubusercontent.com/107916521/174750275-0507a642-fa7d-4d10-8e60-bb75985dd3b9.png)

**Comment by Juliana-Morais** [comment]
Hello,

I apologize for the inconvenience. The development team is looking into this issue. I'll let you know once it's been fixed.

Best regards,
Juliana

**Comment by Juliana-Morais** [comment]
The issue has been fixed. Booster and manual subscription to "Document Information Extraction Trial UI" is now possible. Please try again.

**Comment by Juliana-Morais** [comment]
The issue has been fixed. Booster and manual subscription to "Document Information Extraction Trial UI" is now possible. Please try again.

**Comment by Juliana-Morais** [comment]
The issue has been fixed. Booster and manual subscription to "Document Information Extraction Trial UI" is now possible. Please try again.
