### ISSUE TITLE
Re-build and re-deploy the .mtar file

### ISSUE THREAD

**Issue by AlexanderSchmidt** [sap-tutorials/Tutorials#18530]
Tutorials: https://developers.sap.com/tutorials/btp-app-launchpad-service.html
--------------------------

I got the an error related to service plan for html5-repo when trying to deploy via 'cf deploy cpapp_1.0.0.mtar':

"Creating service "cpapp-html5-repo-host" from MTA resource "cpapp-html5-repo-host"...
Service operation failed: Controller operation failed: 404 Updating service "cpapp-html5-repo-host" failed: Not Found: Error creating service "cpapp-html5-repo-host" from offering "html5-repo-host" and plan "app-host": Service plan app-host not found."

I tried creating the service manually in BTP COCKPIT which works, but then I get this error during deployment:
"Error determining actions to execute on service "cpapp-html5-repo-host": Service described by MTA resource "cpapp-html5-repo-host" of type [html5-repo-host/app-host] does not match already existing service "cpapp-html5-repo-host" of type [html5-apps-repo/app-host] and needs to be recreated. Use command line option "--delete-services" to enable the deletion of the existing one."

Adding "--delete-services" to the command line results in the first error.

Any help would be appreciated.

/Alex

**Comment by manjuX** [comment]
Hi Alex,

You could try to undeploy it first using:

`cf undeploy cpapp --delete-service-keys --delete-services`.

Also kindly check that you have the following entitlements:
![image](https://user-images.githubusercontent.com/93712176/174548531-5faf6bb5-e722-42ce-90cd-74680a3a47d4.png)

if you still get the same errors please share your mta.yaml.

Best regards,
Manjunath

**Comment by AlexanderSchmidt** [comment]
Hi @manjuX,
Thanks for your reply. I've tried the undeploy command which went successul. 

Unfortunately the error on deploy still persists. Here is the full console output
`C:\Users\Alex\git\sap-tut\cpapp>cf deploy cpapp_1.0.0.mtar
Deploying multi-target app archive cpapp_1.0.0.mtar in org xxxxxxxtrial / space dev as xxxxx..

Uploading 1 files...
  C:\Users\Alex\git\sap-tut\cpapp\cpapp_1.0.0.mtar
OK
Operation ID: d328531b-f0d8-11ec-807e-eeee0a9143f8
Deploying in org "6a9fcae7trial" and space "dev"
Detected MTA schema version: "3"
No deployed MTA detected - this is initial deployment
Detected new MTA version: "1.0.0"
Processing service "cpapp-destination"...
Creating service "cpapp-destination" from MTA resource "cpapp-destination"...
Processing service "cpapp-db"...
Creating service "cpapp-db" from MTA resource "cpapp-db"...
Processing service "cpapp-html5-repo-host"...
Creating service "cpapp-html5-repo-host" from MTA resource "cpapp-html5-repo-host"...
Service operation failed: Controller operation failed: 404 Updating service "cpapp-html5-repo-host" failed: Not Found: Error creating service "cpapp-html5-repo-host" from offering "html5-repo-host" and plan "app-host": Service plan app-host not found.
Processing service "cpapp-uaa"...
Setting service "cpapp-uaa" parameters from "xs-security.json"
Proceeding with automatic retry... (3 of 3 attempts left)
Creating service "cpapp-uaa" from MTA resource "cpapp-uaa"...
Creating service "cpapp-html5-repo-host" from MTA resource "cpapp-html5-repo-host"...
Service operation failed: Controller operation failed: 404 Updating service "cpapp-html5-repo-host" failed: Not Found: Error creating service "cpapp-html5-repo-host" from offering "html5-repo-host" and plan "app-host": Service plan app-host not found.
Proceeding with automatic retry... (2 of 3 attempts left)
Creating service "cpapp-html5-repo-host" from MTA resource "cpapp-html5-repo-host"...
Service operation failed: Controller operation failed: 404 Updating service "cpapp-html5-repo-host" failed: Not Found: Error creating service "cpapp-html5-repo-host" from offering "html5-repo-host" and plan "app-host": Service plan app-host not found.
Proceeding with automatic retry... (1 of 3 attempts left)
Creating service "cpapp-db" from MTA resource "cpapp-db"...
Creating service "cpapp-html5-repo-host" from MTA resource "cpapp-html5-repo-host"...
Service operation failed: Controller operation failed: 404 Updating service "cpapp-html5-repo-host" failed: Not Found: Error creating service "cpapp-html5-repo-host" from offering "html5-repo-host" and plan "app-host": Service plan app-host not found.
1 of 1 done
1 of 1 done
Process failed.`

I am working with a fresh trial account and the entitlements look fine:
![image](https://user-images.githubusercontent.com/5268487/174675430-19d747d3-7709-44e0-8a05-321cc4a6fe1d.png)

Here is my mta.yaml file (which is basically the same as from there https://github.com/SAP-samples/cloud-cap-risk-management/tree/cap-mta-deployment) and the operation log that I was able to download.
[mta.yaml.zip](https://github.com/sap-tutorials/Tutorials/files/8943572/mta.yaml.zip)

Thanks,
Alexander

**Comment by manjuX** [comment]
Hi Alexander,

looking at the logs there seem to be errors with the db creation as well: `Caused by: com.sap.cloudfoundry.client.facade.CloudControllerException: Controller operation failed: 502 Updating service "cpapp-db" failed: Bad Gateway: Error creating service "cpapp-db" from offering "hana" and plan "hdi-shared": CF-ServiceBrokerRequestRejected(10001): Service broker error: Service broker hana-broker failed with: Can not create service instance 'cpapp-db': There is no database available. Ensure that you have a database available in space 'dev' within organization 'xxxxxxxxtrial'.` Do you start your database before deployments?

can you checkout the `logging` branch from the repository as described [here](https://developers.sap.com/tutorials/btp-app-create-directory.html#9089d56e-19da-4e0c-9374-1df57625cb25), and deploy the application?

Best Regards,
Manju

**Comment by iwonahahn** [comment]
Hi @AlexanderSchmidt,

Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. If you still have questions, feel free to open a new issue.

Best regards,
Iwona
