### ISSUE TITLE
Create an Account on the SAP Gateway Demo System

### ISSUE THREAD

**Issue by rdvnatcnibm** [sap-tutorials/Tutorials#18539]
Tutorials: https://developers.sap.com/tutorials/gateway-demo-signup.html
--------------------------

Write here how you think we can improve the tutorial ...

The registration page is not available for the past couple days, could you please fix that?
![Screenshot 2022-06-21 at 10 30 23](https://user-images.githubusercontent.com/85572083/174754261-d799369e-7a72-45e9-a126-ed36e56cff11.png)

**Comment by jung-thomas** [comment]
I've reported the issue with the registration page to our support team. I'll let you know once they have it corrected.

**Comment by jung-thomas** [comment]
The registration page is back now. Sorry for an inconvience.
