### ISSUE TITLE
SAP HANA as the Database for a CAP Java Application

### ISSUE THREAD

**Issue by muru82** [sap-tutorials/Tutorials#18548]
https://developers.sap.com/tutorials/cp-cap-java-hana-db.html

using visual studio for the exercise, faced couple of issues in HDI deployment...
cds deploy --to hana:bookstore-hana failed 

solution:
1.Login to the HANA cloud central and ensure that the HANA instance is running.
2.if you get socket error,
then in the HANA cloud central enable access from all IP address ( by default only access from BTP is allowed, this is just a test setting.. more details see the blog below to add specific IP address)
![image](https://user-images.githubusercontent.com/12719799/175055578-f58ea5c2-1514-4e69-9c05-5e6f88222448.png)

credit:https://blogs.sap.com/2020/10/30/allow-connections-to-sap-hana-cloud-instance-from-selected-ip-addresses-using-the-command-line/

**Comment by iwonahahn** [comment]
Hi @muru82,

Thank you for your contribution. We are always trying to improve our tutorials and will get back to you asap with an update.

Best regards,
Iwona

**Comment by zhangbaiyi** [comment]
Sorry, may I ask that are you using a BTP trial account? I couldn't create HANA instance in this step. There's same [ issue ](https://answers.sap.com/questions/13611189/error-cf-resourcenotfound-creation-of-service-key.html) in the forum. An answer said it is because hdi-shared plan isn't included in trial... But there's a free tier HANA DB, isn't it.

**Comment by muru82** [comment]
Yes i am using the trial account. i see two service in the trial one of them have hdi-shared plan
![image](https://user-images.githubusercontent.com/12719799/176846333-351b65dd-ed2b-48dc-bb99-890b562a381b.png)

**Comment by zhangbaiyi** [comment]
> Yes i am using the trial account. i see two service in the trial one of them have hdi-shared plan did you create the hana cloud instance ? ![image](https://user-images.githubusercontent.com/12719799/176846333-351b65dd-ed2b-48dc-bb99-890b562a381b.png)

I think I'll look into this. I tried to create but not succeeded

**Comment by iwonahahn** [comment]
Hi @muru82,

The dev colleagues are still reviewing the updated content and two new tutorials, so please give us some more time to test it with the latest release. Will get back to you here.

Best regards,
Iwona

**Comment by iwonahahn** [comment]
Hi @muru82,

The issue should be resolved with the update we did yesterday, so I am closing the issue. If you still have questions, feel free to reopen the issue.

Best regards,
Iwona
