### ISSUE TITLE
Create a Reusable Service

### ISSUE THREAD

**Issue by ted9527** [sap-tutorials/Tutorials#18541]
Tutorials: https://developers.sap.com/tutorials/cp-cap-java-reusable-service.html
--------------------------

Write here how you think we can improve the tutorial ...

Two issues:
1. the picture in step5.2 is not right.  There is "npm run deploy" on this picture
2. I follow this guide today at 2022/06/21, NOT in trial account, however, after step6 updating the application.yaml, when I start the app, I got the below error:
 "java.lang.IllegalStateException: Cannot load driver class: org.sqlite.JDBC"

  Then I made this change: **profiles: dev**, then the app could start.

**Comment by iwonahahn** [comment]
Hi @ted9527,

Thank you for your contribution. We are always trying to improve our tutorials and will get back to you asap with an update.

Best regards,
Iwona

**Comment by ted9527** [comment]
Some update from me:
About issue 2, 
The error "java.lang.IllegalStateException: Cannot load driver class: org.sqlite.JDBC" is caused by the driver is not installed at all.
Check <project_name>/srv/pom.xml, add following:
        <dependency>
            <groupId>org.xerial</groupId>
            <artifactId>sqlite-jdbc</artifactId>
        </dependency>

this pom.xml file is different when using "mvn -B archetype:generate" depending on **DarchetypeVersion**
if -DarchetypeVersion=1.17.0, there is sqlite-jdbc dependency in the pom.
However, if -DarchetypeVersion=1.23.1 or DarchetypeVersion=1.25.0, sqlite-jdbc is not in pom.

**Comment by iwonahahn** [comment]
Hi @ted9527,

The dev colleagues are still reviewing the updated content and two new tutorials, so please give us some more time to test it with the latest release. Will get back to you here.

Best regards,
Iwona

**Comment by iwonahahn** [comment]
Hi @ted9527,

The issue should be resolved with the update we did yesterday, so I am closing the issue. If you still have questions, feel free to reopen the issue.

Best regards,
Iwona
