### ISSUE TITLE
Deploy CAP with SAP HANA Cloud project as MTA

### ISSUE THREAD

**Issue by dongtianxiaozi** [sap-tutorials/Tutorials#18543]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-cap-deploy-mta.html
--------------------------

I skipped the user authentication steps (https://developers.sap.com/tutorials/hana-cloud-cap-add-authentication.html) and have deployed cap applications to BTP, but when I try to open application router ( step 6), it shows error 'Not Found' in the browser window.

is xs-security.json file mandatory to deploy into BTP CF?

**Comment by jung-thomas** [comment]
If you skipped a whole tutorial, then this will certainly impact what the final deployment tutorial is telling you to do.  If you never created an XSUAA or xs-security.json, then there are references to things in the deployment tutorial that won't exist.  No, it isn't required to have an xs-security.json to deploy to BTP CF, but this particular project (and it's mta.yaml) expect and reference such a file.

**Comment by jung-thomas** [comment]
So your app router works fine when you test it locally?  And it deploys OK - no errors in the service log?

**Comment by dongtianxiaozi** [comment]
Good day to you! Yes, it works fine when test locally.
App router works fine finally after adjusted xs-app.json file as below:
{
  **"welcomeFile":"interation_items/webapp/index.html",**
  "authenticationMethod": "none",
  "routes": [{
      "source": "/catalog/(.*)",
      "destination": "srv-api",
      "csrfProtection": true
  },
  **{ "source": "/(.*)", "localDir": "." }**
]
}
