### ISSUE TITLE
Create reusuable service - SQLLITE

### ISSUE THREAD

**Issue by muru82** [sap-tutorials/Tutorials#18540]
https://developers.sap.com/tutorials/cp-cap-java-reusable-service.html#55485b03-5e1e-4ca6-9660-c4e02aee7184

i am using visual studio..
i see the sqllite db in my project
![image](https://user-images.githubusercontent.com/12719799/174794917-9c28c612-d441-4453-84bb-73cdba445cbf.png)
if i change the profile from **dev to default then it does not build** 
![image](https://user-images.githubusercontent.com/12719799/174795410-02ff6b66-23b0-4990-b2ce-38ab1df625bf.png)
CURL runs thru and i can query i see data in 
![image](https://user-images.githubusercontent.com/12719799/174795581-f392215b-e3fb-4287-a027-cf57f881a9d7.png)
I tried looking up data in SQLITEDB via extension no data was there.
AdminService.Java is deleted and no longer part of the project
after that i do a CTRL+C and then bring up the application again
now when i query http://localhost:8080/odata/v4/AdminService/Categories(10) .. i do not get data back, so there is no persistence yet
could you please help

**Comment by muru82** [comment]
this was the missing step.. ( if possible please add this to the tutorial)

mvn spring-boot:run -D spring-boot.run.profiles=dev

credit: https://blogs.sap.com/2020/12/08/get-start-for-cap-java/

**Comment by iwonahahn** [comment]
Hi @muru82,

The issue should be resolved with the update we did yesterday, so I am closing the issue. If you still have questions, feel free to reopen the issue.

Best regards,
Iwona
