### ISSUE TITLE
Create a Basic Node.js Application with Express Generator

### ISSUE THREAD

**Issue by MartinStenzig** [sap-tutorials/Tutorials#18555]
Tutorials: https://developers.sap.com/tutorials/basic-nodejs-application-create.html
--------------------------

Step 2 - Feedback 1

From the description in the step, it is not clear where in the existing app you should make the change. I would add something to the explanation like. 

"To make the necessary changes you should navigate to /routes/index.js and replace the current default...
router.get('/', function(req, res, next) {
  res.render('index', { title: 'Express' });
 }); 
... with the following code snippet [the one that is currently in the instructions

Step 2- Feedback 2
The question for step 2 is currently "Can you access the application you deployed into the Kyma runtime?" and my answer No is not valid. I think you have the wrong question in here as up to this point in the tutorial, you have not deployed anything in Kyma yet.

**Comment by TiaXu1122** [comment]
For this point, actually, this is my old version which was attached for an unknown reason. I will follow this issue to let the newest version synced correctly. 

_Step 2- Feedback 2
The question for step 2 is currently "Can you access the application you deployed into the Kyma runtime?" and my answer No is not valid. I think you have the wrong question in here as up to this point in the tutorial, you have not deployed anything in Kyma yet._
