### ISSUE TITLE
Connect Using the SAP HANA Node.js Interface

### ISSUE THREAD

**Issue by dongtianxiaozi** [sap-tutorials/Tutorials#18553]
Tutorials: https://developers.sap.com/tutorials/hana-clients-node.html
--------------------------

in Step 2, face below error when install hana client with command 'npm install @sap/hana-client'. Could you please guide how to resolve below error?

npm ERR! code ELIFECYCLE
npm ERR! errno 3221225477
npm ERR! @sap/hana-client@2.12.25 install: `node checkbuild.js`
npm ERR! Exit status 3221225477
npm ERR!
npm ERR! Failed at the @sap/hana-client@2.12.25 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by danielva** [comment]
Which platform are you installing this on?  
Is there an additional log file with more details?

When searching for that error, there were a few mentions of a check in Node.js for 32 bit Windows.  Noting that the @sap/hana-client Node.js driver supports 64 bit Windows only as mentioned in [3165810 - SAP HANA Client Supported Platforms](https://launchpad.support.sap.com/#/notes/3165810) note. 

Regards,
Dan

**Comment by danielva** [comment]
Can you double check to see if you are running 32-bit Microsoft Windows or 64-bit?  Noting that the driver is not supported under 32-bit Microsoft Windows.

I believe this can be seen in the Windows about dialog.  More details can be found at https://www.howtogeek.com/howto/21726/how-do-i-know-if-im-running-32-bit-or-64-bit-windows-answers/

Regards,
Dan

**Comment by dongtianxiaozi** [comment]
I solved this issue after reinstalled latest nodejs. Hope it helps for other people :)
