### ISSUE TITLE
Use the Cloud Connector to Connect SAP HANA On-Premise to SAP HANA Cloud, SAP HANA Database

### ISSUE THREAD

**Issue by dongtianxiaozi** [sap-tutorials/Tutorials#18576]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-mission-extend-08.html
--------------------------

Dear Team,

During step 4, I can't find below BTP subaccount region in cloud connector administration region list. Could you please guide how to resolve it to process further?

**Region:** Europe (Frankfurt) AWS 2
**API Endpoint:** https://api.cf.eu12.hana.ondemand.com
![Region_Issue](https://user-images.githubusercontent.com/101193065/176566295-6afac51b-f893-4137-90aa-9f17fcf354c8.png)

**Comment by jmmargo** [comment]
@thomashammerSAP as you have taken these over from Christopher, I wanted to being this feedback to your attention.

**Comment by whome000** [comment]
> ## Tutorials: https://developers.sap.com/tutorials/hana-cloud-mission-extend-08.html
> Dear Team,
> 
> During step 4, I can't find below BTP subaccount region in cloud connector administration region list. Could you please guide how to resolve it to process further?
> 
> **Region:** Europe (Frankfurt) AWS 2 **API Endpoint:** https://api.cf.eu12.hana.ondemand.com ![Region_Issue](https://user-images.githubusercontent.com/101193065/176566295-6afac51b-f893-4137-90aa-9f17fcf354c8.png)

Hi,

Sorry for the belated reply and hope you had a chance to resolve the issue.
If not, please find the detailed tutorial for Cloud Connector configuration from the following.
https://learning.sap.com/learning-journeys/connecting-sap-btp-and-on-premise-systems-using-the-cloud-connector

Best regards,
Tae-Suk
SAP HANA Product Management

**Comment by jmmargo** [comment]
Thank you @whome00 for the solution.  As such, I will close this issue.  Please reopen it if needed.
