### ISSUE TITLE
Set Up Workflow Management in Cloud Cockpit

### ISSUE THREAD

**Issue by HS20220630** [sap-tutorials/Tutorials#18577]
Tutorials: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-1-setup.html
--------------------------

On Step2, I got this error message and couldn't continue this tutorial.

"We are sorry, but we have encountered an unexpected internal error. Please try again later."

**Comment by ArchanaShukla** [comment]
This issue no longer exists. Please reopen if it still exists
