### ISSUE TITLE
Configure Business Rules, Workflow and Process Visibility

### ISSUE THREAD

**Issue by ahmedkhan29789** [sap-tutorials/Tutorials#18584]
Tutorials: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-2-configure.html
--------------------------

Hi,
The troubleshooting step only gives a solution when the developer has enabled two-factor authentication, What if the developer has not enabled two-factor authentication and gets "Bad gateway error", I and many new learners are struggling with this step, Can you please help us in resolving "Bad gateway error"

**Comment by ArchanaShukla** [comment]
There are 3 ways to resolve this, if it still exists then reopen this ticket

- If you have 2 FA enabled then you have use password + passcode in the destination password
- You need to have a user in API Business Hub which means that you have to login atleast once
- If you have SAP Universal ID then use this: https://launchpad.support.sap.com/#/notes/3085908
