### ISSUE TITLE
Service broker xsuaa failed : Adding the UI and Approuter Module to the MTA -> Rebuilding and Redeploying

### ISSUE THREAD

**Issue by vran848115** [sap-tutorials/Tutorials#18586]
Hi Team,

Action : Adding the UI and Approuter Module to the MTA -> Rebuilding and Redeploying.

Service broker error: Service broker xsuaa failed with: Error updating application risk-management-Explr!t68758 (Cannot change AppId with update. Old AppId: risk-management-FullStackCloud!t68758 New AppId: risk-management-Explr!t68758)
I am getting error. Please advise.

Attaching screenshot , Operation Log & mta.yaml.

<img width="1505" alt="image" src="https://user-images.githubusercontent.com/33994614/176981548-9f4e5bbe-3f7f-4380-89fa-74edca64812d.png">
[OPERATION (1).log](https://github.com/sap-tutorials/Tutorials/files/9032184/OPERATION.1.log)
[mta (1).txt](https://github.com/sap-tutorials/Tutorials/files/9032189/mta.1.txt)

user: risk-management $ cf deploy risk-management_1.0.0.mtar
Deploying multi-target app archive risk-management_1.0.0.mtar in org a2bfda91trial_explore1-3e2undv2 / space Explr as vishwa.ranjan3********...

Service operation failed: Controller operation failed: 502 Updating service "risk-management-xsuaa" failed: Bad Gateway: CF-ServiceBrokerBadResponse(10001): Service broker error: Service broker xsuaa failed with: Error updating application risk-management-Explr!t68758 (Cannot change AppId with update. Old AppId: risk-management-FullStackCloud!t68758 New AppId: risk-management-Explr!t68758) 

Best Regards,
Vishwa Ranjan

**Comment by vran848115** [comment]
Subsection step :- Adding the UI and Approuter Module to the MTA

**Comment by MichaelCzcz** [comment]
Thanks for the update. You are referring to a learning journey on SAP Learning. This channel, is only for issues with developer tutorials in the Tutorial Navigator.
What you could do is using the feedback button in that learning journey, use the "Get Technical Support" link at the bottom of the page, ask your question in the [SAP Community](https://answers.sap.com/index.html) or tweet your question and reference  [@SAPEDU](https://twitter.com/SAPEDU) and #saplearning.

**Comment by vran848115** [comment]
@MichaelCzcz : What do you mean by "issues with developer tutorials in the Tutorial Navigator."? Could you please point me to it with a link or something ?
I am referring to this . 
https://learning.sap.com/service/media/CLD200_20_en-US_media/CLD200_20_en-US_simulations/sap_wpb/trainer/9_5_3_371/trainer.html#mode=uebung&show=project!PR_AddApproutertoMTA_Ex:uebung&hash=20

I followed this .
<img width="1572" alt="image" src="https://user-images.githubusercontent.com/33994614/177276695-a3f2fa5f-47ff-489b-9c0d-9028441bcafd.png">

**Comment by markushaug** [comment]
Hi Vishwa,

the xsuaa service is defined by the 'xs-security.json' file. Could you please share the content of that file?

Thanks,
Markus

**Comment by MichaelCzcz** [comment]
@vran848115 This is the Tutorial Navigator: https://developers.sap.com/tutorial-navigator.html

**Comment by vran848115** [comment]
Hi @markushaug ,
Thank you for responding. 
Below is from xs-security.json.
<img width="1349" alt="image" src="https://user-images.githubusercontent.com/33994614/177288725-d7501841-6bec-40c4-83ca-7fdb3d64036d.png">

`
{
    "xsappname": "risk-management",
    "tenant-mode": "dedicated",
    "scopes": [
      {
        "name": "$XSAPPNAME.RiskViewer",
        "description": "RiskViewer"
      },
      {
        "name": "$XSAPPNAME.RiskManager",
        "description": "RiskManager"
      }
    ],
    "attributes": [],
    "role-templates": [
      {
        "name": "RiskViewer",
        "description": "generated",
        "scope-references": ["$XSAPPNAME.RiskViewer"],
        "attribute-references": []
      },
      {
        "name": "RiskManager",
        "description": "generated",
        "scope-references": ["$XSAPPNAME.RiskManager"],
        "attribute-references": []
      }
    ]
  }`

**Comment by markushaug** [comment]
Hi @vran848115,

Thanks. This file looks fine. Could you please send me the mta.yaml file as well?

**Comment by vran848115** [comment]
Sure @markushaug .
Here it goes.
`
_schema-version: '3.1'
ID: risk-management
version: 1.0.0
description: "Template for the the SAP Extension Suite Learning Journey"
parameters:
  enable-parallel-deployments: true
build-parameters:
  before-all:
    - builder: custom
      commands:
        - npm ci
        - npx -p @sap/cds-dk cds build --production

modules:
  - name: risk-management-srv
    type: nodejs
    path: gen/srv
    parameters:
      buildpack: nodejs_buildpack
    build-parameters:
      builder: npm-ci
    provides:
      - name: srv-api # required by consumers of CAP services (e.g. approuter)
        properties:
          srv-url: ${default-url}
    requires:
      - name: risk-management-db
      - name: risk-management-xsuaa
      - name: risk-management-destination-service

# -------------------- SIDECAR MODULE ------------------------
  - name: risk-management-db-deployer
   # ------------------------------------------------------------
    type: hdb
    path: gen/db
    parameters:
      buildpack: nodejs_buildpack
    requires:
      # 'hana' and 'xsuaa' resources extracted from CAP configuration
      - name: risk-management-db
      - name: risk-management-xsuaa

# -------------------- APPROUTER -----------------------------
  - name: risk-management-approuter
    # ------------------------------------------------------------
    type: nodejs
    path: approuter
    requires:
     - name: risk-management-xsuaa
     - name: srv-api
       group: destinations
       properties:
        forwardAuthToken: true
        strictSSL: true
        name: srv-binding
        url: "~{srv-url}"
    build-parameters:
      requires:
        - name: risk-management-app
          artifacts:
          - ./*
          target-path: resources
# -------------------- UI -----------------------------------
  - name: risk-management-app
    # ------------------------------------------------------------
    type: html5
    path: app
    build-parameters:
      supported-platforms: []
 
resources:
  - name: risk-management-db
    type: com.sap.xs.hdi-container
    parameters:
      service: hana # or 'hanatrial' on trial landscapes
      service-plan: hdi-shared
    properties:
      hdi-service-name: ${service-name}

  - name: risk-management-xsuaa
    type: org.cloudfoundry.managed-service
    parameters:
      service: xsuaa
      service-plan: application
      path: ./xs-security.json
      config:
        xsappname: 'risk-management-${space}'
        role-collections:
        - name: 'RiskManager-${space}'
          description: Manage Risks
          role-template-references:
          - $XSAPPNAME.RiskManager
        - name: 'RiskViewer-${space}'
          description: View Risks
          role-template-references:
          - $XSAPPNAME.RiskViewer

# ------------------------------------------------------------
  - name: risk-management-destination-service
    # ------------------------------------------------------------
    type: org.cloudfoundry.managed-service
    parameters:
      service: destination
      service-plan: lite
`

**Comment by vran848115** [comment]
mta (1).yaml

**Comment by vran848115** [comment]
Here is the path :- https://github.com/vran848115/risk-management/blob/main/mta%20(1).yaml [https://github.com/vran848115/risk-management/blob/main/mta%20(1).yaml](url)

**Comment by vran848115** [comment]
Thank you for your time @markushaug , it is resolved.
I needed to unbind and delete the binding of xsuaa in the cockpit.

**Comment by markushaug** [comment]
Great to hear, that you were able to resolve it!

**Comment by markushaug** [comment]
That looks fine. Please also show me the content of your mta.yaml file. 

Thanks, 
Markus
