### ISSUE TITLE
Create an Application with SAP AppGyver

### ISSUE THREAD

**Issue by dongtianxiaozi** [sap-tutorials/Tutorials#18581]
Tutorials: https://developers.sap.com/tutorials/appgyver-create-application.html
--------------------------
AppGyver app created from BTP AppGyver platform is crashed after installed on android emulator app with below error: 

Could you pls help?

btw, I didn't face such issue for AppGyver standalone platform.

`2022-06-30 22:50:16.995 7485-7485/com.skfirebase.app E/LoadedApk: Unable to instantiate appComponentFactory
    java.lang.ClassNotFoundException: Didn't find class "com.skfirebase.app.appComponentFactoryFix" on path: DexPathList[[zip file "/data/app/com.skfirebase.app-HEA7Oyk9_majLk31rHs19w==/base.apk"],nativeLibraryDirectories=[/data/app/com.skfirebase.app-HEA7Oyk9_majLk31rHs19w==/lib/x86, /data/app/com.skfirebase.app-HEA7Oyk9_majLk31rHs19w==/base.apk!/lib/x86, /system/lib]]`

**Comment by heytombeck** [comment]
Thanks for raising this. I'll ask the development team for more information.

**Comment by heytombeck** [comment]
Hi - the development team have asked you to try to disable your Firebase data/auth/connector and then attempt the tutorial example. This isn't a prerequisite / a part of the steps for this specific example currently.

**Comment by dongtianxiaozi** [comment]
> Hi - the development team have asked you to try to disable your Firebase data/auth/connector and then attempt the tutorial example. This isn't a prerequisite / a part of the steps for this specific example currently.

The tutorial is good. That's only the name with 'firebase' :). I tried to build the appgyver app without firebase auth/message/connection. The apk file is still failed when open it in my android emulator. Can you please guide who can help me on this issue?

**Comment by heytombeck** [comment]
The development contact asked for you to check this: https://docs.appgyver.com/docs/google-firebase (especially the first video) and try again.
 
 In case the issue persists, please submit your problem as a bug report to https://tracker.appgyver.com/.
