### ISSUE TITLE
Configure Launchpad

### ISSUE THREAD

**Issue by audrey-j07** [sap-tutorials/Tutorials#18599]
Tutorials: https://developers.sap.com/tutorials/spa-configure-launchpad.html
--------------------------

Hi team,
First, thank you for making such a useful tutorial on the very latest product and feature!

For launchpad service, to use the SPA pages, I encounter some error for Visibility Scenario Dashboard, Process Trigger. I managed to find a [tutorial](https://blogs.sap.com/2022/03/08/configure-process-visibility-dashboard-integration-with-fiori-launchpad-part-7/comment-page-1/#comment-630448) on how to configure Process Trigger to direct to form correctly. But for Visibility Scenario Dashboard, I use the same method - create a local copy, put in scenarioID, I still encounter error. Another HTML5 app from SPA - Visibility Scenario Instances, I'm not sure when to use it and how to make it visible to the group in Launchpad, it seems has some restriction on showing.
![Error message](https://user-images.githubusercontent.com/100930555/177906367-d49f7e9d-956f-4475-a209-fbb24fd17d42.PNG)
![Visibility Scenario Instances missing](https://user-images.githubusercontent.com/100930555/177907069-f7bc398a-60f4-4408-9fe9-abc1c287676d.png)

Therefore, I have a few ask here for this tutorial, can you help:
1. To add in Process Trigger configuration
2. To add in Visibility Scenario Dashboard configuration
3. To add in Visibility Scenario Instances configuration

Your help is much appreciated!

Regards,
Audrey

**Comment by shielddz** [comment]
I will be checking this issue and come back to you soon.

**Comment by shielddz** [comment]
Hi Audrey,

Sorry for the late reply. The tutorial was updated end of last week, please check again the last part of the tutorial [Configure Launchpad](https://developers.sap.com/tutorials/spa-configure-launchpad.html) and comeback to us if the issue still persists.

**Comment by audrey-j07** [comment]
@shielddz thank you so much for the update!

**Comment by jmmargo** [comment]
This tutorial has been removed from production.
