### ISSUE TITLE
Develop Your First SAPUI5 Web App on Cloud Foundry

### ISSUE THREAD

**Issue by vladimirkosmos** [sap-tutorials/Tutorials#18597]
Mission: https://developers.sap.com/mission.sapui5-cf-first.html
--------------------------

Hi! Missing link in tutorial
![image](https://user-images.githubusercontent.com/104683816/177803762-ba5655c8-5c52-4eca-aaf0-9d9ccf60011a.png)

**Comment by jmmargo** [comment]
I have created an AEM record so this is now published with link.
