### ISSUE TITLE
Create a Developer User in SAP BTP ABAP Environment

### ISSUE THREAD

**Issue by norikoszilagy** [sap-tutorials/Tutorials#18598]
Tutorials: https://developers.sap.com/tutorials/abap-environment-developer-user.html
--------------------------

The app "Maintain Employees" is not found.

**Comment by niloofar-flothkoetter** [comment]
did you login with the Administrator user in the dashboard? and which system are you using?

**Comment by norikoszilagy** [comment]
Hi.

I was just following the steps mentioned in the tutorial.  I don’t think I logged in with the administrator user.

Noriko

From: Niloofar Flothkoetter ***@***.***>
Sent: Friday, July 8, 2022 12:06 AM
To: sap-tutorials/Tutorials ***@***.***>
Cc: Szilagy, Noriko ***@***.***>; Author ***@***.***>
Subject: [External] Re: [sap-tutorials/Tutorials] Create a Developer User in SAP BTP ABAP Environment (Issue #18598)

This message is from an EXTERNAL SENDER - be CAUTIOUS, particularly with links and attachments.
________________________________


did you login with the Administrator user in the dashboard? and which system are you using?

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sap-2Dtutorials_Tutorials_issues_18598-23issuecomment-2D1178632781&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=Rv1hkFuc9unuq2NClzEfntEjdY9UtDejLGSk1D0Mt6M&m=nEXJ3btrVRxv7z5odvTKpx4Lo9OSI6FFKpoae5LPe8NBxk2b2syoT5axSLiLpPMR&s=kRvJsjXIbjyBgZv7g4RG9FJJX4CGTpJE9APwXDCrsUM&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AWAMZEN5BR55IQGSRNPPWLDVS7HPDANCNFSM527BUGXQ&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=Rv1hkFuc9unuq2NClzEfntEjdY9UtDejLGSk1D0Mt6M&m=nEXJ3btrVRxv7z5odvTKpx4Lo9OSI6FFKpoae5LPe8NBxk2b2syoT5axSLiLpPMR&s=-n5qVf6JyqXm86VjWe0yOO2hL-UOc_6pkyoFZOB33ts&e=>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

________________________________

This message is for the designated recipient only and may contain privileged, proprietary, or otherwise confidential information. If you have received it in error, please notify the sender immediately and delete the original. Any other use of the e-mail by you is prohibited. Where allowed by local law, electronic communications with Accenture and its affiliates, including e-mail and instant messaging (including content), may be scanned by our systems for the purposes of information security and assessment of internal compliance with Accenture policy. Your privacy is important to us. Accenture uses your personal data only in compliance with data protection laws. For further information on how Accenture processes your personal data, please see our privacy statement at https://www.accenture.com/us-en/privacy-policy.
______________________________________________________________________________________

www.accenture.com

**Comment by niloofar-flothkoetter** [comment]
You will need admin rights to be able to see and manage "Maintain Employees". Step2-4: Login with admin user and password in SAP Fiori Launchpad.
A developer user has no access to the "Maintain Employees" App.
You may ask for the admin user or administration rights on your system.

**Comment by norikoszilagy** [comment]
Hi.

I am just following the steps on the tutorial using SAP Trial system.  Will you please add the step to give myself the admin rights?

Noriko

From: Niloofar Flothkoetter ***@***.***>
Sent: Monday, July 11, 2022 12:12 AM
To: sap-tutorials/Tutorials ***@***.***>
Cc: Szilagy, Noriko ***@***.***>; Author ***@***.***>
Subject: [External] Re: [sap-tutorials/Tutorials] Create a Developer User in SAP BTP ABAP Environment (Issue #18598)

This message is from an EXTERNAL SENDER - be CAUTIOUS, particularly with links and attachments.
________________________________


You will need admin rights to be able to see and manage "Maintain Employees". Step2-4: Login with admin user and password in SAP Fiori Launchpad.
A developer user has no access to the "Maintain Employees" App.
You may ask for the admin user or administration rights on your system.

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sap-2Dtutorials_Tutorials_issues_18598-23issuecomment-2D1180046458&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=Rv1hkFuc9unuq2NClzEfntEjdY9UtDejLGSk1D0Mt6M&m=uRH-tkImEvC5hz3OpiYw2utMMpTp9BjdAAHAXByJuERFM70inKtM_-BphzrOhwpx&s=1sLezMtaRLU5yy7GsBgYcMRmsKMlcaGYL62_-VI420Q&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AWAMZEOOQWEBN7ECN6RL4GDVTPCNVANCNFSM527BUGXQ&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=Rv1hkFuc9unuq2NClzEfntEjdY9UtDejLGSk1D0Mt6M&m=uRH-tkImEvC5hz3OpiYw2utMMpTp9BjdAAHAXByJuERFM70inKtM_-BphzrOhwpx&s=T3lkcQVwiZ5sQDYED0VxHlVa9S7KkwMzQK0GNZuOYEI&e=>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

________________________________

This message is for the designated recipient only and may contain privileged, proprietary, or otherwise confidential information. If you have received it in error, please notify the sender immediately and delete the original. Any other use of the e-mail by you is prohibited. Where allowed by local law, electronic communications with Accenture and its affiliates, including e-mail and instant messaging (including content), may be scanned by our systems for the purposes of information security and assessment of internal compliance with Accenture policy. Your privacy is important to us. Accenture uses your personal data only in compliance with data protection laws. For further information on how Accenture processes your personal data, please see our privacy statement at https://www.accenture.com/us-en/privacy-policy.
______________________________________________________________________________________

www.accenture.com

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
