### ISSUE TITLE
Use SAP HANA as the Database for a CAP Java Application

### ISSUE THREAD

**Issue by jcarter-sap** [sap-tutorials/Tutorials#18603]
Tutorials: https://developers.sap.com/tutorials/cp-cap-java-hana-db.html
--------------------------

I have completed all the previous steps for tutorial, but am unable to complete this stage.

I am able to set my CF endpoint, and login in using my SAP credentials (using trial account).

I have installed @sap/hdi-deploy and updated my .cdsrc.json

but when I run CDS deploy:

```
user: bookstore $ cds deploy --to hana:bookstore-hana
[deploy] - Starting deploy to SAP HANA ...
[deploy] -
[deploy] - Creating build tasks
[cds] - determining build tasks for project [/home/user/projects/bookstore].
[cds] - the following build tasks will be executed
[cds] -    {
     "build": {
       "target": ".",
       "tasks": [
         {"for":"java-cf", "src":"srv", "options":{"model":["db","srv"]}}
       ]
     }
   }

[deploy] - Running build
[cds] - building project [/home/user/projects/bookstore], clean [true]
[cds] - cds [5.8.3], compiler [2.15.4], home [/extbin/npm/globals/lib/node_modules/@sap/cds]

[cds] - done > wrote output to:
   db/src/gen/.hdiconfig
<truncated>
   db/src/gen/sap.common.Currencies_texts.hdbtable

[cds] - build completed in 456 ms

[deploy] -
[deploy] - Using container bookstore-hana
[deploy] - Getting service bookstore-hana
[ERROR] CF-ResourceNotFound: Creation of service key failed (10010)
```

[I have tried creating the database manually, and sharing the database into my dev space with no change.  ](https://sap.stackenterprise.co/questions/17630)

Is there a specific set of instructions I could follow to resolve this?

**Comment by jcarter-sap** [comment]
Hi @manjuX 

Thanks for the suggestion!  I don't have any any DB instances at the moment and the same problem occurs.  I've tried the following to resolve:

- follow the tutorial as written, believing it will create the database and connect it for me (via CF).  I was able to inspect that the DB was there, and was configured as expected but still fails at service key creation.
- created the database manually, and having multiple databases, including the one created by CF.
- creating a database, deleting all other instances.

Looks to be the same result in all cases.

Is there a set of explicit manual steps I can follow to replicate what CF is doing that might help with diagnosis?

**Comment by manjuX** [comment]
Hi @jcarter-sap ,

For clarity, In the third case did you create a Hana Instance in Hana Cloud Central and had only one database there?

Because when you run the command it creates a "HDI container" in an existing Hana instance.

Here is an example of the two types when I run `cf services`:
![image](https://user-images.githubusercontent.com/93712176/178451742-81d817f0-08ef-4c9f-8697-82720d5c5510.png)

Here `cpapp-db` is the hdi-container that got automatically created for me in my `cpapp` database instance.

Best regards,
Manju

**Comment by jcarter-sap** [comment]
Hi,

Thanks for your help -- I've unblocked myself.

The link you posted previously allowed me to move forward.  I created the database manually, and then created an cdi-shared instance linked via the database UUID.

I think this step is missing from the tutorial, or in most cases does it happen automatically?
