### ISSUE TITLE
Create Custom Analytical Queries

### ISSUE THREAD

**Issue by Jessie00000** [sap-tutorials/Tutorials#18601]
Tutorials: https://developers.sap.com/tutorials/abap-custom-analytical-queries.html
--------------------------

Write here how you think we can improve the tutorial ...

The prerequisite seems not correct. It mentioned "The Business user requires the Role SAP_CA_BC_ANA_AQD_PC to access the Query Designer." However this role is not existing. As checked in fiori apps library (https://fioriappslibrary.hana.ondemand.com/sap/fix/externalViewer/#/detail/Apps('F1572')/S12OP), the role should be SAP_BR_ANALYTICS_SPECIALIST. And the business catalog is SAP_CA_BC_ANA_AQD. So I think it was a mistake.

**Comment by mervey45** [comment]
Hi @Jessie00000 ,

thank you for your feedback, we'll update this information as soon as possible.

Best regards, 
Merve
