### ISSUE TITLE
Create a Portal Site

### ISSUE THREAD

**Issue by nicoschoenteich** [sap-tutorials/Tutorials#18614]
Tutorials: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-create-site.html
--------------------------

Hi there, not sure if it's a problem on my end but I don't see the "Pages" tab in step 3.1 (see below screen shot). I do have the `Portal_Admin` role assigned to my user. Any idea why that is?

![Screenshot 2022-07-14 at 10 44 21](https://user-images.githubusercontent.com/65965098/178941642-6755eb86-f458-4326-9545-d18ed123412b.png)

**Comment by LindsayBert** [comment]
Hi sorry for not replying earlier - I was on vacation and missed the notification.  The Portal tutorials have been replaced by the Launchpad tutorials.  Please try this mission instead: https://developers.sap.com/mission.launchpad-cf.html 

Thanks
Lindsay

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by nicogeburek** [comment]
Thanks a lot @LindsayBert, but the [UI theme designer documentation](https://help.sap.com/docs/BTP/09f6818d8e064537973102d6289e2aca/26c100668d0047af9db9141ab1d92571.html?locale=en-US) is still linking to this tutorial, so you might want to replace that link, too.

**Comment by LindsayBert** [comment]
Hi - thanks for letting me know.
I'm not the author of the UI theme designer documentation but I will try and find out who it is.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
