### ISSUE TITLE
Protect Your API Proxy by Adding Application Key Verification

### ISSUE THREAD

**Issue by horsemanjackyliu** [sap-tutorials/Tutorials#18613]
Tutorials: https://developers.sap.com/tutorials/hcp-apim-create-product.html
--------------------------

When I Click Publish, the error Unable to publish Product alwatys shows .  I have assigned my self all the role collection with APIM .

Jacky Liu

**Comment by I501000** [comment]
in browser dev tool, the error is 

he following problem occurred: HTTP request failed400,Bad Request,{"error":{"code":"DEV_PORTAL_ONBOARDING_PENDING","message":{"lang":"en","value":"The current operation failed because {0} is not setup completely. Please setup {0}. Retry once done."}}}

**Comment by kulkarnir** [comment]
Hello Jacky, 

Can you please try to launch **API Business Hub Enterprise**(old name developer portal). Click on **Navigation link**  present in the top right corner & select API Business Hub Enterprise. 

Try after you launch the API Business Hub Enterprise, if this did not work please let me know the error 

![image](https://user-images.githubusercontent.com/26405634/178941026-2bee6dc7-c04f-4b60-a636-da411e0f500a.png)

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
