### ISSUE TITLE
Access destination from BTP in vscode

### ISSUE THREAD

**Issue by aliasad466** [sap-tutorials/Tutorials#18619]
Hello, I have seen some resources on how to access destinations from BTP in BAS. But one thing is confusing to me, lets say I have oauth protected CAP service deployed on a BTP space. I want to create a FIORI Elements app based on the CAP OData service. How can I do that in Vscode? for BAS, I can make use of the destination while generating the app. not sure how the same could be done in vscode?

**Comment by MichaelCzcz** [comment]
@aliasad466 Please provide the name of the tutorial you are haven problems with. Thank you.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
