### ISSUE TITLE
Add Transactional Behavior to Your Core Data Services

### ISSUE THREAD

**Issue by jung-thomas** [sap-tutorials/Tutorials#18624]
Tutorials: https://developers.sap.com/tutorials/abap-environment-transactional-enablement.html
--------------------------

Step 5 - the implementation of the behavior class provided by the tutorial results in a short dump.  

```
Error analysis
The application has indicated exception "CX_SADL_DUMP_APPL_MODEL_ERROR" as the reason for the
termination:
Processing was aborted because of an application modeling error: See previous in exception chain.
The exception is related to the previous exception "CX_SADL_GW_V2_FATAL_REQUEST" that occurred in
program "SAPMHTTP", in line 0 of include "???". The reason for this exception
was:
Fatal error in SADL OData v2 request processing (mapping provider 'ZS_BOOKING_TPJ')
The exception is related to the previous exception "CX_RAP_HANDLER_NOT_IMPLEMENTED" that occurred in
program "CL_RAP_BHV_PROCESSOR==========CP", in line 23 of include "CL_RAP_BHV_PROCESSOR==========CM01G". The reason for this exception
was:
Handler not implemented; Method: INSTANCE_AUTHORIZATION, Involved Entities: ZI_BOOKING_TPJ

Information on where terminated
The termination occurred in ABAP program or include "CL_SADL_SHORTDUMP=============CP", in "TRIGGER_APPL_MODEL_ERROR_DUMP". The
main program was "SAPMHTTP".
```

This even shows as problem in the Behavior Definition:
![image](https://user-images.githubusercontent.com/12159356/179366674-148dc895-9886-47de-b733-0137c0aa4be5.png)

The quick fix for this problem does insert an empty get_instance_authorization into the behavior class and then the short dumps no longer occur.
![image](https://user-images.githubusercontent.com/12159356/179366722-b5d00558-2cd6-433f-8054-8d6a2eae1665.png)

**Comment by mervey45** [comment]
Hi @jung-thomas ,

thank you for your feedback, I will update this tutorial as soon as possible.

Best regards, 
Merve
