### ISSUE TITLE
Create an SAP Fiori Elements-Based UI

### ISSUE THREAD

**Issue by OlMue** [sap-tutorials/Tutorials#18634]
Tutorials: https://developers.sap.com/tutorials/btp-app-create-ui-fiori-elements.html
--------------------------

Hi,
in Step 4 (_Make header info editable_), Point 2 (_To add a Mitigation, click on the value help icon in the input field..._), I don't see the input help under _Items_. I clicked on the input help icon, the _Mitigations_ window opens, but the available values aren't shown.

This is what it looks like:

![Snag_1e271ad](https://user-images.githubusercontent.com/39769800/179779198-edbb1d36-a9d6-484b-b0fa-06407593c45b.png)

However, if I type in _Embargo [...]_ on the main screen, I can select the mitigation types:

![Snag_1e39ec3](https://user-images.githubusercontent.com/39769800/179779483-e59c2dd0-d34c-45dc-94d0-2d0c982e94e1.png)

So, the data is there, it's just not displayed as the input help as described in the tutorial step. After that, everything is fine again.

**Comment by manjuX** [comment]
Hi @OlMue ,

Can you check that you are using the latest version of the `SAP Fiori Tools - Extension Pack`? The version I have is `1.6.7`. If its up to date then I would like to check your UI Annotations. If you are storing your code on GitHub Please share the link or share the file `risk-service-ui.cds`. This file contains the annotations to use the `description` property in the mitigations value help as described [here](https://developers.sap.com/tutorials/btp-app-create-ui-fiori-elements.html#814dcfd1-a2e7-41c0-8819-13423b210f88).

Best regards,
Manju

**Comment by OlMue** [comment]
Hi @manjuX ,

Thanks for your answer! Nice to talk to you here. ;-)

I also have `1.6.7` for the extension pack. Please find attached the `risk-service-ui.cds`. I had copied it from the `tutorial\templates\create-ui-fiori-elements\srv` folder with no changes. Just in case, I also attached the entire `cpapp` project.

[risks-service-ui.zip](https://github.com/sap-tutorials/Tutorials/files/9182537/risks-service-ui.zip)
[cpapp.zip](https://github.com/sap-tutorials/Tutorials/files/9182513/cpapp.zip)

Thanks!
Oliver

**Comment by manjuX** [comment]
Hi @OlMue ,

Likewise, Thank you for trying out the tutorial and providing feedback :).

Thanks for providing the entire project, There seems to be an issue with the particular version of UI5 used (1.104.0) and I was able to replicate your issue with that version. To fix the issue please generate the Fiori Elements app with the latest version `1.104.1`. 

First delete the risks application,
  1. Invoke the Command Palette by selecting it from: View -> Command Palette or typing Ctrl + Shift + P.
  2. Type "Fiori: Delete Application from CAP Project.
  3. A list of applications from the current folder will be shown, click on the Risks application and select yes if you get a dialog asking to confirm the deletion.

Then generate the application again but select the latest version which is currently `1.104.1`.

Hope this helps.

Best regards,
Manju

**Comment by OlMue** [comment]
Hi @manjuX , this did the trick! Thanks for your help.
Best regards,
Oliver
