### ISSUE TITLE
Configure Authentication and Authorization on SAP BTP

### ISSUE THREAD

**Issue by kamng** [sap-tutorials/Tutorials#18638]
Tutorials: https://developers.sap.com/tutorials/cp-cap-java-security-cf.html
--------------------------

Write here how you think we can improve the tutorial ...
In Step 4: Set up REST client for testing on SAP BTP
update step 4
.... select OAuth 2.0 for the field Type and **Request Header** for field **Add auth data to**

**Comment by beckermarc** [comment]
The value `Add auth data to` for field `Request Header` is the default in my case. Wasn't this the case in your scenario?

**Comment by kamng** [comment]
For some unknown reason, it changed to Request URL for me while I setup the OAuth 2.0, I think it better to explicitly indicate it in the step since it is not show in the screenshot.

**Comment by beckermarc** [comment]
Okay, thanks for the clarification. We will add a hint to the tutorial :)

**Comment by iwonahahn** [comment]
Hi @kamng,

the hint was added in the tutorial.

Best reagrds,
Iwona
