### ISSUE TITLE
Create an SAPUI5 App from the Command Line

### ISSUE THREAD

**Issue by miroslavpetrovic** [sap-tutorials/Tutorials#18654]
Tutorials: https://developers.sap.com/tutorials/cp-cf-sapui5-local.html
--------------------------

Hi Colleagues,

I am facing an issue while trying to start webapp locally.

Step 3

Test the webapp locally

npm start

I followed the tutorial and installed all prerequisites but can not figure out what the issue is. Everything seems ok in ui5.yaml and package.json files when it comes to the ui5-middleware-livereload. I have attached the command output.

Best,

Miro
[npm start.txt](https://github.com/sap-tutorials/Tutorials/files/9183076/npm.start.txt)

**Comment by nicogeburek** [comment]
Hi Miro,
Can you try and delete the `package-lock.json` file as well as the `node_modules` directory and do a fresh `npm install`?
Also, can you please run `yo easy-ui5 --plugins` to log all relevant versions you are using?
BR, Nico

**Comment by miroslavpetrovic** [comment]
Hi Nico, 

if I remove the node_modules I can not run the npm install command any more.

C:\Windows\System32\com.myorg.nico>npm install
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js'
←[90m    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:778:27)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)←[39m
←[90m    at node:internal/main/run_main_module:17:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []
}

I also tried removing nodejs and installing it again.

Here is the output of the yo easy-ui5 --plugins
Node.js: v16.16.0
yeoman-environment: 3.9.1
generator-easy-ui5: 3.4.0
home: C:\Users\I504091\AppData\Roaming\npm\node_modules\generator-easy-ui5
pluginsHome: C:\Users\I504091\AppData\Roaming\npm\node_modules\generator-easy-ui5\plugin-generators

Available generators:
  - generator-ui5-project: 0.2.0
Best,

Miro

**Comment by nicogeburek** [comment]
Hi Miro, are you sure you are in the right directory (the root level of your UI5 application that has been generated) when running `npm install`?

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
