### ISSUE TITLE
Prepare Your Kyma Development Environment

### ISSUE THREAD

**Issue by maxstreifeneder** [sap-tutorials/Tutorials#18661]
Tutorials: https://developers.sap.com/tutorials/btp-app-kyma-prepare-dev-environment.html
--------------------------

Hey! seems like one of the links is broken. 

Step 4: _In case you experience problems running the commands, check [Command Line Interpreters](https://developers.sap.com/tutorials/btp-app-_command-line-interpreters.html) for more details on recommended CLIs._

**Comment by manjuX** [comment]
Hi @maxstreifeneder ,

Thank you for reporting this issue, We'll fix the broken link. In the meantime the right link is `step 2` in the tutorial [here](https://developers.sap.com/tutorials/btp-app-set-up-local-development.html#69e6093a-9876-411b-84ec-9c4f86024f83).

Best Regards,
Manju

**Comment by manjuX** [comment]
Hi @maxstreifeneder ,

The link has been fixed so I am closing this issue. Please reopen the issue if you need further support.

Best regards,
Manju
