### ISSUE TITLE
Get an Account on SAP BTP to Try Out Free Tier Service Plans

### ISSUE THREAD

**Issue by beapasch** [sap-tutorials/Tutorials#18669]
Tutorials: https://developers.sap.com/tutorials/btp-free-tier-account.html
--------------------------
The first step of the tutorial needs to be updated as the SAP Store offers two models now: 
Scroll down to Plans and Pricing and select Start Now.

Start now isn't available but you need to select the Paygo or CPEA model.

**Comment by AnnikaGonnermann** [comment]
Thanks @beapasch . The changes are adapted and will be published with the next release. Expect some time in between. Best Annika

**Comment by AnnikaGonnermann** [comment]
Thanks @beapasch, changes are now visible!
