### ISSUE TITLE
Expose Integration Flow Endpoint as API and Test the Flow

### ISSUE THREAD

**Issue by edwin7** [sap-tutorials/Tutorials#18672]
Tutorials: https://developers.sap.com/tutorials/cp-starter-isuite-api-management.html
--------------------------

I can not find package Connect to SAP Business Technology Platform Services under Discover.

**Comment by Karunaharan** [comment]
@edwin7 - do you mean that you are not able to find the package in the API Portal Discover space? Or in the Cloud Integration Discover space? In this step, you are requested to find the package in the API Portal Discover space.
Could you please try again and let me know?

Regards,
Karuna

**Comment by Karunaharan** [comment]
Hello @edwin7 - I checked sometime back and I was able to find the package "Connect to SAP Business Technology Platform Services" in the API Portal Discover space. Could you please check again?

**Comment by edwin7** [comment]
<img width="1915" alt="Screenshot 2022-08-01 at 18 59 30" src="https://user-images.githubusercontent.com/709198/182143179-d9d3da0b-acd3-4af7-96c3-173189ceb784.png">

No package found. Am I in the right page?
