### ISSUE TITLE
Set Up SAP HANA Cloud for Kyma

### ISSUE THREAD

**Issue by HamzaM1** [sap-tutorials/Tutorials#18675]
Tutorials: https://developers.sap.com/tutorials/btp-app-kyma-hana-cloud-setup.html
--------------------------

The "[Create a Live Account](https://developers.sap.com/tutorials/btp-app-_create-a-live-account.html)." link at the bottom of the page is not working. I think the tutorial was deleted?

**Comment by manjuX** [comment]
Hi @HamzaM1 ,

Thank you for reporting this issue, we will fix the link. In the meantime the correct link is [here](https://developers.sap.com/tutorials/btp-app-kyma-prepare-btp.html#f8247c01-6348-4090-ad41-43a4795363a3), Then you need to go to Step 3: `Create a Live Account`.

Best regards,
Manju

**Comment by manjuX** [comment]
Hi @HamzaM1 ,

The link has been fixed, so I am closing this issue.

Best regards,
Manju
