### ISSUE TITLE
Create a Directory for Development

### ISSUE THREAD

**Issue by sakodeve** [sap-tutorials/Tutorials#18676]
Tutorials: https://developers.sap.com/tutorials/btp-app-create-directory.html
--------------------------

branch name not mentioned

Write here how you think we can improve the tutorial ...

**Comment by iwonahahn** [comment]
Hi @sakodeve,

Thank you for your feedback. We are closing the issue. If you still have questions, feel free to open a new issue.

Best regards,
Iwona
