### ISSUE TITLE
Set Up Your SAP Cloud Integration Tenant

### ISSUE THREAD

**Issue by griveraa** [sap-tutorials/Tutorials#18671]
Hello Team,
I am facing issues with my Tenant provisioning. It is getting stuck after completion of 80 percent. I closed the browser & retried multiple times. But I can see the same problem persists.
Here are my trial account details:
Global Account: afc9be95trial
Subaccount: trial
Error Message:
Tenant provisioning is in progress and it can take 60 minutes. Please wait for the provisioning to complete before creating service broker instances.
![image](https://user-images.githubusercontent.com/81275484/181793043-6a5fb503-ee20-40a2-a642-57ad3766e479.png)

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. These GitHub issues are to resolve issues (i.e., problems/errors) with the tutorials. Your question seems more general and likely 
would get more visibility -- and a better answer -- in the SAP Community's Questions & Answers. You can ask your question at:
https://answers.sap.com/index.html
