### ISSUE TITLE
Set Up SAP HANA Cloud for Kyma

### ISSUE THREAD

**Issue by HamzaM1** [sap-tutorials/Tutorials#18688]
Tutorials: https://developers.sap.com/tutorials/btp-app-kyma-hana-cloud-setup.html
--------------------------

Hi,
At the second section this tutorial says:
Copy the folder scripts from templates/kyma-add-helm-chart to your project root folder.

Where can you find templates/kyma-add-helm-chart ? Is this supposed to be a link?

**Comment by manjuX** [comment]
Hi @HamzaM1 ,

Before you work on this tutorial you would have followed the prerequisite tutorials mentioned. In the prerequisites there is a tutorial called [`Create a Directory for Development`](https://developers.sap.com/tutorials/btp-app-create-directory.html). In this tutorial you would have downloaded the tutorial into a folder called `tutorial` and the templates folder is present there.

Best regards,
Manju

**Comment by HamzaM1** [comment]
I see. My fault for not checking. Thanks!
