### ISSUE TITLE
Generate and Use Text Classification Model with SAP AI Launchpad

### ISSUE THREAD

**Issue by YoheiFukuhara** [sap-tutorials/Tutorials#18687]
Tutorials: https://developers-dev-green.wcms-nonprod.c.eu-de-2.cloud.sap/tutorials/ai-launchpad-producer.html
--------------------------

Write here how you think we can improve the tutorial ...

All Image files on the tutorial are not displayed.
Probably, the links on the tutorial are wrong like below one.
https://developers.sap.com/tutorials/ai-launchpad-producer/jcr:content.github-proxy.1641814834.file/img/add-con-dialog.png

**Comment by LunaticMaestro** [comment]
Thanks @YoheiFukuhara for reporting the issue. However this tutorial is now deprecated.

I would recommend you to please follow any other tutorial of SAP AI Core. **All the tutorials of SAP AI Core now contains steps using SAP AI Launchpad**. The steps covered are basically the steps of using SAP AI Launchpad as producer of AI scenario (use case).

**Comment by LunaticMaestro** [comment]
@jmmargo The following tutorial is deprecated (files removed from PROD repo) yet the tutorial is appearing over tutorial navigator
https://developers.sap.com/tutorials/ai-launchpad-producer.html

Can you please look into the issue?

**Comment by jmmargo** [comment]
This has now been removed from the tutorial navigator.
