### ISSUE TITLE
Display Fetched Data in Your AppGyver Application

### ISSUE THREAD

**Issue by mem1b** [sap-tutorials/Tutorials#18697]
Tutorials: https://developers.sap.com/tutorials/appgyver-display-information.html
--------------------------

as shown in the picture the calorific content per 100g should be 157 but why is this not the right answer?

**Comment by kirillleventcov** [comment]
Hi @mem1b,

The following issue has been fixed! [Commit](https://github.com/sap-tutorials/Tutorials/commit/7f62b8329ee451558839d270626d8647f8123c36)
