### ISSUE TITLE
Get a Free Account on SAP BTP Trial - Consider removing the "free" word from title to avoid confusion

### ISSUE THREAD

**Issue by ajmaradiaga** [sap-tutorials/Tutorials#18703]
Tutorials: https://developers.sap.com/tutorials/hcp-create-trial-account.html
--------------------------

I would suggest removing the "free" word from the title of this tutorial. The suggested title would be: "Get an account on SAP BTP Trial".

**Why?**
No one ever gets charged for their usage in the SAP BTP Trial environment and including the  "free" word confuses users looking to adopt the SAP BTP Free Tier. 

Also, it will be beneficial to include a brief explanation of what the BTP trial environment is and clearly state that this is not a landscape intended for productive usage.

**Comment by qmacro** [comment]
Totally agree, not sure where this tutorial came from originally, but it needs addressing for sure.

**Comment by qmacro** [comment]
[Done](https://github.com/sap-tutorials/Tutorials/commit/802ab996634777313a88779dc57d24cb07f225c9).
