### ISSUE TITLE
Screenshots need to be changed in Employee Onboarding Sample Scenario

### ISSUE THREAD

**Issue by BaskarThambiayah** [sap-tutorials/Tutorials#18706]
Issue: Screenshots needs to be changed in Employee Onboarding Sample Scenario.

Steps to reproduce:
Tutorial 3: Run the Employee Onboarding Sample Scenario ( https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-5-run.html )
Step 2 : Process the Employee Onboarding events
                      2.   Select Employee Onboarding scenario and click Process Data.
  Screenshot In Tutorial:
![image](https://user-images.githubusercontent.com/60343237/184071341-a5bfd521-1284-45f5-b314-42adf6f28a49.png)

  Actual Screen in UI:
![image](https://user-images.githubusercontent.com/60343237/184071421-e8985be1-c91e-4d66-9972-9f23d7db6afa.png)

                     3. Refresh to see the processing details.
  Screenshot in Tutorial:
![image](https://user-images.githubusercontent.com/60343237/184071599-fb5700a1-5cfc-4de7-bc7d-7ee46339eb38.png)

  Actual Screen in UI:
![image](https://user-images.githubusercontent.com/60343237/184071672-b56d44ce-15f4-4cb4-96f5-faf85543b9e8.png)

Step 5 : View process visibility workspace
                   1. In the Workflow Management Fiori launchpad, open Monitor Visibility Scenarios application, click Process Data and Refresh to see the new batch of processed events.
   Screenshot in Tutorial:
![image](https://user-images.githubusercontent.com/60343237/184072021-7ecdbb25-17bd-49bd-ae35-ac46ea24585f.png)

Actual Screen in UI:
![image](https://user-images.githubusercontent.com/60343237/184072096-b008f625-9cd6-4d6e-8338-260fa10df375.png)

Step 7: View process visibility workspace for completed workflow
                    1. In the Workflow Management Fiori launchpad, choose Monitor Visibility Scenarios to process the new set of events.
    Screenshot in Tutorial:
![image](https://user-images.githubusercontent.com/60343237/184072313-b123943c-09b1-412a-a9a5-a95224ab7de0.png)

    Actual Screen in UI:
![image](https://user-images.githubusercontent.com/60343237/184072379-9810ace9-ac28-486f-861c-18e1b97df649.png)

Kindly look into this and update the document with latest screenshots.

Labels to be added:
Scenario label: SCPTest-eboard
Sprint Label: SCPTest-2208A
Landscape Label: trail2(Trial US East (VA) (AWS) ) & trail3 (AP21 Azure)
Priority: Medium

Thanks & regards,
Baskar

**Comment by ArchanaShukla** [comment]
All the screenshots have been updated and pushed to production
