### ISSUE TITLE
Build and Deploy Your SAP Fiori App to SAP Business Technology Platform

### ISSUE THREAD

**Issue by FarozanFarman** [sap-tutorials/Tutorials#18713]
Tutorials: https://developers.sap.com/tutorials/appstudio-fioriapps-mta-build-deploy.html
--------------------------

Suggestion: Screenshots need to be added as there is a UI change in Build and Deploy Your SAP Fiori App to SAP Business Technology Platform.

Steps to reproduce:
Tutorial 6: Build and Deploy Your SAP Fiori App to SAP Business Technology Platform (https://developers.sap.com/tutorials/appstudio-fioriapps-mta-build-deploy.html )
Step 2: Set Cloud Foundry preferences

3.When prompted, select the API endpoint, provide your credentials, organization, and space for your project.

Here, the UI has been changed and it points to a new screen, and no more prompts appear. So I suggest we can add a screenshot.

Screenshot:
![image](https://user-images.githubusercontent.com/71028764/184287313-1127c345-cb5c-4db5-84c7-cc521ccb6a2b.png)

Kindly look into this and update the document with latest the screenshots.

Labels to be added:
Scenario label: SCPTest-fbizapp
Sprint Label: SCPTest-2208A
Landscape Label: trail2, trail3
Priority: Medium

Thanks & regards,
Farozan

**Comment by raz-korn** [comment]
Done.
