### ISSUE TITLE
Take a Tour of SAP BTP Trial

### ISSUE THREAD

**Issue by xtbirihan** [sap-tutorials/Tutorials#18718]
Tutorials: https://developers.sap.com/tutorials/cp-trial-quick-onboarding.html
--------------------------

[Getting Started with a Trial Account in the ABAP Environment](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/720c423ef1a8498ab690cf0e5512ba50.html). URL is dead.

**Comment by iwonahahn** [comment]
Hi @xtbirihan,

The link was fixed --› [Getting Started in the ABAP Environment](https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/2ffdd2412aff494dbf3de31089c965d4.html?locale=en-US&version=Cloud) and therefore we close this issue.

Best regards,
Iwona
