### ISSUE TITLE
Integrate Chatbot with SAP Process Automation

### ISSUE THREAD

**Issue by ssimsekler** [sap-tutorials/Tutorials#18716]
Tutorials: https://developers.sap.com/tutorials/spa-create-automation-api-trigger.html
--------------------------
Hi

Most people will use the "free tier" for the tutorial exercise. One of  the tutorial steps asks to create an instance with plan "standard". Is this paid or free? To me, unless it says free, it may be paid, which makes me refrain from completing the step.

So, it should be made clear whether creating such an instance would incur any cost or not.

Kind Regards

Serdar

**Comment by jmmargo** [comment]
This tutorial has since been removed from production.
