### ISSUE TITLE
Make Predictions for House Prices with SAP AI Core

### ISSUE THREAD

**Issue by karimmohraz** [sap-tutorials/Tutorials#18710]
Tutorials: https://developers.sap.com/tutorials/ai-core-deploy.html
--------------------------

I am not sure if the dockerfile needs to be changed:
lines 12- 14:
# Required to execute script
RUN chgrp -R nogroup /app && \
    chmod -R 770 /app

If I am not mistaken, AI Core docker is running with user nobody essentially equal to everybody in terms of permissions.
However,     chmod -R 770 /app does not give even read rights to user nobody which results in access errors to files in the directory.

**Comment by LunaticMaestro** [comment]
Thanks for pointing Karim, the colleagues will shortly check & rectify.
CC: @helenaaaaaaaaaa  TODO

**Comment by helenaaaaaaaaaa** [comment]
@LunaticMaestro I wait for your clarification
