### ISSUE TITLE
Create an SAP BTP ABAP Environment Trial User - Document Update

### ISSUE THREAD

**Issue by FarozanFarman** [sap-tutorials/Tutorials#18712]
Tutorials: https://developers.sap.com/tutorials/abap-environment-trial-onboarding.html

Issue: Screenshots need to be changed in Create an SAP BTP ABAP Environment Trial User Scenario.

Steps to reproduce:
Tutorial 1: Run the Create an SAP BTP ABAP Environment Trial User ( https://developers.sap.com/tutorials/abap-environment-trial-onboarding.html#01f8d771-8f42-4bdf-8ca0-7bb229be45e5 )
Step 3 : Create ABAP cloud project
2. Select Use Cloud Foundry Environment and click Next >.
Screenshot In Tutorial:
![image](https://user-images.githubusercontent.com/71028764/184283064-e322c1c0-6aef-4172-a20c-b5b7a1b7ca64.png)

Screenshot in actual:
![image](https://user-images.githubusercontent.com/71028764/184283093-3ad41008-7a4f-4b46-a993-1dcb5e9dd201.png)

Kindly look into this and update the document with latest the screenshots.

Labels to be added:
Scenario label: SCPTest-fabap
Sprint Label: SCPTest-2208A
Landscape Label: trail2(Trial US East (VA) (AWS) )
Priority: Medium

Thanks & regards,
Farozan

**Comment by mervey45** [comment]
Hi @FarozanFarman ,

I have following screen. Did you use ADT oder Eclipse?
![image](https://user-images.githubusercontent.com/27953324/186138554-459ed68f-493a-4728-b581-e3efe63dfab0.png)

**Comment by MichaelCzcz** [comment]
@FarozanFarman Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by FarozanFarman** [comment]
Hi @MichaelCzcz ,

I am sorry; I missed replying you. I have used ADT. And as per tutorial, both the methods are mentioned so screenshot must be updated accordingly.

Thanks and Regards,
Farozan

**Comment by mervey45** [comment]
Created following pr for this issue: #20129
