### ISSUE TITLE
Deploy a CAP Business Service to SAP Business Technology Platform

### ISSUE THREAD

**Issue by akintranslator** [sap-tutorials/Tutorials#18720]
Tutorials: https://developers.sap.com/tutorials/cap-service-deploy.html
--------------------------

I am noob and might be missing some pointers.
However the tutorial lacks info on how to install mta, cf plugins and how to create a hana database (if you run the "cf deploy gen/mta.tar" without a database it fails. And since message is very long, it is quite difficult for a newbie to understand what the error is about, let alone how to solve it.
I had to figure out how to add a database to dev space.
In addition there are some issues specific to MacOs users. Some user in community suggested I need to use nvm for installing the required packages.
Without nvm it is impossible to install mtb (MTA builder). It gives a timeout message for some reason.

**Comment by renejeglinsky** [comment]
Hi @akintranslator ,

thank you for your feedback. I'll check how we can improve the tutorial and get back to you here.

All the best,
René

**Comment by renejeglinsky** [comment]
Hi @akintranslator,

the information which tools are needed is part of the prerequisites. From there we link to the original source that contains the "How-to" information. 

What I've done:
I added a pointer ad each place a certain tool is needed the first time. So if one doesn't read the prerequisites, one can find the needed information then.

Wrt to nvm: This is very specific and not related to the tutorial as such. It's more of an edge case that you could figure out how to solve. And I think such information should not be part of a usual flow. But I'm also open for other opinions on that matter.

You'll see my changes in a couple of days when they are published. Closing here for now. Feel free to re-open the issue if you have further points.

Thanks a lot @akintranslator!

All the best,
René
