### ISSUE TITLE
Use Custom Business Configurations app

### ISSUE THREAD

**Issue by gregorwolf** [sap-tutorials/Tutorials#18729]
Tutorials: https://developers.sap.com/tutorials/abap-environment-maintain-bc-app.html
--------------------------

Hello @jmmargo and @sepp4me,

I try to complete the above tutorial in my BTP Free Tier ABAP Environment. It seems that the Custom Business Configurations App was renamed to "Maintain Business Configurations":

<img width="928" alt="Screenshot 2022-08-18 at 23 26 44" src="https://user-images.githubusercontent.com/2639535/185498153-d0706934-d75d-4561-b6a0-1254360318ff.png">

Seems that this change is already active in the Free Tier. You will find in the [What's New for SAP Business Technology Platform](https://help.sap.com/whats-new/cf0cb2cb149647329b5d02aa96303f56?Environment=ABAP&locale=en-US):

> The Maintain Business Configurations app is now renamed to Custom Business Configurations. 

So the tutorial needs also an adjustment.

Best Regards
Gregor

**Comment by jmmargo** [comment]
Thank you for reporting this Gregor.  I have assigned it to Patrick for review and revision.

**Comment by sepp4me** [comment]
Hi Gregor,

this weekend the upgrade to SAP BTP 2211 is scheduled. After that, system and tutorial will be in sync again.
Sorry for the inconvenience.

Regards,
  Patrick

**Comment by sepp4me** [comment]
System and tutorial should be in sync again
