### ISSUE TITLE
Enable Services for Sales Tracker App

### ISSUE THREAD

**Issue by sejopa80** [sap-tutorials/Tutorials#18765]
Tutorials: https://developers.sap.com/tutorials/cp-apim-sales-tracker-services-enable.html
--------------------------

In the tutorial it indicates to access "Access Neo Trial" but I can't find this option in my BTP cockpit. Is it possible that it is outdated? I am waiting for an answer. Best Regards,

**Comment by jmmargo** [comment]
This tutorial will soon be deprecated.  Thank you.
