### ISSUE TITLE
Subscribe to the Low-Code / No-Code Service in SAP BTP

### ISSUE THREAD

**Issue by iwonahahn** [sap-tutorials/Tutorials#18764]
Tutorials: https://developers.sap.com/tutorials/appgyver-subscribe-service.html
--------------------------

Write here how you think we can improve the tutorial ...

step 3, the answer for the validation should be modified from `Service successfully executed` to `Booster executed successfully` as shown in the screenshot to not confuse the user.

<img width="629" alt="2022-09-06_11-05-07" src="https://user-images.githubusercontent.com/22098308/188595000-6ea3e24d-6ae0-4fed-9ea8-0ddbf738ea7a.png">

**Comment by kirillleventcov** [comment]
Fix PR: #18771 
The change is live in production.
