### ISSUE TITLE
Upload Data to Data Attribute Recommendation

### ISSUE THREAD

**Issue by cabhishekin** [sap-tutorials/Tutorials#18787]
Tutorials: https://developers.sap.com/tutorials/cp-aibus-dar-upload-data.html
--------------------------

could you please share any dataset for material masters? Creation of material masters are a tedious process and any feature to predict critical values like Material Group, product hierarchy, division etc

**Comment by Juliana-Morais** [comment]
Hi,

Besides the dataset from BestBuy (https://github.com/SAP-samples/data-attribute-recommendation-postman-tutorial), we don’t have any other dataset for material masters that we can share.

Best regards,
Juliana
