### ISSUE TITLE
Set Up SAP Business Application Studio for CAP Java

### ISSUE THREAD

**Issue by LukyBruce** [sap-tutorials/Tutorials#18788]
Tutorials: https://developers.sap.com/tutorials/cp-cap-java-app-studio.html
--------------------------
![image](https://user-images.githubusercontent.com/112454793/190057542-2f48f700-ff35-4101-b5ab-9783faa790d6.png)

There's typo.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. Actually, there are two correct spellings: artefact (BE) and artifact (AE).

@iwonahahn What do you say?

**Comment by renejeglinsky** [comment]
Thanks @LukyBruce for catching this. I'll change it to AE for consistency, as this is used in the majority of tutorials.
