### ISSUE TITLE
Create a CAP Business Service with Node.js Using Visual Studio Code- Error while executing " Order a Book" request.

### ISSUE THREAD

**Issue by FarozanFarman** [sap-tutorials/Tutorials#18784]
Tutorials: https://developers.sap.com/tutorials/cp-apm-nodejs-create-service.html
--------------------------
Issue: Error while executing " Order a Book" request.

Steps to reproduce:
At Step 10: 
Add custom logic:
3. Execute the Order a Book request.
This triggers the logic above and reduces the stock.
Here, we get the below error:
![image](https://user-images.githubusercontent.com/71028764/189906177-c903a2ea-8b8d-408c-aca8-00c62dcee581.png)

![image](https://user-images.githubusercontent.com/71028764/189906266-6256840d-ca50-4454-bbca-4d90960ba6a6.png)

Thus in the next step, i.e., "4.Execute the Browse Books request again.
The stock of book 201 is lower than before. In the response you also see, that overstocked books get a discount now.", the required output is not observed. The stock doesn't reduce.

Please look into the issue.

Labels to be added:
Sprint Label: 2209A
Scenario Label: SCPTest-banode
Landscape Label: trial2
Priority: High

Thanks and Regards,
Farozan

**Comment by renejeglinsky** [comment]
Hi @FarozanFarman ,

the Order a Book request is a POST request:
![image](https://user-images.githubusercontent.com/32062331/189910085-57c4aea4-d58c-4b25-b3b2-c7a14d0a2716.png)

Your screenshot shows a GET request and in Step 9 you copy the requests that should work.
Please check again. Thanks.

All the best,
René

**Comment by FarozanFarman** [comment]
Hi @renejeglinsky,

That's exactly what the issue is. You've got it right! The screenshot is of the logs, which reads as a GET call. But the test.http file says a POST call.
Here's the piece of code:
###
#
# Order a Book
#
POST http://localhost:4004/catalog/Orders
Content-Type: application/json;IEEE754Compatible=true

{"book_ID": 201, "amount": 5}

Screenshot:
![image](https://user-images.githubusercontent.com/71028764/190310819-f8aed901-d8d8-475a-bd2c-f1619c63698d.png)


As per the document, I should click over the link and get the required results but it points differently.

Let me know if I have understood it wrong. Thanks René

Regards,
Farozan

**Comment by renejeglinsky** [comment]
Hi @FarozanFarman,

I think I found the issue. You've clicked on the URL behind POST. But you should use the "Send Request" Button that appears above the POST request:
![image](https://user-images.githubusercontent.com/32062331/190476167-559f16ad-2fd0-4d53-bfaa-c94008462109.png)

I think the root issue is related to the obviously not enough described procedure of sending the request, which you already pointed me to in https://github.com/sap-tutorials/Tutorials/issues/18783.

Therefore I'm closing this one as a duplicate and will provide in a fix in https://github.com/sap-tutorials/Tutorials/issues/18783.

Thanks a lot for your valuable feedback! :)

All the best,
René
