### ISSUE TITLE
Deploy Your Multi-Target Application (MTA)

### ISSUE THREAD

**Issue by kirillgromyko** [sap-tutorials/Tutorials#18794]
Tutorials: https://developers.sap.com/tutorials/btp-app-cap-mta-deployment.html
--------------------------

Write here how you think we can improve the tutorial ...

I had a few issues with Step 8.

1. When running "mbt build -t ./" it dropped an error "Error: could not build the MTA project: could not execute the "make -f Makefile_20220918093942.mta p=cf mtar= strict=true mode= t=\"./\"" command: exec: "make": executable file not found in %PATH%"
although I followed the previous steps when configuring MTA, the PATH variable had not been updated in the system. To resolve this, the PATH variable should be it. For me it was "C:\Program Files (x86)\GnuWin32\bin" to PATH.

2. At the beginning of the step it says "Delete your older package-lock.json to avoid errors due to use of older versions.", which I did (although I re-named it to "package-lock.json_old"), but the it failed with the following error 

"npm ERR! The `npm ci` command can only install with an existing package-lock.json or
npm ERR! npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or
npm ERR! later to generate a package-lock.json file, then try again."

It looks that it did not attempt to re-create the file, but was just stopping because the file was not found.

When I added the file back by re-naming from "package-lock.json_old" to "package-lock.json", it did not work because package.json and package-lock.json were no in sync.

In order to resolve the error I had to re-create package-lock.json with "npm install --package-lock-only"

After this, it all worked well.

Please consider to add these two notes if anyone else has encountered the same issues.

**Comment by manjuX** [comment]
Hi @kirillgromyko ,

Thank you for taking time to provide your feedback. Regarding the first issue are you using git bash as we describe [here](https://developers.sap.com/tutorials/btp-app-prepare-dev-environment-cap.html#7fcd6340-ecee-4ffd-af71-d8d221d5e161)? We are working on adding the command for recreating the package-lock.json.

Thanks and best regards,
Manju

**Comment by slavipande** [comment]
Hi @kirillgromyko,

Please take a look and follow the steps in [Step 2: (For Windows) Install make tool](https://developers.sap.com/tutorials/btp-app-cap-mta-deployment.html#aa7224e1-4610-485f-991a-f2ed4528f03d).

It mentions specifically to add `C:\Program Files (x86)\GnuWin32\bin` to your PATH variable and restart VS Code afterwards.

Hope this helps.
Please let us know in case you have other issues.

Best regards,
Svetoslav

**Comment by iwonahahn** [comment]
Hi @kirillgromyko,

Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. If you still have questions, feel free to open a new issue.

Best regards,
Iwona
