### ISSUE TITLE
Build your first automation using Outlook SDK of SAP Process Automation

### ISSUE THREAD

**Issue by audrey-j07** [sap-tutorials/Tutorials#18799]
Tutorials: https://developers.sap.com/tutorials/spa-create-outlook-automation.html
--------------------------
Hi team,
In step 3.5, the field "foldername" in SPA as "outlook" leads me to automation error, as my outlook does not have folder called "outlook", it's better to specify the use of this field.

Also, in step 3.5, the help portal documentation on "SearchCriterionList" directs to a blank page, I believe the link below is what it refers to. Hope this gets updated.
https://help.sap.com/doc/e57d7b179db649e6b5f2d26d9894f9d9/Cloud/en-US/datatypes/emailSearchCriterion.html

Thank you and have a good day.

**Comment by r3ksk** [comment]
Hello, I have submitted an update which will be reviewed by our reviewers and the tutorial will be amended shortly. thanks for your time and evaluating this tutorial

**Comment by audrey-j07** [comment]
Thank you for the prompt reply and action!

**Comment by r3ksk** [comment]
It is live now ... https://developers.sap.com/tutorials/spa-create-outlook-automation.html#67f54135-e91a-4175-8e91-0d59eec14ebd. I will close the ticket
