### ISSUE TITLE
Add Multitenancy to a Node.js Application Secured by the SAP Authorization and Trust Management service (XSUAA)

### ISSUE THREAD

**Issue by dongtianxiaozi** [sap-tutorials/Tutorials#18803]
Tutorials: https://developers.sap.com/tutorials/cp-cf-security-xsuaa-multi-tenant.html
--------------------------
I followed the tutorials. But after step 9, it displays XS Advanced logon screen when open the approuter app link of provider subaccount. 
Could you please guide how to resolve it or any missing step? Thanks!

Below is the manifest.yml detail:
applications:
# Product List Application
- name: sk-2022-multi-product-list
  instances: 1
  memory: 128M
  routes:
    - route: sk-2022-multitenancy-product.cfapps.eu12.hana.ondemand.com
  path: myapp
  buildpacks:
    - nodejs_buildpack  
  timeout: 180
  services:
    - sk-2022-xsuaa-service-tutorial  
    - sk-2022-saas-registry-tutorial4      
# Application Router
- name: sk-2022-multi-approuter
  routes:
    - route: approuter-product-sk-2022.cfapps.eu12.hana.ondemand.com
  path: approuter
  buildpacks:
    - nodejs_buildpack
  memory: 128M
  services:
    - sk-2022-xsuaa-service-tutorial  
  env:
    destinations: >
      [
        {"name":"sk-products-destination",
         "url":"https://sk-2022-multitenancy-product.cfapps.eu12.hana.ondemand.com",
         "forwardAuthToken": true}
      ]
    TENANT_HOST_PATTERN: "^(.*)-approuter-product-sk-2022.cfapps.eu12.hana.ondemand.com"

**Comment by MichaelPShea** [comment]
Hi @dongtianxiaozi 
Sorry we have been so long in answering. We have been trying to troubleshoot where things went wrong for you in the tutorial. If you still have the files, we suspect that maybe you created the XSUAA service instance with a name different from that in the services you listed sk-2022-xsuaa-service-tutorial. Can we still help you or shall we close this issue?
