### ISSUE TITLE
Prepare the SAP SuccessFactors Extension UI with CDS Annotations

### ISSUE THREAD

**Issue by TIAXU** [sap-tutorials/Tutorials#18824]
Tutorials: https://developers.sap.com/tutorials/cap-extend-sfsf-ui-annotations.html
--------------------------

When executing the step 4: Test the application UI and save the project, it returns error like this:
May you please help have a look?
![image](https://user-images.githubusercontent.com/11452005/192932202-a8943ed7-7edc-4c11-b8cb-27baaeecaf23.png)
![image](https://user-images.githubusercontent.com/11452005/192932400-84d09c56-7d3b-4427-8349-0298e2f5bd58.png)

**Comment by ale-biagi** [comment]
Hi @TIAXU,
