### ISSUE TITLE
Create and Run an ABAP Application

### ISSUE THREAD

**Issue by ceedee666** [sap-tutorials/Tutorials#18830]
Tutorials: https://developers.sap.com/tutorials/abap-create-basic-app.html
--------------------------

There is a small formatting error in the question at the end of the tutorial. 

![CleanShot 2022-10-01 at 09 36 02@2x](https://user-images.githubusercontent.com/235757/193398590-5a4bfe1e-5f0e-433b-a539-29a745ec5812.png)

**Comment by qmacro** [comment]
Hi Christian, thanks for this - looks like a rendering issue that is a little eager to interpret newlines with HTML and then HTML-encode the HTML :-) I've addressed this specific instance (the update to the tutorial will take some time to come through) and alerted the team that looks after the engine.
