### ISSUE TITLE
Display Fetched Data in Your AppGyver Application

### ISSUE THREAD

**Issue by keita-f** [sap-tutorials/Tutorials#18831]
Please correct the barcode in the picture of the can used in the tutorial "Display Fetched Data in Your AppGyver Application" as it is unclear and unreadable.

https://developers.sap.com/tutorials/appgyver-display-information.html#top

**Comment by thecodester** [comment]
I didn't realize you and others would want to use it as a barcode to scan in the app.

I will update the picture but also provide the barcode separately, as it will be more readable.

**Comment by thecodester** [comment]
Fixed and added separate barcode to scan - https://github.com/sap-tutorials/Tutorials/commit/64cd7dbbdd65eadc052dda98357c437cb1da4fcf
