### ISSUE TITLE
Add Transactional Behavior to Your Core Data Services

### ISSUE THREAD

**Issue by mohamedyosufdeenjmh** [sap-tutorials/Tutorials#18832]
Tutorials: https://developers.sap.com/tutorials/abap-environment-transactional-enablement.html
--------------------------

In Step 4 (Create behavior implementation), point number 2 is given as follows:
"Provide the name Z_I_BOOKING_XXX and a description and click Next."

But there is no "Z_I_BOOKING_XXX" mentioned in the next screenshot.

**Comment by mervey45** [comment]
Hi @mohamedyosufdeenjmh ,

thank you for your feedback. We will correct this as soon as possible.

Best regards, 
Merve
