### ISSUE TITLE
Tour the SAP Community 2022 - Can't complete first question

### ISSUE THREAD

**Issue by fleischr** [sap-tutorials/Tutorials#18840]
Tutorials: https://developers.sap.com/tutorials/community-2022.html
--------------------------

First question asks 'what is the current featured mission on the community page'. I answered 'ABAP Code Challenge' - but this was marked as incorrect. maybe the stored answer is out of date?

**Comment by lenastodal** [comment]
Hi @fleischr - thanks for opening the issue and apologies for the late reply. 
There was a mismatch on the homepage which got adjusted. The rule got updated and meanwhile both answers should be accepted; the more colloquial term for our challenge "ABAP Code Challenge" and the official name "SAP Community Code Challenge - ABAP". 
Apologies for the inconvenience caused! 
Best, 
Lena
