### ISSUE TITLE
Tutorial Page abap-environment-deploy-cf-production.md Issue. PROD

### ISSUE THREAD

**Issue by SAPDocs** [sap-tutorials/Tutorials#18843]
Tutorial issue found: [https://github.com/sap-tutorials/Tutorials/blob/master/tutorials/abap-environment-deploy-cf-production/abap-environment-deploy-cf-production.md](https://github.com/sap-tutorials/Tutorials/blob/master/tutorials/abap-environment-deploy-cf-production/abap-environment-deploy-cf-production.md) contains invalid tags. Even though your tutorial was created, the invalid tags listed below were disregarded. Please double-check the following tags:
- software-products>sap-business-application-studio

 Affected server: PROD

**Comment by mervey45** [comment]
Hi @SAPDocs ,

what is the correct tag to use?

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
software-product>sap-business-application-studio

**Comment by mervey45** [comment]
Hi @MichaelCzcz ,

thank you, didn't see the s at the end. I created following pr: #18844 to correct it.

Best regards,
Merve
