### ISSUE TITLE
Tutorial Page cp-mobile-dev-kit-create-customer.md Issue. PROD

### ISSUE THREAD

**Issue by SAPDocs** [sap-tutorials/Tutorials#18849]
Tutorial issue found: [https://github.com/sap-tutorials/Tutorials/blob/master/tutorials/cp-mobile-dev-kit-create-customer/cp-mobile-dev-kit-create-customer.md](https://github.com/sap-tutorials/Tutorials/blob/master/tutorials/cp-mobile-dev-kit-create-customer/cp-mobile-dev-kit-create-customer.md)  - file path is not unique. Your tutorial was not created.

 Affected server: PROD

**Comment by MichaelCzcz** [comment]
Tutorial was moved to another repo and was temporarily existing in two places.
