### ISSUE TITLE
Tutorial Page cp-mobile-bas-setup.md Issue. PROD

### ISSUE THREAD

**Issue by SAPDocs** [sap-tutorials/Tutorials#18845]
Tutorial issue found: [https://github.com/sap-tutorials/Tutorials/blob/master/tutorials/cp-mobile-bas-setup/cp-mobile-bas-setup.md](https://github.com/sap-tutorials/Tutorials/blob/master/tutorials/cp-mobile-bas-setup/cp-mobile-bas-setup.md)  - file path is not unique. Your tutorial was not created.

 Affected server: PROD

**Comment by sandeep-tds** [comment]
Hi Michael, 

The tutorial is only present in this location: https://github.com/sap-tutorials/sap-mobile-development-kit/blob/main/tutorials/cp-mobile-bas-setup/cp-mobile-bas-setup.md

and it can be accessed publicly here: https://developers.sap.com/tutorials/cp-mobile-bas-setup.html

Thus, we are closing the ticket. 

Please feel free to re-open the ticket if needed.
