### ISSUE TITLE
Run a Business Process from the Launchpad

### ISSUE THREAD

**Issue by AmauryVanEspen** [sap-tutorials/Tutorials#18857]
Tutorials: https://developers.sap.com/tutorials/spa-run-business-process-launchpad.html

Not able to validate step 4
--------------------------

Write here how you think we can improve the tutorial ...

**Comment by pbujnicka** [comment]
Hello, 
could you please provide the steps to reproduce the issue?
If possible please provide the screen-shots.
Thank you.

**Comment by AmauryVanEspen** [comment]
seems to be OK right now
