### ISSUE TITLE
Deploy Commerce Mock Application in the Kyma Runtime

### ISSUE THREAD

**Issue by mohamedyosufdeenjmh** [sap-tutorials/Tutorials#18855]
Tutorials: https://developers.sap.com/tutorials/cp-kyma-mocks.html
--------------------------
This is about Step 2 - Point number 5.
In the YAML section, there is no separate "Deployment" and "Service" pane.
How to get those panes as mentioned in this tutorial?
Is this an error or am I doing it in the wrong way? Please suggest.

![image](https://user-images.githubusercontent.com/38460935/194819134-423763aa-6772-4e80-bef1-c7253e09a62d.png)

**Comment by jcawley5** [comment]
Thank you for the feedback. This will be fixed in 

https://github.com/sap-tutorials/Tutorials/pull/18859
