### ISSUE TITLE
Create Your First ABAP Console Application

### ISSUE THREAD

**Issue by marianfoo** [sap-tutorials/Tutorials#18858]
Tutorials: https://developers.sap.com/tutorials/abap-environment-console-application.html#742a4005-c060-44e7-9012-39ef914d0a0d
--------------------------
The Answer on the Test is wrong.
The wrong answer saved here is :
`out->write('Hello SAP Cloud Platform ABAP Environment!').`
The correct answer is:
`out->write( 'Hello SAP Cloud Platform ABAP Environment!' ).`

Wrong whitespaces already mentioned here: https://github.com/sap-tutorials/Issues/issues/635

Also at Step 5 there is still a wrong statement: `out->write('Hello World!').` without whitespaces.

**Comment by mervey45** [comment]
Created following pr for this issue: #20129
