### ISSUE TITLE
Set Up Workflow Management in Cloud Cockpit -Booster is failing

### ISSUE THREAD

**Issue by FarozanFarman** [sap-tutorials/Tutorials#18854]
Tutorials: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-1-setup.html
--------------------------
Issue: Set Up Workflow Management in Cloud Cockpit -Booster is failing

Steps to reproduce:
Go to : https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-1-setup.html
Follow till : STEP 2 : Set up your account using Booster 
At step: 2. Automated onboarding will be started with pre-configured steps.

Here, it is failing while creation of the service instances:
![image](https://user-images.githubusercontent.com/71028764/194816883-5d187228-4181-4a88-be4c-f191b1d941bd.png)

![image](https://user-images.githubusercontent.com/71028764/194816942-f510e8e1-8d50-4e07-b57e-e42905b1f76b.png)

I checked the subaccount, all the required entitlements are present:
![image](https://user-images.githubusercontent.com/71028764/194817085-323cf9c2-547b-4cc0-94c6-84b9b9e53f59.png)

![image](https://user-images.githubusercontent.com/71028764/194817121-22e55e68-895b-4e40-a5a5-e529548fe30d.png)

![image](https://user-images.githubusercontent.com/71028764/194817189-34b78711-68fd-468e-9dd0-b320a76ae879.png)

My observation:
I feel it is failing because there is an update in the landscape ID that is the endpoint. The API endpoint of the subaccount contains the extended landscape ID:
https://api.cf.us10-001.hana.ondemand.com

I cannot continue the execution manually as the details required for creation of the service instances and destination are not available in the document.

Please look into the issue and update accordingly. Currently the scenario is in blocked state.

Labels to be added:
Scenario label: SCPTest-eboard
Sprint Label: SCPTest-2210A
Landscape Label: trail2(Trial US East (VA) (AWS) )
Priority: High

Thanks and Regards,
Farozan

**Comment by ArchanaShukla** [comment]
Hello @FarozanFarman,
I just freshly created the trial account and ran the Booster and it worked fine.
