### ISSUE TITLE
Tutorial Page btp-app-kyma-prepare-xsuaa.md Issue. PROD

### ISSUE THREAD

**Issue by SAPDocs** [sap-tutorials/Tutorials#18865]
Tutorial issue found: [https://github.com/sap-tutorials/Tutorials/blob/master/tutorials/btp-app-kyma-prepare-xsuaa/btp-app-kyma-prepare-xsuaa.md](https://github.com/sap-tutorials/Tutorials/blob/master/tutorials/btp-app-kyma-prepare-xsuaa/btp-app-kyma-prepare-xsuaa.md) contains invalid tags. Even though your tutorial was created, the invalid tags listed below were disregarded. Please double-check the following tags:
- software-product>sap-btp-kyma-runtime

 Affected server: PROD

**Comment by iwonahahn** [comment]
fixed yesterday
