### ISSUE TITLE
Use Redis in the Kyma Runtime to Store and Retrieve Data

### ISSUE THREAD

**Issue by mohamedyosufdeenjmh** [sap-tutorials/Tutorials#18869]
Tutorials: https://developers.sap.com/tutorials/cp-kyma-redis-function.html
--------------------------

Step 2 -> Point Number 2 returns the below error when pasting the contents of **"cache-order-function.yaml"** file and clicking on **"Create"**.
Failed to create the Function: the API version in the data (serverless.kyma-project.io/v1alpha2) does not match the expected API version (serverless.kyma-project.io/v1alpha1)

![image](https://user-images.githubusercontent.com/38460935/194938418-4738d44c-7edc-4b1a-ba07-590ac11e5b7f.png)

**Comment by jcawley5** [comment]
Hello, currently there is an issue with the console UI excepting the latest version of the serverless CRD. For now you can either apply it using kubectl or use the previous version of the sample which can be found at 

https://github.com/SAP-samples/kyma-runtime-extension-samples/tree/da1f01854e9ade45ce360393ad10f5f19276c044/redis-function/k8s

**Comment by jcawley5** [comment]
Tracking issue at [1929](https://github.com/kyma-project/busola/issues/1929)

**Comment by mohamedyosufdeenjmh** [comment]
Thank you, @jcawley5. I am able to do the tutorial successfully with the alternative files provided by you.
