### ISSUE TITLE
Use Trial to Subscribe to Document Information Extraction Trial UI - Instance creation not mentioned

### ISSUE THREAD

**Issue by RanjishPR** [sap-tutorials/Tutorials#18871]
Tutorials: https://developers.sap.com/tutorials/cp-aibus-dox-ui-sub.html
--------------------------

Hello,

This document mentions about the creation of only the subscription. Creation of the instance 'Document Information Extraction Trial' and its respective service key is also needed to complete the process, so that the application 'Document Information Extraction Trial UI' can be launched successfully.

Thanks & Best Regards,
Ranjish

Sprint Label - SCPTest-2210A
Landscape Label – trail2 for Trial US East (VA) (AWS)
Priority Label – Medium

**Comment by Juliana-Morais** [comment]
Hi Ranjish,

That's why this tutorial has a Prerequisite: "You have created a service instance for Document Information Extraction: [Create Service Instance for Document Information Extraction] (https://developers.sap.com/tutorials/cp-aibus-dox-service-instance.html)."

Best regards,
Juliana

**Comment by RanjishPR** [comment]
Hi Juliana,

Sorry that I missed this part. I shall close the ticket.

Thanks & Best Regards,
Ranjish
