### ISSUE TITLE
Expose Integration Flow Endpoint as API and Test the Flow - 'Edit in API Designer' shows a Blank Screen

### ISSUE THREAD

**Issue by RanjishPR** [sap-tutorials/Tutorials#18877]
Tutorials: https://developers.sap.com/tutorials/cp-starter-isuite-api-management.html
--------------------------

Hello,

At step 2 of this tutorial(Define the API), when the actions are performed as per sub step 8, a blank screen appears in the API designer, which is not as expected.

Please see the screen shot attached with this message.

![Blank Screen](https://user-images.githubusercontent.com/105277535/195065566-46058b94-a53f-471b-87d1-6329ebe9928e.jpg)

Thanks & Best Regards,
Ranjish

Sprint Label - SCPTest-2210A
Landscape Label – trail2 for Trial US East (VA) (AWS)
Priority Label – High

**Comment by sreejithppsap** [comment]
The same issue exists in the AP region as well.
![image](https://user-images.githubusercontent.com/58926896/195067941-44604d49-07fe-4a68-9f72-cb30dd75454b.png)

**Comment by Karunaharan** [comment]
Hello @RanjishPR - I have reported the issue to the concerned team. Will keep you posted as soon as it is fixed.

**Comment by Karunaharan** [comment]
The issue was fixed a few weeks back. I was on vacation and hence the delay in communication.

Karuna
