### ISSUE TITLE
Create a Development Project in SAP Business Application Studio

### ISSUE THREAD

**Issue by mohamedyosufdeenjmh** [sap-tutorials/Tutorials#18870]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-mission-trial-7.html
--------------------------

Step 2 - Point number 14: After providing all the information and once the Finish button is clicked, got the below errors.
![image](https://user-images.githubusercontent.com/38460935/194945299-8c595708-5e22-4ebc-8638-6c6931ebc2cb.png)
![image](https://user-images.githubusercontent.com/38460935/194945832-4284d56c-59a0-40f0-9584-2af7d5c568da.png)

I have then manually opened the project via open folder option in Business Application Studio.
Followed all the subsequent steps.
In Step 7 - Point number 5, after clicking on Deploy button, got the below error:
![image](https://user-images.githubusercontent.com/38460935/194945723-e76531e7-de6e-410a-8628-7208ccd5e422.png)

@chriskollhed @VijayKrishnanSR

**Comment by VolkerSaggau** [comment]
Hi Mohamend, 
can you please let me know which landscape you are using. Trial, Free Tier, US10, EU10,....

Also:

Have you tried the same step but before doing a "cf login" please.

1. Either with a terminal session and type cf login
2. or with the CF symbol on the left side (around the middel of the symbol) and do the cf login there.
4. Be sure you have a proper binding of you project
Let me know the hwo this works for you
BR
Volker

**Comment by mohamedyosufdeenjmh** [comment]
> Hi Mohamend, can you please let me know which landscape you are using. Trial, Free Tier, US10, EU10,....
> 
> Also:
> 
> Have you tried the same step but before doing a "cf login" please.
> 
> 1. Either with a terminal session and type cf login
> 2. or with the CF symbol on the left side (around the middel of the symbol) and do the cf login there.
> 3. Be sure you have a proper binding of you project
>    Let me know the hwo this works for you
>    BR
>    Volker

Hi Volker,
I am using Free Tier.
My subaccount is created in US East (VA) region, but my URL has eu10 in it.
Please find the below screenshot.
![image](https://user-images.githubusercontent.com/38460935/195088928-c5794be2-a80a-46f9-9146-7dd11692e4c6.png)

I have tried as suggested (by doing a cf login), still I am getting the same error.

**Comment by mohamedyosufdeenjmh** [comment]
Please refer to https://answers.sap.com/questions/13732450/unable-to-deploy-sap-hana-project.html

**Comment by VolkerSaggau** [comment]
We did a fix by engineering and the issue should be solved
