### ISSUE TITLE
Subscribe to SAP Process Automation Using Booster in SAP BTP Free Tier

### ISSUE THREAD

**Issue by Lysannej** [sap-tutorials/Tutorials#18873]
Tutorials: https://developers.sap.com/tutorials/spa-subscribe-booster.html
--------------------------

Hi Team,

According to Step 1 (first tutorial), the SAP Process Automation is only available in the SAP BTP Free Tier Account (so not in a Trial Account).
When continuing to the next tutorial - Create a Business Process, it is stated otherwise. The Prerequisites is stated as follows: "You will need either a trial account with the SAP Process Automation enabled (as described by this blog), or a regular account with the free-tier service plan for SAP Process Automation (as described in Subscribe to SAP Process Automation Using Booster in SAP BTP Free Tier)." Here it looks as if Process Automation is also available within a Trial Account.

This might lead to some confusion.

Kind regards,
Lysanne Jansen

**Comment by chaitanya-priya-puvvada** [comment]
Celine, please update it accordingly since SBPA is available on the Trial account from Nov 2022.Looks like some the places were missed in updating the statement

**Comment by celineaudinsap** [comment]
Hello, updates have been completed.
