### ISSUE TITLE
Access Your Launchpad Site with SAP Mobile Start

### ISSUE THREAD

**Issue by VinayakTamse01** [sap-tutorials/Tutorials#18872]
Hi,

[](url)Tutorials: https://developers.sap.com/tutorials/mobile-start-access-launchpad-site.html
--------------------------

In Step 5. : Try the App
3. Within the Application screen you can use the search bar to find specific applications.
Here, observation: Position of Search bar has Changed. Please Refer the Screenshot

Expected :
![FioriLaunchpadExpected](https://user-images.githubusercontent.com/108262863/195008111-012b7827-938d-4a79-a5f3-63f65d3c88c6.PNG)

Actual:

![AccessLaunchpadSiteMobileSite](https://user-images.githubusercontent.com/108262863/195008291-b4925839-247a-40ef-a4ba-da9a02fa9eda.jpg)

Please update the screenshot accordingly.

Labels:
Landscape Labels - trail2
Sprint Label: SCPTest-2210A
Scenario Label: SCPTest-psite
Priority: Low

Regards,
Vinayak Tamse

**Comment by dennis-koehler** [comment]
Tutorial got updated in https://github.com/sap-tutorials/Tutorials/pull/23023
With that screenshots got updated to reflect the current state.
