### ISSUE TITLE
Implement Your First Screen in an iOS App

### ISSUE THREAD

**Issue by mohamedyosufdeenjmh** [sap-tutorials/Tutorials#18876]
Tutorials: https://developers.sap.com/tutorials/fiori-ios-scpms-starter-mission-02.html
--------------------------

In Step 5, after importing SAPOData and SharedFmwk, pasting the below code block results in an error: **"Cannot find type 'ESPMContianerOnlineODataController' in scope"** and **"Cannot find 'self' in scope"**.

```
  /// First retrieve the destinations your app can talk to from the AppParameters.
  let destinations = FileConfigurationProvider("AppParameters").provideConfiguration().configuration["Destinations"] as! NSDictionary

  /// Create a computed property that uses the OnboardingSessionManager to retrieve the onboarding session and uses the destinations dictionary to pull the correct destination. Of course you only have one destination here. Handle the errors in case the OData controller is nil. You are using the AlertHelper to display an AlertDialogue to the user in case of an error. The AlertHelper is a utils class provided through the Assistant.
  var dataService: ESPMContainer<OnlineODataProvider>? {
        guard let odataController = OnboardingSessionManager
                .shared
                .onboardingSession?
                .odataControllers[ODataContainerType.eSPMContainer.description] as? ESPMContainerOnlineODataController else {
            AlertHelper.displayAlert(with: "OData service is not reachable, please onboard again.", error: nil, viewController: self)
            return nil
        }
        return odataController.dataService
    }
```

@KevinMuessig

**Comment by KevinMuessig** [comment]
Hi @mohamedyosufdeenjmh, thank you for your comment. Let me investigate and fix the tutorial as soon as possible.

Best,
KM

**Comment by KevinMuessig** [comment]
Hi @sandeep-tds ,

as you're working on that tutorial at the moment, could you take this over?

Thanks,

KM

**Comment by sandeep-tds** [comment]
Hi @mohamedyosufdeenjmh @KevinMuessig 

I have taken over the task now and will aim to provide a resolution in two weeks.

Warm Regards
Sandeep T D S

**Comment by jmmargo** [comment]
I assume a resolution has been provided.  I am closing this issue.  If it needs to be reopened, please do so.
