### ISSUE TITLE
Create an SAP BTP ABAP Environment Trial User-Pointing to different API endpoint

### ISSUE THREAD

**Issue by KeerthiMohankumar** [sap-tutorials/Tutorials#18875]
Tutorials: https://developers.sap.com/tutorials/abap-environment-trial-onboarding.html
--------------------------
**At Step 3: Create ABAP cloud project
 3: Enter your connection settings

It is pointing to different API endpoint, in other words it is not pointing to the extended landscape endpoint which is "https://api.cf.us10-001.hana.ondemand.com/", hence unable to access the subaccount. And its throwing the below error:**
![image](https://user-images.githubusercontent.com/107237818/195050090-db06f296-d091-4fef-8c81-7364699b8295.png)

 _**Thus, proceeding with this method is blocked.**_

![image](https://user-images.githubusercontent.com/107237818/195049598-7848a660-b3a1-4979-bfd5-ffd0ffbd8e4d.png)

Please check and update the document accordingly.

Labels to be added:
Sprint Label: 2210A
Scenario Label: SCPTest-fabap
Landscape Label: trial2
Priority: High

Regards,
Keerthi

**Comment by mervey45** [comment]
Hi @KeerthiMohankumar ,

is your trial account still available on SAP BTP cockpit? Seems like you need to extend it. If you still have any issues contact me again. 

Best regards, 
Merve

**Comment by KeerthiMohankumar** [comment]
Hi @mervey45 ,

This issue is still reproducible.

Kind Regards,
Keerthi
