### ISSUE TITLE
Connect Your AppGyver Application to a Public API

### ISSUE THREAD

**Issue by mohamedyosufdeenjmh** [sap-tutorials/Tutorials#18886]
Tutorials: https://developers.sap.com/tutorials/appgyver-connect-publicapi.html
--------------------------

Step 2 -> Point number 3:
In the table, the value for field **"Is optional"** is mentioned as **"Enabled"**.
But in the subsequent screenshot shows the field Is optional as **"disabled"**.

**Comment by thecodester** [comment]
In the instructions I will change to disabled.

**Comment by thecodester** [comment]
Changed Is_Optional to Disabled -- https://github.com/sap-tutorials/Tutorials/commit/64cd7dbbdd65eadc052dda98357c437cb1da4fcf
