### ISSUE TITLE
Tutorial Page xpa-sac-hxm-workforceplanning-gettoknow.md Issue. PROD

### ISSUE THREAD

**Issue by SAPDocs** [sap-tutorials/Tutorials#18891]
Tutorial issue found: [https://github.com/sap-tutorials/Tutorials/blob/master/tutorials/xpa-sac-hxm-workforceplanning-gettoknow/xpa-sac-hxm-workforceplanning-gettoknow.md](https://github.com/sap-tutorials/Tutorials/blob/master/tutorials/xpa-sac-hxm-workforceplanning-gettoknow/xpa-sac-hxm-workforceplanning-gettoknow.md) contains invalid tags. Even though your tutorial was created, the invalid tags listed below were disregarded. Please double-check the following tags:
- software-product-function>sap-analytics-cloud-analytics-designer

 Affected server: PROD

**Comment by RudolfLindt93** [comment]
pushed the tutorial again with updated tags
