### ISSUE TITLE
Tutorial Page xpa-sac-hxm-successfactors-writeback.md Issue. PROD

### ISSUE THREAD

**Issue by SAPDocs** [sap-tutorials/Tutorials#18894]
Tutorial issue found: [https://github.com/sap-tutorials/Tutorials/blob/master/tutorials/xpa-sac-hxm-successfactors-writeback/xpa-sac-hxm-successfactors-writeback.md](https://github.com/sap-tutorials/Tutorials/blob/master/tutorials/xpa-sac-hxm-successfactors-writeback/xpa-sac-hxm-successfactors-writeback.md) contains invalid tags. Even though your tutorial was created, the invalid tags listed below were disregarded. Please double-check the following tags:
- software-product-function>sap-analytics-cloud-analytics-designer

 Affected server: PROD

**Comment by KRANIG** [comment]
updated to 
software-product-function>sap-analytics-cloud\,-analytics-designer
with https://github.com/sap-tutorials/Tutorials/pull/18899
