### ISSUE TITLE
Call a Remote Function Module From SAP Business Technology Platform (BTP), ABAP Environment

### ISSUE THREAD

**Issue by gregorwolf** [sap-tutorials/Tutorials#18908]
Tutorials: https://developers.sap.com/tutorials/abap-env-rfc.html
--------------------------

# STEP 15 Add error handling to the class for the RFC connection

The variable msg isn't defined. I've added:

```ABAP
        DATA msg TYPE c LENGTH 200.
```

To fix this problem. I would also suggest to move this step before "STEP 13 Test the class" as it will avoid raising a dump if the configuration wasn't correct or the Cloud Connector is not connected.

**Comment by julieplummer20** [comment]
Hi - I've updated this now. Sorry for the delay; it slipped off my radar. 
Many thanks Julie.
