### ISSUE TITLE
Add Views and Define Routes to Access Them

### ISSUE THREAD

**Issue by mohamedyosufdeenjmh** [sap-tutorials/Tutorials#18909]
Tutorials: https://developers.sap.com/tutorials/sapui5-101-add-routing.html
--------------------------

Completed all the pre-requisite tutorials,
In Step 4 of this tutorial, while testing, just an empty screen is displayed, and no data is displayed from the OData service.
![image](https://user-images.githubusercontent.com/38460935/196166332-22d3cb83-6ac2-4b4a-be33-77ee372ee818.png)

**Comment by nicoschoenteich** [comment]
Thanks for reporting this @mohamedyosufdeenjmh. I just submitted a PR for a fix. See [this issue](https://github.com/sap-tutorials/Tutorials/issues/18898) to learn how to proceed for now.

**Comment by nicoschoenteich** [comment]
I just had another look at this and found the real issue: You have to change the pattern for the first route ("RouteView1") from `:?query:` to `RouteView1` in the `webapp/manifest.json` file, so that we can define a new default route.

**Comment by mohamedyosufdeenjmh** [comment]
Thank you, @nicoschoenteich !
