### ISSUE TITLE
Call a Remote Function Module From SAP Business Technology Platform (BTP), ABAP Environment

### ISSUE THREAD

**Issue by gregorwolf** [sap-tutorials/Tutorials#18907]
Tutorials: https://developers.sap.com/tutorials/abap-env-rfc.html
--------------------------

In Step 6 Create variables the Source Code isn't formatted. In the next step it looks fine:

![Screenshot 2022-10-15 at 10 48 49](https://user-images.githubusercontent.com/2639535/195977921-bcc0fb0a-ec4b-4ea2-a0b6-e5a9d319ab40.png)

**Comment by julieplummer20** [comment]
Hi Gregor, Thanks. I'll get that sorted.

**Comment by julieplummer20** [comment]
Hi Gregor, I'm about to release these tutorials, so I'll close this issue.
