### ISSUE TITLE
Provision an Instance of SAP HANA Cloud, SAP HANA Database

### ISSUE THREAD

**Issue by softy12** [sap-tutorials/Tutorials#18916]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-mission-trial-2.html
--------------------------

I'm logged into BTP's Cockpit under my global account, subaccount, and space. Then under SAP HANA Cloud tab I click on Create -> SAP HANA Database. A new browser page gets opened requesting to Choose your identity provider. Here I click on "Sign in with default identity provider." button. On next logon page regardless if I try to login with my S* user or with my SAP Universal ID I always end up with an error: "Sorry, we could not authenticate you. Try again."

Any idea what I'm doing wrong? Thanks

**Comment by danielva** [comment]
Sorry that this did not work.  I am unable to reproduce this.
