### ISSUE TITLE
Set Up SAP Business Application Studio for Development

### ISSUE THREAD

**Issue by josemseren** [sap-tutorials/Tutorials#18913]
Tutorials: https://developers.sap.com/tutorials/appstudio-onboarding.html
--------------------------

Write here how you think we can improve the tutorial ...

I get always the "technical error" that you can see in the image below:

![image](https://user-images.githubusercontent.com/50585940/196194243-d365e13d-aa1b-4f23-95e6-25665832ef85.png)

Is it possible to fix it?

Thanks

**Comment by josemseren** [comment]
Another problem I have with the tutorial is that my progress is not saved. I finished any tutorial then I leave it and when I came back later the progress is back to zero.

**Comment by raz-korn** [comment]
@MichaelCzcz : Both issues are related to the tutorial system. Not to BAS.
Please assign to the relevant person.

Thanks- Raz

**Comment by jmmargo** [comment]
@josemseren this seems to be an issue related to Universal ID.  Can you please check to make sure that when you are using tutorials, you are 1) logged in and 2) logged in to the account that you use when completing tutorials.  If you are having trouble, please contact me directly at joshua.margo@sap.com and we can set up time to work through this together.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
