### ISSUE TITLE
Enhance Behavior With Action and Validation

### ISSUE THREAD

**Issue by SatheesP** [sap-tutorials/Tutorials#18918]
Dear Team,

Tutorials: https://developers.sap.com/tutorials/abap-environment-behavior-action.html
--------------------------

Please update source code of this tutorial with
The transactional key %tky for wherever %key obsolete component is there

-Sathees

**Comment by mervey45** [comment]
Hi @SatheesP , 

thank you for your feedback. We'll check this and update the correspoding tutorial.

Best regards, 
Merve
