### ISSUE TITLE
Add an SAPUI5 App to Your Launchpad Site

### ISSUE THREAD

**Issue by boghyon** [sap-tutorials/Tutorials#18923]
Tutorials: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-new-sapui5.html
--------------------------

In step 2, there is the following note:

> When working in your own environment, it’s better to integrate SAPUI5 apps by configuring a destination to the relevant system and setting the app properties to use this destination. In this case in the **App UI Technology** dropdown list, you would select `SAPUI5`. This configuration allows you to better manage your content in the Dev-QA-Prod lifecycle.

But there is no "SAPUI5" in the dropdown list:

![Launchpad service application technology dropdown list](https://user-images.githubusercontent.com/12143247/196461209-7ae850ab-40ab-45b4-859c-7ad63575a2ea.png)

**Comment by LindsayBert** [comment]
Hi

To see the SAPUI5 option, you need to create a destination to a system.  For an example of how to do this, see https://developers.sap.com/tutorials/cp-portal-cloud-foundry-gateway-connection.html 

Thanks
Lindsay
