### ISSUE TITLE
Set Up SAP Launchpad Service Using a Trial Account

### ISSUE THREAD

**Issue by m-badura** [sap-tutorials/Tutorials#18921]
Tutorials: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-getting-started.html
--------------------------

The link under Prerequisites leads to an SAP website in Hebrew:
https://www.sap.com/israel/products/technology-platform/trial.html

I remove "israel" from the address and proceed.

"Scroll down and click Get trial now."

I don't see any "Get trial now" link, button, whatsoever...

Step 5:
"The Launchpad Service page opens with 3 tabs that include information about the service as well as the two different plans."

I can see only 2 tabs: Overview and Application Plans

**Comment by LindsayBert** [comment]
Hi 

Thanks for your feedback.  I've fixed the link and the other changes - they were changes to SAP BTP which we are not always informed about.
The updates will only be visible after the tutorial is pushed to production.

Thanks Lindsay
