### ISSUE TITLE
Deploy a CAP Business Service to SAP Business Technology Platform

### ISSUE THREAD

**Issue by ValterAraujoJr** [sap-tutorials/Tutorials#18925]
Tutorials: https://developers.sap.com/tutorials/cap-service-deploy.html
--------------------------

Hello there. Thanks for the tutorial. Could you please help on the issue below?

I am stuck at the step: **Deploy using cf deploy**

When I try to execute the command as required: **mbt build -t gen --mtar mta.tar**

My environment is:
**@sap/cds: 6.2.2
@sap/cds-compiler: 3.3.2
@sap/cds-dk: 6.2.1
@sap/cds-dk (global): 6.2.1
@sap/cds-foss: 4.0.0
@sap/cds-mtx: -- missing --
Node.js: v16.18.0**

My package.json dependencies is:
 **"dependencies": {
    "@sap/cds": "^6",
    "express": "^4",
    "@sap/xssec": "^3",
    "passport": "^0",
    "hdb": "^0.19.0"
  },**

I am getting the error below:
PS C:\vdev\cpa01\my-bookshop> mbt build -t gen --mtar mta.tar
>>
[2022-10-18 15:15:00]  INFO Cloud MTA Build Tool version 1.2.18
[2022-10-18 15:15:00]  INFO generating the "Makefile_20221018151500.mta" file...
[2022-10-18 15:15:00]  INFO done
[2022-10-18 15:15:00]  INFO executing the "make -f Makefile_20221018151500.mta p=cf mtar=mta.tar strict=true mode= t=\"gen\"" command...
[2022-10-18 15:15:01]  INFO validating the MTA project
[2022-10-18 15:15:01]  INFO running the "before-all" build...
[2022-10-18 15:15:01]  INFO executing the "npx -p @sap/cds-dk cds build --production" command...
..[cds] - determining build tasks for project [C:\vdev\cpa01\my-bookshop].
[cds] - the following build tasks will be executed
[cds] -    {
     "build": {
       "target": "gen",
       "tasks": [
         {"for":"hana", "src":"db", "options":{"model":["db","srv","app"]}},  
         {"for":"nodejs", "src":"srv", "options":{"model":["db","srv","app"]}}
       ]
     }
   }

[cds] - building project [C:\vdev\cpa01\my-bookshop], clean [true]
[cds] - cds [6.2.2], compiler [3.3.2], home [C:\vdev\cpa01\my-bookshop\node_modules\@sap\cds]

[cds] - done > wrote output to:
   gen\db\my-bookshop.db
   gen\db\package.json
   gen\db\src\.hdiconfig
   gen\db\src\gen\.hdiconfig
   gen\db\src\gen\.hdinamespace
   gen\db\src\gen\CatalogService.Authors.hdbview
   gen\db\src\gen\CatalogService.Books.hdbview
   gen\db\src\gen\CatalogService.Books_texts.hdbview        
   gen\db\src\gen\CatalogService.Countries.hdbview
   gen\db\src\gen\CatalogService.Countries_texts.hdbview    
   gen\db\src\gen\CatalogService.Orders.hdbview
   gen\db\src\gen\csv\my.bookshop-Authors.csv
   gen\db\src\gen\csv\my.bookshop-Authors.hdbtabledata      
   gen\db\src\gen\csv\my.bookshop-Books.csv
   gen\db\src\gen\csv\my.bookshop-Books.hdbtabledata        
   gen\db\src\gen\localized.CatalogService.Authors.hdbview  
   gen\db\src\gen\localized.CatalogService.Books.hdbview    
   gen\db\src\gen\localized.CatalogService.Countries.hdbview
   gen\db\src\gen\localized.CatalogService.Orders.hdbview   
   gen\db\src\gen\localized.my.bookshop.Authors.hdbview     
   gen\db\src\gen\localized.my.bookshop.Books.hdbview       
   gen\db\src\gen\localized.my.bookshop.Orders.hdbview      
   gen\db\src\gen\localized.sap.common.Countries.hdbview    
   gen\db\src\gen\my.bookshop.Authors.hdbtable
   gen\db\src\gen\my.bookshop.Books.hdbtable
   gen\db\src\gen\my.bookshop.Books_texts.hdbtable
   gen\db\src\gen\my.bookshop.Orders.hdbtable
   gen\db\src\gen\sap.common.Countries.hdbtable
   gen\db\src\gen\sap.common.Countries_texts.hdbtable       
   gen\db\undeploy.json
   gen\srv\.cdsrc.json
   gen\srv\package-lock.json
   gen\srv\package.json
   gen\srv\srv\_i18n\i18n.json
   gen\srv\srv\cat-service.js
   gen\srv\srv\csn.json

[cds] - build completed in 508 ms

.[2022-10-18 15:15:04]  INFO validating the MTA project
[2022-10-18 15:15:04]  INFO building the "my-bookshop-srv" module...
[2022-10-18 15:15:04]  INFO executing the "npm clean-install --production" command...
.npm WARN config production Use `--omit=dev` instead.
.npm ERR! code EUSAGE
npm ERR!
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR!
npm ERR! Missing: @sap/xssec@3.2.14 from lock file
npm ERR! Missing: hdb@0.19.5 from lock file
npm ERR! Missing: passport@0.6.0 from lock file
npm ERR! Missing: axios@0.26.1 from lock file
npm ERR! Missing: debug@4.3.4 from lock file
npm ERR! Missing: jsonwebtoken@8.5.1 from lock file
npm ERR! Missing: node-rsa@1.1.1 from lock file
npm ERR! Missing: valid-url@1.0.9 from lock file
npm ERR! Missing: follow-redirects@1.15.2 from lock file
npm ERR! Missing: jws@3.2.2 from lock file
npm ERR! Missing: lodash.includes@4.3.0 from lock file
npm ERR! Missing: lodash.isboolean@3.0.3 from lock file
npm ERR! Missing: lodash.isinteger@4.0.4 from lock file
npm ERR! Missing: lodash.isnumber@3.0.3 from lock file
npm ERR! Missing: lodash.isplainobject@4.0.6 from lock file
npm ERR! Missing: lodash.isstring@4.0.1 from lock file
npm ERR! Missing: lodash.once@4.1.1 from lock file
npm ERR! Missing: ms@2.1.3 from lock file
npm ERR! Missing: semver@5.7.1 from lock file
npm ERR! Missing: jwa@1.4.1 from lock file
npm ERR! Missing: buffer-equal-constant-time@1.0.1 from lock file
npm ERR! Missing: ecdsa-sig-formatter@1.0.11 from lock file
npm ERR! Missing: asn1@0.2.6 from lock file
npm ERR! Missing: passport-strategy@1.0.0 from lock file
npm ERR! Missing: pause@0.0.1 from lock file
npm ERR! Missing: ms@2.1.2 from lock file
npm ERR!
npm ERR! Clean install a project
npm ERR!
npm ERR! Usage:
npm ERR! npm ci
npm ERR!
npm ERR! Options:
npm ERR! [-S|--save|--no-save|--save-prod|--save-dev|--save-optional|--save-peer|--save-bundle]
npm ERR! [-E|--save-exact] [-g|--global] [--global-style] [--legacy-bundling]
npm ERR! [--omit <dev|optional|peer> [--omit <dev|optional|peer> ...]]
npm ERR! [--strict-peer-deps] [--no-package-lock] [--foreground-scripts]
npm ERR! [--ignore-scripts] [--no-audit] [--no-bin-links] [--no-fund] [--dry-run]
npm ERR! [-w|--workspace <workspace-name> [-w|--workspace <workspace-name> ...]]
npm ERR! [-ws|--workspaces] [--include-workspace-root] [--install-links]
npm ERR!
npm ERR! aliases: clean-install, ic, install-clean, isntall-clean
npm ERR!
npm ERR! Run "npm help ci" for more info

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\I575721\AppData\Local\npm-cache\_logs\2022-10-18T22_15_05_996Z-debug-0.log
[2022-10-18 15:15:07] ERROR could not build the "my-bookshop-srv" module: could not execute the "npm clean-install --production" command: exit status 1
make: *** [my-bookshop-srv] Error 1
Error: could not build the MTA project: could not execute the "make -f Makefile_20221018151500.mta p=cf mtar=mta.tar strict=true mode= t=\"gen\"" command: exit status 2
PS C:\vdev\cpa01\my-bookshop>

**Comment by renejeglinsky** [comment]
Hi @ValterAraujoJr,

thanks for reporting this. As the error log states, executing `npm install` should solve this situation for you. I'll add a step to the tutorial that is aligned with the [deployment guide of the CAP documentation](https://cap.cloud.sap/docs/guides/deployment/to-cf#5-freeze-dependencies), to prevent such situations.

All the best,
René

**Comment by renejeglinsky** [comment]
I added the step and therefore close this issue. Thanks again!
