### ISSUE TITLE
Create and Configure Forms

### ISSUE THREAD

**Issue by mohamedyosufdeenjmh** [sap-tutorials/Tutorials#18935]
Tutorials: https://developers.sap.com/tutorials/spa-create-forms.html
--------------------------

Step 3 -> Point number 12:
I hope the text "For the below **Input Field** enter the label and select the **Read Only** checkbox." is not required, as the subsequent form field that was mentioned below is of type Paragraph and it has no Read Only checkbox available.
![image](https://user-images.githubusercontent.com/38460935/196710980-d30b34a9-5914-4cb1-967b-fa6b82d1488d.png)

**Comment by pbujnicka** [comment]
Thank you for the feedback. An update was published.
