### ISSUE TITLE
Deploy Your SAPUI5 App

### ISSUE THREAD

**Issue by bmaciag** [sap-tutorials/Tutorials#18947]
Tutorials: https://developers.sap.com/tutorials/sapui5-101-deploy-application.html
--------------------------

Hi, currently I have an issue with this tutorial any maybe someone could help:

I did the CF sign in but I cant select any org and space
![image](https://user-images.githubusercontent.com/26123384/197028452-c181d4cd-6615-4c9e-bde0-8dcd33b03898.png)

But in general there is an existing org and space
![image](https://user-images.githubusercontent.com/26123384/197028546-53ba08cd-ae5b-491f-b791-43a05058e20b.png)

Any suggestions how to solve this?

**Comment by nicoschoenteich** [comment]
Hi @bmaciag, looks like you signed in to Cloud Foundry using the wrong API endpoint. The org you are trying to login to sits in an extension landscape (`eu10-004`) so you will have to change that in the SAP Business Application Studio. You can use the command `cf login -a` in the terminal to specify another API endpoint. There is probably also a way to do it via the GUI.
