### ISSUE TITLE
Add User Authentication to Your Application (SAP HANA Cloud)

### ISSUE THREAD

**Issue by SatheesP** [sap-tutorials/Tutorials#18949]
Hello Team,
Tutorials: https://developers.sap.com/tutorials/hana-cloud-cap-add-authentication.html
--------------------------

1. Tech Bytes video - 6 steps are there, but tutorial 5 steps and missing "Adjust yaml".
2. default-env.json file is available only in /app folder level and not project folder level.
3. default-env.json configuration section it-self missing in tutorial

-Sathees

**Comment by jung-thomas** [comment]
I'm sorry but I'm not able to understand your feedback. This tutorial does not use a default-env.json.
