### ISSUE TITLE
Create an Empty SAPUI5 Project - Error when creating a project with FIORI Application generator

### ISSUE THREAD

**Issue by ALEJONO** [sap-tutorials/Tutorials#18954]
Hi.

I'm following the tutorial [Create an Empty SAPUI5 Project](https://developers.sap.com/tutorials/sapui5-101-create-project.html) for**Creating an empty SAPUI5 Project** in SAP Business Application Studio with SAP Fiori tools. 

Every time I reach step 3, in which an empty project must be created, I run **Fiori Application Generator**, all the sub-steps are completed without any problems and therefore I click on Finish, then project generation starts but always ends showing up the following **error**:

> The extension providing '**sap.ux.application.modeler.info**' view is not capable of restoring it.
Want to help fix this? Please inform the extension developer to register a [reviver](https://code.visualstudio.com/api/extension-guides/webview#serialization).

Could anybody tell me the reason for this error and maybe how to avoid it in order to successfully create the project?
@IObert, @jmmargo

Kind regards,

Ale.

**Comment by IObert** [comment]
@nicoschoenteich this might be something for you :)

**Comment by cjbernal** [comment]
Hi @ALEJONO, sorry to see that you are having an issue. I have reached out to colleagues from the SAP Fiori tools Application Generator team to see if they can help answer your question.

Kind regards,
Conrad

**Comment by Klaus-Keller** [comment]
Hi @ALEJONO,

There are known problems in some circumstances. Did you do as request in step "3: Create a new project"

>First, you need to select the workspace for your project by choosing from menu File > Open Workspace and select projects folder.

before you generated the app? If not, that might cause this issue.

Cheers,
Klaus

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
