### ISSUE TITLE
Get a Free Account on SAP BTP Trial

### ISSUE THREAD

**Issue by m-badura** [sap-tutorials/Tutorials#18950]
Tutorials: https://developers.sap.com/tutorials/hcp-create-trial-account.html
--------------------------

In Step 6 I'm requested to click the button "Enter Your Trial Account", which can also be seen in the screenshot.
But the button is now called "Go To Your Trial Account".

**Comment by qmacro** [comment]
Thanks for another accurate observation! I've [made a change](https://github.com/sap-tutorials/Tutorials/commit/8e13187fed35902109b8f68ce16b86de5bc5653f) here as well to reflect the new wording on the button. The change should show up in the tutorial sometime soon!
