### ISSUE TITLE
CORS issue in tutorial "Create an SAP Fiori Elements-Based UI"

### ISSUE THREAD

**Issue by abap-weasel** [sap-tutorials/Tutorials#18961]
Tutorials: https://developers.sap.com/tutorials/btp-app-create-ui-fiori-elements.html
--------------------------

Hi, following the tutorial for CAP app. I am Stuck at Step 3 section 2. When trying to test application after app generator via http://localhost:4004/risks/webapp/index.html nothing happens Browser console shows error:

Access to XMLHttpRequest at 'https://ui5.sap.com/shells/sandbox/fioriSandboxCOnfig.json' from origin 'http://localhost:4004' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested ressource. 

Fiori preview is still working fine. Please advise on how to fix and update guide accordingly. -- Thank you!

**Comment by manjuX** [comment]
Hi @abap-weasel,

Can you share which version of UI5 you chose to generate the application? I used 1.107.1 and I do not see this error when I click the link so it's possible it's only occurring for a particular version.

Best regards,
Manju

**Comment by Mato70** [comment]
Hi,
I got same error when I try to open http://localhost:4004/launchpage.html#Shell-home.
I use 1.108.0 

Best Regards, 
Tamas

**Comment by Mato70** [comment]
This is the full console log:

jquery-dbg.js:10224 Access to XMLHttpRequest at 'https://ui5.sap.com/shells/sandbox/fioriSandboxConfig.json' from origin 'http://localhost:4004' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
send @ jquery-dbg.js:10224
ajax @ jquery-dbg.js:9805
jQuery.ajax @ jquery-compat-dbg.js:338
applyDefaultApplicationConfig @ sandbox.js:161
bootstrap @ sandbox.js:283
(anonymous) @ sandbox.js:22
Promise.then (async)
xx-bootTask @ sandbox.js:21
S @ Core-dbg.js:477
boot @ Core-dbg.js:468
(anonymous) @ Object-dbg.js:255
(anonymous) @ sap-ui-core.js?bundle-code-2:2
jquery-dbg.js:10224

GET https://ui5.sap.com/shells/sandbox/fioriSandboxConfig.json net::ERR_FAILED 404
send @ jquery-dbg.js:10224
ajax @ jquery-dbg.js:9805
jQuery.ajax @ jquery-compat-dbg.js:338
applyDefaultApplicationConfig @ sandbox.js:161
bootstrap @ sandbox.js:283
(anonymous) @ sandbox.js:22
Promise.then (async)
xx-bootTask @ sandbox.js:21
S @ Core-dbg.js:477
boot @ Core-dbg.js:468
(anonymous) @ Object-dbg.js:255
(anonymous) @ sap-ui-core.js?bundle-code-2:2
sandbox.js:174

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'status')
    at Object.error (sandbox.js:174:141)
    at u (jquery-dbg.js:3500:31)
    at Object.fireWith [as rejectWith] (jquery-dbg.js:3630:7)
    at k (jquery-dbg.js:9913:14)
    at Function.ajax (jquery-dbg.js:9814:5)
    at jQuery.ajax (jquery-compat-dbg.js:338:22)
    at applyDefaultApplicationConfig (sandbox.js:161:28)
    at bootstrap (sandbox.js:283:21)
    at sandbox.js:22:17

**Comment by Mato70** [comment]
I changed the url 
from https://ui5.sap.com/test-resources/sap/ushell/bootstrap/sandbox.js
to https://sapui5.hana.ondemand.com/1.108.0/test-resources/sap/ushell/bootstrap/sandbox.js
solved my issue.
