### ISSUE TITLE
Consume SAP BTP Services In SAP Kyma

### ISSUE THREAD

**Issue by jastill** [sap-tutorials/Tutorials#18964]
Tutorials: https://developers.sap.com/tutorials/btp-kyma-extension.html
--------------------------

Write here how you think we can improve the tutorial ...

In step 3.4 the tutorial refers to <Custom-Domain> should this be <cluster-domain>?

"https://fioriapp.<cluster-domain>/**"

**Comment by LalithManokar** [comment]
HI @jastill ,

It should be replaced with your cluster domain before deploying the file.
- "https://fioriapp.<cluster-domain>/**"

Find your cluster domain and replace in the createservice.yaml file

to find your cluster domain please run the below command and replace  in the createservice.yaml file
kubectl cluster-info

Please check the step 3.4 to find your cluster domain.

Regards,
Lalith.S

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
