### ISSUE TITLE
Secure a Multitenant Application with the Authorization and Trust Management Service (XSUAA)

### ISSUE THREAD

**Issue by rcaziraghi** [sap-tutorials/Tutorials#19804]
Tutorials: https://developers.sap.com/tutorials/secure-multitenant-app-xsuaa-kyma.html
--------------------------

Hello,

The deployment file "k8s-deployment-services.yaml" references the old service catalog (due to the migration from Service Catalog to SAP BTP Service Operator, I think). I could not deploy without adjustments to the file.

I suggest correcting the "k8s-deployment-services.yaml" file due to the migration.

Thank you.

**Comment by rcaziraghi** [comment]
Hello,

I adjusted the files to deploy the application with success. I can provide these files for the tutorial update. Please let me know the best way to reach you if I can be helpful.

Thank you.

**Comment by TIAXU** [comment]
> Hello,
> 
> I adjusted the files to deploy the application with success. I can provide these files for the tutorial update. Please let me know the best way to reach you if I can be helpful.
> 
> Thank you.

Do you mind sharing your repo with me? If your repo is private, maybe you can add me for the time being. Thanks in advance!

**Comment by rcaziraghi** [comment]
Repo shared. The lines I've encountered issues with in the "k8s-deployment-services.yaml" file are commented, but you can delete them if you want. I've kept the lines to remember what I've changed.

**Comment by rcaziraghi** [comment]
Hello @TIAXU 

I've made more changes in the repo files to deploy the application to a different Kyma instance. I've switched from trial to Free Tier. The files are a little bit different from the tutorial, but it's working as intended.

Please let me know if I can be of any further help.

**Comment by TIAXU** [comment]
> 

Hi rcaziraghi,
Thanks in advance! And I will check and update them based on your repo.

**Comment by TiaXu1122** [comment]
@rcaziraghi Hi rcaziraghi, could you please share your repo again? I cannot find it now.

**Comment by TiaXu1122** [comment]
Fix with commit: https://github.com/sap-tutorials/Tutorials/pull/22891
