### ISSUE TITLE
Ask and Answer Questions on SAP Community

### ISSUE THREAD

**Issue by bvarwig** [sap-tutorials/Tutorials#20125]
Tutorials: https://developers.sap.com/tutorials/community-qa.html
--------------------------

Write here how you think we can improve the tutorial ...
![image](https://user-images.githubusercontent.com/8438658/199669181-08e5a696-b441-4b49-8297-1add2d3b216f.png)

Regards Britta

**Comment by lenastodal** [comment]
Hi @bvarwig - thanks for reaching out and suggesting to hyperlink it. I think it's a great idea and I will follow through on it. 
Thank you, 
Lena
