### ISSUE TITLE
Create a Simple Database Table for ABAP Environment

### ISSUE THREAD

**Issue by larshp** [sap-tutorials/Tutorials#20131]
Tutorials: https://developers.sap.com/tutorials/abap-environment-create-table.html
--------------------------

In step 7, code example, please fix the whitespace

`DATA:it_bookings TYPE TABLE OF ztbooking_xxx.`, either remove the colon, or add a space after it, eg. `DATA it_bookings TYPE TABLE OF ztbooking_xxx.`

`out->write( 'data inserted successfully!').` should be `out->write( 'data inserted successfully!' ).` to be nice ABAP code

**Comment by mervey45** [comment]
Hi @larshp ,

thank you for your feedback. We'll update this as soon as possible. I created PR #20409 for this fix.

Best regards, 
Merve
