### ISSUE TITLE
Deploy a Multitenant Application to a Provider subaccount, Kyma Runtime

### ISSUE THREAD

**Issue by rcaziraghi** [sap-tutorials/Tutorials#20138]
Tutorials: https://developers.sap.com/tutorials/deploy-multitenant-app-kyma.html
and
Tutorials: https://developers.sap.com/tutorials/deploy-nodejs-application-kyma.html
--------------------------

Hello experts,

Before step 6 of both aforementioned tutorials shouldn't be an instruction to rename "kubelogin.exe", as is instructed in step 4 of the "Deploy Your CAP Application on SAP BTP Kyma Runtime -> Deploy Your CAP Application on SAP BTP Kyma Runtime"(https://developers.sap.com/tutorials/btp-app-kyma-prepare-dev-environment.html) tutorial?

![image](https://user-images.githubusercontent.com/18582796/200602788-c3740699-4a2f-46d3-a4dd-ab17a029304c.png)

I could not find this instruction in both the tutorials at the header, and I did not need to rename the executable before this moment because I did that tutorial before the others, however, if a new developer tries to create the registry password without that step the following error happens:

```
error: failed to create secret Post "https://api.c-9460142.kyma.ondemand.com/api/v1/namespaces/multitenancy-ns/secrets?fieldManager=kubectl-create&fieldValidation=Strict": getting credentials: exec: executable kubectl-oidc_login not found

It looks like you are trying to use a client-go credential plugin that is not installed.
```

After that step, I could create the secret.

Please let me know if I can be of any help.

Rafael Caziraghi

**Comment by TiaXu1122** [comment]
update prerequisites in this commit: https://github.com/sap-tutorials/Tutorials/pull/22891
