### ISSUE TITLE
Create an SAP Fiori Elements-Based UI

### ISSUE THREAD

**Issue by Mato70** [sap-tutorials/Tutorials#20136]
Tutorials: https://developers.sap.com/tutorials/btp-app-create-ui-fiori-elements.html
--------------------------
Hi, Thank you for this awsome tutorial!

After this step "3. Try and fill in data in the main group fields Priority and Impact and choose Create." the next page is not the list, but a form of the created new record without button to go to the list.

**Comment by manjuX** [comment]
Hi @Mato70,

Thank you for your feedback, after creating a new risk you can use the browser's back button to navigate back to the list view. You do get a shell toolbar when you complete the launchpage tutorial which will have a back navigate button.

We'll make it clearer in the documentation that you need to navigate back to the list page.

Best regards,
Manju

**Comment by slavipande** [comment]
Thanks for submitting this issue. We've improved the wording of this step.
Hence, I'll be closing this issue.

Best regards,
Sveto
