### ISSUE TITLE
Set Up Integration Suite Trial

### ISSUE THREAD

**Issue by sreejithppsap** [sap-tutorials/Tutorials#20399]
Tutorials: https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html - 'Add Capabilities' button not working.
--------------------------

Write here how you think we can improve the tutorial ...

**In STEP 3 Provision the capabilities** - 1. In the Integration Suite home page, choose Add Capabilities to activate the capabilities offered by Integration Suite.
**Expected Result: 'Activate Capabilities' popup window should be displayed. 
Actual Result:**  'Add Capabilities' button does not work.

Please check the attached video file '**Add_Capabilities_Not_Working.mp4**'.

Labels to be added:
Scenario label: SCPTest-cloudin
Sprint Label: SCPTest-2211A
Landscape Label: trail3 (AP Region)
Priority: High

Thanks and Regards
Sreejith

**Comment by sreejithppsap** [comment]
https://user-images.githubusercontent.com/58926896/201012714-60c0a11b-7818-4998-b0e4-61be6e2f95df.mp4

**Comment by Karunaharan** [comment]
Hi @sreejithppsap 
The issue is fixed and you should be able to add capabilities now.

Regards,
​Karuna
