### ISSUE TITLE
Set Up Integration Suite Trial- Assign Role Collection - A minor correction for the input field.

### ISSUE THREAD

**Issue by sreejithppsap** [sap-tutorials/Tutorials#20404]
Tutorials: https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html- Assign Role Collection - A minor correction for the input field.
--------------------------

Write here how you think we can improve the tutorial ...

**In STEP 2**
Subscribe to the service
In the dialog that appears, select Integration Provisioner. Choose Assign Role Collection.
**6.** In the dialog that appears, select **Integration Provisioner**. Choose Assign Role Collection.

The actual value is “ Integration_Provisioner” and not “Integration Provisioner”. (Underscore in between 'Integration' and 'Provisioner')
If user does a copy paste from the tutorial into the filter the result is as follows:

If you provide “Integration Provisioner”, nothing will be displayed.
Only if you give “Integration_Provisioner” the expected entry will be displayed. 

Please update the tutorial accordingly.

Please refer attached image(**Integration_Provisioner.jpg**) for more clarity.

![Integration_Provisioner](https://user-images.githubusercontent.com/58926896/201030230-db6a4a0b-bff9-4ae4-875b-b950edb9be05.jpg)

Labels to be added:
Scenario label: SCPTest-cloudin
Sprint Label: SCPTest-2211A
Landscape Label: trail2(Trial US East (VA) (AWS) )  & trail3 (AP Region)
Priority: Low

Thanks and regards
Sreejith

**Comment by Karunaharan** [comment]
Hi @sreejithppsap,
This is fixed now. Will be available ASAP.
