### ISSUE TITLE
Configure Business Rules, Workflow and Process Visibility  - SAP Business Application Studio UI changed.

### ISSUE THREAD

**Issue by sreejithppsap** [sap-tutorials/Tutorials#20402]
Tutorials: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-2-configure.html - SAP Business Application Studio UI changed. Please update the tutorial accordingly.
--------------------------

Write here how you think we can improve the tutorial ...

**STEP 5 : Download and import workflow sample application** 
3. Click on the Dev Space to go into the workspace and from File menu choose Open Workspace
4. Drag and drop the extracted cf-onboarding-sample project in the dialog and click Open.

**Points to improve** : SAP Business Application Studio UI has been updated. Please update the steps and screenshots in the tutorial accordingly.  Please see the attached document (SAP_Business_Application_Studio_Screen_Updated.docx) for more clarity.
[SAP_Business_Application_Studio_Screen_Updated.docx](https://github.com/sap-tutorials/Tutorials/files/9977892/SAP_Business_Application_Studio_Screen_Updated.docx)

Labels to be added:
Scenario label: SCPTest-eboard
Sprint Label: SCPTest-2211A
Landscape Label: trail2(Trial US East (VA) (AWS) ) & Trial3 (AP Region)
Priority: Medium

Thanks and Regards
Sreejith

**Comment by sreejithppsap** [comment]
Labels to be added:
Scenario label: SCPTest-eboard
Sprint Label: SCPTest-2211A
Landscape Label: trail2(Trial US East (VA) (AWS) ) & Trial3 (AP Region)
Priority: High

**Comment by FarozanFarman** [comment]
Hi,

These issues are still reproducible in March exectution

Thanks and Regards,
Farozan

**Comment by BaskarThambiayah** [comment]
Hi Colleagues,
Closing this ticket as this tutorial is replaced with "Build Your First Business Process with SAP Build Process Automation".
Thank you
