### ISSUE TITLE
Biz.App.Studio Screenshots needs to be changed in tutorial "Build an SAP Fiori App that Consumes Data from an On-Premise System"

### ISSUE THREAD

**Issue by BaskarThambiayah** [sap-tutorials/Tutorials#20400]
Hi Colleagues,

Tutorial: https://developers.sap.com/group.appstudio-fiori.html
Issue: SAP Business Application Studio relevant screenshots needs to be changed in the tutorial "Build an SAP Fiori App that Consumes Data from an On-Premise System" as per the new UI change.

1. Tutorial : https://developers.sap.com/tutorials/appstudio-devspace-fiori-create.html (Create a Dev Space for SAP Fiori Apps)
     Step 2: Open the SAP Fiori dev space
                 2. The SAP Fiori dev space opens and the Welcome tab appears.
                 
![image](https://user-images.githubusercontent.com/60343237/201012808-6eacac0d-6eb5-443f-a810-a19796bcb581.png)

2. Tutorial: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html (Create an SAP Fiori App Using SAP Business Application Studio)
     Step 1: Create new Multitarget Application project
![image](https://user-images.githubusercontent.com/60343237/201013135-9e48101b-598f-4354-ad9f-572e587311fd.png)

     Step 2: Open the project's workspace
![image](https://user-images.githubusercontent.com/60343237/201013259-ce34c39c-9927-4638-9ce0-41d514d9541d.png)

     Step 5: Open the layout editor and the code editor
                 4. Choose Open With > Layout Editor.
    
![image](https://user-images.githubusercontent.com/60343237/201013414-81cf0d55-e564-49df-9b5e-7dae0f928b51.png)

Please look into this and update the latest screenshots as per the SAP Business Application Studio UI change.

Labels to be added:
Scenario label: SCPTest-fbizapp
Sprint Label: SCPTest-2211A
Landscape Label: trail2(Trial US East (VA) (AWS) ) & trial3 (AP Region)
Priority: High

Many thanks & regards,
Baskar

**Comment by raz-korn** [comment]
@BaskarThambiayah , 

We plan to have the tutorial updated for TechEd.

Regards - Raz
