### ISSUE TITLE
Display Fetched Data in Your AppGyver Application

### ISSUE THREAD

**Issue by aristotelesquintanar** [sap-tutorials/Tutorials#20401]
Tutorials: https://developers.sap.com/tutorials/appgyver-display-information.html
--------------------------

In the **Step2**, says:
Select **Data Variables** and then click your **_Open food facts_** variable.
but is lacking a _mini-step_.  It should say:
Select **Data and Variables**, then choose **Data Variable** and finally click your **_Open food facts_** variable.

**Comment by thecodester** [comment]
But it does say Data & Variables, and then below the picture it says Data Variables, no?

**Comment by jmmargo** [comment]
Assuming this has been resolved, I am closing the issue.  Please reopen if needed.
