### ISSUE TITLE
Create an Empty ReactJs Project "generator failed"

### ISSUE THREAD

**Issue by himanshukr17** [sap-tutorials/Tutorials#20410]
Tutorial :- [https://blogs.sap.com/2021/07/05/react-development-with-sap-business-application-studio/](https://blogs.sap.com/2021/07/05/react-development-with-sap-business-application-studio/)
At the time of creation of react js project it show below error after select Data source

{"message":"@sapdmz/html5-project:app generator failed - process.on(uncaughtException) Cannot read properties of undefined (reading 'find')","stack":"TypeError: Cannot read properties of undefined (reading 'find')\n\tat module.exports._setConnectivityData (/extbin/npm/globals/lib/node_modules/@sapdmz/generator-reactjs-module/generators/app/index.js:470:41)\n\tat module.exports._promptServiceMapping (/extbin/npm/globals/lib/node_modules/@sapdmz/generator-reactjs-module/generators/app/index.js:373:43)\n\tat module.exports.prompting (/extbin/npm/globals/lib/node_modules/@sapdmz/generator-reactjs-module/generators/app/index.js:59:46)"}

![image](https://user-images.githubusercontent.com/48213505/201483643-a7595e41-c7bd-47ca-bbaf-b99ddbbc226b.png)

<img width="1440" alt="Screenshot 2022-11-12 at 9 44 16 PM" src="https://user-images.githubusercontent.com/48213505/201483657-f20247bc-7557-49eb-acbd-8028a1b7c763.png">

here you can check my destination connection 

![image](https://user-images.githubusercontent.com/48213505/201483728-23b3025a-4d08-4465-af34-afa75cedb5f9.png)

**Comment by MichaelCzcz** [comment]
These GitHub issues are to resolve issues (i.e., problems/errors) with the tutorials that are part of the Tutorial Navigator. Your question seems to be about a tutorial that's part of a blog and 
would get more visibility -- and a better answer -- in that blog's comment section.
