### ISSUE TITLE
Display Data from the Northwind Service

### ISSUE THREAD

**Issue by rcaziraghi** [sap-tutorials/Tutorials#20416]
Tutorials: https://developers.sap.com/tutorials/sapui5-fiori-cf-display-data.html
--------------------------

Hello,

In steps 1, 2, and 3 of this tutorial, we are instructed to create a new view to display the list of products. Watching the tutorial and images I understand that we are instructed to do so because a previous version of *generator-easy-ui5* would not have an outer container created by default.

However, that is not the case anymore. Please see the image attached below in comparison to the image in step3:

![image](https://user-images.githubusercontent.com/18582796/201664083-2ef4ea63-b56a-473b-9cd1-2c57d83636a1.png)

In my fresh installment, I have an "App" and a "Main" view, rendering the view creation (to create the outer/inter container) irrelevant.

I suggest to adapt the tutorial to use the new "main" view as the "product" view. Steps 1, 2, and 3 would need corrections. 

Please let me know if I can be of any help in this correction.

Thank you.

Rafael Caziraghi.

**Comment by nicoschoenteich** [comment]
Hi @rcaziraghi, thanks a lot, good catch. The easy-ui5 generator indeed got an update a few months back with exactly that change. Thanks for pointing it out. BR, Nico

**Comment by rcaziraghi** [comment]
Hello @nicoschoenteich 
Always happy to help. Should I create a pull request to address this issue and issue https://github.com/sap-tutorials/Tutorials/issues/20415 ?
PS: Congrats on TechEd! It was awesome. 
Best regards,
Rafael

**Comment by nicoschoenteich** [comment]
Hi @rcaziraghi, thanks a lot. I will fix the issues later today. Best, Nico
