### ISSUE TITLE
Create a Fiori Launchpad App

### ISSUE THREAD

**Issue by rcaziraghi** [sap-tutorials/Tutorials#20415]
Tutorials: https://developers.sap.com/tutorials/sapui5-fiori-cf-create-project.html
--------------------------

Hello,

Just minor adjustment, but there are 2 new parameters in generator-easy-ui5 at this moment (step 1):

? What do you want to do? Create a new OpenUI5/SAPUI5 project                          [app]
? How do you want to name this project? products
? Which namespace do you want to use? tutorial
**? Do you want to enable the SAP Fiori elements flexible programming model? No**
? On which platform would you like to host the application? SAP Launchpad service
? Which view type do you want to use? XML
? Where should your UI5 libs be served from? Content delivery network (SAPUI5)
? Would you like to create a new directory for the project? Yes
? Would you like to add JavaScript code assist libraries to the project? Yes
**? Would you like to initialize a local git repository for the project? Yes**
? What name should be displayed on the Fiori Launchpad tile? Products

Thank you.

**Comment by nicoschoenteich** [comment]
Hi @rcaziraghi, that's right, thanks for pointing it out. Will add the 2 new question soon. BR, Nico
