### ISSUE TITLE
Integrate List Report into ABAP Fiori Launchpad: Execute transport task (Optional) 

### ISSUE THREAD

**Issue by peterpersiel** [sap-tutorials/Tutorials#20448]
Tutorials: https://developers.sap.com/tutorials/abap-environment-abap-flp.html
--------------------------
In step 6, Execute transport task (Optional) it's mentioned to execute the transport task. Please rename "execute" to "release" the transport task. 

Finally, please add another section after releasing transport task, to also release the transport request. Only if also the transport request is released, the space/page objects would be exported and could be imported e.g. in production system.

**Comment by mervey45** [comment]
Hi @peterpersiel,

thank you for your feedback. I created follwing PR: #20764 to solve this issue.

Best regards, 
Merve
