### ISSUE TITLE
Integrate List Report into ABAP Fiori Launchpad, Prerequisites

### ISSUE THREAD

**Issue by peterpersiel** [sap-tutorials/Tutorials#20445]
Tutorials: https://developers.sap.com/tutorials/abap-environment-abap-flp.html
--------------------------

In the beginning of the tutorial there is a remark "Hint: Your Business Application Studio subscription needs to be in the same subaccount as the ABAP system." but in the tutorial Business Application Studio is never used.

**Comment by peterpersiel** [comment]
Please add to prerequisites of this tutorial to enable spaces layout in FLP in order to see app tiles that are added to spaces/pages.
Documentation: https://help.sap.com/docs/SAP_S4HANA_CLOUD/4fc8d03390c342da8a60f8ee387bca1a/64a5e1675ce7413791a654d2228a90be.html?state=TEST&version=2208.502

**Comment by mervey45** [comment]
Hi @peterpersiel ,

thank you for your feedback. I created following PR: #20484 for this GitHub issue.

Best regards, 
Merve
