### ISSUE TITLE
Integrate List Report into ABAP Fiori Launchpad: Alternative 1

### ISSUE THREAD

**Issue by peterpersiel** [sap-tutorials/Tutorials#20447]
Tutorials: https://developers.sap.com/tutorials/abap-environment-abap-flp.html
--------------------------
In step 4, Alternative 1 as transport one should select "testing transport", but transport created in previous step is called Transport_Request_XXX.

**Comment by mervey45** [comment]
Hi @peterpersiel ,

thank you for your comment. Testing transport is the transport request, that was already created. Transport_Request_XXX has not been created, like in step 3.6 (https://developers.sap.com/tutorials/abap-environment-abap-flp.html) described. This step was added to show the default transport request.

Best regards, 
Merve
