### ISSUE TITLE
Enhance Behavior With Action and Validation: More information

### ISSUE THREAD

**Issue by peterpersiel** [sap-tutorials/Tutorials#20441]
Tutorials: https://developers.sap.com/tutorials/abap-environment-behavior-action.html
--------------------------

For the last link in step 11, More Information to open sap course https://open.sap.com/courses/cp13 the formatting seems to be broken.

**Comment by mervey45** [comment]
Hi @peterpersiel ,

thank you for your feedback. I created following PR: #20484 for this GitHub issue.

Best regards, 
Merve
