### ISSUE TITLE
Integrate List Report into ABAP Fiori Launchpad: Create transport request or use default transport request

### ISSUE THREAD

**Issue by peterpersiel** [sap-tutorials/Tutorials#20446]
Tutorials: https://developers.sap.com/tutorials/abap-environment-abap-flp.html
--------------------------

For step 3, Create transport request or use default transport request you need access to Export Customizing Transports app. You don't have access to this app with the SAP_BR_ADMINISTRATOR role but you need the role SAP_BR_BPC_EXPERT and in particular business catalogs SAP_CORE_BC_BCT_TRN_MNG_PC and SAP_CORE_BC_BCT_TRN_REL_PC assigned to your user in order to use the app. Please mention as prerequisite.

**Comment by mervey45** [comment]
Hi @peterpersiel ,

thank you for your feedback. I created following PR: #20484 for this GitHub issue.

Best regards, 
Merve
