### ISSUE TITLE
Create a Custom RAP Business Object to Trigger Purchase Requisitions API: Prerequisites

### ISSUE THREAD

**Issue by peterpersiel** [sap-tutorials/Tutorials#20458]
Tutorials: https://developers.sap.com/tutorials/abap-s4hanacloud-procurement-purchasereq-shop.html
--------------------------
In prerequisites of the tutorial the SAP_PRC_BC_PURCHASER_PR business catalog is mentioned. This business catalog does not exist (anymore).
SAP_MM_BC_PR_MANAGE_PC business catalog includes the Manage Purchase Requisitions app. Business catalog is for example included in business role template SAP_BR_PURCHASER. Please change accordingly.

**Comment by peterpersiel** [comment]
Please also add following prerequisite:

> Use Starter Development Tenant in S/4HANA Cloud for the tutorial to have necessary sample data in place. See https://help.sap.com/docs/SAP_S4HANA_CLOUD/a630d57fc5004c6383e7a81efee7a8bb/e022623ec1fc4d61abb398e411670200.html?state=DRAFT&version=2208.503 (3-System Landscape and Transport Management).

**Comment by mervey45** [comment]
Hi @peterpersiel ,

thank you for your feedback. I created following PR: #20484 for this GitHub issue.

Best regards, 
Merve
