### ISSUE TITLE
Tutorial Page appstudio-devspace-fiori-create.md Issue. PROD

### ISSUE THREAD

**Issue by SAPDocs** [sap-tutorials/Tutorials#20452]
Tutorial issue found: [https://github.com/sap-tutorials/Tutorials/blob/master/tutorials/appstudio-devspace-fiori-create/appstudio-devspace-fiori-create.md](https://github.com/sap-tutorials/Tutorials/blob/master/tutorials/appstudio-devspace-fiori-create/appstudio-devspace-fiori-create.md) contains invalid tags. Even though your tutorial was created, the invalid tags listed below were disregarded. Please double-check the following tags:
- products>sap-btp-cloud-foundry-environment

 Affected server: PROD

**Comment by raz-korn** [comment]
Hi @MichaelCzcz ,
Which tag should be used instead?
Regards - Raz

**Comment by MichaelCzcz** [comment]
The tag as such is correct, but the name space "products" is not. It has been replaced by "software-product" many months ago.

**Comment by raz-korn** [comment]
Pushed to production and create PR.
