### ISSUE TITLE
Integrate List Report into ABAP Fiori Launchpad, missing step Add app to page section

### ISSUE THREAD

**Issue by peterpersiel** [sap-tutorials/Tutorials#20465]
Tutorials: https://developers.sap.com/tutorials/abap-environment-abap-flp.html
--------------------------

After alternative 1 and 2, there is a final step missing to add the travel app to the default section in the Launchpad page.

Please add this step in the tutorial: https://help.sap.com/docs/SAP_S4HANA_CLOUD/4fc8d03390c342da8a60f8ee387bca1a/7b42aad18c53439db2cce55719253674.html?state=TEST&version=2208.502 --> How to Edit the Page Content

**Comment by mervey45** [comment]
Hi @peterpersiel,

thank you for your feedback. I created follwing PR: #20764 to solve this issue.

Best regards, 
Merve
