### ISSUE TITLE
Create a SAP Fiori App and Deploy it to SAP S/4HANA Cloud, ABAP Environment: Create IAM App and business catalog

### ISSUE THREAD

**Issue by peterpersiel** [sap-tutorials/Tutorials#20460]
Tutorials: https://developers.sap.com/tutorials/abap-s4hanacloud-procurement-purchasereq-shop-ui.html
--------------------------

In step 10 package is ZTRAVEL_APP_XXX but should be Z_PURCHASE_REQ_XXX. Please adjust accordingly.

**Comment by mervey45** [comment]
Hi @peterpersiel ,

thank you for your feedback. I created following PR: #20484 for this GitHub issue.

Best regards, 
Merve
