### ISSUE TITLE
Tutorial Page appstudio-devspace-fiori-create.md Issue. PROD

### ISSUE THREAD

**Issue by SAPDocs** [sap-tutorials/Tutorials#20470]
Tutorial issue found: [https://github.com/sap-tutorials/Tutorials/blob/master/tutorials/appstudio-devspace-fiori-create/appstudio-devspace-fiori-create.md](https://github.com/sap-tutorials/Tutorials/blob/master/tutorials/appstudio-devspace-fiori-create/appstudio-devspace-fiori-create.md) contains invalid tags. Even though your tutorial was created, the invalid tags listed below were disregarded. Please double-check the following tags:
- software-product>sap-btp-cloud-foundry-environment

 Affected server: PROD

**Comment by MichaelCzcz** [comment]
software-product>sap-btp--cloud-foundry-environment is the correct one

**Comment by raz-korn** [comment]
Done.
