### ISSUE TITLE
Undeploy Your Multi-Target Application (MTA)

### ISSUE THREAD

**Issue by roman-zaglauer** [sap-tutorials/Tutorials#20471]
Tutorials: https://developers.sap.com/tutorials/btp-app-undeploy-cap-application.html
--------------------------

Please point out that the "cpapp" is the mta-id.

Thank you! 

Kind regards,
Roman

**Comment by manjuX** [comment]
Hi, I'm closing this ticket as the reference was added to the tutorial. Please open a new ticket if you would like to provide additional feedback for our tutorials. Thank you.
