### ISSUE TITLE
Define and Expose a CDS-Based Travel Data Model

### ISSUE THREAD

**Issue by iwonahahn** [sap-tutorials/Tutorials#20516]
Tutorials: https://developers.sap.com/tutorials/abap-environment-data-model.html
--------------------------

Write here how you think we can improve the tutorial ...

Remove the duplicate, marked in red, as this is the same as in the note above ...

<img width="1327" alt="2022-11-17_20-14-46" src="https://user-images.githubusercontent.com/22098308/202538111-676bfa9a-aca0-4409-92f5-5083972bf0e4.png">

**Comment by mervey45** [comment]
Hi @iwonahahn ,

thank you for your feedback. I created following PR: #20739 for this issue.

Best regards, 
Merve

**Comment by iwonahahn** [comment]
Hi @mervey45,

Thanks a lot for the quick fix.

Best regards,
Iwona
