### ISSUE TITLE
Use SQL on Files to query data from multiple directory

### ISSUE THREAD

**Issue by AmauryVanEspen** [sap-tutorials/Tutorials#20688]
Tutorials: https://developers.sap.com/tutorials/data-lake-sof-multiple-directories.html
--------------------------

the link in description are broken:
[Getting Started with Data Lake Files HDLFSCLI](https://developers.sap.com/tutorials/data-lake-sof-multiple-directories/jcr:content.github-proxy.1668456005.file/developers.sap.com/tutorials/data-lake-file-containers-hdlfscli)
[Use SOF to Query data from Single Directory](https://developers.sap.com/tutorials/data-lake-sof-multiple-directories/jcr:content.github-proxy.1668456005.file/developers.sap.com/tutorials/data-lake-sof-single-directory)

**Comment by jmmargo** [comment]
I have tested both of these links by launching them from the tutorial and they both work.  Perhaps the navigator was experiencing an issue at the time, but now I am unable to reproduce the error.

**Comment by danielva** [comment]
This tutorial no longer appears to be published.
