### ISSUE TITLE
Getting Started with Data Lake Files HDLFSCLI

### ISSUE THREAD

**Issue by cheshiret** [sap-tutorials/Tutorials#20691]
Tutorials: https://developers.sap.com/tutorials/data-lake-file-containers-hdlfscli.html
--------------------------
Hi colleagues,

I'm trying to install with mac, and got below errors,

Preparing to install
Extracting the JRE from the installer archive...
Unpacking the JRE...
Extracting the installation resources from the installer archive...
Configuring the installer for this system's environment...

Launching installer...

JRE libraries are missing or not compatible....
Exiting....

Is it supported with mac? If yes, can we add more details about the JRE version that I should installed?

Currently, my java version is:
java --version
java 11.0.15.1 2022-04-22 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.15.1+2-LTS-10)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.15.1+2-LTS-10, mixed mode)

**Comment by sap-daniel** [comment]
Hello Tony,

In the operation system drop down menu you are able to identify what operating systems are supported.

![Screenshot 2022-11-21 at 9 18 56 AM](https://user-images.githubusercontent.com/47360311/203077960-e120f6ea-da85-403e-b72b-0f65e5d10d6e.png)

It looks to support Windows and Linux.

Best,
Daniel
