### ISSUE TITLE
Create a Development Project in SAP Business Application Studio

### ISSUE THREAD

**Issue by wolfbaum03** [sap-tutorials/Tutorials#20750]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-mission-trial-7.html
--------------------------

The SQL statement for the user creation does not work, as stated in the tutorial. Currently:
create user UPS_GRANTOR password "DnATBG!1" NO FORCE_FIRST_PASSWORD_CHANGE
It really should be:
create user UPS_GRANTOR password "DnATBG!1" NO FORCE_FIRST_PASSWORD_CHANGE SET usergroup default

**Comment by VolkerSaggau** [comment]
Hi Wolfbaum03,

1.) The statements works on my HANA Clouf without the "set USERGROUP DEFAULT"
2.) There is however a documentation error that will be corrected with HC QRC4 /22 to indicate that the option "SET USERGROUP DEFAULT" is optional. 
As such I will not correct the tutorial.

BR
Volker
