### ISSUE TITLE
Create Level-Based Hierarchies in SAP Data Warehouse Cloud

### ISSUE THREAD

**Issue by V3r0x** [sap-tutorials/Tutorials#20759]
Tutorials: https://developers.sap.com/tutorials/data-warehouse-cloud-level-based-hierarchies.html
--------------------------

The tutorial **doesnt mention to define keys for a hierarchy**.

**Comment by meganhoy** [comment]
Hi @V3r0x , can you please provide more context

**Comment by jmmargo** [comment]
@V3r0x there has not been a response for over a year and a half.  I am closing this issue.  If it still needs to be addressed, please reopen the issue.  Thank you.
