### ISSUE TITLE
Connect Your SAP Build Application to a Public API

### ISSUE THREAD

**Issue by GRABLERE** [sap-tutorials/Tutorials#20758]
Tutorials: https://developers.sap.com/tutorials/appgyver-connect-publicapi.html
--------------------------

First of all thanks for the awesome tutorial.
Small Suggestion: In Step 2 in the description as well as screenshot you name the relative path as /product/{barcode}.json . I believe the ".json" should be removed.

**Comment by thecodester** [comment]
The API works with or without but I will remove

**Comment by thecodester** [comment]
Done - https://github.com/sap-tutorials/Tutorials/commit/64cd7dbbdd65eadc052dda98357c437cb1da4fcf

Picture still has JSON ... will do another time.
