### ISSUE TITLE
Create a Custom RAP Business Object to Trigger Purchase Requisitions API

### ISSUE THREAD

**Issue by DiegoValzar** [sap-tutorials/Tutorials#20766]
Hi,

I implemented the code on tutorial https://developers.sap.com/tutorials/abap-s4hanacloud-procurement-purchasereq-shop.html

When press the create button on the Fiori temporary app, I get an error with text: "An exception was rised"
![image](https://user-images.githubusercontent.com/69528603/204572027-f7e6c5d7-7681-4d92-90b8-a11c7e8cd991.png)

I set a breakpoint after the MODIFY ENTITIES sentence, and noticed REPORTED DATA and FAILED DATA are empty
![image](https://user-images.githubusercontent.com/69528603/204585940-a00880c0-37b7-48e7-addf-3a8c73d9597d.png)

I also surrounded the MODIFY ENTITIES by a TRY ENDTRY sentence, but didn't catch any exception.

Reviewing the Feed Reader I noticed a gateway error was triggered. The text is "Frontend Error: An exception was raised, Service: /SAP/-ZSB_SHOP_001-0001"
![image](https://user-images.githubusercontent.com/69528603/204574632-6350a823-c449-46d6-8b15-2c65486efbcb.png)

Debugging the code I noticed a message error is triggered in class CL_BP_R_PURCHASEREQNTP. The error is caused because plant 1010 doesn't exist in my system.

Anyways, my objective writing this post is to ask you why the sentence MODIFY ENTITIES i_purchaserequisitiontp doesn't return the errors triggered by inside class CL_BP_R_PURCHASEREQNTP, but instead a Gateway error is triggered. Do you know some other way to catch this error?

Regards.

**Comment by mervey45** [comment]
Hi @DiegoValzar ,

thank you for your message. We are currently working on this tutorial. As soon as we have an solution, we'll update this accordingly.

Best regards, 
Merve
