### ISSUE TITLE
Develop Your First SAPUI5 Web App with SAP Business Application Studio

### ISSUE THREAD

**Issue by m-badura** [sap-tutorials/Tutorials#20784]
Group: https://developers.sap.com/group.sapui5-cf-bas.html
--------------------------

I don't quite get it: this group has 4 tutorials. In first three I'm setting up my environment, in the fourth I should debug my UI5 app. Which I don't have, since I just started my journey and only set up my environment. Are here some tutorials missing?

**Comment by cjbernal** [comment]
Hi @m-badura, sorry to see that you had an issue with this tutorial group. There does appear to be an issue with the tutorials provided. I am working with the Developer Tutorials team to update the group with the proper tutorials.

**Comment by jmmargo** [comment]
It appears that two tutorials were added to this group to address the initial feedback.  I am closing this now, but please reopen if the provided solution is not sufficient.
