### ISSUE TITLE
Manage Entitlements on SAP BTP Trial

### ISSUE THREAD

**Issue by m-badura** [sap-tutorials/Tutorials#20781]
Tutorials: https://developers.sap.com/tutorials/cp-trial-entitlements.html
--------------------------

In step 3, but also in Step 4, we can read "click Enter Your Trial Account", but the button is called "Go To Your Trial Account".
Okay, that's something I can still understand.
But then I should use "dropdown menus, choose Show: > Subaccounts and Subaccounts: > trial and then choose Go". There is nothing like that! I have only one dropdown menu: "Select Entities", where I can find and chosse my trial-subaccount to see its entitlements. That's disturbing!

**Comment by Jessica-Katz** [comment]
Hi m-badura,

You're right - thanks for spotting this, it is a bit outdated.

To quickly help you: on the page "Entity Assignemnts", click the icon in the **Select Entities** element - that will give you a popover to select directories or subaccounts. Here, select the subaccount you want to manage the entitlements for. 
After that the process as described in the tutorial should be the same.

I've assigned this issue to my colleague @AnjaNicoleKretz - she will take care that the procedure and the screenshots will be updated.

Thank you for your feedback.

**Comment by jmmargo** [comment]
As the tutorial has been updated, I am closing this issue.
