### ISSUE TITLE
Create an SAP BTP ABAP Environment Trial User

### ISSUE THREAD

**Issue by m-badura** [sap-tutorials/Tutorials#20783]
Tutorials: https://developers.sap.com/tutorials/abap-environment-trial-onboarding.html
--------------------------

In Step 1 I should "Navigate to the trial global account by clicking Enter Your Trial Account." There is also an appropriate screenshot. But the button is called "Go To Your Trial Account".
Okay, that's something I can still understand.

But then, under Boosters, I should start preparing my account for ABAP trial. But after clicking "Start" I got an error message like this:
https://blogs.sap.com/wp-content/uploads/2019/09/error-4.png

Well, I found my way through, but I think maybe it would be better, to put a hint, that if one has this problem, this tutorial should be followed:
https://developers.sap.com/tutorials/cp-trial-entitlements.html

Step 4 is empty?!

**Comment by mervey45** [comment]
Hi @m-badura , 

thank you for your feedback. I created following PR: #20785 to update this issue.

Best regards, 
Merve
