### ISSUE TITLE
Deploy Your Business Application to Cloud Foundry

### ISSUE THREAD

**Issue by ekansh005** [sap-tutorials/Tutorials#20793]
Tutorials: https://developers.sap.com/tutorials/appstudio-cap-deploy-app.html
--------------------------

There is no plan 'hdi-shared' while creating instance of HANA trial. The new plan is securestore.

**Comment by Paolaufer** [comment]
Hi,
I will look into this.
Thank you.

**Comment by Paolaufer** [comment]
HI,
The procedure is correct.
The 'hdi-shared' plan is still relevant.
![image](https://github.com/user-attachments/assets/54f89954-6db9-412b-a7b2-ec639485b108)
