### ISSUE TITLE
Create an Empty SAPUI5 Project

### ISSUE THREAD

**Issue by nicoschoenteich** [sap-tutorials/Tutorials#20792]
Tutorials: https://developers.sap.com/tutorials/sapui5-101-create-project.html
--------------------------

Hi @cjbernal,

For some reason I can't retrieve the subaccount level destination in the Fiori Application Generator wizard, although I am logged in to the correct CF org. The BAS I am using is also in the same CF org. Do you have any idea why that is?

Logging in again and restarting the dev space didn't fix it.

Best, Nico

<img width="1045" alt="Screenshot 2022-12-09 at 10 44 28" src="https://user-images.githubusercontent.com/65965098/206673931-33b5dffa-a745-4d9c-b43e-55bf96415041.png">

<img width="1122" alt="Screenshot 2022-12-09 at 10 45 03" src="https://user-images.githubusercontent.com/65965098/206673919-72a3b05b-d712-4da2-8855-735b090f6958.png">

**Comment by cjbernal** [comment]
Hi @nicoschoenteich, sorry to hear that you are having an issue. I have forwarded this to my colleagues working on the Application Generator to see if they can better help you out. They should be by soon :-) 

Kind regards,
Conrad

**Comment by theStiggySpd** [comment]
Hi @nicoschoenteich Can you please confirm the destination properties as mentioned here: https://developers.sap.com/tutorials/cp-cf-create-destination.html
