### ISSUE TITLE
Steps are missing in "Expose Integration Flow Endpoint as API and Test the Flow" tutorial

### ISSUE THREAD

**Issue by KeerthiMohankumar** [sap-tutorials/Tutorials#20800]
Hi,

In Tutorial 3 : https://developers.sap.com/tutorials/cp-starter-isuite-api-management.html
in Step 2 : Define the API

Steps are missing to navigate to Design API page, so unable to create an API

Labels to be added:
Scenario label: SCPTest-cloudin
Sprint Label: SCPTest-2212A
Landscape Label: trail2, trail3
Priority: High

Kindly look into this issue

Thanks & Regards,
Keerthi

**Comment by Karunaharan** [comment]
Hi @KeerthiMohankumar - this part is already covered in Step 2 of the tutorial. Please confirm.

Regards,
Karuna

**Comment by KeerthiMohankumar** [comment]
Hi @Karunaharan 

At step 2, the steps are mentioned as below:
1. Choose Design > APIs > Create to create an API.
2. On the Create API dialog, next to Select: choose URL and specify the following parameters:

But there are no steps mentioned on navigating to design page, to proceed with further steps.

Regards,
Keerthi

**Comment by KeerthiMohankumar** [comment]
Hi Karunaharan,

There is no "API's" option under Design, I could only find "Integrations", Please find the attached screenshot for reference..
![image](https://user-images.githubusercontent.com/107237818/207547805-2f5f9a4e-742d-4f7d-a2f8-fedd80b016ef.png)


Regards,
Keerthi

**Comment by Karunaharan** [comment]
Ok, I get it now.
This is because you haven't assigned the roles for API design that are mentioned in Step 4 of https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html. Please assign them to proceed further.

Regards, Karuna

**Comment by Karunaharan** [comment]
Hi Keerthi,
As one last attempt, could you please share a screenshot of your roles in the BTP cockpit? And also, try to logout from Integration Suite and log in again. We have seen cache issues in the past. This might help as well.

**Comment by Karunaharan** [comment]
Hi Keerthi,
Did the logout and re-log in work?

**Comment by KeerthiMohankumar** [comment]
Hi Karuna,
No, It didn't work karuna
