### ISSUE TITLE
Create a Simple OData Service with Mobile Back-End Tools

### ISSUE THREAD

**Issue by Alexd-sap** [sap-tutorials/Tutorials#20802]
Tutorials: https://developers.sap.com/tutorials/cp-mobile-backend-tools-simple-odata.html
--------------------------

Write here how you think we can improve the tutorial ...

At the step where we add Entities to the OData model I have observed some issues:
1.Once the csdl.xml file is created, once double-clicked , it opens the XML editor by default. You have to use the Open With option to open the Graphical Editor.
2.The Graphical Editor in BAS does not provide the option to Add an Entity. There is no Menu bar with the options Entity Types/Complex Types/ The "plus" button to add an entity etc.

**Comment by Manuel-Stampp** [comment]
Thank you for reporting the issue and the comment.
I am currently evaluating options to restructure and update the Tutorial.
I will update it as soon as possible.

**Comment by MichaelCzcz** [comment]
@Manuel-Stampp Any updates?
