### ISSUE TITLE
Create a Launchpad Site Using the SAP Launchpad Service

### ISSUE THREAD

**Issue by rcaziraghi** [sap-tutorials/Tutorials#20826]
Tutorials: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-create-sitelaunchpad.html
--------------------------

Hello,

In step 1 (Create site) of the above-mentioned tutorial we have the following question:

_Select 3 tabs that are available when you access the SAP Launchpad service.
Site Directory
Content Manager
App Editor
Provider Manager_

Shouldn't 'Provider Manager' be 'Channel Manager'?

![image](https://user-images.githubusercontent.com/18582796/208309995-fda9a7be-1a1d-4401-8d3b-e84c123ee74d.png)

Thank you.

**Comment by LindsayBert** [comment]
Yes - I need to rebrand all the launchpad tutorials and there are terminology changes as well that I will update at the same time.  This will be done by the 11th January when the rebranding is released

**Comment by LindsayBert** [comment]
Hi

The tutorial was updated and published a few weeks ago
