### ISSUE TITLE
Npm asks for confidential information stored in "fiori/v2/system" from my keychain information 

### ISSUE THREAD

**Issue by merveguel** [sap-tutorials/Tutorials#20839]
Hello all,

I am currently following the "[Deploy your ABAP application with SAP Business Application Studio](https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html)" tutorial. I have already completed all the previous steps successfully but completely stuck at Step 6.

As I try to run "npm start" command, I receive the following pop-up asking for my /fiori/v2/system login information:
<img width="466" alt="Screenshot 2022-12-30 at 22 34 46" src="https://user-images.githubusercontent.com/14961341/210113512-8fc3cb43-f14f-4a0d-a0c8-8acf3a2b0bca.png">

These are the error lines, that are thrown as I couldn't complete the keychain login.
error backend-proxy-middleware Error retrieving from secure store. Service: [fiori/v2/system], key: [https://6654aaf7-905f-48ea-b013-3811c03fcba8.abap.us10.hana.ondemand.com]
error backend-proxy-middleware An unknown error occurred.
error backend-proxy-middleware Error retrieving from secure store. Service: [fiori/v2/system], key: [https://6654aaf7-905f-48ea-b013-3811c03fcba8.abap.us10.hana.ondemand.com]

The key "https://6654aaf7-905f-48ea-b013-3811c03fcba8.abap.us10.hana.ondemand.com" is my ABAP Service instance endpoint information.

From SAP BTP ABAP environment "default_key.json" service key:  
 "sap.cloud.service": "com.sap.cloud.abap",
  "systemid": "TRL",
  "endpoints": {
    **"abap": "https://6654aaf7-905f-48ea-b013-3811c03fcba8.abap.us10.hana.ondemand.com"**
  },

The issue is that, I don't have this login password credentials (have tried already my trial account login, didnt work) since I am using a trial account for ABAP development on SAP BTP, the login credentials are done automatically via browser.

<img width="597" alt="Screenshot 2022-12-30 at 22 45 30" src="https://user-images.githubusercontent.com/14961341/210113678-51004308-8c03-451c-b1f2-53d125294365.png">

I am looking for your help on this matter.

Thanks in advance,
Merve Gül

**Comment by mervey45** [comment]
Hi @merveguel , 

your login credentials should be the same as your trial account. Please reset your password and try it out again.
If you are still facing issues, please get in contact with us again.

Thank you.

Best regards, 
Merve
