### ISSUE TITLE
Query the Database Using SQL Statements

### ISSUE THREAD

**Issue by henrystuifzand** [sap-tutorials/Tutorials#20837]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-mission-trial-6.html
--------------------------

When submitting the answer SELECT * FROM which I think is correct a Technical Error message appears.

**Comment by danielva** [comment]
Thanks for reporting the issue.  Your answer was correct but the tutorial validation had a technical issue.  I have updated the question to avoid the error.
