### ISSUE TITLE
Tutorial Connect to HubSpot : Update needed, HubSpot API Keys are no longer in share

### ISSUE THREAD

**Issue by merveguel** [sap-tutorials/Tutorials#20831]
Hello All,

Quite recently I have started to follow the [Connect to HubSpot](https://developers.sap.com/tutorials/cp-apim-openconnectors-connect-hubspot.html) tutorial. However, according to the HubSpot website, HubSpot API keys will no longer open for creation and usage (Note can be found in the Private Apps tab). Therefore I appreciate it if you could update the tutorial and provide an alternative way.

<img width="1149" alt="Screenshot 2022-12-21 at 19 58 08" src="https://user-images.githubusercontent.com/14961341/208983498-2b3210de-e1df-41bd-b203-4a970219f1a5.png">

Best,
Merve

**Comment by gulmmerve** [comment]
Hi @shilpavij

I appreciate it if you could take a look at it.

Thanks in advance,
Merve

**Comment by jmmargo** [comment]
This tutorial will soon be deprecated.  Thank you.
