### ISSUE TITLE
Installing SAP HANA, express edition with Docker

### ISSUE THREAD

**Issue by Boltzmann** [sap-tutorials/Tutorials#20830]
Tutorials: https://developers.sap.com/tutorials/hxe-ua-install-using-docker.html
--------------------------

Replace `sudo docker pull store/saplabs/hanaexpress:2.00.054.00.20210603.1` with `docker pull saplabs/hanaexpress`. The old string is outdated.

**Comment by JCurrie27** [comment]
Thanks for the string correction. The tutorial will be updated.
