### ISSUE TITLE
Expose Integration Flow Endpoint as API and Test the Flow

### ISSUE THREAD

**Issue by juderegys** [sap-tutorials/Tutorials#20849]
Tutorials: https://developers.sap.com/tutorials/cp-starter-isuite-api-management.html
--------------------------

I am following the step 2 and I get teh following error:

"Missing configurations; Please contact support team to configure virtual host."

Please let me know how I can fix this.

Thanks,
Jude

**Comment by Karunaharan** [comment]
Hi @juderegys - are you using the tutorial on a trial system or a production one? Please confirm.

Regards,
Karuna

**Comment by juderegys** [comment]
Hi Karuna,, I am using the trial system.
Thanks,
Jude
