### ISSUE TITLE
Create a Node.js Application via Cloud Foundry Command Line Interface - The redirect_uri has an invalid domain

### ISSUE THREAD

**Issue by MaximilienFourmyBeyond** [sap-tutorials/Tutorials#20840]
Tutorials: https://developers.sap.com/tutorials/btp-cf-buildpacks-node-create.html
--------------------------
Hello,

I got the following error when trying the web url in step 3.16 :
The redirect_uri has an invalid domain

The error is described in the following note :
2864831 - "The redirect_uri has an invalid domain" error when using a custom domain in Cloud Foundry

It seems that we need to have the following lines in the xs-security.json file :
"oauth2-configuration": {
        "redirect-uris": ["https://*.cfapps.*.hana.ondemand.com/**"]
    }

Once the service updated (with command line cf update-service nodeuaa -c xs-security.json), the error is fixed.

**Comment by Joysie** [comment]
Thank you, @MaximilienFourmyBeyond!

I'll test it too and update the tutorial.

**Comment by Joysie** [comment]
Hi @MaximilienFourmyBeyond,

I apologize for the late reply!

Thank you again for catching this glitch. I tested the scenario again - this additional configuration is needed indeed, but only for trial accounts.  I updated and improved the tutorial accordingly. 

Best regards,
Gergana
