### ISSUE TITLE
Create an Account on the SAP Gateway Demo System - Step 5 - Validate URL

### ISSUE THREAD

**Issue by S0024437095** [sap-tutorials/Tutorials#20850]
Tutorials: https://developers.sap.com/tutorials/gateway-demo-signup.html
--------------------------

Hello,

I have a problem with the tutorial "Create an Account on the SAP Gateway Demo System".
In step 5 ("Go to SAP Easy Access page ") there is a technical error when I want to check/validate the URL link, see below.
https://sapes5.sapdevcenter.com/sap/bc/gui/sap/its/webgui#

Am I doing something wrong? Could you check it please?
Thanks and best regards
Mark

**Comment by anfisc** [comment]
The URL works for me.
Can you please provide more details what kind of technical error occurs when you try to use the above mentioned URL?
Do you have registered for a user in ES5 using our registration form?
https://register.sapdevcenter.com/SUPSignForms/

**Comment by jmmargo** [comment]
It seems that this validation was removed from the tutorial.  Therefore, I will close this issue.
