### ISSUE TITLE
Create an ABAP Database Table and Relevant ABAP Dictionary Objects

### ISSUE THREAD

**Issue by Huargh** [sap-tutorials/Tutorials#22729]
Tutorials: https://developers.sap.com/tutorials/abap-dev-create-table.html
--------------------------

Step 17 asks you to activate the method, which creates the table entries. Step 18 then performsthe data preview of the table. What's missing is, that you have to run the method you created in 17. It should be noted, that you have to run this as "ABAP Application (Console)" --> F9, because with the normal execution, the unreferenced out-> raises a runtime error

**Comment by julieplummer20** [comment]
Hi Huargh,
Many thanks - I'll update the tutorial.
Best wishes, Julie Plummer.
