### ISSUE TITLE
Provision an Instance of SAP HANA Cloud, SAP HANA Database

### ISSUE THREAD

**Issue by EarleB** [sap-tutorials/Tutorials#22723]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-mission-trial-2.html
--------------------------

Several users have noted the same issue with this part of the tutorial, but it hasn't been addressed by anyone yet.  If you search the SAP Community for "SAP HANA Cloud Trial Choose your identity provider?", you'll see a couple of users encountering a request to sign in that never works.  Is it some sort of SAML related issue?  Please fix it.  Thanks.

**Comment by danielva** [comment]
I don't believe this issue has come up again recently so am closing for now.  Please re-open if you are still seeing the issue.
