### ISSUE TITLE
Tutorial Page fiori-tools-cap-modify-object-page.md Issue. PROD

### ISSUE THREAD

**Issue by SAPDocs** [sap-tutorials/Tutorials#22721]
Tutorial issue found: [https://github.com/sap-tutorials/Tutorials/blob/master/tutorials/fiori-tools-cap-modify-object-page/fiori-tools-cap-modify-object-page.md](https://github.com/sap-tutorials/Tutorials/blob/master/tutorials/fiori-tools-cap-modify-object-page/fiori-tools-cap-modify-object-page.md) contains invalid tags. Even though your tutorial was created, the invalid tags listed below were disregarded. Please double-check the following tags:
- products>sap-fiori-elements

 Affected server: PROD

**Comment by cjbernal** [comment]
@MichaelCzcz I checked this and found that the SAP Fiori elements tag is given as `software-product-function>sap-fiori-elements`. in my branch, as well as the document above. Can we close this?

**Comment by jmmargo** [comment]
The tag has been corrected.
