### ISSUE TITLE
Launchpad Service name is changed to SAP Build Work Zone

### ISSUE THREAD

**Issue by BaskarThambiayah** [sap-tutorials/Tutorials#22727]
Tutorials: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-getting-started.html
Set Up SAP Launchpad Service Using a Trial Account

Hi Colleagues,

In the above mentioned tutorial, at Step 1: Subscribe to the SAP Launchpad service, and the sub-step 5, it is mentioned as "Enter launchpad in the search box and click the Launchpad Service tile.".

But we are getting "No services match your search criteria".

Observation: Actually "Launchpad" service name is changed now and it should be "SAP Build Work Zone". So please update the document with updated steps and the corresponding screenshot.
Please find the below screenshots for your reference.

![image](https://user-images.githubusercontent.com/60343237/212279595-f4445c76-1949-4095-8d2e-dd1988a8da3b.png)

![image](https://user-images.githubusercontent.com/60343237/212279619-2d8b8f93-90fd-47ec-8c4e-ddc5c19da1fe.png)

Labels to be added:
Scenario label: SCPTest-fbizapp
Sprint Label: SCPTest-2301A
Landscape Label: trail2(Trial US East (VA) (AWS) ) & Trial3 (AP Region)
Priority: High

Many thanks & regards,
Baskar

**Comment by LindsayBert** [comment]
Hi - I'm aware about the rebranding and the tutorials have all been rebranded except for the screenshots that I was not able to update until the new tile name was visible in the cockpit.  The tutorials will be published in the coming days with all the updates.
Thanks Lindsay

**Comment by LindsayBert** [comment]
Hi

This tutorial is rebranded including the screenshots.  You need to search for the SAP Work Zone, standard edition tile.
