### ISSUE TITLE
Extend the Bookstore with Custom Code

### ISSUE THREAD

**Issue by Mrc2** [sap-tutorials/Tutorials#22734]
Tutorials: https://developers.sap.com/tutorials/cp-cap-java-custom-logic.html
--------------------------

Write here how you think we can improve the tutorial ...

This tutorial varies from what happens with the latest tools.

None of the entities ending in **_text** show up when running mvn spring-boot:run .

Also using the bookstore from the Run Configuration is not loading properly when following the tutorial verbatim.   It indicates the bookstore is not a valid project.   Manually configuring launch.json to run the configuration provides no guideance on what to do to fix the problem.

Only way to run is mvn spring-boot:run which does not allow debugging at break points.    

As a senior java developer who has extensively used and customized netbeans, eclipse, intellij, and somewhat with VS code the refactoring set up is not intuitive to clean up imports, align code, set up styling,  make better use of spring configurations, edit template languages.   The java editing features so far are a handicap using BAS.

**Comment by renejeglinsky** [comment]
Hi Mike,
Thank you for your feedback. Pls allow me to take some time and also look at it with my colleagues.

All the best,
René

**Comment by renejeglinsky** [comment]
Hi @Mrc2,
thanks again that you took the time to provide your feedback. We appreciate it.

- I'm going to add a new screenshot that shows what recently is served. You're absolutely right, that this has changed. For quite a while already. I'm sorry about that.
- For me using the run configuration works w/o problems. I did had some trouble updating dependencies but no need to configure the launch.json or fall back to the CLI. Maybe it was temporary?
- BAS is our tool of choice for this tutorial. I do understand that this is not everyone's preference, but in the end I hope it's possible to transfer the knowledge gained here to your favorite IDE and keep on working there.

Will close this PR with the upcoming PR containing the new screenshot.

Thanks and all the best,
René
