### ISSUE TITLE
Set Up SAP Business Application Studio for Development

### ISSUE THREAD

**Issue by wombling** [sap-tutorials/Tutorials#22732]
Tutorials: https://developers.sap.com/tutorials/appstudio-onboarding.html
--------------------------

Noting that when logging into the BAS it does not like it if you are logged into BTP using your universal ID that has multiple S users associated. I had to re-log into BTP using my s-user and not my email address. Perhaps there could be some detail about what to do if this occurs.

![image](https://user-images.githubusercontent.com/2967008/212589927-b0d200e8-b0b3-4fd1-95a4-553059d5c2b9.png)

![image](https://user-images.githubusercontent.com/2967008/212589953-0116afd5-4066-45b0-9029-83e435748197.png)

click on the link to open BAS -> new window opens and prompts for log-in - Strange that SSO not working here with universal ID.

![image](https://user-images.githubusercontent.com/2967008/212589977-8e92a317-e732-4c1f-abec-49b5eb8a3a82.png)

![image](https://user-images.githubusercontent.com/2967008/212590023-6ce9ac79-cd0e-4704-931f-73b2ed06c68f.png)

![image](https://user-images.githubusercontent.com/2967008/212590074-9c46bcfa-51b9-4fe3-ae6d-96f06e6e9818.png)

instead use S user to then log into BAS.

![image](https://user-images.githubusercontent.com/2967008/212590618-214634cf-5b26-4ff5-8ecb-81c918e7bf9a.png)

![image](https://user-images.githubusercontent.com/2967008/212590168-221a1360-8a3e-4f46-8d31-a016be062bd6.png)

Thanks,

Chris

**Comment by jmmargo** [comment]
@raz-korn @birgits22 has this been resolved?  Looks like an update has been done earlier this year.

**Comment by jmmargo** [comment]
Thank you @birgits22
