### ISSUE TITLE
Reuse a CAP Java Service

### ISSUE THREAD

**Issue by Mrc2** [sap-tutorials/Tutorials#22733]
Tutorials: https://developers.sap.com/tutorials/cp-cap-java-service-reuse.html
--------------------------

Write here how you think we can improve the tutorial ...

there is a typo in the preceding tutorial - index.cds should be

using from './db/schema';
using from './srv/admin-services';

not
using from './db/schema';
using from './srv/admin-service';

**Comment by renejeglinsky** [comment]
Thank you Mike.
Will let you know when I fixed it in production.

All the best,
René

**Comment by renejeglinsky** [comment]
Hi @Mrc2,

checking the tutorial I don't think this needs to be changed. It's in line with the filename of the `admin-service.cds`. Have you got an error that you could share with me?

**Comment by renejeglinsky** [comment]
Thanks @Mrc2 for taking the time to create this issue. I'm closing this issue now due to inactivity. If you want to dig in again, feel free to add a comment and we can re-open it.

All the best,
René
