### ISSUE TITLE
Tutorial Page fiori-tools-cap-modify-object-page.md Issue. PROD

### ISSUE THREAD

**Issue by SAPDocs** [sap-tutorials/Tutorials#22742]
Tutorial issue found: [https://github.com/sap-tutorials/Tutorials/blob/master/tutorials/fiori-tools-cap-modify-object-page/fiori-tools-cap-modify-object-page.md](https://github.com/sap-tutorials/Tutorials/blob/master/tutorials/fiori-tools-cap-modify-object-page/fiori-tools-cap-modify-object-page.md) contains invalid tags. Even though your tutorial was created, the invalid tags listed below were disregarded. Please double-check the following tags:
- software-product>sap-fiori-elements
- softrware-product>sap-business-technology-platform

 Affected server: PROD

**Comment by MichaelCzcz** [comment]
@cjbernal there is one typo that I missed in the review and the other tag should be software-product-function>sap-fiori-elements

**Comment by cjbernal** [comment]
@MichaelCzcz No worries. Here's the PR: https://github.com/sap-tutorials/Tutorials/pull/22749/

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
