### ISSUE TITLE
Add an API Proxy to a Product

### ISSUE THREAD

**Issue by oarthursilva** [sap-tutorials/Tutorials#22744]
Tutorials: https://developers.sap.com/tutorials/hcp-apim-create-product.html
--------------------------

Hello,

I am having a weird error message when publishing the product.

<img width="378" alt="image" src="https://user-images.githubusercontent.com/13890456/213336699-c235ffcd-ffd7-42d4-a5d3-11499ad97a79.png">

_currently setup: BTP trial_

**Comment by oarthursilva** [comment]
I just found a message on console

```
2023-01-19 09:41:33.253600 The following problem occurred: HTTP request failed400,Bad Request,{"error":{"code":"DEV_PORTAL_ONBOARDING_PENDING","message":{"lang":"en","value":"The current operation failed because {0} is not setup completely. Please setup {0}. Retry once done."}}} -  
```

**Comment by oarthursilva** [comment]
Hello @kulkarnir @MichaelCzcz,

Any update? this been a blocker for concluding tutorials.

**Comment by kulkarnir** [comment]
Hello Arthur, 

Thanks for providing the details, It appears like the **API Business Hub Enterprise** is not configured.
Please click on **Navigation Links** (top right corner in APIPortal) and select **API Business Hub Enterprise** 

![image](https://user-images.githubusercontent.com/26405634/214104607-e10e6b94-34dd-4d66-8c46-b4ac412f8620.png)

This should configure the API Business Hub Enterprise,  please try to publish the product and let us know if you face any issues

Thank you 
Raghu

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
