### ISSUE TITLE
Tutorial use-case is against SAP license terms

### ISSUE THREAD

**Issue by larshp** [sap-tutorials/Tutorials#22745]
Hi,
For the tutorial https://developers.sap.com/tutorials/btp-app-ext-service-add-consumption.html

The use-case is:

> This tutorial shows you how to extend your CAP application to manage risks associated with suppliers. For that you will consume supplier information that is part of the SAP S/4HANA Business Partner to your CAP application.

Ie. taking data from a SAP product into a custom application(ie. non-SAP product)

SAP has licensed CAP as per described in https://tools.hana.ondemand.com/developer-license-3.1.txt

See section
> (d) permit mass data extraction from an SAP product to a non-SAP product, including use, modification, saving or other processing of such data in the non-SAP product

Ie. the tutorial actively suggests a use-case that is against SAP license terms for the software used

**Comment by slavipande** [comment]
Hi there @larshp ,

Thanks for raising this point!

We're looking into it and will get back to you ASAP after we check all aspects of the matter.

Best regards,
Svetoslav

**Comment by sebster4** [comment]
Hi Lars,

here we go again... :-)

As written in my last email: After discussions with our legal team we were under the impression that the license only permits mass data extraction from a SAP system for the purpose to use it exclusively in a non-SAP systems. In this case we assume that we do not work against the license as CAP is being positioned as programming model for the SAP BTP. License situation is currently changing for CAP as we open source CAP in a step-wise approach and use the Apache 2.0 license for the Open Source modules, see: https://github.com/cap-js 

As always our general disclaimer: we are no legal experts, the statements represent our current understanding...

Best regards
Sebastian

**Comment by larshp** [comment]
thanks, see email

**Comment by manjuX** [comment]
Hi @larshp,

As it has been 2 Weeks I will be closing this issue. Please open another one if you need support regarding our tutorials.

Best regards,
Manju

**Comment by larshp** [comment]
heh, well, I did not get an answer to my email

I'm trying to not do the arguments for the license here, but we can do that if you prefer?
