### ISSUE TITLE
Configure and Run a Predefined SAP Continuous Integration and Delivery (CI/CD) Pipeline

### ISSUE THREAD

**Issue by maxstreifeneder** [sap-tutorials/Tutorials#22741]
Tutorials: https://developers.sap.com/tutorials/btp-app-ci-cd-btp.html
--------------------------
Dear colleagues,

the link to the SAP Help portal for the Initial setup in step 2.14 is dead. Could you please correct it? 

Thanks in advance & cheers,
Max

**Comment by manjuX** [comment]
Hi @maxstreifeneder ,

Thanks for finding the broken link, I have made a PR (https://github.com/sap-tutorials/Tutorials/pull/22783) to fix this issue.

Thanks and Best Regards,
Manju

**Comment by manjuX** [comment]
Closing as the fix has been merged. Thanks!
