### ISSUE TITLE
Use Pre-Trained Tensorflow Models with a GPU in SAP AI Core

### ISSUE THREAD

**Issue by shobhit009** [sap-tutorials/Tutorials#22760]
Tutorials: https://developers.sap.com/tutorials/ai-core-tensorflow-byod.html
--------------------------

It seems quiz answer is not correctly evaluated. 
<img width="889" alt="Screenshot 2023-01-25 at 2 57 24 PM" src="https://user-images.githubusercontent.com/17519343/214527027-99673dd7-4645-4b5a-b24e-cb92c6e2eff3.png">

**Comment by gianfranco-s** [comment]
@shobhit009 you'll find the correct answer in https://help.sap.com/docs/sap-ai-core/sap-ai-core-service-guide/choose-resource-plan-train
That url is subtly hinted in `Step 6: Create workflow to serve your model`

I'm not posting a screenshot to avoid spoiling the answer

**Comment by jmmargo** [comment]
As a solution has been provided, I will close this issue.
