### ISSUE TITLE
Set Up SAP Launchpad Service Using a Trial Account

### ISSUE THREAD

**Issue by nicoschoenteich** [sap-tutorials/Tutorials#22764]
Tutorials: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-getting-started.html
--------------------------

Hi all,
The SAP Launchpad Service has been renamed to `SAP Build Work Zone standard edition`. Texts and screen shots should be updated accordingly.
Best, Nico

**Comment by LindsayBert** [comment]
All tutorials have been rebranded - there is a problem with publishing them because the tag  "software-product>sap-build-work-zone—standard-edition” isn't available yet.
I'm in contact with Joshua about it.
Thanks Lindsay

**Comment by nicoschoenteich** [comment]
Hi Lindsay,
Thanks for the swift response. Can you let me know once the tag is available? I will start working on rebranding my tutorials then.
Best, Nico

**Comment by LindsayBert** [comment]
I am told that it will be available on Friday - hope that's the case.
