### ISSUE TITLE
Detect and Highlight Entities from Unstructured Text with Pre-trained Models

### ISSUE THREAD

**Issue by rcaziraghi** [sap-tutorials/Tutorials#22770]
Tutorials: https://developers.sap.com/tutorials/cp-aibus-ber-swagger-ui.html
--------------------------

Hello,

In the code snippets provided for this tutorial, the quotation marks were missing from the modelVersion attribute. Here is an example of the affected code:

```
{
   "text":"Von: lena nova <office@scomputercenter.bg> Gesendet: Montag, 21. Januar 2019, 19:13 Uhr An: canu, ana <ana.canu@company.com>; office@computercenter-bg.com Betreff: RE: M & B EOOD 2639710315 Sehr geehrter Kunde, ich sende Ihnen Informationen für unsere Zahlung. Proforma 198305906 ist ein Teil der Rechnung 4830476570 / 11.01.2019. Rechnungsdatum Betrag in EUR 4830473772 14.12.2018 9,28 € 4830474632 21.12.2018 29,16 € 4830475244 28.12.2018 46,19 € 4830475919 4.1.2019 9,28 € 198305906 10.1.2019 9,29 € 103,20 € 4830476570 11.1.2019 37,13 198305906 10.1.2019 -9,29 € 27,84 Einen schönen Tag noch! Mit freundlichen Grüßen, lena lena nova Verkaufsleiterin M & B EOOD-Computer Center 11, Angel Kanchev Str; 1000, Sofia, Bulgarien Tel.: + 359 2 981 58 57; Mobil: + 359 889 61 13 21 E-Mail: office@scomputercenter.bg Besuchen Sie uns unter: www.computercenter.bg",
   "modelName":"sap_email_business_entity",
   "modelVersion":2
}
```

I was able to successfully query the entities in the Swagger UI only after making the correction of adding the quotation marks to the modelVersion attribute, like so:

`"modelVersion":"2"`

Please let me know if there is any further information or assistance that I can provide.

Best regards,
Rafael

**Comment by Juliana-Morais** [comment]
Hi Rafael,

Thank you for the feedback. This has been changed recently. I'll make sure to update the payload examples in our tutorials and also in the help portal documentation to include the quotation marks to the modelVersion attribute values.

Best regards,
Juliana
