### ISSUE TITLE
Installing SAP HANA, express edition with Docker

### ISSUE THREAD

**Issue by gregorwolf** [sap-tutorials/Tutorials#22771]
Tutorials: https://developers.sap.com/tutorials/hxe-ua-install-using-docker.html
--------------------------

I think this tutorial needs to be removed or marked with a message that the Docker Image for HANA Express isn't available anymore. Currently I get this error when pulling:

```
docker pull saplabs/hanaexpress
Using default tag: latest
Error response from daemon: manifest for saplabs/hanaexpress:latest not found: manifest unknown: manifest unknown
```

**Comment by gregorwolf** [comment]
Mabe there is still hope as an answer to #18398 was that it is under investigation.

**Comment by MichaelCzcz** [comment]
@JCurrie27 In addition to solving this issue please also update the tutorial's author information. Thank you.

**Comment by JCurrie27** [comment]
I noticed the Docker URL changed from
https://hub.docker.com/r/saplabs
to
https://hub.docker.com/u/saplabs
I've modified the tutorial accordingly. Could this solve your access issues?
