### ISSUE TITLE
Issue with generating data on table snwd_so_inv_item

### ISSUE THREAD

**Issue by castrogeneris** [sap-tutorials/Tutorials#22775]
Hello, 

I'm working on this tutorial:
[https://github.com/sap-tutorials/Tutorials/issues/3210](url)

And I can not generate data on table snwd_so_inv_item, I search a little and the closer I got was to run transaction: STC01 and then Tasklist: SAP_BASIS_EPM_OIA_CONFIG

I figured out the parameters but I would need confirmation on what to put in "Recereate Master Data", I don't know if it's specting a Yes o Y o No or N or else. Anyway if i leave it blank task list runs ok, but still no data on table snwd_so_inv_item.

I'm stuck there, thanks for any input.

**Comment by MichaelCzcz** [comment]
@castrogeneris The link you have provided does not point to a tutorial. Kindly add the correct link. Thank you.

**Comment by castrogeneris** [comment]
> @castrogeneris The link you have provided does not point to a tutorial. Kindly add the correct link. Thank you.

I have found the solution!

Thanks for the correction. This is the link of the tutorial:
[https://developers.sap.com/tutorials/abap-display-data-queries.html](url)

The shown transaction and parameters helped me:

![image](https://user-images.githubusercontent.com/8144282/215658732-9fcf4191-e1e7-4bec-b088-6cac7d9e1664.png)
