### ISSUE TITLE
Configure SAP API Management policies to avoid CORS issues and generate an API Key

### ISSUE THREAD

**Issue by bdbais** [sap-tutorials/Tutorials#22777]
Tutorials: https://developers.sap.com/tutorials/btp-integration-suite-integral-api-management.html
--------------------------

On write "preflight" step, there is a bug on API Management UI, the Update stay on grey/disable , to avoid it and save your changes, you must create a dummy assign message anywhere, save it and remove it.

**Comment by jmmargo** [comment]
@mariajosesap can you please respond to this user's feedback?

**Comment by mariajosesap** [comment]
Hi @bdbais @jmmargo , that's right, there's a bug in the service that prevents from saving/updating the policy when adding the "preflight" condition. The recommendation on how to solve it, it's included in the tutorial. The other option is to create the preflight condition first and then add the setCORS condition in the PostFlow.

**Comment by jmmargo** [comment]
Thank you for the solution @mariajosesap.  As such I will close this issue.  @bdbais if you need to reopen this issue, please feel free to do so.
