### ISSUE TITLE
Deploy the SAP SuccessFactors Extension Database to SAP HANA Cloud

### ISSUE THREAD

**Issue by toddmfisher** [sap-tutorials/Tutorials#22780]
Tutorials: https://developers.sap.com/tutorials/cap-extend-sfsf-deploy-hc.html
--------------------------

When I reach the step to deploy the hdb via "cds deploy –-to hana" i get the error "Error: no service definition found; there must be at least one service definition for the deployment target"

Note:

- using BAS from trial account

- When I execute "cds add hana" my package.json shows dependencies.hdb = "^0.19.0" and db.kind = "hana-cloud" (attached)[package-json.txt](https://answers.sap.com/storage/temp/2132259-package-json.txt)[terminal.txt](https://answers.sap.com/storage/temp/2132260-terminal.txt)

thanks
[package_json.txt](https://github.com/sap-tutorials/Tutorials/files/10548147/package_json.txt)
[terminal.txt](https://github.com/sap-tutorials/Tutorials/files/10548146/terminal.txt)

**Comment by ale-biagi** [comment]
I did some testing in my own base project and found that **@sap/cds** CLI node module after version 6.2.2 are broken for the HANA deployment process (some previous versions - e.g. 6.1.3 - had other issues as well). This includes the latest cds version: 6.5.0. When it starts to create the service instance for the HDI container it, somehow, does not find the CAP service definition (**.cds** file in the **srv** folder) whilst previous steps of the process (e. g. source code generation of the HDB artifacts) do find it. So, it's clearly a bug of the cds CLI. Please, check the cds version in your terminal with: **cds --version**.

I recommend you raise an incident ticket to the CAP product team reporting this issue. Meanwhile you can "downgrade" your cds CLI version to 6.2.2 (this one I tested and it seems to work fine). To do it, just change the **@sap/cds** version in the dependencies of your **package.json** (which is currently "^6") to "6.2.2". BAS will raise an "unsatisfied dependency" problem in that line, so just click on it and it will show a tiny lightbulb on the left. Click there and select "fix all dependency issues". Then, check your cds version again in the terminal to make sure it's 6.2.2.

However, that version won't update **default-env.json** as explained in the tutorial. Therefore, to overcome it just run **cds watch --profile hybrid** whenever you want to access your data from HANA. If you switch back your **db.kind** to **"sql"** then you can keep using the usual **cds watch** command.

As it's not a problem of the tutorial itself I'm closing this issue.

Best Regards,
Alessandro

**Comment by toddmfisher** [comment]
Understood, thank you
