### ISSUE TITLE
Create an SAP Fiori App Using SAP Business Application Studio

### ISSUE THREAD

**Issue by ciction** [sap-tutorials/Tutorials#22786]
Tutorials: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html
--------------------------

Hi I have been following along with the tutorials but there seems to be an issue when connecting from BAS to the oData service from ES5 (when creating the Fiori project).

![image](https://user-images.githubusercontent.com/7746507/216344347-366d8bf0-e05a-460a-a42c-55a88c7a46ab.png)

I have an identical destination setup in BTP to ES5 (based on the prequel tutorial) .
Checking the destination gives me the expected 307 response code

**Comment by raz-korn** [comment]
Hi @ciction ,

I've just tried it and it works OK.
I suggest that you try again, and if it fails, refer to [issue 36](https://github.com/sap-tutorials/Issues/issues/36).

Regards - Raz

**Comment by jmmargo** [comment]
As a solution was provided, I am closing this issue.
