### ISSUE TITLE
Access Your Launchpad Site with SAP Mobile Start

### ISSUE THREAD

**Issue by SoumyaGyanapnor** [sap-tutorials/Tutorials#22811]
Hi,

Tutorials: https://developers.sap.com/tutorials/mobile-start-access-launchpad-site.html
--------------------------

Issue: Regarding Documentation Update
Here, observation: In the documentation ANDROID tab is missing only IOS tab is mentioned for that Documentation Update is required.

Steps to reproduce:
In STEP 2:  Access QR-Codes in the User Settings
                  3. In the Settings screen, choose the SAP Mobile Start Application tab.
please refer the below screenshot,

Expected:
![Expected](https://user-images.githubusercontent.com/124772107/217733445-154835da-0af1-43ac-92bd-a4a13546b109.png)

Actual:

![Actual](https://user-images.githubusercontent.com/124772107/217733526-ee0f33c2-1d8b-42ba-8503-721f851a41bc.png)

Please update the documentation as per the screenshot accordingly.

Labels:
Landscape Labels - trail3, trail2
Sprint Label: SCPTest-2302A
Scenario Label: SCPTest-psite
Priority: Medium

Thanks and Regards,
Soumya Gyanapnor

**Comment by dennis-koehler** [comment]
The tutorial got updated with https://github.com/sap-tutorials/Tutorials/pull/23023
With that screenshots got updated to reflect the current state. This also addresses this issue. 

Happy to close it now, sorry it took so long.
