### ISSUE TITLE
Generate Metrics and Compare Models in SAP AI Core

### ISSUE THREAD

**Issue by Chr1st1anG** [sap-tutorials/Tutorials#22817]
Tutorials: https://developers.sap.com/tutorials/ai-core-metrics.html
--------------------------

Step 8 Line 44
`aic_connection.metrics.log_metrics` should be `aic_connection.log_metrics`

**Comment by MichaelCzcz** [comment]
@NikhilD16 Please also update the author information.

**Comment by jmmargo** [comment]
As this has been resolved, I am closing the issue.
