### ISSUE TITLE
Connection to HANA IQ store from CAP based application

### ISSUE THREAD

**Issue by karoor** [sap-tutorials/Tutorials#22812]
Mission: https://developers.sap.com/mission.btp-deploy-cap-kyma.html
--------------------------

We have a requirement for our project where in we want to connect to HANA IQ store from CAP application.
We want to know if this can be achieved? If yes, do you have any reference document or git repository  which explains how to connect to IQ store or HANA data lake from CAP application?

**Comment by MichaelCzcz** [comment]
These GitHub issues are to resolve issues (i.e., problems/errors) with the tutorials. Your question seems more general and likely 
would get more visibility -- and a better answer -- in the SAP Community's Questions & Answers. You can ask your question at:
https://answers.sap.com/index.html
