### ISSUE TITLE
Set Up SAP Data Intelligence, Trial Edition

### ISSUE THREAD

**Issue by jonesdaniel009** [sap-tutorials/Tutorials#22816]
Tutorials: https://developers.sap.com/tutorials/dataintelligence-trial-v2-setup.html
--------------------------
Hi the SAP DI trial is no longer available in CAL as far as I can see, have verified this with Aus local SAP team. Will SAP DI be available a trial anytine soon? and I Will there be an updated tutorial to follow that? Thanks Daniel

**Comment by MichaelCzcz** [comment]
@NikhilD16 Please also update the author information.

**Comment by NikhilD16** [comment]
As of January 31, 2023, the DI Trial CAL image is no longer available. If you are using the trial as an existing SAP customer, please reach out to your account executive and work with them to explore different options available to you.

Refer to the blog https://blogs.sap.com/2022/07/14/sap-data-intelligence-trial-edition-3.2/
