### ISSUE TITLE
Create a Dev Space for SAP Fiori Apps

### ISSUE THREAD

**Issue by Venkatpicons** [sap-tutorials/Tutorials#22822]
Tutorials: https://developers.sap.com/tutorials/appstudio-devspace-fiori-create.html
--------------------------
Issue: Documentation update

Step 1--- Create a preconfigured SAP Fiori dev space
@Step 5:  Click Create Dev Space.

Here,the screenshot mentioned in the tutorial is not matching with the actual screen.

Kindly update the same.

Attached screenshot for your reference.
![image](https://user-images.githubusercontent.com/60374957/218071676-0d14818d-4d8e-4747-95ab-477289098df2.png)

Labels to be added:
Scenario Label: SCPTest-fbizapp
Sprint label: SCPTest-2302A
Landscape label: trail2, trail3
Priority: Low

Kind regards
Venkat

**Comment by raz-korn** [comment]
@birgits22  - low priority, can wait for a later update.
