### ISSUE TITLE
Configure SAP Build Application to Open Device Camera

### ISSUE THREAD

**Issue by JyothsnaPraveen** [sap-tutorials/Tutorials#22835]
Tutorials: https://developers.sap.com/tutorials/appgyver-configure-camera.html
--------------------------

The api call is not working.

**Comment by jmmargo** [comment]
@thecodester can you please reply to this user's feedback?

**Comment by thecodester** [comment]
@JyothsnaPraveen On the off chance that this is still relevant, can you provide more details about what is not working. I can call the API. Besides, this tutorial does not involve calling the API, only scanning the barcode.
