### ISSUE TITLE
Create a Custom RAP Business Object to Trigger Purchase Requisitions API

### ISSUE THREAD

**Issue by peterpersiel** [sap-tutorials/Tutorials#22842]
Tutorials: https://developers.sap.com/tutorials/abap-s4hanacloud-procurement-purchasereq-shop.html
--------------------------

Please correct

Business Catalog SAP_BR_PURCHASER needs to be assign to your business user

to

Business role SAP_BR_PURCHASER needs to be assign to your business user

**Comment by mervey45** [comment]
Hi @peterpersiel ,

thank you for your feedback. I created following PR: #22865 for this update.

Best regards, 
Merve
