### ISSUE TITLE
Create an Empty SAPUI5 Project

### ISSUE THREAD

**Issue by Mart53** [sap-tutorials/Tutorials#22854]
Tutorials: https://developers.sap.com/tutorials/sapui5-101-create-project.html
--------------------------

Write here how you think we can improve the tutorial ...
Before step 7 works, the following exercise must be completed: 
https://developers.sap.com/tutorials/cp-cf-create-destination.html

2023-Feb-17

**Comment by cjbernal** [comment]
Hi @Mart53, from where did you access this tutorial? Did you try to complete it standalone? Or as part of an overall tutorial mission? This will help us clarify and update prerequisites.

Coming from the `Create a Web Front End with SAPUI5` mission, I see that the `Create a Destination in the SAP BTP Cockpit` tutorial you linked to is part of the series, right before `Create an empty SAPUI5 project`. This could be made more clear by listing the completion of the destination tutorial as a prerequisite, but I want to make sure it's not also missing elsewhere.

**Comment by Mart53** [comment]
Hi cjbernal,
Wow thank you for your fast reply. I think I googled it (something like UI5 BTP) because I had issues with another training (maybe I open an extra issue for that). So I started with https://developers.sap.com/tutorials/sapui5-101-create-project.html in the middel of the mission as you wrote. Next time I'll look a step further back to check if I have everything.

**Comment by cjbernal** [comment]
Hi @Mart53,

Got it. Thanks for your feedback. In that case, we can update the tutorial and mention that that the previous tutorial will need to be completed as well. Please do open up another issue for the other tutorial you're having a problem with -- hopefully you can get the help you need from there!

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
