### ISSUE TITLE
Prepare SAP Launchpad Service Setup

### ISSUE THREAD

**Issue by AjitKP** [sap-tutorials/Tutorials#22866]
Tutorials: https://developers.sap.com/tutorials/btp-app-kyma-launchpad-service-setup.html
--------------------------

Write here how you think we can improve the tutorial ...
Step 5: fiori add deploy-config cf is fialing with error "This Fiori application is within a CAP project and deployment should be configured as part of the CAP project."

This needs a mta.yaml file. however it is not mentioned anywhere if you follow the steps from beginning.

**Comment by manjuX** [comment]
Hello,

Thank you for your feedback. We will update the tutorial,  please run `cds add mta` in the root folder of your project. The Kyma projects with Fiori UIs will need the MTA to be present and this command will add that.

Best regards,
Manju

**Comment by slavipande** [comment]
Hi @AjitKP ,

Thanks for pointing this out. We've added a step to the tutorial for the creation of `mta.yaml`. The changes should be visible within a couple of days. 

Hence, I'll be closing this issue.
Please do not hesitate to contact us again if you have any questions.

Best regards,
Svetoslav
