### ISSUE TITLE
Enhance Behavior With Action and Validation

### ISSUE THREAD

**Issue by BaerbelW** [sap-tutorials/Tutorials#22863]
Tutorials: https://developers.sap.com/tutorials/abap-environment-behavior-action.html
--------------------------

Given that there are a lot of different bits & pieces which need to be created / used for this and the linked tutorial [to deploy your ABAP application with SAP Business Application Studio](https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html) it would be helpful to know why each of them is needed and what piece of the FIORI app they control. Right now, I find this rather confusing, like a jumbled heap of puzzle pieces without knowing what the overall picture is and how the individual pieces fit into it.

In addition, a "cheat sheet" regarding the naming conventions used for the many different objects created during the tutorial would be helpful to make (more) sense of the objects now in the package:
![grafik](https://user-images.githubusercontent.com/18588108/220094071-89825ebb-87fe-487f-b065-a6b530041f2b.png)

Perhaps something like this already exists somewhere, but I didn't spot it right away. I do have a hunch that it be useful for newbies to all of this like me who are really easy to confuse!

Thanks much and cheers
Bärbel

**Comment by mervey45** [comment]
Hi @BaerbelW , 

thank you for your feedback. We will consider your feedback. The overall information you'll get in this tutorial:  https://developers.sap.com/tutorials/abap-environment-restful-programming-model.html
Which is a part of this group: https://developers.sap.com/group.abap-env-restful-managed.html 

Best regards, 
Merve
