### ISSUE TITLE
Deploy Your Multi-Target Application (MTA)

### ISSUE THREAD

**Issue by LotharBender** [sap-tutorials/Tutorials#22864]
Tutorials: https://developers.sap.com/tutorials/btp-app-cap-mta-deployment.html
--------------------------

Write here how you think we can improve the tutorial ...

Step 6 `Exclude CSV files from deployment` describes that CSV files used for testing purposes shall be deleted using `npx rimraf` for productive deployments. 
The better approach would be to define this sample data in the folder `test/data` instead. This ensures that it will be loaded by default when using `cds watch`, but it will not be added by `cds build --production` or `cds watch --production`.
You may want to give it a try.
See also https://answers.sap.com/questions/13823398/csv-file-ignore-while-deploying-to-production.html

Regards,
Lothar

**Comment by manjuX** [comment]
Hi @LotharBender ,

I could not find test/data mentioned on capire other than in the multitenancy chapter, I can check with my colleagues but do you have any resource mentioning this is the recommendation/best practice?

Best regards,
Manju

**Comment by LotharBender** [comment]
Hi Manju,

this documentation is currently being written, but not yet available. 
I will add a link once the corresponding Capire documentation has been released. We will distinguish test data from predefined application data.

- Lothar

**Comment by manjuX** [comment]
Hi,

I'll close this issue as it has been open for some time now. Please contact me or create a new issue if there has been a resolution already.

Best regards,
Manju
