### ISSUE TITLE
Configure Launchpad

### ISSUE THREAD

**Issue by Badk0m** [sap-tutorials/Tutorials#22879]
Hi
I try create launchpad using script https://developers.sap.com/tutorials/spa-configure-launchpad.html.
Step 5 error Cannot create destination for service instance SPA-instance automatically. You can create the destination manually.
Can you help fix it?

**Comment by jmmargo** [comment]
@celineaudinsap can you please reply to this user's feedback?

**Comment by celineaudinsap** [comment]
Hello,
We have updated the above mentioned tutorial: https://developers.sap.com/tutorials/spa-configure-workzone.html
Please let me know if you still encounter the issue.
Best regards,
Céline
