### ISSUE TITLE
Create a SAP Fiori App in Visual Studio Code and Deploy it to SAP BTP, ABAP Environment

### ISSUE THREAD

**Issue by soschlegel** [sap-tutorials/Tutorials#22875]
Tutorials: https://developers.sap.com/tutorials/abap-environment-vs-code.html
--------------------------

The "HINT" -Section in Step 3 would be better as an additional step 8 (optional). At the moment, it's not that nice to read and these steps are only important in error cases, if the wizard is filled correctly...

**Comment by mervey45** [comment]
Hi @soschlegel ,

Thank you for your feedback. We will consider it.

Best regards, 
Merve
