### ISSUE TITLE
Value for AUTH url and Access Token Url to use in postman

### ISSUE THREAD

**Issue by pranavhonrao9** [sap-tutorials/Tutorials#22871]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-mission-trial-2.html
--------------------------

Will you please add information about what should we provide as a value for AUTH URL and Access Token URL which we get from cf env <app>
https://developers.sap.com/tutorials/cp-cap-java-security-cf.html

**Comment by danielva** [comment]
The following tutorial demonstrates how to add a service key to an SAP HANA Cloud instance and use those values to create a bearer token that can be used in a REST client such as Postman.

https://developers.sap.com/tutorials/hana-cloud-alerts-rest-api.html

Hope that helps,
Dan van Leeuwen
