### ISSUE TITLE
Debug Your SAPUI5 App with SAP Business Application Studio

### ISSUE THREAD

**Issue by yellapunagesh** [sap-tutorials/Tutorials#22882]
Tutorials: https://developers.sap.com/tutorials/appstudio-sapui5-debug.html
--------------------------

https://developers.sap.com/tutorials/appstudio-devspace-fiori-create.html

There is no linkage between the previous lesson and this. from where did this repo come from!!

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. There is a "Next" button in the previous tutorial and a "Previous" button in this tutorial. Both are working. Please check/try again.
![image](https://user-images.githubusercontent.com/57144076/222072769-0c8bed51-dac4-4d1a-8efe-5af64c3518b0.png)
![image](https://user-images.githubusercontent.com/57144076/222073282-4b73aee9-22ed-4dc2-ae54-4bfb27938dce.png)

**Comment by jmmargo** [comment]
I do not understand the question as these are contained in our standard Tutorials repository.  What do you mean by "from where sis this repo come from?"
