### ISSUE TITLE
Set Up the SAP HANA Cloud Service

### ISSUE THREAD

**Issue by martinknechtel** [sap-tutorials/Tutorials#22893]
Tutorials: https://developers.sap.com/tutorials/btp-app-hana-cloud-setup.html
--------------------------

The quiz is on using an existing HANA Cloud instance. But I followed the other path: creating a new instance, so the quiz should be about creating a new instance :-)

See my screenshot below:
<img width="1718" alt="Screenshot 2023-03-01 at 14 58 52" src="https://user-images.githubusercontent.com/2546644/222162643-598c61bd-6f07-4184-9d39-8a30a91d7cc1.png">

**Comment by manjuX** [comment]
Hi @martinknechtel ,

Thank you for your feedback, I will check on how to make this question more relevant for everyone. Please create a new issue in case you need further support with working through our tutorial.

Best regards,
Manju

**Comment by slavipande** [comment]
Hi @martinknechtel,

Thanks for submitting this issue. We've updated the HANA setup question.
Hence, I'll be closing this issue.

Best regards,
Sveto
