### ISSUE TITLE
SAP HANA XS Advanced, Creating an HDI Module

### ISSUE THREAD

**Issue by vitpilk** [sap-tutorials/Tutorials#22902]
Tutorials: https://developers.sap.com/tutorials/xsa-hdi-module.html
--------------------------
Something is wrong in the  window where the generated select statement is to be pasted. I am getting "Technical Error" in response to the sql statement I generated and I don't find anything wrong with it.

SELECT TOP 1000
	"PURCHASEORDERID",
	"HISTORY.CREATEDBY",
	"HISTORY.CREATEDAT",
	"HISTORY.CHANGEDBY",
	"HISTORY.CHANGEDAT",
	"NOTEID",
	"PARTNER",
	"CURRENCY",
	"GROSSAMOUNT",
	"NETAMOUNT",
	"TAXAMOUNT",
	"LIFECYCLESTATUS",
	"APPROVALSTATUS",
	"CONFIRMSTATUS",
	"ORDERINGSTATUS",
	"INVOICINGSTATUS"
FROM "DB_1"."PurchaseOrder.Header"

**Comment by jung-thomas** [comment]
Can you post a screenshot of the error or a bit more details?  Is it really just "technical error"?

**Comment by jung-thomas** [comment]
Can you please provide more details about your error. Otherwise I'll have to close this issue.
