### ISSUE TITLE
Create a SAP Build Work Zone, Standard Edition Site for Your Kyma CAP App

### ISSUE THREAD

**Issue by martinknechtel** [sap-tutorials/Tutorials#22903]
Tutorials: https://developers.sap.com/tutorials/btp-app-kyma-work-zone-subscribe.html
--------------------------

Step 1: there are two plans "standard". The tutorial description and screenshot should be extended so that it is clear the plan "standard: Subscription" has to be chosen and not "standard: Instance". See my screenshot below.

<img width="1718" alt="Screenshot 2023-03-05 at 07 23 32" src="https://user-images.githubusercontent.com/2546644/222945293-9eba9666-3828-45df-91cf-17f6036bff5f.png">

**Comment by slavipande** [comment]
Hi @martinknechtel ,

Thanks for pointing this out!

We've updated the steps of the tutorial and added a note explaining the diff between the plans.
Changes should be visible soon

Hence, I'll be closing this issue.

Best regards,
Svetoslav
