### ISSUE TITLE
Docker PSE error

### ISSUE THREAD

**Issue by joshipul** [sap-tutorials/Tutorials#22908]
I tried setting up the docker but while installing I get below error
import_p12: ERROR -- PSE "/usr/sap/HXE/HDB90/hana/sec/sap_system_pki_instance.pse" already exists!

Detailed log
hana_express  | Finished execution of hook /hana/hooks/pre_start/130_update_clean_wdisp (exit code 0)
hana_express  | Executing hook /hana/hooks/pre_start/310_init_ssfs ...

hana_express  |         System PKI master key already created
hana_express  |         Creating system PKI SSFS ...
hana_express  |         Generating system PKI CA ...
hana_express  |         Creating openssl.cnf file for CA ...
hana_express  |         Creating self signed certificate for CA ...
hana_express  |         Generating a 4096 bit RSA private key

hana_express  |         ...............................................................................................++
hana_express  |         ..........................++
hana_express  |         writing new private key to '/tmp/tmp.Xcj0dVTfT9/key.pem'
hana_express  |         -----
hana_express  |         Exporting PEM to P12 ...
hana_express  |         Importing P12 into PSE ...
hana_express  |         Found key 'INDEX=0,SIG=YES,ENC=NO,MD5-FINGERPRINT=EF1E AAB8 70C9 6748 D03B 3542 AA72 C9C3,KEYID=A16E37AD1F752C7EE3EE08A742AE7DE1D99343D9'
hana_express  | 
hana_express  |         !!! WARNING: For security reasons it is recommended to use a PIN/passphrase
hana_express  |         !!! WARNING: which is at least 8 characters long and contains characters in
hana_express  |         !!! WARNING: upper and lower case, numbers and non-alphanumeric symbols.
hana_express  | 
hana_express  |         PSE "/tmp/tmp.Xcj0dVTfT9/ca.pse" was written
hana_express  | 
hana_express  |         Generating system PKI CA done
hana_express  |         Adding system PKI CA to system PKI SSFS ...
hana_express  |         Creating pin for sap_system_pki_instance.pse
hana_express  |         Storing pin for sap_system_pki_instance.pse in secure file store
hana_express  |         Generating sap_system_pki_instance.pse ...
hana_express  |         Creating openssl.cnf file for server certificate ...
hana_express  |         Creating server certificate ...
hana_express  |         Generating a 4096 bit RSA private key
hana_express  |         .........................................++
hana_express  |         .............++
hana_express  |         writing new private key to '/tmp/tmp.Xcj0dVTfT9/key2.pem'
hana_express  |         -----
hana_express  |         Signing server certificate ...
hana_express  |         Building complete chain ...
hana_express  |         Exporting PEM to P12 ...
hana_express  |         Importing P12 into PSE ...
hana_express  |         Found key 'INDEX=0,SIG=YES,ENC=YES,MD5-FINGERPRINT=EFC0 8EDD D27E 1BC6 8467 95C4 0309 2780,KEYID=14BF1F706EAB7BD208D4BAEEDFE0ECA1745C2276'
hana_express  |         import_p12: ERROR -- PSE "/usr/sap/HXE/HDB90/hana/sec/sap_system_pki_instance.pse" already exists!
hana_express  | 

hana_express exited with code 5

[ERROR]: Stopping setup because HANA failed to start correctly

Any idea what could be wring here?

**Comment by MichaelCzcz** [comment]
These GitHub issues are to resolve issues (i.e., problems/errors) with the tutorials. Your question seems more general and likely 
would get more visibility -- and a better answer -- in the SAP Community's Questions & Answers. You can ask your question at:
https://answers.sap.com/index.html
