### ISSUE TITLE
https://developers.sap.com/tutorials/cp-starter-integration-cpi-design-iflow.html

### ISSUE THREAD

**Issue by Venkatpicons** [sap-tutorials/Tutorials#22919]
Issue: Failed to connect to system while configuring the odata V2 Adapter under processing tab step no: 4 and 5.

URL used as per tutorial:  https://refapp-espm-ui-cf.cfapps.eu10.hana.ondemand.com/espm-cloud-web/espm.svc

![image](https://user-images.githubusercontent.com/60374957/224246710-56b184a8-7e19-4d45-8552-3de32f80bc16.png)

Labels to be added:
Scenario Label: SCPTest-cloudin
Sprint label: SCPTest-2303A
Landscape label: trail2, trail3
Priority: High

Kind regards
Venkat

**Comment by Karunaharan** [comment]
Hi @Venkatpicons - we identified this issue already and working on it to fix it. Thanks for notifying me.

**Comment by Karunaharan** [comment]
Hi @Venkatpicons - the issue is resolved now.

Karuna
