### ISSUE TITLE
Enhance the Business Object Behavior With Unmanaged Internal Numbering

### ISSUE THREAD

**Issue by MOETLING** [sap-tutorials/Tutorials#22914]
Tutorials: https://developers.sap.com/tutorials/abap-environment-rap100-early-numbering.html
--------------------------

Hi, 

I was struggling with step 1 "Define internal early numbering". 
In addition to adding "early numbering" to the behavior definition, I also had to change the mandatory / readonly property for TravelID:
 From these two entries:

  *field ( mandatory : create )
   TravelID;
[...]
  field ( readonly : update )
   TravelID;*

To that:

  *field ( readonly )
   TravelID;*

As far as I can see, this step is missing in both the text description of the required steps and is also not shown in the screenshot of the changed behavior definition.

Without this change, I was still prompted to provide a travelID when hitting the Create button.

**Comment by mervey45** [comment]
Hi @MOETLING , 

thank you for your feedback. These two fields were created from the RAP Generator automatically. Which ADT version do you have?

field ( mandatory : create )
TravelID;
[...]
field ( readonly : update )
TravelID;

Best regards, 
Merve

**Comment by mervey45** [comment]
Hi @MOETLING ,

thank you so much for all this information. I will have a look myself, if needed I will update this tutorial with your input.

Best regards, 
Merve
