### ISSUE TITLE
Get an Account on SAP BTP to Try Out Free Tier Service Plans => Add to Cart is missing (Step 1)

### ISSUE THREAD

**Issue by MaximilienFourmyBeyond** [sap-tutorials/Tutorials#22925]
Tutorials: https://developers.sap.com/tutorials/btp-free-tier-account.html
--------------------------

Write here how you think we can improve the tutorial ...

In Step 1 Log On in SAP Store, it's indicated :
Scroll down to Plans and Pricing. Select Based on Usage > Add to Cart.
But there is no option "Add to Cart":
<img width="978" alt="image" src="https://user-images.githubusercontent.com/14924866/224971733-990aacc3-276a-4348-a391-f89fd887cbe6.png">

Do you know if there is a new way to get a free tier account ?

Thanks for your help.
Regards

**Comment by MaximilienFourmyBeyond** [comment]
For information the button Add to Cart is visible when using the Start Selection Guide:
<img width="586" alt="image" src="https://user-images.githubusercontent.com/14924866/224973305-c1927043-a0dd-4e08-b223-bc6d7e1b6339.png">

But nothing happen when clicking on it:
<img width="667" alt="image" src="https://user-images.githubusercontent.com/14924866/224973444-48e11824-60e2-459b-837b-89ed69c5e24b.png">

**Comment by AnnikaGonnermann** [comment]
Hi @MaximilienFourmyBeyond!

Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by AnnikaGonnermann** [comment]
Hi @MaximilienFourmyBeyond - just checking in with you. We have not forgotten your request, but I will need to ask you for your patience a little bit longer so that we can provide you with a solution. All the best, Annika

**Comment by AnnikaGonnermann** [comment]
Hi @MaximilienFourmyBeyond  thank for your patience. The issue has been fixed. Best, Annika
