### ISSUE TITLE
Secure Your Application on SAP Business Technology Platform Cloud Foundry

### ISSUE THREAD

**Issue by vishal2052** [sap-tutorials/Tutorials#22929]
Tutorials: https://developers.sap.com/tutorials/s4sdk-secure-cloudfoundry.html
--------------------------

Write here how you think we can improve the tutorial ...

Please in the code snippet also include the "imports".

I am referring to the below document. There are many issues with the provided sample code but the most irritating one is that in many places code snippet have been provided without imports. 
This makes it difficult to use the code in effective manner.

e.g. Class with name "Converter" which used in the sample SecurityConfiguration.java sample  exists in so many packages that it becomes difficult to find the correct one. 

https://developers.sap.com/tutorials/s4sdk-secure-cloudfoundry.html#9d7f3abc-099f-4a1a-b1f6-273c5ce822bb

**Comment by CharlesDuboisSAP** [comment]
Hello @vishal2052,

The `SecurityConfiguration` in part 5 does contain imports, especially for `Converter`.
The other imports should be one click with your IDE.

Best, Charles
