### ISSUE TITLE
Connect to HubSpot - API Key depreciated.

### ISSUE THREAD

**Issue by ASRHARDING** [sap-tutorials/Tutorials#22941]
Tutorials: https://developers.sap.com/tutorials/cp-apim-openconnectors-connect-hubspot.html
--------------------------

The API Key method of accessing HubSpot has been deprectiated, and is no longer accessible after the 30 November 2022.
https://developers.hubspot.com/changelog/upcoming-api-key-sunset

It is no longer possible to conduct this tutorial since SAP Open Connector for HubSpot does not support Private Apps, the replacement to using an API Key .

Please update this tutorial for using OAuth instead, or update for Private Apps when the HubSpot open connector has been amended to work with HubSpot Private Apps.

Kind regards, Andrew.

**Comment by jmmargo** [comment]
This tutorial will soon be deprecated.  Thank you.
