### ISSUE TITLE
Broken links in AI Tutorial - Create Custom Template for Custom Documents

### ISSUE THREAD

**Issue by asalan316** [sap-tutorials/Tutorials#22942]
While following the tutorial, the sample files were not downloaded due to PAGE Not FOUND

- [Create Custom Template for Custom Documents]( https://github.com/sap-tutorials/Tutorials/blob/4eb20a6d327b74d2d7d7f0fb9e4c77f939d425cd/tutorials/cp-aibus-dox-ui-template-custom/cp-aibus-dox-ui-template-custom.md)
<img width="964" alt="Screenshot 2023-03-21 at 11 00 27" src="https://user-images.githubusercontent.com/7829351/226573327-d341e187-e1c8-456a-8e01-ca963fedf675.png">

Thanks

Regards,
Arsalan Khan

**Comment by Juliana-Morais** [comment]
Hi Arsalan,

I'm really sorry for the inconvenience. I'll fix the broken links in the MD file ASAP. In the meantime, you can access the document samples using the following links:
- https://github.com/sap-tutorials/Tutorials/blob/4eb20a6d327b74d2d7d7f0fb9e4c77f939d425cd/tutorials/cp-aibus-dox-ui-template-custom/sample-power_of_attorney-1.pdf
- https://github.com/sap-tutorials/Tutorials/blob/4eb20a6d327b74d2d7d7f0fb9e4c77f939d425cd/tutorials/cp-aibus-dox-ui-template-custom/sample-power_of_attorney-2.pdf
- https://github.com/sap-tutorials/Tutorials/blob/4eb20a6d327b74d2d7d7f0fb9e4c77f939d425cd/tutorials/cp-aibus-dox-ui-template-custom/sample-power_of_attorney-3.pdf

Best regards,
Juliana
