### ISSUE TITLE
Get an Account on SAP BTP to Try Out Free Tier Service Plans

### ISSUE THREAD

**Issue by ahmedkhan29789** [sap-tutorials/Tutorials#22947]
Tutorials: https://developers.sap.com/tutorials/btp-free-tier-account.html
--------------------------

I have a free trial individual account, Is it possible that I can covert it free tier account simply?

**Comment by AnnikaGonnermann** [comment]
Hi @ahmedkhan29789, if you have a trial account you cannot convert it to an account with free tier service plans as trial is a closed-off sandbox environment type of account. For more information, see the fowing resources:
- SAP Help Portal ["Trial Accounts and Free Tier"](https://help.sap.com/docs/btp/sap-business-technology-platform/trial-accounts-and-free-tier?version=Cloud )
- Tutorial Navigator ["Get an Account on SAP BTP to Try Out Free Tier Service Plans"](https://developers.sap.com/tutorials/btp-free-tier-account.html)




Best
Annika
