### ISSUE TITLE
Add Transactional Behavior to Your Core Data Services - syntax error and dump

### ISSUE THREAD

**Issue by BaerbelW** [sap-tutorials/Tutorials#22951]
Tutorials: https://developers.sap.com/tutorials/abap-environment-transactional-enablement.html
--------------------------

Hi!

In Step 5 I copied the code as instructed but received a Syntax error preventing the activation of the code:
![grafik](https://user-images.githubusercontent.com/18588108/227927381-8133bffe-dc70-4d1d-aa71-a134819010bd.png)

I could activate the Class zbp_i_booking_bwi after commenting out these statements in the Local Types:
![grafik](https://user-images.githubusercontent.com/18588108/227928498-3f6e3456-717c-417e-b24b-fa980ffc4fe8.png)

I then try to preview the SAP Fiori elements app in the next step which first seems to work by displaying this screen:
![grafik](https://user-images.githubusercontent.com/18588108/227929479-39bd95a7-43ed-4880-a57f-34bcc0ab9661.png)

But as soon as I hit "Go", I get a short dump but have no clue why as the dump information is rather cryptic (at least for me):
![grafik](https://user-images.githubusercontent.com/18588108/227930087-cbe29f7e-8c5d-48d5-a3b0-15b96b90f1ce.png)

Is this something I should be able to resolve myself and if yes, where and how?

Thanks much and Cheers
Bärbel

**Comment by mervey45** [comment]
Hi @BaerbelW ,

thank you for your feedback. We'll update this as soon as possible.

Best regards, 
Merve
