### ISSUE TITLE
Subscribe to the SAP Launchpad Service

### ISSUE THREAD

**Issue by AriannaMussoBarcucci** [sap-tutorials/Tutorials#22958]
Tutorials: https://developers.sap.com/tutorials/btp-app-launchpad-service.html
--------------------------

Good tutorial!
I noticed you are still using the old naming convention for the SAP launchpad Service. Due to the re-branding, it is now called 'SAP Build Work Zone, standard edition'.
It might be a good idea to update the SAP product name, so that the naming convention is followed and consistent across all SAP products.
Cheers,
Arianna

**Comment by manjuX** [comment]
Hi Arianna,

Thank you for bringing this to my notice, It seems like the old ones haven't been deleted, I'll take care of that. The tutorial has been updated and the new one is [here](https://developers.sap.com/tutorials/btp-app-work-zone-subscribe.html).
Hope you have a good day!

Thanks and best regards,
Manju

**Comment by manjuX** [comment]
Hi Arianna,

The old tutorials have now been deleted so I'm closing this issue. Please make a new issue if you need further support.

Thanks and best regards,
Manju
