### ISSUE TITLE
Get Started with SAP Rapid Application Development by Mendix

### ISSUE THREAD

**Issue by J-Goerlich** [sap-tutorials/Tutorials#22950]
Tutorials: https://developers.sap.com/tutorials/mendix-onboarding.html
--------------------------

I can no longer find the "SAP Rapid Application Development by Mendix" in the SAP Discovery Center.

**Comment by Paolaufer** [comment]
Hi.
Mendix has indeed been removed from the SAP Discovery Center.
SAP now has its own low-code solution: SAP Build (https://www.sap.com/products/technology-platform/low-code.html).
Mendix remains a trusted partner supporting the BTP platform as a customer choice, but SAP is focusing on our native built solutions. 
I invite you to take a look at SAP Build.
