### ISSUE TITLE
Create a Calculation View with Differential Privacy in SAP HANA Cloud

### ISSUE THREAD

**Issue by ValterAraujoJr** [sap-tutorials/Tutorials#22968]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-calculation-view-differential-privacy.html
--------------------------

At step 4 it says: "src/data/models", however, the correct is "src/models"

![image](https://user-images.githubusercontent.com/32312757/229038626-5ccec7d5-7da2-4680-bf80-25d26c50fff9.png)

**Comment by jung-thomas** [comment]
Thanks. I have updated this.
