### ISSUE TITLE
Create Business Configuration Maintenance Object

### ISSUE THREAD

**Issue by BaerbelW** [sap-tutorials/Tutorials#22962]
Tutorials: https://developers.sap.com/tutorials/abap-environment-business-configuration-object.html
--------------------------

Step 5 Create Business Configuration Maintenance Object --> Substep 7

Intstructions state to delete code in methods LHC_ZI_ERRORCODE###→VALIDATE**RECORDCHANGES** and LHC_ZI_ERRORCODE###TEXT→VALIDATERECORDCHANGES
![grafik](https://user-images.githubusercontent.com/18588108/228515290-6e914b7e-b874-4481-ba43-4eafb756b5ba.png)

However, the code "generated" in the previous step does not contain methods with those names in the two local classes but shows  methods VALIDATE**TRANSPORTREQUEST** instead.
![grafik](https://user-images.githubusercontent.com/18588108/228517795-b0798207-eddb-4b9a-a7a9-ec79aecba9f9.png)

Could there be something I missed in the tutorial causing this, or is there a mismatch between the instructions and what got generated?

Thanks and Cheers
Bärbel

**Comment by mervey45** [comment]
Hi @BaerbelW ,

we will check this and will update this tutorial, if needed.

Best regards, 
Merve

**Comment by sepp4me** [comment]
Hi @BaerbelW,

thank you. The name of the generated methods changed in one of the recent releases.
The correct method name is VALIDATETRANSPORTREQUEST.

Fixed by #22996 

Regards,
  Patrick
