### ISSUE TITLE
Set Up SAP Data Intelligence, Trial Edition

### ISSUE THREAD

**Issue by mareikewalther** [sap-tutorials/Tutorials#22971]
Tutorials: https://developers.sap.com/tutorials/dataintelligence-trial-v2-setup.html
--------------------------

There is no trial edition for SAP DI. Why does this mission exist?

**Comment by NikhilD16** [comment]
The Data Intelligence On-Prem tutorial has been retired.

**Comment by NikhilD16** [comment]
The Data Intelligence On-Prem tutorial has been retired. The mission has been decommissioned from the website as well.
