### ISSUE TITLE
Create a UI Using Freestyle SAPUI5 - STEP: 2 you can't select "SAPUI5 freestyle"

### ISSUE THREAD

**Issue by Mart53** [sap-tutorials/Tutorials#22977]
Tutorials: https://developers.sap.com/tutorials/btp-app-create-ui-freestyle-sapui5.html
--------------------------

Hi all,
**STEP: 2 you can't select "SAPUI5 freestyle" anymore.** 

Only "SAP Fiori" & "Deprecated Templates" is shown after starting "Fiori: Open Application Generator".

Selecting "Deprecated Templates"  -> "SAP Fiori Worklist Application" will still allow you to do the exercise, 
but it is really confusing and took quite some time to find why "SAPUI5 freestyle" is not showing up and what to do.

It would also be helpful to update this here: https://help.sap.com/docs/SAP_FIORI_tools/42532dbd1ebb434a80506113970f96e9/160b4d8c680c463daf20c7399e2dc6ad.html?locale=en-US

In regards to this page https://ui5.sap.com/#/topic/a460a7348a6c431a8bd967ab9fb8d918 it looks like that:
"SAP Fiori" -> "Basic (SAPUI5 freestyle)" seems to be the correct approach now.

BR
Mart53

**Comment by manjuX** [comment]
Hi @Mart53 ,

I'm sorry for the inconvenience. We'll update our tutorial to match this change, until we update the tutorial the workaround you mentioned will work.

Best regards,
Manju

**Comment by slavipande** [comment]
Hi @Mart53 ,

Thanks for pointing this out!

We've updated the instructions in this step to reflect that the worklist **SAP Fiori Worklist Application** is now under **Deprecated Templates**. The change should be published soon. 

In the meantime, we're adapting the tutorial so it uses the new SAP Fiori worklist templates.
Hence, I'll be closing this issue.

Best regards,
Svetoslav
