### ISSUE TITLE
xs command not recognized (SAP hana express edition 2.0)

### ISSUE THREAD

**Issue by NickZubiashvili** [sap-tutorials/Tutorials#22973]
Hello,

I downloaded 
1. **Getting Started with SAP HANA, express edition (Virtual Machine Method)**
2. **Server only virtual machine**
packages from the download manager, after that I install that image on my VMware Workstation, and after all configurations, I got a message on http://xsehost:8090 that "XSEngine is up and running"

Now I'm trying to test my XSA installation, by running the command:
`xs login -u XSA_ADMIN -p "password" -s SAP`
and got the message that xs is not recognized
`if "xs" is not a typo you can use command-not-found to lookup the package that contains it, like this: cnf xs`

**Comment by MichaelCzcz** [comment]
These GitHub issues are to resolve issues (i.e., problems/errors) with the tutorials. Your question seems more general and likely 
would get more visibility -- and a better answer -- in the SAP Community's Questions & Answers. You can ask your question at:
https://answers.sap.com/index.html
