### ISSUE TITLE
Define and Expose a CDS-Based Travel Data Model

### ISSUE THREAD

**Issue by KeerthiMohankumar** [sap-tutorials/Tutorials#22985]
Tutorials: https://developers.sap.com/tutorials/abap-environment-data-model.html
--------------------------
Issue : Failed to open Travel booking application on the UI 
Steps to reproduce: -
Follow the tutorial with the mentioned prerequisites.
At step 4: Create service Binding
-->After Creating a service bending, activate your service binding and then publish it.
-->Double click on travel processor to open the application on UI.

Application fails with an below error:
![Screenshot (142)](https://user-images.githubusercontent.com/107237818/231667873-8da0ff3d-de1f-43a6-8799-6c80441f35d8.png)
![image](https://user-images.githubusercontent.com/107237818/231667952-cd6b4399-5f43-405c-b322-422521776179.png)

Please look into the issue

Labels to be added:
Scenario label: SCPTest-SCPTest-fabap
Sprint Label: SCPTest-2304A
Landscape Label: trail2
Priority: High

Thanks and Regards,
Keerthi

**Comment by mervey45** [comment]
Hi,

this has been updated.

Best regards, 
Merve

**Comment by KeerthiMohankumar** [comment]
Hi @mervey45 ,

The Issue still persists and I'm getting the same error.

Kind Regards
Keerthi

**Comment by mervey45** [comment]
Hi @KeerthiMohankumar , 

in this tutorial there is no step with preview. Please continue with following tutorial to start the preview: https://developers.sap.com/tutorials/abap-environment-behavior.html. There you should be able to see the preview:
![image](https://github.com/sap-tutorials/Tutorials/assets/27953324/0a4a9455-dfc1-4644-95d7-d27319683375)


Best regards, 
Merve
