### ISSUE TITLE
Create an SAP Fiori App Using SAP Business Application Studio : Build an SAP Fiori App that Consumes Data from an On-Premise System -Template Selection. Not able to find 'SAP UI5 freestyle' in the dropdown.

### ISSUE THREAD

**Issue by sreejithppsap** [sap-tutorials/Tutorials#22981]
Tutorials: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html
--------------------------
Write here how you think we can improve the tutorial ...

STEP 3 : 
****
For Template Selection, select the following, and click Next.
Step	Parameter	Value
A	Application type	SAPUI5 freestyle
B	Which template do you want to use?	SAPUI5 Application tile

**Points to improve** : After selecting 'SAP Fiori' application, in step 3, the user is asked to select 'Application type' as	'SAPUI5 freestyle', but 'Application Type' is not available. It is shown as 'template Type' and also value 'SAPUI5 freestyle' is not available in the dropdown.

Please see the attached document (Template_Selection_Error.docx) for more clarity.
[Template_Selection_Error.docx](https://github.com/sap-tutorials/Tutorials/files/11210565/Template_Selection_Error.docx)

Labels to be added:
Scenario label: SCPTest-fbizapp
Sprint Label: SCPTest-2304A
Landscape Label: trail2(Trial US East (VA) (AWS) ) & Trial3 (AP Region)
Priority: High

Thanks and Regards
Sreejith

**Comment by raz-korn** [comment]
@birgits22 : I think there are several threads on this topic.
We should update the tutorial.

Thanks - Raz

**Comment by BaskarThambiayah** [comment]
@birgits22, Many thanks for the document update. We have successfully executed this scenario now.
Hence please close this issue.
Thanks & regards,
Baskar
