### ISSUE TITLE
https://developers.sap.com/tutorials/cap-service-deploy.html

### ISSUE THREAD

**Issue by KeerthiMohankumar** [sap-tutorials/Tutorials#22987]
Issue:

After Successful deployment, while accessing the application, we get the below error: 
![image](https://user-images.githubusercontent.com/107237818/231729756-8d779d98-d4bc-4c54-8c76-72ba0cadf52d.png)

This is with reference to the ticket - https://github.com/sap-tutorials/Tutorials/issues/22722

Kindly Look into this issue..

Labels to be added:
Scenario label: SCPTest-banode
Sprint Label: SCPTest-2304A
Landscape Label: trail2
Priority: High

Thanks & Regards,
Keerthi

**Comment by renejeglinsky** [comment]
Hi @KeerthiMohankumar ,

I think I found the issue. Could you pls test the following:

Edit the `xs-security.json` to change the redirect-uris:

```
"oauth2-configuration": {
    "redirect-uris": [
      "https://*.us10-001.hana.ondemand.com/**"
    ]
  },
```

It appears, that the previous definition was to strict.

**Comment by KeerthiMohankumar** [comment]
Hi @renejeglinsky ,

It worked and I'm able to access the application. Thanks for the Support.

Thanks & Regards
Keerthi
