### ISSUE TITLE
Configure Business Rules, Workflow and Process Visibility - Build and deploy workflow - Deploy MTA Archive is failing.

### ISSUE THREAD

**Issue by sreejithppsap** [sap-tutorials/Tutorials#22982]
Tutorials: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-2-configure.html
--------------------------
Write here how you think we can improve the tutorial ...

STEP 6
Build and deploy workflow

**Points to improve** : Deploy MTA Archive is failing: Please find the log below:

Operation ID: 31754ef7-d8f2-11ed-8595-eeee0a82bc8f
Deploying in org "9d8c2af3trial" and space "dev"
Detected MTA schema version: "3"
No deployed MTA detected - this is initial deployment of MTA with ID "sample.onboarding.mta"
Detected new MTA version: "0.0.1"
Creating service key "onboarding-wm_workflow-credentials" for service instance "wm_workflow"...
Uploading content module "onboarding" in target service "wm_workflow"...
Deploying content module "onboarding" in target service "wm_workflow"...
[onboarding] [FATAL] Deployment of ConfirmOrChangeEquipment.form failed , Error Details: 500 Internal Server Error: "{"error":{"code":"bpm.workflowruntime.rest.internal.server.error","message":"Internal server error","logId":"b9e1c5a9-46c5-4913-8ad2-b8240cd4dc51"}}"
[onboarding] [FATAL] Deployment of AcceptWorkplace.form failed , Error Details: 500 Internal Server Error: "{"error":{"code":"bpm.workflowruntime.rest.internal.server.error","message":"Internal server error","logId":"d648a9ad-df29-41c8-bd6e-606421451c5c"}}"
[onboarding] [FATAL] Deployment of ApproveEquipment.form failed , Error Details: 500 Internal Server Error: "{"error":{"code":"bpm.workflowruntime.rest.internal.server.error","message":"Internal server error","logId":"1d5b5fdb-c7fe-4b2b-88df-8c3056b245d1"}}"
[onboarding] [FATAL] Deployment of onboard.workflow failed , Error Details: 500 Internal Server Error: "{"error":{"code":"bpm.workflowruntime.rest.internal.server.error","message":"Internal server error","logId":"76731e15-48b0-4242-8e11-80b4516d0f54"}}"
Content deployment for module "onboarding" failed. Download the logs "onboarding_wm_workflow" via the dmol command and check them for more information.
A step of the process has failed. Retrying it may solve the issue.
Proceeding with automatic retry... (3 of 3 attempts left)
Deploying content module "onboarding" in target service "wm_workflow"...
[onboarding] [FATAL] Deployment of file Id 3794b0db-d8f2-11ed-80b6-c3445c18ea57  Failed, Error details: while trying to invoke the method com.sap.bpm.wds.core.model.WorkflowModuleContent.getSubcontents() of a null object loaded from local variable 'obj'
Error checking status of content deployment from module "onboarding" in content service "wm_workflow": Content deployment for module "onboarding" failed due to invalid content. Download the logs "onboarding_wm_workflow" via the dmol command and check them for more information. 
Process failed.
Use "cf deploy -i 31754ef7-d8f2-11ed-8595-eeee0a82bc8f -a abort" to abort the process.
Use "cf deploy -i 31754ef7-d8f2-11ed-8595-eeee0a82bc8f -a retry" to retry the process.
Use "cf dmol -i 31754ef7-d8f2-11ed-8595-eeee0a82bc8f" to download the logs of the process.

*  The terminal process "/bin/bash '-c', 'cf deploy "/home/user/projects/cf-onboarding-sample/cf-onboarding-sample/mta_archives/sample.onboarding.mta_0.0.1.mtar"'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it.

Labels to be added:
Scenario label: SCPTest-eboard
Sprint Label: SCPTest-2304A
Landscape Label: Trial3 (AP Region)
Priority: High

Thanks and Regards
Sreejith

**Comment by BaskarThambiayah** [comment]
Hi @ArchanaShukla ,
Retested in AP Region as part of May month execution cycle and this issue is resolved now.
Hence please close this ticket.

Many thanks & regards,
Baskar
