### ISSUE TITLE
Expose Integration Flow Endpoint as API and Test the Flow

### ISSUE THREAD

**Issue by SoumyaGyanapnor** [sap-tutorials/Tutorials#22986]
Hi
Tutorials: https://developers.sap.com/tutorials/cp-starter-isuite-api-management.html
--------------------------
Issue: Regarding Documentation Update
Here, observation: In the documentation to define and expose an integration flow endpoint as an API, there is no API option to switch to the API management portal in the DESIGN Artifact section. But it is in the SETTINGS section to Switch to the API portal and to create an API.

URL used as per tutorial:https://developers.sap.com/tutorials/cp-starter-isuite-api-management.html

Steps to reproduce:
In Step2, Define the API
1.Choose Design > APIs > Create to create an API.
In the documentation please mention SETTINGS instead of DESIGN.
please refer the below screenshot

Expected:

![Expected](https://user-images.githubusercontent.com/124772107/231681004-69b7fbcf-b81e-4e9b-8450-c13b802da102.png)

![Expected1](https://user-images.githubusercontent.com/124772107/231681090-0073e166-f93d-4747-ae88-856dff88911f.png)

Actual:

![Actual](https://user-images.githubusercontent.com/124772107/231681254-a97515e7-471f-4638-8f93-7c4028b8360c.png)

Please update the documentation as per the screenshot accordingly.
Labels:
Scenario Label: SCPTest-cloudin
Sprint label: SCPTest-2304A
Landscape label: trail2, trail3
Priority: High

Thanks & Regards,
Soumya Gyanapnor

**Comment by Karunaharan** [comment]
Thanks for the finding @BaskarThambiayah - will fix this!

Karuna

**Comment by BaskarThambiayah** [comment]
Hi Karuna,
Many thanks for looking into this issue 👍 

Regards,
Baskar

**Comment by Karunaharan** [comment]
Fixed and republished!
