### ISSUE TITLE
Deploy Commerce Mock Application in the Kyma Runtime

### ISSUE THREAD

**Issue by pahlkelerch** [sap-tutorials/Tutorials#22997]
Tutorials: https://developers.sap.com/tutorials/cp-kyma-mocks.html
--------------------------

Step 6 - 'Create a Formation' shows a screenshot, which might be not up to date. I see an additional field 'Formation Type'.  Here I have to choose 'Side-by-side extensibility with Kyma'. You may update the tutorial accordingly.
Beside that also 'Custom' is offered as option which seems **not** to be an official option and where I run into issues with it later on. Here a change in the cockpit/Formation UI might be required.

**Comment by grego952** [comment]
Thank you!
The tutorial is now up-to-date.
