### ISSUE TITLE
Create a Destination in the SAP BTP Cockpit

### ISSUE THREAD

**Issue by jensniemeyer** [sap-tutorials/Tutorials#23009]
Tutorials: https://developers.sap.com/tutorials/cp-cf-create-destination.html
--------------------------
Hi Nico,

a full exmaple how to call ODATA on a Cloud for Customer system from BTP would be great.
I am missing the link, after creating the destination how to call the backend oData from  e.g. my UI5 client

**Comment by nicoschoenteich** [comment]
Hi @jensniemeyer,

Sorry for the late reply - somehow I didn't get this issue assigned and only stumbled across it accidentally.
Sounds like what you are looking for is a tutorial on the cloud connector - [this one](https://developers.sap.com/tutorials/btp-app-ext-service-cloud-connector.html) one will do?
There is no direct URL to call a destination. What you would do to call a destination from a (UI5) client is set up an approuter and bind that to the destination service. See my blog post here: https://blogs.sap.com/2022/08/03/sap-tech-bytes-consume-data-using-destinations-with-an-approuter-cloud-foundry-basics-3/

Best, Nico
