### ISSUE TITLE
Unclear/outdated screenshot on "Get a Free Account on SAP BTP Trial" tutorial, step 8

### ISSUE THREAD

**Issue by chrisma** [sap-tutorials/Tutorials#23001]
Tutorials: https://developers.sap.com/tutorials/hcp-create-trial-account.html
--------------------------

* Tutorial: "Get a Free Account on SAP BTP Trial"
* Step: STEP 8 Learn about the service marketplace
* Issue: Screenshot of location of "Service Marketplace" tab/mean is slightly unclear / outdated. Currently the "Service Marketplace" menu is grouped under the "Services" heading. A click on the heading is necessary to show the required subitem. The screenshot could include this information.
* Browser: Google Chrome Version 112.0.5615.49 (Official Build) (x86_64), Safari Version 16.3 (18614.4.6.1.6)

![image](https://user-images.githubusercontent.com/1652117/233026371-092d0fb8-ef89-487a-992d-303b612d3d69.png)
![SCR-20230419-kakn](https://user-images.githubusercontent.com/1652117/233026003-26d0da39-b71d-401b-ae13-d7ab1178d5b2.png)

**Comment by qmacro** [comment]
Thanks, [fixed](https://github.com/sap-tutorials/Tutorials/commit/73aa27717684a5b588a82d37d7bb2c0a7aaae3f9)!
