### ISSUE TITLE
Typo in "Get Ready for UI5-Development on Your Local Machine" tutorial, step 4

### ISSUE THREAD

**Issue by chrisma** [sap-tutorials/Tutorials#23002]
Tutorials: https://developers.sap.com/tutorials/cp-cf-sapui5-local-setup.html
--------------------------

Tutorial: Get Ready for UI5-Development on Your Local Machine
Step: STEP 4 Install the MTA build tool

![image](https://user-images.githubusercontent.com/1652117/233036845-626be026-32aa-4584-ae1e-c5a0ed7bc934.png)

**Comment by nicoschoenteich** [comment]
Thanks!
