### ISSUE TITLE
Add notice to "Create an App for SAP Build Work Zone, standard edition" on required Node.js version

### ISSUE THREAD

**Issue by chrisma** [sap-tutorials/Tutorials#23003]
Tutorials: https://developers.sap.com/tutorials/sapui5-fiori-cf-create-project.html
--------------------------

* Tutorial: Create an App for SAP Build Work Zone, standard edition
* Step: Scaffold a SAPUI5 project
* Issue: Running the recommended `yo easy-ui5 project` results in an `ENOENT` error
* Notes: According to [this](https://answers.sap.com/questions/13847380/error-using-yo-easy-ui5-project-generator.html) SAP Community post, the used `generator-ui5-project` is incompatible with Node.js versions greater than 16. This could be indicated in the tutorial as a requirement.

<img width="796" alt="image" src="https://user-images.githubusercontent.com/1652117/233043884-a2bea5ff-f3a9-439b-a98f-f2e4e8ecc677.png">

**Comment by SugguSandeep29** [comment]
**As You Installed Node JS Version v19.9.0 it does not support, It Supports the Version Node.js 16.20.0**
https://nodejs.org/en/download/releases

**Check out this discussion thread -** 
https://github.com/SAP/generator-easy-ui5/issues/105
https://stackoverflow.com/questions/75890076/error-while-generating-a-ui5-project-using-generator-easy-ui5-in-cli
https://answers.sap.com/questions/13861329/error-while-creating-a-sapui5-project-using-genera.html

Thank You.

**Comment by nicoschoenteich** [comment]
Hi there, we fixed the issue regarding Node >16 with https://github.com/ui5-community/generator-ui5-project/pull/67, so no need to put a disclaimer in the Tutorial.
Best, Nico

**Comment by SugguSandeep29** [comment]
Thank You 
@nicoschoenteich 
For Update :)
