### ISSUE TITLE
Get to Know SAP Tutorials

### ISSUE THREAD

**Issue by erikhansen-chevron** [sap-tutorials/Tutorials#23006]
Tutorials: https://developers.sap.com/tutorials/tutorial-first-steps.html
--------------------------

Write here how you think we can improve the tutorial ...
I was doing this first tutorial:
https://developers.sap.com/tutorials/tutorial-first-steps.html
I think that step 6 should be showing an image and instead is showing this:
![image](https://user-images.githubusercontent.com/131266266/233075127-973a9b67-d3a1-41fe-88d7-abc05ce60f50.png)

**Comment by jmmargo** [comment]
The proper image now shows in the tutorial.  Please reopen if the problem persists for you.
