### ISSUE TITLE
CdsService has been depracted

### ISSUE THREAD

**Issue by pkeilbach** [sap-tutorials/Tutorials#23019]
The `com.sap.cds.services.cds.CdsService` has been deprecated, but still appears in a lot of code blocks across all CAP-Java tutorials, for example here:

https://github.com/sap-tutorials/Tutorials/blob/1c620d83fd3aacf9741ff05633d9c6451aeba697/tutorials/cp-cap-java-custom-logic/cp-cap-java-custom-logic.md?plain=1#L71

![image](https://user-images.githubusercontent.com/28002199/234633357-deb13471-603c-4333-9f70-73004119ee49.png)

It would be great if you could replace it with the `CqnService` in all the CAP-Java tutorials.

**Comment by renejeglinsky** [comment]
Thanks @pkeilbach for opening this issue. I'm sorry I missed it for such a long time.
I'll fix that with my colleagues and ship an update in the coming weeks.
