### ISSUE TITLE
Add a Custom Event Handler tutorial step 1 JAVA

### ISSUE THREAD

**Issue by ManuRibeiro** [sap-tutorials/Tutorials#23010]
In the tutorial, there is a deprecated library (com.sap.cds.services.cds.CdsService) which you should replace with (com.sap.cds.services.cds.CqnService) and with this change in the Event creations you should use:
**@On(event = CqnService.EVENT_CREATE, entity = "AdminService.Products")** for event create and **@On(event = CqnService.EVENT_READ, entity = "AdminService.Products")** for event read.

Hope it helps!! :D

**Comment by renejeglinsky** [comment]
Thanks @ManuRibeiro for opening this issue. I'll fix that with my colleagues and ship an update in the coming weeks.

**Comment by renejeglinsky** [comment]
Duplicate #23019

**Comment by renejeglinsky** [comment]
Oh I've just seen that your issue is from April! I'm sorry that I missed it.

**Comment by renejeglinsky** [comment]
Fixed: https://github.com/sap-tutorials/Tutorials/commit/8ae2e61c156ec09be53ad3ef86099510dbd9cf91
