### ISSUE TITLE
Java Version Error

### ISSUE THREAD

**Issue by pkeilbach** [sap-tutorials/Tutorials#23022]
FYI, I only got this working by setting `<jdk.version>8</jdk.version>` in the `pom.xml` (root-level)

https://github.com/sap-tutorials/Tutorials/blob/1c620d83fd3aacf9741ff05633d9c6451aeba697/tutorials/cp-cap-java-deploy-cf/cp-cap-java-deploy-cf.md?plain=1#L92

**Comment by renejeglinsky** [comment]
Again, sorry @pkeilbach. And also again: I think this is now obsolete with our recent major. But I'll check again :)

**Comment by renejeglinsky** [comment]
Can be closed now. Thanks!
