### ISSUE TITLE
Connect to HubSpot

### ISSUE THREAD

**Issue by shajipapn** [sap-tutorials/Tutorials#23025]
Tutorials: https://developers.sap.com/tutorials/cp-apim-openconnectors-connect-hubspot.html
--------------------------

Write here how you think we can improve the tutorial ...

Seems API key is replaced by tokens in private app. I am getting an error while using token as API key.
despite what's shown in tutorial Can i use Outh in this case?

could you also suggest, what's the redirect url i need to use in oauth case

**Comment by shajipapn** [comment]
![1](https://user-images.githubusercontent.com/65648079/235045919-6c13d422-4be2-41b3-a926-da3861df2029.png)
![2](https://user-images.githubusercontent.com/65648079/235045937-fb428179-a5ba-4a46-9a8c-258f1ea0fc34.jpg)

**Comment by shajipapn** [comment]
![3](https://user-images.githubusercontent.com/65648079/235046124-5ecb567e-7248-4d71-8b1a-9029fafb4be6.png)

**Comment by shajipapn** [comment]
![4](https://user-images.githubusercontent.com/65648079/235048465-aea5027d-2c1f-4405-a436-c2c17ff0d51a.png)

**Comment by jmmargo** [comment]
Vikram, can you help with this issue?  I am not sure who the current owner of this tutorial is.  Thank you.

**Comment by Vikramkulkarni01** [comment]
Hi Joshua,

I’ve neither written nor responsible author of this tutorial. I can see that SHILPA VIJ created this tutorial. Kindly assign this issue to her.

***@***.***

Best Regards,
Vikram Kulkarni,
Senior User Assistance Developer, BTPX ADAI IN.
SAP LABS INDIA PVT. LTD., 138, EPIP, Whitefield, Bengaluru 560066, Karnataka, India.
Tel: +918043298210, Mobile: +919731965015, Email: ***@***.******@***.***>




From: Joshua Margo ***@***.***>
Date: Friday, 26 July 2024 at 9:08 PM
To: sap-tutorials/Tutorials ***@***.***>
Cc: Kulkarni, Vikram ***@***.***>, Assign ***@***.***>
Subject: Re: [sap-tutorials/Tutorials] Connect to HubSpot (Issue #23025)

Vikram, can you help with this issue? I am not sure who the current owner of this tutorial is. Thank you.

**Comment by jmmargo** [comment]
This tutorial will soon be deprecated.  Thank you.
