### ISSUE TITLE
Add JDK Version to maven command

### ISSUE THREAD

**Issue by pkeilbach** [sap-tutorials/Tutorials#23020]
I think similar to [here](https://github.com/sap-tutorials/Tutorials/pull/22936/commits/b1e60a39fcf6a491bb1d75a5f273adf3a962b969), the `-DjdkVersion=11` flag needs to be added to the `mvn` command, otherwise it will fail.

https://github.com/sap-tutorials/Tutorials/blob/1c620d83fd3aacf9741ff05633d9c6451aeba697/tutorials/cp-cap-java-service-reuse/cp-cap-java-service-reuse.md?plain=1#L44

**Comment by renejeglinsky** [comment]
Sorry again @pkeilbach for not having seen your issue. I think with the recent major update this is not needed anymore. But I'll check again with my colleagues.

**Comment by renejeglinsky** [comment]
Can be closed now. Thanks!

**Comment by pkeilbach** [comment]
No worries, and thank you, @renejeglinsky!
