### ISSUE TITLE
Enable Events from SAP S/4HANA Cloud to SAP BTP

### ISSUE THREAD

**Issue by zfrk** [sap-tutorials/Tutorials#23035]
Tutorials: https://developers.sap.com/tutorials/btp-app-events-enable-s4hc.html
--------------------------

Hi @iwonahahn and @slavipande ,

Is this tutorial update? I count find Enterprise Event Enablement on S4Hana Cloud?

Tutorial update date is December 2022 and seems pretty new but I am not sure.

I will be happy if you inform me ?

Regards,

Zafer

**Comment by slavipande** [comment]
Hi @zfrk ,

Thanks for submitting this issue!

We'll look at it in the coming days and respond ASAP.

Best regards,
Svetoslav

**Comment by zfrk** [comment]
Hi @slavipande,

I found a way how to do that. You can add CBC activation part. Because there isn't any manage your solution part any more on the S4Hana Cloud.

Best Regards,
Zafer
