### ISSUE TITLE
Create Instance of SAP Event Mesh | No longer available in BTP Trial

### ISSUE THREAD

**Issue by JulianKuipers** [sap-tutorials/Tutorials#23046]
Tutorials: https://developers.sap.com/tutorials/cp-enterprisemessaging-instance-create.html
--------------------------

Hi, I was going through this tutorial and found myself running into a wall while creating the Event Mesh Instance in my Trial account. Sadly I received the following message:

```Service broker error: Service broker enterprise-messaging-service-broker failed with: Service broker parameters are invalid: The plan dev, lite and application must not be used anymore. The trial offering for the Event Mesh Service is discontinued. For more details, please read the blog: https://blogs.sap.com/2023/02/01/sap-event-mesh-trial-to-be-retired/.```

Maybe you can add this as a warning to the beginning of the tutorial?

Is there a workaround to try this out?

Hope to hear from you.

Kind regards,
Julian Kuipers

**Comment by jmmargo** [comment]
Pradeep, as the original author, can you please respond to this issue?

**Comment by jmmargo** [comment]
@pradeeppanda-sap please reply to this feedback ASAP.

**Comment by rbrainey** [comment]
Hi Julian. Event Mesh was -- indeed -- retired from Trial.  The Tutorial has been updated and marked as "License Required".  Sorry we did not catch that sooner for you.  Thanks for reporting this!

**Comment by rbrainey** [comment]
Warning added with a pointer to the definition of SAP BTP commercial accounts.
