### ISSUE TITLE
ui5 appto cloud foundry

### ISSUE THREAD

**Issue by adnan-siddiqu** [sap-tutorials/Tutorials#23041]
Hi I have created some local tiles from the UI5 html tiles and added to catalog and group and roles over night I see those tiles are duplicate meaning two tiles are showing up for each tile created and the original HTML tile that I copied from also updated with my name as creator and creation date as yesterday. even when i delete the duplicated tiles I cannot update the content its giving me error.
something like below do you guys have any suggestion. I dont even know what to make of this error log?

{"error":{"name":"FdcReplicateError","error":{"config":{"url":"https://ui5-flexibility-design-and-configuration.cfapps.us20.hana.ondemand.com/sap/bc/ui2/app_index/replicate","data":"{\"instanceId\":\"623208e6-2b9a-4df7-842b-72acfa98c230\",\"appHostIds\":[],\"boundAppHostIds\":[\"530f5ba4-be28-449f-ad24-42759071ade6\",\"93b62901-822a-46d6-b6d8-61b68888b3c8\",\"0c9ff7e9-6038-4336-9b15-c0a4f594a039\",\"bdee47ae-2916-43c7-8d99-d0081d22d9b5\",\"b54587a6-52f5-49c5-82e0-c2002e2a9a7d\",\"477e8e12-d912-41da-99d5-094e11e6eddd\"],\"contexts\":{\"a4ad10e5-13a1-4304-9014-

**Comment by jmmargo** [comment]
Can you please specify the title or URL of the tutorial in question?

**Comment by jmmargo** [comment]
@cjbernal might this be an issue with one of your tutorials?  
https://developers.sap.com/tutorials/appstudio-sapui5-create.html

**Comment by cjbernal** [comment]
Hi @jmmargo based on the description -- an issue with tiles for UI5 apps -- I do not believe this is an issue with that tutorial or something related. That group has to do with developing an application only. 

@adnan-siddiqu could you please provide the tutorial you followed to create the tile?

**Comment by jmmargo** [comment]
@adnan-siddiqu please reopen this issue if it is still relevant.
