### ISSUE TITLE
Install the MultiApps Cloud Foundry CLI Plugin

### ISSUE THREAD

**Issue by bashoi1234** [sap-tutorials/Tutorials#23044]
Tutorials: https://developers.sap.com/tutorials/cp-cf-install-cliplugin-mta.html
--------------------------

Write here how you think we can improve the tutorial ...

in the step 3. in order to verify the tools is working i was entered the following commad.
cf plugins | find /I "multiapps"
above the following . i was noticed me that the find parameter is wrong.
so i try the following one. it is working 
cf plugins | findstr /I "multiapps"

**Comment by jmmargo** [comment]
DJ, is the above information of use to you?  I ask because you are listed as a contributor and Marius is no longer with the company.

**Comment by qmacro** [comment]
Hi @bashoi1234 - the command `cf plugins | find /I "multiapps` works fine in a Windows command prompt. As does yours.  Perhaps you're using PowerShell?
