### ISSUE TITLE
Create an Empty SAPUI5 Project

### ISSUE THREAD

**Issue by nicoschoenteich** [sap-tutorials/Tutorials#23040]
Tutorials: https://developers.sap.com/tutorials/sapui5-101-create-project.html
--------------------------

Hi!

Here are some suggestions on how we could improve the tutorial:

1.  The tutorial still shows the old theia-based screen shots of the SAP Business Application Studio
2. The command palette is now accessible via `Menu > View > Command Palette...` (this also changed with the move to Code-OSS)
3. The template window looks a bit different now. Users first have to select `SAP Fiori Application` and then choose the `Basic` template under the `SAP Fiori` category. The old `SAPUI5 freestyle` category was removed.

![2023-05-09_13-13-29](https://github.com/sap-tutorials/Tutorials/assets/65965098/b7efe9a2-b2a0-4d72-bdaa-935b9ffdb2bb)
![Screenshot 2023-05-09 at 13 13 57](https://github.com/sap-tutorials/Tutorials/assets/65965098/8a5977d8-6aec-4df1-9915-4d9e17e72b84)

**Comment by nicoschoenteich** [comment]
cc @cjbernal

**Comment by cjbernal** [comment]
@nicoschoenteich I have updated all of the screenshots and changed the text related to the command palette command. Please take a look and the QA version and make sure it looks okay: https://developers-qa-blue.wcms-nonprod.c.eu-de-2.cloud.sap/tutorials/sapui5-101-create-project.html

I have two concerns that I came across during the revisions, so please pay extra attention to the following steps: 

1. Step 2, substep 3: There are no selectable Cloud Foundry Organizations or Spaces to select after login. The tutorial appears to proceed fine without them, but this means no success messages are displayed. Should we simply remove this substep? 
2. Step 4: There was no default Run Configuration. I had to create one, despite following all of the prerequisite steps/tutorials. I have now included instructions for doing so, with images

**Comment by nicoschoenteich** [comment]
Hi @cjbernal,

I think your changes didn't make it into QA, as there is no green check behind your commits and I can't see them in QA. I did check your changes directly and in the commits though and they look good.

Regarding your questions:
1. Is it possible you didn't have to specify an org and space because you only had one org and space in the CF endpoint you connected to?
2. Yes, I also didn't have a default run configuration. Good that you added a new step.

Thanks!

**Comment by cjbernal** [comment]
Thanks for looking @nicoschoenteich. The changes appear live for me now -- I simply pushed another smaller change. 

With regards to the org/space -- should we just remove this step then? I'm not sure what the setups will be for users of this tutorial and I'm definitely not an expert on the configuration. I would defer to someone who knows better here but if we can skip it, why not do so to reduce the risk of user confusion? Because, yes, I only had the one org and space since I create everything explicitly for the tutorial :-)

**Comment by nicoschoenteich** [comment]
Hi @cjbernal,
The changes look good!
I think we can keep the substep for setting the org and space. Everyone who has more than one space will have to do it - and even if you don't have to do it it's no big deal.

Maybe we can rephrase:

Next, you need to *might have to* select the Cloud Foundry Organization and space you want use. [...]

Best, Nico

**Comment by cjbernal** [comment]
Thanks @nicoschoenteich! I made the change. If it looks good to you, I will push to production.

**Comment by nicoschoenteich** [comment]
Thanks! Looks good. Ready to push 👍🏼
