### ISSUE TITLE
Error: Error: Invalid character in entity name Line: 0 Column: 517 Char: =

### ISSUE THREAD

**Issue by hereAnshul** [sap-tutorials/Tutorials#23067]
Its not really an issue but I am not sure where else to post my query.
While following the "[Develop Full-Stack Offline Mobile App](https://developers.sap.com/mission.mbt-offline-app.html)" journey,
All the steps goes well, the CSDL, the OData, the build, the deployment, the test, but as soon as I reach the point of Client Onboarding, I always get this Invalid entity name error.
It happened when I followed the tutorial line by line, plus it also happened when I tried to define my own metadata.
Am I missing something ? I am slightly clueless since everything before [this](https://github.com/sap-tutorials/Tutorials/blob/master/tutorials/cp-mobile-backend-tools-mdk-onboarding/cp-mobile-backend-tools-mdk-onboarding.md) works alright for me.

I use BTP trial account for this tutorial.
![image](https://github.com/sap-tutorials/Tutorials/assets/36290935/6077683f-032b-4c56-9e63-74154368d20d)

Problem is this error gives me very less/ambiguous information.
I would appreciate a hand or at-least direction to the right place to get help.
Thank You

**Comment by hereAnshul** [comment]
@Manuel-Stampp sorry for a direct ping.
I am not sure how these things work.

Just a quick query,

I see some tutorial have the (free tier ready) tag on them and the aforementioned tutrial doesn't.
Do by any chace that's the reason why I get this error when I try to consume the service ? 

Again irrespective of the fact if I follow the tutorial end to end of creat my own CSDL, client onboarding always leads to error.

Some direction ? Sorry and ty.

**Comment by Manuel-Stampp** [comment]
Hi @hereAnshul 
Please apologize the response time. I hope you were able to sort out that issue in the meantime?
Free Tier shouldn't be the reason for this.
It is possible that this error came from user propagation in business application studio.
For user propagation in MDK Templates, as far as I understand, the Role/Role Collection "Business_Application_Studio_Administrator" is required.
Have you checked if the same error also appears in other MDK Tutorials?
