### ISSUE TITLE
Deploy Your First SAPUI5 App

### ISSUE THREAD

**Issue by ValterAraujoJr** [sap-tutorials/Tutorials#23065]
Tutorials: https://developers.sap.com/tutorials/appstudio-sapui5-create.html
--------------------------

Hello there,

All images in the tutorial are missing, it getting 404 for all images. See screenshot below:
<img width="1669" alt="image" src="https://github.com/sap-tutorials/Tutorials/assets/32312757/5e27cd94-ec2e-4fb4-8dc0-628095c38218">

Thanks,
Valter

**Comment by jmmargo** [comment]
Images are appearing as expected.
