### ISSUE TITLE
Installing SAP HANA, express edition with Docker

### ISSUE THREAD

**Issue by jackge007** [sap-tutorials/Tutorials#23075]
Tutorials: https://developers.sap.com/tutorials/hxe-ua-install-using-docker.html
--------------------------

Write here how you think we can improve the tutorial ...

'groupadd haeadm -g 79'
'useradd hxeadm -u 12000 -g 79'

learners have to add user and group manually first before run hana express in container, otherwise they would be we stuck on below issue

hxecont  | ERROR: Insufficient permissions on /hana/mounts. Required permissions: rwx

**Comment by jmmargo** [comment]
John, can you please respond to this user's suggestion?

**Comment by JCurrie27** [comment]
Thanks for the feedback - the section "Create a Directory to Persist SAP HANA, express edition Data Outside of the Container" was removed from the tutorial so readers should no longer hit this issue.
