### ISSUE TITLE
Consume a Stripe service from SAP Open Connectors and SAP Cloud Integration to create payment transactions

### ISSUE THREAD

**Issue by wemoove** [sap-tutorials/Tutorials#23070]
Tutorials: https://developers.sap.com/tutorials/btp-integration-suite-integral-openconnectors.html
--------------------------
On Step 3, it's not clear how to get the Element data. I was able to see it but I think people will miss it.

**Comment by jmmargo** [comment]
Mariajose, can you please respond to this issue?

**Comment by mariajosesap** [comment]
Hi Joshua,

I changed my laptop not so long ago and lost all the git configurations to make changes.

Could you please update the tutorial for me?, the Element Data is the Instance Token, highlighted in the screenshot on the step 2.

Hope this helps.

Majo

Mariajosé Martínez
Sr. Solution Advisor ☁️ | SAP Business Technology Platform
E: ***@***.******@***.***> | M: +1 (437) 423 1803 | Join me on LinkedIn<https://secure-web.cisco.com/1uMa8sImfgClqZARRoKftfZ4vwBFl8aLKBbMcgpALZjQEtX3gs_efvpdR_cJMbD8oylzGmkdKht_WX_QxPN7Qx83Aj_piXWyYZ5DTf37oAiKdp7Bd_HfACnvNp0qgmBihvVfQJf4hPq8oza2qvOq_idwpowK5J_4A9VDUnsqBRfhz09HrTp1AKVwfVErvIGqLAMLJu6U68OD6-LSend1Pb7uO_pb5cMQiMcUl9cK6DvqUi6z1h0Gsi-SNejTxC_10a-C3mCRSCJrVmkjhR2jWJ9t65Sl_M_lrBetQBMAjMSl-rkvy7E8c14MQV7mWmTFB/https%3A%2F%2Fwww.linkedin.com%2Fin%2Fmariajosemq%2F>
SAP Canada. 222 Bay St Suite-2000, Toronto, ON M5K 1B7, Canada.

Learn more about SAP Business Technology Platform here<https://secure-web.cisco.com/1Mtf9Tta72xx5rkbGgADBc6Mc37SyKfXFtBEblnYFHWgUpv7l0m1UPKeyWySOr-hUKTwqlFiE4YjA121oTvH-A6xN67LV7g4NGT-7QTKcuAvjJdwVP4hpsuWevgApdf3x_QyW17Bnx_cKXEvNATnL23BgH6Rnsl2uGJ8ScZjYPcmB0GNYWTdYLTWhz82v6sgc_Ms_EsROrzJOZE_oDr6WiG1ThzyLs4l3m1BMjpWbtl1pghx4GMVw0r9i8c-AKTo73F-2aR4klpq46S2aPSJEWhHxbtOWKknDOoKmaSIYRApcNpv9RO3V8Ih-1tYFqnKu/https%3A%2F%2Fwww.sap.com%2Fproducts%2Fbusiness-technology-platform.html>.

***@***.***<https://www.sap.com/products/business-technology-platform.html>

**Comment by jmmargo** [comment]
Clarification for where the data comes from has been added on step 2.  Thank you for the feedback.
