### ISSUE TITLE
Create an SAP Cloud Application Programming Model Project for SAP HANA Cloud

### ISSUE THREAD

**Issue by Smux** [sap-tutorials/Tutorials#23087]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-cap-create-project.html
--------------------------

The tutorial seems to be outdated. We already encountered people in our unit having multiple deployment issues due to that.
Step 5 suggest to adjust the CAP project configuration by removing the "gen/db" path config for the deployer module and adding "db" instead. It also suggest to add a build configuration in the cds section of the package.json.
Both changes are outdated imo. The CAP sample repositories as well as production apps that are using CAP use "gen/db" as a path and configure the deploy format for the HANA artifacts in the package json by adding on the root of the cds config.
```
  "hana": {
      "deploy-format": "hdbtable"
    }
```

This seems to be the latest best practice :)

**Comment by jung-thomas** [comment]
gen/db is the default configuration for CAP projects. However when using HANA Native tooling like the Calculation View editor, it is necessary to adjust this path. This was the workaround provided by the development team in order for the CAP project to be fully compatible with the HANA native tooling.
