### ISSUE TITLE
Implement Roles and Authorization Checks In CAP

### ISSUE THREAD

**Issue by nikolasimeonov77** [sap-tutorials/Tutorials#23089]
Tutorials: https://developers.sap.com/tutorials/btp-app-cap-roles.html
--------------------------

Hi,
I followed the steps to set up the authorizations and rechecked my configurations. Unfortunately, the authentication does not work for me as it's supposed to be. When I choose the *Risks* and *Mitigations* pages at http://localhost:4004/launchpage.html#Shell-home, I am able to view them without providing credentials. I don't think it's a browser issue as I tried with multiple browers.

**Comment by manjuX** [comment]
Hi @nikolasimeonov77 ,

can you share your code on github so that we can check what the issue might be, also sometimes you need to restart your cds watch command for changes to take effect.

Best regards,
Mahati (She/Her)

**Comment by smahati** [comment]
Hi,

Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. If you still have questions, feel free to open a new issue.

Best regards,
Mahati
