### ISSUE TITLE
Prepare Your Development Environment for CAP

### ISSUE THREAD

**Issue by nikolasimeonov77** [sap-tutorials/Tutorials#23086]
Tutorials: https://developers.sap.com/tutorials/btp-app-prepare-dev-environment-cap.html
--------------------------

Hi all,
You provide a link to the CAP release notes at https://cap.cloud.sap/docs/releases/. It seems that according to the links, the latest release notes are at https://cap.cloud.sap/docs/releases/apr23. I would then expect that the latest cds.js version is 6.8.1. However, I've just installed my CAP package and see the following:
@sap/cds: 6.8.4
@sap/cds-compiler: 3.9.4
@sap/cds-dk: 6.8.3
@sap/cds-dk (global): 6.8.3
@sap/cds-foss: 4.0.1
@sap/cds-mtx: -- missing --
@sap/cds-mtxs: 1.8.4
@sap/eslint-plugin-cds: 2.6.3
Node.js: v18.16.0

Unfortunately, I don't find any release note info for the 6.8.4 version? Or, is this just a new patch or fix to the published 6.8.1 verson?

Thanks!

Nikola

**Comment by renejeglinsky** [comment]
Hi Nikola,

usually the release note do not contain any changes for patch releases. We just count up the numbers here and in this case we missed to change it. Sorry for that. That's not an issue with the tutorial, so I think it's safe to close it.

Cheers René
