### ISSUE TITLE
Add Business Logic to Your Application

### ISSUE THREAD

**Issue by nikolasimeonov77** [sap-tutorials/Tutorials#23088]
Tutorials: https://developers.sap.com/tutorials/btp-app-cap-business-logic.html
--------------------------
Hi,
In step 2, please explian how to reload this page. I finished the previous tutorial a couple of days ago, and now I cant't start the page out of the box with VS Code. It took me about 10 minutes to find out that I can run the _cds watch_ command in my _cpapp_ folder in Git Bash  in order to start the applocation. I then need to open http://localhost:4004/risks/webapp/index.html to see the app in the browser. It would be much easier if this information is directly provided here.

**Comment by smahati** [comment]
Hi,

Closing as this was discussed in a call.

Best regards,
Mahati
