### ISSUE TITLE
Connect to HubSpot - authentication method changed

### ISSUE THREAD

**Issue by JuBerndt** [sap-tutorials/Tutorials#23097]
Tutorials: https://developers.sap.com/tutorials/cp-apim-openconnectors-connect-hubspot.html
--------------------------

As of November 30, 2022, HubSpot API keys are no longer a supported authentication method for accessing HubSpot APIs. Instead, you should use a private app access token or OAuth to authenticate API calls. Learn more about [this change](https://developers.hubspot.com/changelog/upcoming-api-key-sunset) and how to [migrate an API key integration](https://53.hubspotpreview-na1.com/docs/api/migrate-an-api-key-integration-to-a-private-app) to use a private app instead.

The connection to Hubspot could not be established, so the tutorial should be updated.
This is a mandatory step for further learnings.

I tried several solutions connecting Hubspot with the open connector, but was not successful.
Only via REST API i could connect to the CRM system.

Regards
Jürgen

**Comment by jmmargo** [comment]
This tutorial will be deprecated shortly.
