### ISSUE TITLE
Use Redis in the Kyma Runtime to Store and Retrieve Data

### ISSUE THREAD

**Issue by eric-schulz-dev** [sap-tutorials/Tutorials#23098]
Tutorials: https://developers.sap.com/tutorials/cp-kyma-redis-function.html
--------------------------

Write here how you think we can improve the tutorial ...
in Step 5, the subscription cant be created in the functions menue. Only in "configurations > subscription". Also the form has different names than in the tutorial.

**Comment by jmmargo** [comment]
Jamie, can you please address the user's suggestion, or reassign it to a current owner?

**Comment by grego952** [comment]
The issue was fixed with my May 2024 changes.
