### ISSUE TITLE
Create Database Artifacts Using Core Data Services (CDS) for SAP HANA Cloud

### ISSUE THREAD

**Issue by jmalla** [sap-tutorials/Tutorials#23092]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-cap-create-database-cds.html
--------------------------

I am unable to get past the following step:
3. We need to bind our project to a Database Connection and HDI container instance. Press the bind icon to being the process.

Here are my steps
- I click on the bind icon
- I choose - Bind to an HDI Container
- I choose - MyHANAAPP-dev hana (hdi-shared)

Then I get the following error message:

_Failed to chdir to /local/source/openvscode-server: 
No such file or directory Error: Binding Service MyHANAApp-dev failed : 
Service instance 'MyHANAApp-dev' not found: 
Service instance 'MyHANAApp-dev' failed to be created. 
Error: Failed to open connection to the database, because of: Failed to get connection for database '7abb0e78-ca57-482d-9527-5aa0941ce07c' (7abb0e78-ca57-482d-9527-5aa0941ce07c.hana.trial-us10.hanacloud.ondemand.com:443), because of: SAP DBTech JDBC: Cannot connect to jdbc:sap://7abb0e78-ca57-482d-9527-5aa0941ce07c.hana.trial-us10.hanacloud.ondemand.com:443 [Object is closed: com.sap.db.jdbc.SecureChannelSession@63847d5e 7abb0e78-ca57-482d-9527-5aa0941ce07c.hana.trial-us10.hanacloud.ondemand.com:443 ConnectionID:0 SessionID:0 on sun.nio.ch.UnixAsynchronousSocketChannelImpl[connected local=/10.150.247.60:53936 remote=7abb0e78-ca57-482d-9527-5aa0941ce07c.hana.trial-us10.hanacloud.ondemand.com/44.196.217.154:443]: 10.150.247.60:53936 -> 7abb0e78-ca57-482d-9527-5aa0941c..._

The error seems to indicate that it cannot connect to the database.  However, if I click on the SAP HANA Database Explorer icon, then I can connect to the database and see the Catalog and objects.  So I am not sure why this error is happening.

I tried to create another service instance:

I got the first response:  
The MyHANAApp-hdiMyHANAApp-db-deployer-ws-g2jh2 service has been created.

Then I got the error:  
Failed to chdir to /local/source/openvscode-server: No such file or directory 
Error: Binding Service MyHANAApp-hdiMyHANAApp-db-deployer-ws-g2jh2 failed : Unable to get service key 'SharedDevKey' details: 
Cannot obtain service key 'SharedDevKey' details: CF-ResourceNotFound (Creation of service key initial) [10010]

So I am not sure how to proceed.  

Help is appreciated.  All the steps till then worked fine.  I am signed into the Cloud Foundry endpoint:
Cloud Foundry Endpoint: https://api.cf.us10-001.hana.ondemand.com

Cloud Foundry Target
Target is set to: 3eea8c85trial org and dev space. 

Thanks,
Jay

**Comment by jung-thomas** [comment]
The error is fairly clear that it can't connect to your database.  Check to make sure your database is running. Remember the trail shuts down every night and has to be manually restarted.  Mak sure that the Database Explorer is really connecting to the same DB you created in your org space.  

If HANA is definitely running, did you set the Allow IP to all in the security settings when you created the HANA DB?  This is a common mistake to miss this step and then your DB is NOT be accessible from BAS and you will get exactly this error.
