### ISSUE TITLE
Build a Business Application Using CAP for Java

### ISSUE THREAD

**Issue by Efim163** [sap-tutorials/Tutorials#23104]
Mission: https://developers.sap.com/mission.cap-java-app.html
--------------------------

Hello, in the tutorial everywhere Java 11 is described, but it does not work. it is required to set up Java 17 manually to make it work, and it is not written how to do it in the tutorial. 

E.g.
mvn -B archetype:generate -DarchetypeArtifactId=cds-services-archetype -DarchetypeGroupId=com.sap.cds \
  -DarchetypeVersion=RELEASE -DjdkVersion=11 \
  -DgroupId=com.sap.cap -DartifactId=products-service -Dpackage=com.sap.cap.productsservice

**Comment by renejeglinsky** [comment]
Hi @Efim163 ,
we're about to publish the updated version. I'll let you know here when it's public.

All the best,
René
