### ISSUE TITLE
SAP ALM API 

### ISSUE THREAD

**Issue by jacobahtan** [sap-tutorials/Tutorials#23103]
Tutorials: https://developers.sap.com/tutorials/sap-cloud-alm-sap-build-1.html
--------------------------

Write here how you think we can improve the tutorial ...

step 1 point 5, broken link.
Once this is done you can check if the API is well connected following this tutorial: [Tutorial – Testing SAP BTP Destinations](https://community.sap.com/media/sap-tech-bytes/tutorial---testing-sap-btp-destinations)

**Comment by jmmargo** [comment]
This tutorial has been retired.
