### ISSUE TITLE
Create an SAP Fiori Elements-Based UI

### ISSUE THREAD

**Issue by sahilnandimedala** [sap-tutorials/Tutorials#23114]
Tutorials: https://developers.sap.com/tutorials/btp-app-create-ui-fiori-elements.html
--------------------------

Write here how you think we can improve the tutorial ...

**In Step 3**, When we try to open web app generated, it was giving 404 : Could not load metadata. On analysing, found that the service uri getting used in webapp is different from the one generated.
![image](https://github.com/sap-tutorials/Tutorials/assets/81976044/b465bd95-1a6b-442f-b1f5-80607d493349)

**URI in webapp** - /service/risk
![image](https://github.com/sap-tutorials/Tutorials/assets/81976044/7bac68e5-66e3-47bd-8b16-8a8bede5c1cd)

**Generated URI** - /odata/v4/service/risk
On Changing it to the above one, the UI started rendering.
![image](https://github.com/sap-tutorials/Tutorials/assets/81976044/5648202e-aa1b-4129-94f4-57d8c1791e22)

![image](https://github.com/sap-tutorials/Tutorials/assets/81976044/4f5bfcee-45f0-49cd-80d4-7c2fc779b8c6)

**Comment by jmmargo** [comment]
Mahati, can you please address this user's feedback?

**Comment by smahati** [comment]
Hello,

Sorry for not replying. This issue was due to updates that were not released and would have been resolved as our testers did not find this issue in later test. Please open another issue if it is still occurring.

Best regards,
Mahati
