### ISSUE TITLE
Create Calculation View and Expose via CAP (SAP HANA Cloud)

### ISSUE THREAD

**Issue by jmalla** [sap-tutorials/Tutorials#23118]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-cap-calc-view.html
--------------------------

Going through the CAP tutorials and then the deploy tutorial, now the Calculation Views do not reference the tables correctly.  I am not sure how to fix.  When I first went through the tutorials, I was able to create the Calculation view and add the tables.  

So the first pass, the tutorial was fine:
Create Calculation View and Expose via CAP (SAP HANA Cloud)
https://developers.sap.com/tutorials/hana-cloud-cap-calc-view.html

But then when I went through the tutorial:
https://developers.sap.com/tutorials/hana-cloud-cap-deploy-mta.html
Deploy CAP with SAP HANA Cloud project as MTA

Now the tables in the Calculation view are not able to resolve to the right objects.  Looks like it is broken.

Likewise, when I create another Calculation view, the tables are not showing up when I tried to add them.  Here is my YAML:

`_schema-version: "3.1"
ID: MyHANAApp
description: A simple CAP project.
version: 1.0.0
modules:
- name: MyHANAApp-srv
  type: nodejs
  path: gen/srv
  requires:
  - name: MyHANAApp-db
  - name: MyHANAApp-auth
  provides:
  - name: srv-api
    properties:
      srv-url: ${default-url}
  parameters:
    buildpack: nodejs_buildpack
  build-parameters:
    builder: npm-ci
- name: MyHANAApp-db-deployer
  type: hdb
  path: db
  requires:
  - name: MyHANAApp-db
    properties:
      TARGET_CONTAINER: ~{hdi-container-name}
  - name: cross-container-service-1
    group: SERVICE_REPLACEMENTS
    properties:
      key: ServiceName_1
      service: ~{the-service-name}
  - name: cross-container-service-2
    group: SERVICE_REPLACEMENTS
    properties:
      key: ServiceName_2
      service: ~{the-service-name}
  parameters:
    buildpack: nodejs_buildpack
- name: MyHANAApp
  type: approuter.nodejs
  path: app/
  requires:
  - name: srv-api
    group: destinations
    properties:
      forwardAuthToken: true
      name: srv-api
      url: ~{srv-url}
  - name: MyHANAApp-auth
  parameters:
    disk-quota: 256M
    keep-existing-routes: true
    memory: 256M
resources:
- name: MyHANAApp-db
  type: com.sap.xs.hdi-container
  parameters:
    service: hana
    service-plan: hdi-shared
  properties:
    hdi-container-name: ${service-name}
- name: MyHANAApp-auth
  type: org.cloudfoundry.managed-service
  parameters:
    config:
      tenant-mode: dedicated
      xsappname: MyHANAApp-${org}-${space}
    path: ./xs-security.json
    service: xsuaa
    service-plan: application
- name: cross-container-service-1
  type: org.cloudfoundry.existing-service
  parameters:
    service-name: MyHANAApp-dev
  properties:
    the-service-name: ${service-name}
- name: cross-container-service-2
  type: org.cloudfoundry.existing-service
  parameters:
    service-name: MyHANAApp-hdiMyHANAApp-db-deployer-ws-g2jh2
  properties:
    the-service-name: ${service-name}
parameters:
  enable-parallel-deployments: true
build-parameters:
  before-all:
  - builder: custom
    commands:
    - npx -p @sap/cds-dk cds build --production
`

Not sure if the issue is with the multiple services that were created.

Not sure how to resolve this.

Thanks,
Jay

**Comment by jmmargo** [comment]
Thomas, can you please respond to this user's issue?

**Comment by jung-thomas** [comment]
Can not recreate the issue.  Please provide more details on your deployment.  The tables should deploy with the calculation view.  If they deploy correctly from the development tooling then they should deploy correct via MTAR as well.

**Comment by jmmargo** [comment]
@jmalla as a solution has been provided, I am closing this issue.  Please reopen as required.
