### ISSUE TITLE
Add User Authentication to Your Application (SAP HANA Cloud)

### ISSUE THREAD

**Issue by jmalla** [sap-tutorials/Tutorials#23117]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-cap-add-authentication.html
--------------------------

STEP 5: Test.  Item 2.

I ran into issues when I tried to run:

cds bind --exec -- npm start --prefix app

I go the error since I had already run this once before and the app router service was already running on Port 5000:

user: MyHANAApp $ cds bind --exec -- npm start --prefix app
resolving cloud service bindings...
bound auth to Cloud Foundry managed service MyHANAApp-auth:default
bound db to Cloud Foundry managed service MyHANAApp-hdiMyHANAApp-db-deployer-ws-g2jh2:SharedDevKey

> start
> node node_modules/@sap/approuter/approuter.js

#2.0#2023 07 11 11:47:21:258#+00:00#WARNING#/LoggingLibrary################PLAIN##Dynamic log level switching not available#
#2.0#2023 07 11 11:47:22:564#+00:00#INFO#/approuter#####ljy89jk5##########ljy89jk5#PLAIN##Application router version 14.1.2#
#2.0#2023 07 11 11:47:22:567#+00:00#INFO#/Configuration#####ljy89jk8##########ljy89jk8#PLAIN##No COOKIES environment variable#
node:events:491
      throw er; // Unhandled 'error' event
      ^

**Error: listen EADDRINUSE: address already in use :::5000**
    at Server.setupListenHandle [as _listen2] (node:net:1463:16)
    at listenInCluster (node:net:1511:12)
    at Server.listen (node:net:1599:7)
    at Object.exports.start (/home/user/projects/MyHANAApp/app/node_modules/@sap/approuter/lib/server.js:46:10)
    at /home/user/projects/MyHANAApp/app/node_modules/@sap/approuter/approuter.js:77:15
    at /home/user/projects/MyHANAApp/app/node_modules/@sap/approuter/lib/utils/logger.js:35:5
    at Function.auditLog.v2 (/home/user/projects/MyHANAApp/app/node_modules/@sap/audit-logging/index.js:26:12)
    at Object.module.exports.getAuditLogger (/home/user/projects/MyHANAApp/app/node_modules/@sap/approuter/lib/utils/logger.js:25:16)
    at Approuter.start (/home/user/projects/MyHANAApp/app/node_modules/@sap/approuter/approuter.js:72:14)
    at Object.<anonymous> (/home/user/projects/MyHANAApp/app/node_modules/@sap/approuter/approuter.js:146:6)
Emitted 'error' event on WebSocketServer instance at:
    at Server.emit (node:events:525:35)
    at emitErrorNT (node:net:1490:8)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 5000

In order to continue, I had to kill the process.  I had to list the processes and then kill the one listening at 5000.  
user: MyHANAApp $ lwctl -c basic-tools ps aux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
user           1  0.0  0.0   3056  2120 ?        Ss   10:05   0:00 /opt/lwexec/bin/server /extbin/control/sidecar.Hz4L3e /opt/lwexec/c
user        2357  0.0  0.0   3168  1348 ?        S    11:02   0:00 server: monitor: node-10/node
user        2358  0.0  0.1 904668 50408 ?        Ssl  11:02   0:00 /usr/local/bin/node /home/user/.node_modules_global/bin/cds watch -
user        2619  0.0  0.0   3168  1620 ?        S    11:16   0:00 server: monitor: node-10/npm
user        2620  0.0  0.0   2364    20 ?        Ss   11:16   0:00 node-10/node /usr/local/bin/npm start 
user        2622  0.0  0.0   3168  1620 ?        S    11:16   0:00 server: monitor: node-10/node
user        2623  0.0  0.1 707464 56988 ?        Ssl  11:16   0:02 npm start
user        2634  0.0  0.0   2500   604 ?        S    11:16   0:00 sh -c -- node node_modules/@sap/approuter/approuter.js
user        2635  0.0  0.0   2372   232 ?        S    11:16   0:00 node-10/node node_modules/@sap/approuter/approuter.js 
user        2637  0.0  0.0   3168  1620 ?        S    11:16   0:00 server: monitor: node-10/node
user        2638  0.0  0.2 936940 74436 ?        Ssl  11:16   0:01 /usr/local/bin/node node_modules/@sap/approuter/approuter.js
user        3150  0.1  0.2 11432324 93240 ?      Sl   11:45   0:01 /opt/nodejs/node-v16.19.0-linux-x64/bin/node /home/user/.node_modul
user        3244  0.0  0.0   3168  1612 ?        S    11:59   0:00 server: monitor: #_lw_ps
user        3245  0.0  0.0   6772  3000 ?        Rs   11:59   0:00 /bin/ps aux

user: MyHANAApp $ lwctl -c basic-tools kill -9 2635

Then I was able to run that command to start the service at 5000 through the app router:
user: MyHANAApp $ cds bind --exec -- npm start --prefix app

Users might run into this issue.  It would be good to list the work around if this happens.

Thanks,
Jay

**Comment by jmmargo** [comment]
Hello Thomas, can you please respond to this user's feedback?

**Comment by jung-thomas** [comment]
If you already have it running, you need to stop it and run it again. But in this tutorial we've never told you to run it yet.  So I'm assuming you just have it running still from a previous tutorial.
