### ISSUE TITLE
Get Started with SAP Business Application Studio Screenshot change require as per the latest UI Change

### ISSUE THREAD

**Issue by BaskarThambiayah** [sap-tutorials/Tutorials#23127]
Tutorial: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html

Hi Colleagues,
In "Step **3  Generate an app based on the SAP Fiori Basic template**" of this tutorial, please change "Get Started with SAP Business Application Studio" screenshot as per the latest UI change.

Actual Screenshot as per the UI:
![image](https://github.com/sap-tutorials/Tutorials/assets/60343237/c4f8d3c9-d9c3-42b8-a75b-4cf5802357c1)

Screenshot in the Tutorial:
![image](https://github.com/sap-tutorials/Tutorials/assets/60343237/78e82242-66fe-4427-8723-42eef7f08142)

Labels to be added:
Scenario label: SCPTest-fbizapp
Sprint Label: SCPTest-2307A
Landscape Label: trail2(Trial US East (VA) (AWS) ) & Trial3 (AP Region)
Priority: Low

Many thanks & regards,
Baskar

**Comment by birgits22** [comment]
Hi Baskar, 
I updated the screenshots today. As soon as Josh accepted it you will see the changes.
Best regards,
Birgit

**Comment by birgits22** [comment]
Hi Baskar,
the screenshots are updated. Thus closing this.
Best regards,
Birgit
