### ISSUE TITLE
Create Database Artifacts Using Core Data Services (CDS) for SAP HANA Cloud

### ISSUE THREAD

**Issue by jmalla** [sap-tutorials/Tutorials#23121]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-cap-create-database-cds.html
--------------------------

In Step 3 - Explore generated design time artifacts, I run into an issue when I try to bind to the HDI instance:

This is for item 8:

This part works partly.  The HDI service is created, but the binding fails because it cannot obtain the SharedDevKey

_It will take a minute or two for the service to be created in HANA. A progress bar will be shown in the message dialog_

Failed to chdir to /local/source/openvscode-server: No such file or directory Error: Binding Service MyHANAApp-dev failed : Unable to get service key 'SharedDevKey' details: Cannot obtain service key 'SharedDevKey' details: CF-ResourceNotFound (Creation of service key initial) [10010]

When this happens, I have to manually run:
cds bind -2 MyHANAApp-dev:SharedDevKey

Then it works.  So it looks like the SharedDevKey is created - I can see the MyHANAApp-db in the instances and the SharedDevKey service key.  But somehow there is an issue when we do this from clicking on the bind button.  Hope this helps someone out there with the same issue.

Thanks,
Jay

**Comment by jmmargo** [comment]
Thomas, can you please respond to this user's issue?

**Comment by jung-thomas** [comment]
If you just repeat the bind operation in the tooling it will work. This is documented in the tutorial already:
"Sometimes the binding step fails due to a timing issue. If so simply repeat the binding but this time do not create a new container name but select the existing HDI container that has been created from the previous attempt MyHANAApp-dev"
