### ISSUE TITLE
Tutorial Page private-link-aws.md Issue. PROD

### ISSUE THREAD

**Issue by SAPDocs** [sap-tutorials/Tutorials#23134]
Tutorial issue found: [https://github.com/sap-tutorials/Tutorials/blob/master/tutorials/private-link-aws/private-link-aws.md](https://github.com/sap-tutorials/Tutorials/blob/master/tutorials/private-link-aws/private-link-aws.md)  - file path is not unique. Your tutorial was not created.

 Affected server: PROD

**Comment by jmmargo** [comment]
Tutorial was moved to another repository.
