### ISSUE TITLE
Tutorial Page cp-ias-azure-ad.md Issue. PROD

### ISSUE THREAD

**Issue by SAPDocs** [sap-tutorials/Tutorials#23136]
Tutorial issue found: [https://github.com/sap-tutorials/Tutorials/blob/master/tutorials/cp-ias-azure-ad/cp-ias-azure-ad.md](https://github.com/sap-tutorials/Tutorials/blob/master/tutorials/cp-ias-azure-ad/cp-ias-azure-ad.md)  - file path is not unique. Your tutorial was not created.

 Affected server: PROD

**Comment by jmmargo** [comment]
Tutorial was moved to another repository.
