### ISSUE TITLE
Deploy a CAP Business Service to SAP Business Technology Platform

### ISSUE THREAD

**Issue by KeerthiMohankumar** [sap-tutorials/Tutorials#23157]
Tutorials: https://developers.sap.com/tutorials/cap-service-deploy.html

Issue: The application throws "Not Found" error.

At :
STEP 3 :Deploy using cf deploy

The url of the application is "https://50679677trial-dev-my-bookshop.cfapps.us10-001.hana.ondemand.com/app/index.html".
When I go inside the application code, inside the app folder there is no index.html file.

![image](https://github.com/sap-tutorials/Tutorials/assets/107237818/30c6f68b-2bf3-4191-8747-37abd089c765)

Please look into the issue and make changes accordingly.

Labels to be added:
Sprint Label: 2308A
Scenario Label: SCPTest-banode
Landscape Label: trial2
Priority: High

Thanks and Regards,
Keerthi

**Comment by renejeglinsky** [comment]
Hi @KeerthiMohankumar ,

I think I know why this occurs. If I'm right, I'll ship a fix very soon.

Could you try to remove the `welcomeFile` property from the `xs.app.json` and the build and deploy again?

All the best,
René
