### ISSUE TITLE
Lifecycle status remains un-changed after performing the action 'Approve' and the customer name does not appear in any of the cards displayed

### ISSUE THREAD

**Issue by RanjishPR** [sap-tutorials/Tutorials#23156]
Hello,

Tutorial link: [https://developers.sap.com/tutorials/cp-mobile-cards-booster-starter.html[

Trial Cockpit: https://cockpit.hanatrial.ondemand.com/trial/#/home/trial

Steps to reproduce the issue:

1. In the above mentioned tutorial click on Step 4 (View sales order approval card on your mobile device)
2. Follow the steps 1 to 6 mentioned under 'View sales order approval card on your mobile device' 
3.  At step 7 after after 'Approve Order is tapped, it was noticed that the Lifecycle status does not change in any of the cards in question. It is also noted that, the Customer Name in the card that was chosen for the action does not appear in any of the cards displayed.

Please see the screen recording attached with this ticket.

https://github.com/sap-tutorials/Tutorials/assets/105277535/172da9b0-c624-45a3-b89e-2092066a507b

Thanks & Best Regards,
Ranjish

**Comment by sandeep-tds** [comment]
Hi @RanjishPR, 

I am sorry about the delay. 

Can you please share the code that you've used for the action button?

**Comment by RanjishPR** [comment]
Hi @sandeep-tds,

This was done as part of the test validation of this particular starter scenario/tutorial steps(mentioned above). You might have to contact the developers for the code.

Thanks & Best Regards,
Ranjish
