### ISSUE TITLE
Prepare User Authentication and Authorization (XSUAA) Setup

### ISSUE THREAD

**Issue by nikolasimeonov77** [sap-tutorials/Tutorials#23150]
Tutorials: https://developers.sap.com/tutorials/btp-app-prepare-xsuaa.html
--------------------------
The example JSON code should include the following:

"auth": "xsuaa" instead of  "auth": {
          "kind": "xsuaa"
        }

At least, this is what I got in the _package.json_ file.

**Comment by jmmargo** [comment]
Mahati, can you please address the user's feedback?  Thank you.

**Comment by smahati** [comment]
Hello,

Sorry for not updating this issue, this was fixed but the tutorial seems to be unavailable. I'll check.

Best regards,
Mahati

**Comment by smahati** [comment]
Hello,

The tutorial is back and the fix is in place, thank you for your feedback.

Best regards,
Mahati
