### ISSUE TITLE
Build an Application End-to-End Using CAP, Node.js and VS Code

### ISSUE THREAD

**Issue by SGE309** [sap-tutorials/Tutorials#23155]
https://developers.sap.com/tutorials/btp-app-hana-cloud-setup.html

Hello, 

there are some issues on multiple pages with CSS I guess. This leads to issues, as in the example "Set Up the SAP HANA Cloud Service" I can not see the tasks to work on them.

Thank you
![Screenshot 2023-08-08 073941](https://github.com/sap-tutorials/Tutorials/assets/141623504/e9649622-0f41-409d-b1ef-2351098370e0)

**Comment by smahati** [comment]
Hi, Unfortunately this is an infrastructure issue, clearing cache for your browser should fix it. Sorry for the inconvenience.

Best regards,
Mahati
