### ISSUE TITLE
Status bar colour is not getting changed when SAP Business App Studio reloads with project open in workspace

### ISSUE THREAD

**Issue by BaskarThambiayah** [sap-tutorials/Tutorials#23159]
Tutorial: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html

Hi Colleagues,
In "Step 2  Open the project's folder" of this tutorial, at Step 4. it is mentioned as "The status bar color changes to blue, indicating that a workspace or folder is open." 
Actual Result: But there status bar colour is not getting changed.

Screenshot in the Tutorial:
![image](https://github.com/sap-tutorials/Tutorials/assets/60343237/8bb92f6c-a841-4fb5-b1c6-4dee63a14053)

Actual result in the UI:
![image](https://github.com/sap-tutorials/Tutorials/assets/60343237/e238e291-9d04-4e91-bcb7-2aefac76d776)

Labels to be added:
Scenario label: SCPTest-fbizapp
Sprint Label: SCPTest-2308A
Landscape Label: Trial3 (AP Region)
Priority: Low

Many thanks & regards,
Baskar

**Comment by birgits22** [comment]
Hi Baskar,
I changed this - as soon as Joshua accepts the changes, they will become visible.
Best regards,
Birgit

**Comment by birgits22** [comment]
Hi Baskar, 
this has been updated. Thus closing this issue.
Best regards,
Birgit
