### ISSUE TITLE
Create a Simple OData Service with Mobile Back-End Tools - updates required

### ISSUE THREAD

**Issue by ASRHARDING** [sap-tutorials/Tutorials#23158]
Tutorials: https://developers.sap.com/tutorials/cp-mobile-backend-tools-simple-odata.html
--------------------------

While performing the tutorial “Create a Simple OData Service with Mobile Back-End Tools” I encountered a number of differences between the tutorial steps and the actual steps required to complete the tutorial.

Could you please update this tutorial with the variations listed below, and answers to the associated questions would be much appreciated. I have also included a document attachment covering the points below with associated screenshots.

**Step 3 - Generate and run the service**

6.	In the last prompt of the wizard, please locate the previously created metadata.csdl.xml file from your workspace (/home/user/projects/MBTEPMDemoService) and click OK.
Selecting metadata.csdl.xml is not the last screen in the configuration, since after you select the file there are configuration steps 9, 10 & 11.
▫	Creation of tasks.json file Step 9 options:
        	No Only online feature
        	Yess enable offline feature
        Selected Yes enable offline feature.
▫	Creation of tasks.json file Step 10 options:
       	No assign features for native application
       	Yes assign features for MDK application
       Selected Yes assign features for MDK application.
 ▫	Creation of tasks.json file Step 11 - go with default **my-destinations**.
 
**Are the responses given above, correct? What should the responses have been?**

**Step 4 - Configure authentication and app router**

5.	Right-click the folder approuter in your workspace, then select New File to create two new files called package.json & xs-app.json with the content below. 
After saving the new files there is an error listed against package.json.
Fixed this error message by running the following terminal command in folder /srv/approuter/.
npm install @sap/approuter --save

**Not sure if a later action in this tutorial would have fixed this fault anyway.**

8.	Click Terminal > New Terminal, type cf deploy and press Enter.
The cf deploy fails with the error below:
**FAILED**
Error retrieving MTA: Error building MTA Archive: file path /home/user/projects/MBTEPMDemoService/srv/target/odata-service-1.0.0.war not found
Fixed this error by changing the definition of the path in line [9] of mtad.yaml file.
▫	From: 
    path: srv/target/odata-service-1.0.0.war
▫	To: 
    path: srv/deploy/odata-service-1.0.0.war

**Alternatively, I could have copied the odata-service-1.0.0.war file from the /srv/deploy/ folder into the /srv/target/ folder - not sure which it the better, more elegant solution.**

9.	Open and examine the OData service using the approuter via your browser. Find the application route either from the terminal output (red box) or via the applications in BTP Cockpit, as in this screenshot.
 
I do get the "The redirect_uri has an invalid domain" message when trying the application route - the suggested additional code adding the redirect to the xs-security.json files works. 
 
**What are the related code changes you should make to the mtad.yaml file to ensure the config change is preserved when you run the csdl-to-war task?**
[Create a Simple OData Service with Mobile Back-End Tools - Issues.docx](https://github.com/sap-tutorials/Tutorials/files/12327285/Create.a.Simple.OData.Service.with.Mobile.Back-End.Tools.-.Issues.docx)

**Comment by Manuel-Stampp** [comment]
#23250
