### ISSUE TITLE
Deploy Your Multi-Target Application (MTA)

### ISSUE THREAD

**Issue by nikolasimeonov77** [sap-tutorials/Tutorials#23151]
Tutorials: https://developers.sap.com/tutorials/btp-app-cap-mta-deployment.html
--------------------------

In step 4 of this tutorial, I recommend that you first run the _node --version_ command to check that you use the minimal required version of Node.js. If it's higher than 16, you can go ahead and set the v16 limitation.

**Comment by jmmargo** [comment]
Mahati, can you please address this user's feedback?  Thank you.

**Comment by smahati** [comment]
Hello,

Sorry for not replying earlier, I'll fix this and close it after it's published.

Best regards,
Mahati
