### ISSUE TITLE
Subscribe to the SAP Build Work Zone, Standard Edition

### ISSUE THREAD

**Issue by nikolasimeonov77** [sap-tutorials/Tutorials#23168]
Tutorials: https://developers.sap.com/tutorials/btp-app-work-zone-subscribe.html
--------------------------

I found the following issues in this tutorial:
 - In step 4, the screenshots are outdated.
 - In step 5, the image is missing at the end.

**Comment by jmmargo** [comment]
Mahati, can you please address the user's concerns here.

**Comment by smahati** [comment]
Hello,

Sorry for the late reply, I'll take a look at the tutorial. Thanks!

Best regards,
Mahati

**Comment by smahati** [comment]
Hello,

closing as the tutorials are deprecated. please open a new issue if you need further support.

Best regards,
Mahati
