### ISSUE TITLE
Test your SAP Build Work Zone, standard edition site

### ISSUE THREAD

**Issue by garydaley** [sap-tutorials/Tutorials#23166]
Subscribe to the SAP Build Work Zone, Standard Edition
https://developers.sap.com/tutorials/btp-app-work-zone-subscribe.html

STEP 5 Test your SAP Build Work Zone, standard edition site

Risk and Mitigation Applications deployed ok. Both appear in SAP Build Work Zone but hang with pulsing 3 blue dots . 
Console log attached.

[eda646dftrial.launchpad.cfapps.us10.hana.ondemand.com-1692629976.log](https://github.com/sap-tutorials/Tutorials/files/12397904/eda646dftrial.launchpad.cfapps.us10.hana.ondemand.com-1692629976.log)

Please advise.

**Comment by jmmargo** [comment]
Mahati, can you please address the user's concerns above, thank you.

**Comment by smahati** [comment]
Hello,

Sorry for the late reply, The logs aren't helpful and do you still need support?

Best regards,
Mahati
