### ISSUE TITLE
Installing SAP HANA, express edition with Docker

### ISSUE THREAD

**Issue by maatini** [sap-tutorials/Tutorials#23164]
Tutorials: https://developers.sap.com/tutorials/hxe-ua-install-using-docker.html
--------------------------

the instructions are unnecessarily "general". For example

chown <hxeadm userID or name>:<sapsys groupID or name> /data/<directory_name>

The added value of using your own user name and directory name is almost nil.

With these instructions, "mydirectory" suddenly appears. An undefined name for the time being!

mkdir -p /data/mydirectory
chown 12000:79 /data/mydirectory

Again without added value! 
Unfortunately, this problem comes up again and again.

All in all, I find the instructions below average.

**Comment by jmmargo** [comment]
John, can you please address the user's feedback here?  Thank you.

**Comment by JCurrie27** [comment]
Thanks for your tutorial feedback. I've taken this issue to the Docker team and will update the tutorial accordingly.
