### ISSUE TITLE
Create an SAP Mobile Services App for the SAP Service and Asset Manager Mobile App

### ISSUE THREAD

**Issue by igor-sangulin** [sap-tutorials/Tutorials#23174]
Tutorials: https://developers.sap.com/tutorials/mob-app-mao-erp-app-create.html
--------------------------

Could you please fix tutorial so that images are visible? Currently all images are broken
![image](https://github.com/sap-tutorials/Tutorials/assets/110915768/2dc113bd-92af-4f2a-b079-c95687d3ca73)

Thanks!

**Comment by jmmargo** [comment]
The images are now appearing.
