### ISSUE TITLE
Create a Cached OData Service for Improved Offline OData - Step 5 screen updates required

### ISSUE THREAD

**Issue by ASRHARDING** [sap-tutorials/Tutorials#23170]
Tutorials: https://developers.sap.com/tutorials/cp-mobile-backend-tools-cache-db.html
--------------------------

In “Step 5 - Reference your OData service in SAP Mobile Services” some of the tasks/screens to create an MDK Mobile Application are different to those in the BTP trial system.

See the attached document for commentry below with the screenshot images included.

**Differences by Task in the Step:**

2. Select Mobile Applications > Mobile/MDK instead of Mobile/Hybrid.

5. Screen now has a choice between XSUAA Settings for IAS Settings.

6. Before Assign Features screen there is an additional, Role Settings screen.
   The Enable Role Settings is  set by default. Deselect Enable Role Settings is .
   <screenshot>
   Click on Next.

**Note about task 6. above:**
If you leave Enable Role Settings is  set, and assign a role (e.g., “Everyone”), you will most likely encounter the error below when in tutorial “Onboard an MDK Client to Your OData Cache Database” Step 1, Task 7. In OData Collections step, click Select all data collections > Yes.
<screenshot> 
 
Hover over the error and click up ^ icon.
<screenshot> 
Error: Failed to access backed with error Request Failed with status code 403, please check your destination in SAP Mobile Services cockpit.

[Create a Cached OData Service for Improved Offline OData - Issues.docx](https://github.com/sap-tutorials/Tutorials/files/12417216/Create.a.Cached.OData.Service.for.Improved.Offline.OData.-.Issues.docx)

**Comment by Manuel-Stampp** [comment]
#23171
