### ISSUE TITLE
Create a Simple Automation - Prerequisite links don't work

### ISSUE THREAD

**Issue by ASRHARDING** [sap-tutorials/Tutorials#23173]
Tutorials: https://developers.sap.com/tutorials/irpa-simple-automation-helloworld.html
--------------------------

Both the Prerequisite links do not work. 

When you click on them you get the message “Sorry, we couldn’t find that tutorial”. 

It is not possible to start this tutorial since the Prerequisites are essential to provide the RPA environment. 

Please fix the Prerequisite links to enable execution of this tutorial.

Kind regards,
Andrew

**Comment by ASRHARDING** [comment]
By the looks of it iRPA has been subsumed into SAP Build Process Automation, so maybe this tutorial should be removed.

**Comment by jmmargo** [comment]
This tutorial was removed.  Thank you.
