### ISSUE TITLE
Create a Cached OData Service for Improved Offline OData - metadata.csdl.cml code mismatches

### ISSUE THREAD

**Issue by ASRHARDING** [sap-tutorials/Tutorials#23171]
Tutorials: https://developers.sap.com/tutorials/cp-mobile-backend-tools-cache-db.html
--------------------------

The code listing at the end of Step 3 for formetadata.csdl.cml does not match the code changes specified in steps 2 and 3:

•	The annotations additions to entities BusinessPartner & salesOrder, along with entity container com_sap_mbtepmdemoServices, are listed at the beginning of each section in the full code listing at the end of step 3. Whereas, the annotation additions specified in step 2 are instructed to be added at the end of each entity/container section. This makes comparing your code with the listing at the end of step 3 very difficult. Please use the same convention for step 2 and the code listing in step 3, either put annotations at the beginning of sections, or at the end, not both.

•	Step 2, task 5, adds the following annotation code:
   <Annotation Term="Cache.RefreshBy" String="loadAll"/>
   <Annotation Term="HTTP.Destination" String="ES5_GWSAMPLE"/>
   <Annotation Term="HTTP.Request" Qualifier="loadAll" String="GET /BusinessPartnerSet">
Whereas the code listing at the end of step 3 lists an additional annotation for term Cache.LoadAfter string BusinessPartner.
   <Annotation Term="Cache.LoadAfter" String="BusinessPartner"/>
   <Annotation Term="Cache.RefreshBy" String="loadAll"/>
   <Annotation Term="HTTP.Destination" String="ES5_GWSAMPLE"/>
   <Annotation Term="HTTP.Request" Qualifier="loadAll" String="GET /BusinessPartnerSet">
Which version is correct?

•	Minor difference in the commented Annotation Term (line 174 or 176) step x refers to "ES5_GWSAMPLE" while step 3 code listing refers to "SAP_GATEWAY_GWSAMPLE".

Kind regards,
Andrew

**Comment by Manuel-Stampp** [comment]
#23250
