### ISSUE TITLE
Issue with  Turtorial XSA_DEV User:  install SAP HANA 2.0, express edition on a Preconfigured Virtual Machine

### ISSUE THREAD

**Issue by BMBT-DK** [sap-tutorials/Tutorials#23175]
Hello I am following the guide: https://developers.sap.com/group.hxe-install-vm-xsa.html

I am using the application server and VM, using Oracle VM Virtual Box. But cannot access my hana database explorer after the instalation.

The installation seems to almost work, but I get the same error everytime on installation, and that is that when it during installation sets the hana masterpassword for XSA_DEV it gets the error SQLstate 28000. Everytime i start up the VM it prompts me for new password, saying the old one was not legal despite adhering to the rules, but when I then type in a new password it doesnt seem to have permission to change the old one.

I'm having issues accessing my hana cockpit from the XSA menu, in fact it seems only the XSA is working. Is there a way to instantiate the XSA_DEV so i can get to my hana cockpit and populate the database. It seems that the issue is the 3 servives that do not start as shown in the picture.

I can use login as xs-admin-login but not the dev, when I login to the Hana-cockpit/explroer with XSA_DEV as username it can't find the user, and when I do with XSA_ADMIN it just states an internal server error.

![hana3 3889](https://github.com/sap-tutorials/Tutorials/assets/143399881/b884452e-9088-446d-95e7-dda796a4205c)
![hana2 3891](https://github.com/sap-tutorials/Tutorials/assets/143399881/03d4b76f-faa3-4308-aa77-b5c4a6cd7a4e)
![hana1 3888](https://github.com/sap-tutorials/Tutorials/assets/143399881/0a944f7b-b780-4096-ba1e-8f9afecb78b6)
![hana 3890](https://github.com/sap-tutorials/Tutorials/assets/143399881/85d19f74-a984-47d5-a6b1-94cde832d833)
![hana5 3892](https://github.com/sap-tutorials/Tutorials/assets/143399881/4c8e93fc-2a66-433a-986a-bb92d4e7c9cd)

**Comment by jmmargo** [comment]
Hello John, can you please assist this user?  Thank you.

**Comment by JCurrie27** [comment]
Thanks for your feedback. Many thanks if you could log these Database Explorer issues on the HANA Express community Q&A page to take advantage of the HANA Express community support model. The Q&A page receives much more traffic, and other users may be able to provide answers immediately.

To log your questions on the Q&A page, go to https://answers.sap.com/questions/ask.html
