### ISSUE TITLE
Create an Account on the SAP Gateway Demo System

### ISSUE THREAD

**Issue by JanzenSAP** [sap-tutorials/Tutorials#23183]
Tutorials: https://developers.sap.com/tutorials/gateway-demo-signup.html
--------------------------

Step 5 is now different:
"SAP GUI for HTML" is no longer starting up and the "SAP Easy Access" page is also no longer appearing.
Instead, simply the text "Server reached" is displayed.
That's all what will be shown after the user has successfully logged on and performed the mandatory password change.

**Comment by MaxKei** [comment]
I am having same issue, this tutorial and others, connected to this tutorial is not functionating. Meaning, it is almost impossible to continue these courses/tutorials.

For example another one that this WEB SAP GUI is affected is: https://developers.sap.com/tutorials/odata-02-exploration-epm.html

**Comment by jmmargo** [comment]
I am able to reach the SAP GUI for HTML link.  Are you still having issues with this?

**Comment by jmmargo** [comment]
If you are still having an issue with this, please reopen the issue.  I will close it for now.
