### ISSUE TITLE
Create an SAP Fiori Elements Application

### ISSUE THREAD

**Issue by JuergenMair** [sap-tutorials/Tutorials#23180]
Tutorials: https://developers.sap.com/tutorials/fiori-tools-cap-create-application.html
--------------------------

Write here how you think we can improve the tutorial ...

The minimum SAPUI5 version which is shown in the screenshot is not offered any longer (https://developers.sap.com/tutorials/fiori-tools-cap-create-application/jcr:content.github-proxy.1681198212.file/provide-project-attributes.png, one of the first steps in the tutorial). 

As the SAPUI5 versions change very quickly I suggest a comment in the text that the default setting can be used here. 

Kind Regards, 
Juergen

**Comment by jmmargo** [comment]
Joachim, can you please respond to the user's feedback?  Thank you.

**Comment by jo-fiess** [comment]
Hi Juergen, thank you for your proposal, we are reviewing the tutorials currently and will take it into account. regards Joachim
