### ISSUE TITLE
Add a URL App to Your Site

### ISSUE THREAD

**Issue by SoumyaGyanapnor** [sap-tutorials/Tutorials#23188]
Hi,

Tutorial: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-url-applaunchpad.html

Issue: Steps are missing
Here, observation:  when we create the apps and when we add apps to everyone role and  when we click on the Go to site ,  it is showing the error "Cannot find a space asssigned to you".
please refer attached screenshot,

![SAP Fiori Launchpad](https://github.com/sap-tutorials/Tutorials/assets/124772107/2d6e3788-e70a-42fb-a697-d93b49c1e564)

The next step "Adding apps to a page" is missing in the document.

Steps to reproduce:
In STEP  : Add a URL App to Your Site
After Step 4 the further steps are missing.

Labels:
Landscape Labels - trail2, trail3
Sprint Label: SCPTest-2309A
Scenario Label: SCPTest-psite
Priority: High

Thanks & Regards,
Soumya

**Comment by anz-sapfico** [comment]
@SoumyaGyanapnor do you still have this issue?

**Comment by SoumyaGyanapnor** [comment]
Hi anz-sapfico,

Yes the issue is still reproducible..Kindly look into the issue.

Regards,
Soumya

**Comment by mishageorge0** [comment]
Hi,
Its working now for both US&AP region.
<img width="960" alt="image (1)" src="https://github.com/sap-tutorials/Tutorials/assets/153719833/2ed835b6-386d-455c-807e-a1c40fefaa30">

**Comment by BaskarThambiayah** [comment]
Hi,
Issue is resolved now. Hence, I close this ticket.
Thanks
