### ISSUE TITLE
Create ABAPDoc Comments in Your Class (On-Premise) - STEP 9 - Test yourself

### ISSUE THREAD

**Issue by smtpsantiago** [sap-tutorials/Tutorials#23192]
Hi Guys.
how resolved this? i tried -> 
`"! @parameter planetype | <p class="shorttext synchronized"> Type of plane </p>`
and
`"! @parameter PLANETYPE | Type of plane`
appears this message -> "Sorry, that’s not quite right.".

what is wrong?

**Comment by jmmargo** [comment]
I will assume that you are no longer having this issue.  If so, please reopen this issue and include the tutorial that you are referencing.
