### ISSUE TITLE
Create a Development Project in SAP Business Application Studio

### ISSUE THREAD

**Issue by thesse1** [sap-tutorials/Tutorials#23194]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-mission-trial-8.html
--------------------------

I have tried several times, and I always fail in the first step of the tutorial. I have enabled Cloud Foundry Environment and created a “dev” space, cf. screenshot. Then I tried to add an instance mapping to my SAP HANA Cloud database instance, cf. screenshots, but although the dialog pop-up and a notification pop-up would say it would restart the database, this does not happen. And even after restarting the database instance manually, the “Instance Mapping” section stays empty. Even when I stop the instance and try to configure the mapping in stopped state, it does not seem to accept the change. The “Instance Mapping” section stays empty. I also tried filling out the Environment Instance ID and the Environment Group (Space ID). Same result.

Consequently, when I continue the tutorial and try to configure the HDI container, it fails with error message: “Service broker error: Service broker hana-broker failed with: Can not create service instance 'HDI_Tutorial': There is no database with database_id 'dc20d757-a59f-43d6-a6d7-bb81e171dcdc' in space 'dev' within organization '4b6a72d5trial_4b6a72d5trial'. Check the database_id.”

What am I doing wrong? Thanks!

Best regards,
Thomas

![01_cloud_foundry_environment](https://github.com/sap-tutorials/Tutorials/assets/20128287/c91eee0c-8de5-4256-9156-bbf2701f8b7f)
![02_Instance_Mapping_filled_in](https://github.com/sap-tutorials/Tutorials/assets/20128287/3667504e-d3dd-44d7-ac2f-64a4bbff9184)
![03_dialog](https://github.com/sap-tutorials/Tutorials/assets/20128287/ac3cff54-4920-4ca0-bdbd-fcfd596b746a)
![04_pop_up](https://github.com/sap-tutorials/Tutorials/assets/20128287/6d5d9b00-2905-46fb-8950-e6eda62b2253)
![05_Instance_Mapping_empty](https://github.com/sap-tutorials/Tutorials/assets/20128287/0005283c-9c43-4e81-b1cd-19e2e7684463)
![06_Instance_Mapping_with_Environment_Group](https://github.com/sap-tutorials/Tutorials/assets/20128287/cc2c040e-245b-450e-8936-515095bafe8c)

**Comment by thesse1** [comment]
FYI: I have just created a completely new database, and in the creation wizard I already specified the instance mapping. That was successful. You should update your tutorial accordingly.

**Comment by danielva** [comment]
I am sorry this was not working.  I was not able to reproduce the issue so hopefully this has been addressed.
