### ISSUE TITLE
Set Up Integration Suite Trial

### ISSUE THREAD

**Issue by SoumyaGyanapnor** [sap-tutorials/Tutorials#23197]
Hi,

Tutorials: https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html
Issue: Could not create service instances/key

Here, observation: In STEP 3, in the Integration Suite home page When i tried to Add the Capabilities, API Management Capability Activation is failing with the following error.

![Not_Activated_APICapability](https://github.com/sap-tutorials/Tutorials/assets/124772107/b7fcbdd4-b6ec-436a-8c1e-a90a4efa77f7)

When i Reactivated again by that time it got activated.

![Activated ](https://github.com/sap-tutorials/Tutorials/assets/124772107/62c5b67a-3d57-40a9-97e2-cec3c1fef782)

And when i proceeded with the further step, in STEP 4 , Assigning Roles and create service instances using Booster step, From the Booster i Enabled Integration suite by clicking  the Start and  configured the subaccount and Selected Activated Capabilities and when i clicked on finish button then "Assigning Role Collection" and "Assigning Service Quotas" were Activated but Creating Service Instances got failed with the following error:
Error APIMGT100: Activation of API Management capability has failed. Please try again later. If the issue persists, please send your application URL and details of the error message tocpitrialfeedback@sap.com

Error Details:
Could not create service instance/key as the capability is still not activated.
Creating a service instance for the entitlements below failed:
it-rt, Plan : integration-flow
it-rt, Plan : api
Creating service key(s) for the service instances(s) below failed:
it-rt, Plan : integration-flow
it-rt, Plan : api
Solution:
Please wait for the capability to be activated and then execute the booster.

![Instance_Creation_failed](https://github.com/sap-tutorials/Tutorials/assets/124772107/fa5f6ef1-5106-4d18-9266-7c676955d827)

Labels:
Landscape Labels - trail2
Sprint Label: SCPTest-2309A
Scenario Label: SCPTest-cloudin
Priority: High

Thanks & Regards,
Soumya Gyanapnor

**Comment by BaskarThambiayah** [comment]
Issue is resolved. Hence closing this ticket.
