### ISSUE TITLE
Deployment of SAP Fiori App to SAP BTP failed

### ISSUE THREAD

**Issue by BaskarThambiayah** [sap-tutorials/Tutorials#23199]
Hi Colleagues,

Tutorial link: https://developers.sap.com/tutorials/appstudio-fioriapps-mta-build-deploy.html

While executing **Step 3 Deploy the Application** of this tutorial in US Region, the deployment of Fiori App to SAP BTP is failing. I tried executing this scenario multiple times, but it is failing at the deployment stage.

![image](https://github.com/sap-tutorials/Tutorials/assets/60343237/a18efe30-11c7-4f69-ba7c-c006ad872c98)

Kindly check this issue.

Labels to be added:
Scenario label: SCPTest-fbizapp
Sprint Label: SCPTest-2309A
Landscape Label: Trial2 (US Region)
Priority: High

Many thanks & regards,
Baskar

**Comment by birgits22** [comment]
Hi Baskar,

thanks a lot for testing. AS announced via email: please try to check your entitlements. This issue can be caused my a missing service plan. It can be resolved by adding the following service plan (under entitlements):
Authorization and Trust Management Service (technical name XSuaa) . Add all 4 entries. When done the entry should look like this:

![image](https://github.com/sap-tutorials/Tutorials/assets/118737703/d1939795-c3b9-4bb2-a0f6-eb7cc743ab73)

Best regards,
Birgit

**Comment by BaskarThambiayah** [comment]
Hi Birgit,
Many thanks for looking into this issue and the update.
Actually, I always create a new Global Account and subaccount in that Global Account for a particular region and do the test.
Since i had already deleted my Global Account, I tried creating a new account and did this test. Now the deployment is successful and it is working fine.

Request you to update the tutorial with the couple of things needs to be verified to avoid the issue in case if the end user creates a subaccount in the existing Global Account which you mentioned in the email communication of this ticket.
1. Cloud Foundry is not enabled by default and a dev space is needed (I will add a remark that this might need to be done.)
2. The SAP Business Application Studio entitlement needs to be added. Only then it is possible to find it in the service market place. (I will add a remark to the tutorial.)
3. Same for SAP Build workzone.
4. Also, add the following service plan (under entitlements):
Authorization and Trust Management Service (technical name XSuaa) This should look as follows:
![image](https://github.com/sap-tutorials/Tutorials/assets/60343237/8d556850-3f76-49ca-a779-e4ca0995f347)

Many thanks & regards,
Baskar

**Comment by birgits22** [comment]
Hi Baskar,

Many thanks for your feedback. I will add the needed remarks to the tutorial.

Best regards,
Birgit
