### ISSUE TITLE
Create an API Proxy

### ISSUE THREAD

**Issue by christian-noack-diva-e** [sap-tutorials/Tutorials#23209]
Tutorials: https://developers.sap.com/tutorials/hcp-apim-create-api.html
--------------------------

I don't have the quick actions shown in Step 3 and also Step 2 looks different.
![image](https://github.com/sap-tutorials/Tutorials/assets/20838442/efd24e8f-590b-4787-b869-6037a2c24044)

**Comment by jmmargo** [comment]
Karunaharan, althouh you are not the author of this tutorial, you seem to be involved in the group in which this appears.  Can you help me identify the person now responsible for this tutorial?  Thank you.

**Comment by Karunaharan** [comment]
Hi @Kakabira 
Would you be able to update the tutorial? Looks like some screenshots are outdated.
