### ISSUE TITLE
Add SAP HANA Support to Your Project

### ISSUE THREAD

**Issue by je-hal** [sap-tutorials/Tutorials#23208]
Tutorials: https://developers.sap.com/tutorials/btp-app-hana-app-setup.html
--------------------------

The tutorial says to run the following command:

```
cds add hana --for production
```

Then two lines below the tutorial says:
![image](https://github.com/sap-tutorials/Tutorials/assets/34343894/887df776-5ae8-4361-b376-8afd7db599b4)

That's a different command (omitting `--for production`). Why am I that persnickety? Because I checked file `package.json` and the result does not match exactly what is shown in the tutorial. This is what I get for `cds`:

```
  "cds": {
    "requires": {
      "[production]": {
        "db": "hana"
      }
    }
  }
```

So do I need to use another command or is the tutorial outdated and the inserted lines in `package.json` should be different?

**Comment by smahati** [comment]
Hi @je-hal,

Thanks for the issue. I'll take a look if we have some out of date stuff there. What you have looks right.

Best regards,
Maha

**Comment by smahati** [comment]
Hi,

This was fixed, so I'll close this issue now, sorry for updating the issue.

Best regards,
Mahati
