### ISSUE TITLE
Create the CDS Data Model for the SAP SuccessFactors Extension

### ISSUE THREAD

**Issue by DanSchlachter** [sap-tutorials/Tutorials#23203]
Tutorials: https://developers.sap.com/tutorials/cap-extend-sfsf-data-model.html
--------------------------

Hi,

in the tutorial step `Load initial test data` you manually create all the csv files.
Did you know, that there is a command `cds add data` that creates all these files as a convenience function?

Thanks
Daniel

**Comment by jmmargo** [comment]
Alessandro, can you please assist this user?

**Comment by ale-biagi** [comment]
Please, take a look at the year this tutorial was published.
By that time the command you mention (as many others) was not available in the cds CLI.
