### ISSUE TITLE
Prepare Your Development Environment for CAP

### ISSUE THREAD

**Issue by je-hal** [sap-tutorials/Tutorials#23205]
Tutorials: https://developers.sap.com/tutorials/btp-app-prepare-dev-environment-cap.html
--------------------------

The description of the directory structure in step 12 could be much simpler, maybe like this:

***
For the tutorial, you need a directory to develop the app and you need access to the template files. We recommend creating the following directory structure:

| **Directory** |  **Contents** |
|:---|:---|
|  `t-root`  |  Tutorial root directory. Feel free to choose any other directory name. |
| `t-root/tutorial` | The directory containing the clone of the tutorial repository (including the templates). |
| `t-root/cpapp` | The directory for the application you build. |

***

At the moment, the table of the step also includes a directory `t-root/tutorial/templates` and the table somehow suggests to create that one as well. However, in the next step you are supposed to do `git clone https://github.com/SAP-samples/cloud-cap-risk-management tutorial`, which creates subdirectory `templates`. If someone had created that directory in the step before (like me), this will cause an error.

**Comment by smahati** [comment]
Hi @je-hal,

Agreed that the instruction to create it is wrong, I'll make a fix.

Best regards,
Maha

**Comment by smahati** [comment]
The tutorial has been updated ([Reference](https://github.com/sap-tutorials/Tutorials/pull/23267/files#diff-c8b8f08c4f28fd5eed547cc91cb130990059ce6db147b02a05a6bee12b637fbf).

Best regards,
Maha

**Comment by je-hal** [comment]
Hi Maha,

that's much clearer, thank you. 👍

Best regards,
Jens
