### ISSUE TITLE
Create an SAP Fiori Elements-Based UI

### ISSUE THREAD

**Issue by je-hal** [sap-tutorials/Tutorials#23206]
Tutorials: https://developers.sap.com/tutorials/btp-app-create-ui-fiori-elements.html
--------------------------

In step 2 (_Generate the UI with an SAP Fiori elements template_), substep 9/10, it is said that I should leave the default values for all other settings, but for the _Minimum SAPUI5 version_, there is no default version. Users actively need to choose one:

![image](https://github.com/sap-tutorials/Tutorials/assets/34343894/3ac1fd2f-ae2f-419f-baf2-3d3450dd1943)

**Comment by smahati** [comment]
Hi @je-hal ,

I'll check with the fiori team and update it. I would say you should select the latest version for now :).

Best regards,
Maha

**Comment by smahati** [comment]
this has been fixed.

Best regards,
Maha
