### ISSUE TITLE
Prepare for SAP BTP Development: Entitlements couldn't be checked

### ISSUE THREAD

**Issue by je-hal** [sap-tutorials/Tutorials#23204]
Tutorials: https://developers.sap.com/tutorials/btp-app-prepare-btp.html
--------------------------

When checking the entitlements (I use a trial account), some plans listed in the tutorial are not shown in the cockpit. The unit column is missing completely and the linked document (_SAP Business Technology Platform Service Description Guide_) does not contain information for all services (e.g., nothing about the HTML5 Application Repository service).

![image](https://github.com/sap-tutorials/Tutorials/assets/34343894/9bde4afb-d7cd-41f6-bcc0-5dfdd565d902)

**Comment by smahati** [comment]
Hi,

I'm working on the fixes. Sorry for the delay.

Best regards,
Mahati

**Comment by smahati** [comment]
Hello,

closing as the tutorials are deprecated. please open a new issue if you need further support.

Best regards,
Mahati
