### ISSUE TITLE
Use a Local Launch Page

### ISSUE THREAD

**Issue by je-hal** [sap-tutorials/Tutorials#23207]
Tutorials: https://developers.sap.com/tutorials/btp-app-launchpage.html
--------------------------

In step 3, I don't understand why the first answer of the quiz is correct.

The note before tells me that `cds watch` would replace the default page if the file name is `index.html`. That's we choose `launchpage.html` here, to create an additional individual page (right?).

The problem with the first answer may be that readers don't know what "it" refers to, `launchpage.html` or `index.html`. My point is that by choosing `launchpage.html` we in fact prevent that the default page is replaced, so the first answer didn't seem right to me.

A possible answer could be: "To avoid that `cds watch` replaces the default page".

**Comment by smahati** [comment]
Hi @je-hal,

Agreed that it's confusing, I'll improve it.

Best regards,
Maha

**Comment by smahati** [comment]
this tutorial has been removed so, I'll close this issue.
