### ISSUE TITLE
Missing links in 2 tutorials

### ISSUE THREAD

**Issue by aancos** [sap-tutorials/Tutorials#23216]
Hi all,

In mission “[Extend Your SAP HANA On-Premise to SAP HANA Cloud, SAP HANA Database”,](https://developers.sap.com/mission.hana-cloud-extend-on-premise.html) group [“Get Ready to Extend to the Cloud”](https://developers.sap.com/group.hana-cloud-extend-1-get-ready.html), I think that tutorials 1&3 are not linked well:
https://developers.sap.com/tutorials/hana-cloud-mission-extend-01.html
https://developers.sap.com/tutorials/hana-cloud-mission-extend-03.html

Thanks you for your work.

Regards.

**Comment by danielva** [comment]
Thank you for your feedback.  I hope this issue has already been addressed.  I was able to open the two indicated tutorials from the group page.
