### ISSUE TITLE
Learn About Selected CAP Conventions

### ISSUE THREAD

**Issue by frvdp** [sap-tutorials/Tutorials#23217]
Tutorials: https://developers.sap.com/tutorials/btp-cap-beginner-golden-path.html
--------------------------

I'm not an expert and just following the recepy ...

In the first step : tests.http
I had to change GET http://localhost:4004/catalog/Books?
to GET http://localhost:4004/odata/v4/catalog/Books?

I do not recall choosing V4 Odata anywhere ? default selection ?

**Comment by renejeglinsky** [comment]
Hi,
Yes, this is a new default since the last major release. I fixed the tutorial with the linked PR. Thanks for opening the issue and sorry for reacting that late.

All the best
René
