### ISSUE TITLE
Sign up for an SAP HANA Cloud Trial account

### ISSUE THREAD

**Issue by virengupta30** [sap-tutorials/Tutorials#23215]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-mission-trial-1.html
--------------------------

Why the following option to the question "Which of the aspects about the SAP HANA Cloud trial are correct?" is **_**incorrect**_**?
- You can upgrade your trial account to a paid version.
![image](https://github.com/sap-tutorials/Tutorials/assets/47381580/318c40fb-7aa3-45dd-94f3-900e2f867c55)

**Comment by danielva** [comment]
With a free tier SAP HANA Cloud instance, it is possible to directly upgrade to a paid instance as shown step  8 of [Provision an Instance of SAP HANA Cloud, SAP HANA Database](https://developers.sap.com/tutorials/hana-cloud-mission-trial-3.html).  With a trial account, you would need to manually create a new non trial instance and move your tables and data manually.

Hope that helps,
Dan v
