### ISSUE TITLE
Set Up API Management from Integration Suite

### ISSUE THREAD

**Issue by seVladimirs** [sap-tutorials/Tutorials#23213]
Tutorials: https://developers.sap.com/tutorials/api-mgmt-isuite-initial-setup.html
--------------------------
In Step 1's quiz there is type Integration.Provisioner but should be Integration_Provisioner
<img width="1782" alt="image" src="https://github.com/sap-tutorials/Tutorials/assets/9819889/6bb58d42-dbb9-47d1-8f2a-c06f0e666a9f">

**Comment by jmmargo** [comment]
Kasturi, can you please assist with this user's feedback?  Thank you.

**Comment by Kakabira** [comment]
@seVladimirs: I have replaced Integration.Provisioner with Integration_Provisioner.
