### ISSUE TITLE
Enable Services for Sales Tracker App

### ISSUE THREAD

**Issue by abiskop** [sap-tutorials/Tutorials#23223]
Tutorials: https://developers.sap.com/tutorials/cp-apim-sales-tracker-services-enable.html
--------------------------

Write here how you think we can improve the tutorial ...

Hi, the tutorial's first step is to access "Neo Trial", which has been sunset and does not exist anymore. Hence the tutorial is useless in its current form and needs to be either redone or removed.

**Comment by jmmargo** [comment]
Karunaharan, can you please address this user's feedback?  Thank you.

**Comment by Karunaharan** [comment]
Hi @shilpavij 
Would you be able to provide the alternative steps to complete this tutorial mission in Integration Suite?

**Comment by jmmargo** [comment]
This tutorial will soon be deprecated.  Thank you.
