### ISSUE TITLE
Consume SOAP Web Services in SAP Cloud Application Programming Model (CAP)

### ISSUE THREAD

**Issue by swadhinbharat** [sap-tutorials/Tutorials#23226]
Tutorials: https://developers.sap.com/tutorials/cap-soap-service.html
--------------------------

I understand connecting to SOAP service residing in the On-Prem system is not in the scope of this tutorial but is it possible to add notes or something as a guidance or workaround in case someone is working on similar requirement? There are plenty of SOAP services which we need to expose to BTP platform for consumption on our CAP JS project but not getting any official guidance or best practice.

**Comment by ale-biagi** [comment]
https://help.sap.com/docs/connectivity
https://help.sap.com/docs/connectivity/sap-btp-connectivity-cf/cloud-connector
