### ISSUE TITLE
BTP-CAP-BEGINNER-GOLDEN-PATH [outdated screen] 

### ISSUE THREAD

**Issue by hereAnshul** [sap-tutorials/Tutorials#23225]
In the [Learn About Selected CAP Conventions](https://developers.sap.com/tutorials/btp-cap-beginner-golden-path.html) beginner's path.
Shouldn't the contents of the tests.http be as follows,
```
# Browse Books as any user
GET http://localhost:4004/odata/v4/catalog/Books?
  # &$select=title,stock
  # &$expand=currency
  # &sap-locale=de
```
which gives the following correct output,
![image](https://github.com/sap-tutorials/Tutorials/assets/36290935/461586dd-a90d-4ffd-ba20-8a81599bee6c)

instead of 
```
# Browse Books as any user
GET http://localhost:4004/catalog/Books?
  # &$select=title,stock
  # &$expand=currency
  # &sap-locale=de
```
as the current one results in the following,
![image](https://github.com/sap-tutorials/Tutorials/assets/36290935/070b22cc-478e-43d2-9b8c-3571baac9f01)

I think the example and the screengrab need to be corrected [here](https://github.com/sap-tutorials/Tutorials/blob/master/tutorials/btp-cap-beginner-golden-path/request_1.png)

**Comment by renejeglinsky** [comment]
Hi @hereAnshul ,

I fixed this last week. Thanks for providing your feedback and findings here!

All the best,
René
