### ISSUE TITLE
Cannot see CSV data or even download it.

### ISSUE THREAD

**Issue by harshilpatel0** [sap-tutorials/Tutorials#23220]
content of following file is not downloading: 
https://github.com/SAPDocuments/Tutorials/blob/master/tutorials/hana-cloud-calculation-view-differential-privacy/salarydata.csv

and also this link is not opening in my browser: 
https://raw.githubusercontent.com/sap-tutorials/Tutorials/master/tutorials/hana-cloud-calculation-view-differential-privacy/salarydata.csv

Link 1:
![image](https://github.com/sap-tutorials/Tutorials/assets/146342133/3453bd0b-184e-4173-b278-39370834813a)

Link 2:
![image](https://github.com/sap-tutorials/Tutorials/assets/146342133/54404d67-1235-488f-8f3a-e091d3507f1d)

**Comment by jmmargo** [comment]
Thomas, can you please assist with this user's feedback?
