### ISSUE TITLE
Learn About Selected CAP Conventions

### ISSUE THREAD

**Issue by ElisabethPe** [sap-tutorials/Tutorials#23232]
Tutorials: https://developers.sap.com/tutorials/btp-cap-beginner-golden-path.html
--------------------------

In Step 5 the path for the tests.http in my case was POST http://localhost:4004/odata/v4/buy/Orders
The /odata/v4/ part is missing in the code to copy

The same applies for Step 6

**Comment by renejeglinsky** [comment]
This will be fixed with the linked PR. Thanks for opening the issue.

All the best,
René
