### ISSUE TITLE
Create a CAP Project with SAP Business Application Studio

### ISSUE THREAD

**Issue by ElisabethPe** [sap-tutorials/Tutorials#23230]
Tutorials: https://developers.sap.com/tutorials/btp-cap-beginner-bas-wizard.html
--------------------------

In Step 6 there is a mistake in the copyable text for my.bookshop-Books.csv.
The fourth column should be named author_ID (singular). Otherwise cds deploy --to sqlite throws an error.

**Comment by renejeglinsky** [comment]
This will be fixed with the linked PR. Thanks for opening the issue.

All the best,
René
