### ISSUE TITLE
Use Pre-Trained Tensorflow Models with a GPU in SAP AI Core

### ISSUE THREAD

**Issue by z-mvg** [sap-tutorials/Tutorials#23257]
Tutorials: https://developers.sap.com/tutorials/ai-core-tensorflow-byod.html
--------------------------

The link - \
"You have [set up your Git Repository with SAP AI Core](https://help.sap.com/viewer/808d9d442fb0484e9b818924feeb9add/LATEST/en-US/3269092e37d141a293f0dbd7eaafc829.html)" \
is not reachable.

**Comment by gianfranco-s** [comment]
If anyone gets stuck with this, the link should be: https://developers.sap.com/tutorials/ai-core-helloworld.html

**Comment by jmmargo** [comment]
Dhrubajyoti, can you please ensure the link is corrected in the tutorial?  Thank you.

**Comment by gianfranco-s** [comment]
It is not. I get redirected to a `page-not-found`

**Comment by jmmargo** [comment]
The link is now updated.  Thank you.
