### ISSUE TITLE
Create an SAP Fiori Elements-Based UI

### ISSUE THREAD

**Issue by rohithch21** [sap-tutorials/Tutorials#23251]
Tutorials: https://developers.sap.com/tutorials/btp-app-create-ui-fiori-elements.html
--------------------------

There is a discrepancy in what the tutorial suggests vs what actually happens. 

Tutorial says, "By default, the header info is not editable. Hence, you’ll be able to fill in data in the main group fields Mitigation, Priority, and Impact, but won’t be able to fill data in any of the header fields Title or Description."

In my fiori app, "editableHeaderContent" property in manifest is set to _false_. Yet I am able to edit Header Content. Please let me know if I am missing something or this is a bug from Fiori Elements. 
<img width="392" alt="image" src="https://github.com/sap-tutorials/Tutorials/assets/57070779/29320501-0940-4ea7-8028-2b2c3c95d523">

<img width="908" alt="image" src="https://github.com/sap-tutorials/Tutorials/assets/57070779/c3340a7d-325c-4ad7-ba05-4a26cc2c2eb9">

Best Regards,
Rohith C H

**Comment by jmmargo** [comment]
Mahati, please respond to the feedback.  Thank you.

**Comment by smahati** [comment]
Hi,

Sorry that this issue was missed, do you still need support? The difference could have been a bug in a minor version of Elements.

Best regards,
Mahati
