### ISSUE TITLE
Create a CAP Project with SAP Business Application Studio

### ISSUE THREAD

**Issue by MurkuteNidhi** [sap-tutorials/Tutorials#23253]
Tutorials: https://developers.sap.com/tutorials/btp-cap-beginner-bas-wizard.html
--------------------------

As part of prerequisite user must complete [Set Up SAP Business Application Studio for Development](https://developers.sap.com/tutorials/appstudio-onboarding.html) but its not mentioned what type of dev space one should create. Please add this step accordingly.
Because as part of this tutorial its not mentioned about dev space creation in SaaS app.

Step3: With new UI change the run configuration steps have been changed? Because these steps could not find in tutorial.

**Comment by raz-korn** [comment]
Hi @MurkuteNidhi ,

The type of required dev space is mentioned in the Prerequisites section:

![image](https://github.com/sap-tutorials/Tutorials/assets/6040433/142b7a5f-e704-43df-a0a3-9f5a085dcd71)

@renejeglinsky : you may want to emphasize this.

Regards - Raz
