### ISSUE TITLE
Learn About Selected CAP Conventions

### ISSUE THREAD

**Issue by MurkuteNidhi** [sap-tutorials/Tutorials#23255]
Tutorials: https://developers.sap.com/tutorials/btp-cap-beginner-golden-path.html
--------------------------

As mentioned in prerequisite one has to execute [Help Thomas Get Started with SAP HANA](https://developers.sap.com/tutorials/hana-trial-advanced-analytics.html) for HANA setup. And it is observed that in this tutorial HANA Cloud tools subscription is provisioned but there is no step to add required role collections to the user.
Please update it accordingly.

**Comment by renejeglinsky** [comment]
Hi @MurkuteNidhi ,

Do you refer to step 4.6 when you (optionally) enable the _SAP HANA Performance Tools_?

**Comment by renejeglinsky** [comment]
Hi @MurkuteNidhi ,

I'll close this issue for now. If this becomes important again, feel free to comment or reopen.
