### ISSUE TITLE
Set Up API Management from Integration Suite

### ISSUE THREAD

**Issue by franzimickey** [sap-tutorials/Tutorials#23269]
Tutorials: https://developers.sap.com/tutorials/api-mgmt-isuite-initial-setup.html
--------------------------

Write here how you think we can improve the tutorial ...

Hi colleagues,
I am executing tutorial "Set Up API Management from Integration Suite"
During step 5, I don't see an option Settings --> API's.
Could be that this is because of my trial BTP sub account settings. It would help me (and probably others) if it could be pointed out in the tutorial that the step might not be possible for trial accounts and is optional (if that applies) for the success of the tutorial.
Thanks and best regards,
Franziska

**Comment by anz-sapfico** [comment]
Hi Franziska
Are you still looking for a response on this? Have you figured it out?

**Comment by franzimickey** [comment]
Hi, thanks for your message. I tried the whole tutorial again today and now I found the Settings --> APIs. Thanks for checking back with me! Have a great day!

**Comment by franzimickey** [comment]
Yes, I am still looking into it. Somehow, I see Settings --> API's, but only for one moment. After restarting the Integration Suite (like described in step 4), the menu changes completely and I see this one: 
![image](https://github.com/sap-tutorials/Tutorials/assets/74303944/38190243-2a62-4a6b-bb9d-71e8f77dde99)
Could you please help me out? What am I doing wrong?

**Comment by anz-sapfico** [comment]
@franzimickey 
hope you are well !!  You need to assign the required roles to your User ID. Your screenshot looks a bit different to mine, however though, it feels like you have not assigned the relevant roles as per the Tutorial. Also after you have assigned the roles, you need to log out and log back in. With the Integration Suite, it also takes atleast a quarter of an hour sometimes before all the accesses are provisioned, depending on what you have activated. The tutorial also has an API role related question to point people to assign the newly created roles, once the services are provisioned. (see image below)
![image](https://github.com/sap-tutorials/Tutorials/assets/151246871/e7f0d14e-be34-4f0e-8c42-fecd47872bd7)

 As you keep activating the services in the Integration Suite, it starts showing roles in the BTP Cockpit. Can you check, if you have assigned these additional roles to your User Id please?

![WhatsApp Image 2023-11-26 at 19 12 54_f110325b](https://github.com/sap-tutorials/Tutorials/assets/151246871/4a4cde25-50ab-4c0b-99fa-184ec0eb493b)
Post assigning the roles and refreshing the Integration Suite services, I see the below screen, ready for API testing.
![image](https://github.com/sap-tutorials/Tutorials/assets/151246871/69bce1a7-fb78-4939-beb3-88e577fb1922)

**Comment by franzimickey** [comment]
Thanks @anz-sapfico , after assigning the role, I see the same screen you posted above. Thanks a lot! Maybe I was irritated because it somewhat looks different from the description in the tutorial. ;-)

**Comment by franzimickey** [comment]
@anz-sapfico , sorry , I have another question: How do I get from this view 
![image](https://github.com/sap-tutorials/Tutorials/assets/74303944/cd2d32a3-354a-4d6e-92dd-cfb7c2fe2c78)
to the **Configure the API Management Service** page to configure everything (step 5 of the tutorial)?

**Comment by anz-sapfico** [comment]
Hi Franziska

The step 5 was a part of the original setup of the API service. This was completed when you activated the capability in the Integration Suite.

If you are able to see the same screens as I do, the setup is complete.

**Comment by jmmargo** [comment]
Kasturi, can you please respond to this issue?  Thank you.

**Comment by Kakabira** [comment]
@jmmargo: I think @anz-sapfico has already clarified Franziska's queries.
