### ISSUE TITLE
Ingest Live Data into your House Price Predictor with SAP AI Core

### ISSUE THREAD

**Issue by z-mvg** [sap-tutorials/Tutorials#23268]
Tutorials: https://developers.sap.com/tutorials/ai-core-data.html
--------------------------
In Step 15: Use artifacts with workflows using a configuration, the Postman documentation does not come up as a tab. Instead, it comes withing the AI launchpad text with the following text: 
```text
[OPTION BEGIN [Postman]]
...
...
```
And in fact, the syntax error goes into the next step 16 and step 17 as well and there we see leftovers from previous steps:

```text
[OPTION END]

[OPTION BEGIN [SAP AI Core SDK]]
```

**Comment by jmmargo** [comment]
Dhrubajyoti, can you please respond to this user's feedback?  Thank you.

**Comment by sharmaneeleshsap** [comment]
Hi @jmmargo, @z-mvg,

Thanks for the feedback. 
I'm unable to replicate the issue. Seems like it has been fixed - 

![image](https://github.com/user-attachments/assets/5efa698a-30be-4863-aeee-06cc3af84244)

Verified for other steps as well.

Regards,
Neelesh.

(cc: @dhrubpaul)
