### ISSUE TITLE
Identity Access Management in SAP S/4HANA Cloud

### ISSUE THREAD

**Issue by anandSAP** [sap-tutorials/Tutorials#23277]
Create a new tutorial for IAM in S/4HANA Cloud. Similar to https://github.com/SAP-samples/teched2023-DT167/tree/main

**Comment by jmmargo** [comment]
Are you referring to a specific tutorial?  Documents in the SAP-samples organization are not tutorials.

**Comment by jmmargo** [comment]
I dig a little digging and our usual sources for creating tutorials do not have this in their scope.  This would have to come out of security, with whom we do not typically receive content.  Might I suggest trying to ask about this in the [SAP Community](https://community.sap.com/) with for Application developers or with the respective product group?
