### ISSUE TITLE
Expose Integration Flow Endpoint as API and Test the Flow

### ISSUE THREAD

**Issue by BaskarThambiayah** [sap-tutorials/Tutorials#23286]
Hi Colleagues,
In the sub tutorial "**Expose Integration Flow Endpoint as API and Test the Flow**" of the tutorial "**Request Product Details with an Integration Scenario**", at Step 4: **Assign policy template** and the sub step 5. After the success message is displayed, navigate to the **Design > APIs**.

Actually, it should be "After the success message is displayed, navigate to the **Configure > APIs**". Please check and correct it.

Tutorial Link: https://developers.sap.com/tutorials/cp-starter-isuite-api-management.html

Labels to be added:
Scenario Label: SCPTest-cloudin
Sprint label: SCPTest-2311A
Landscape label: trail2, trail3
Priority: High

Many thanks & regards,
Baskar

**Comment by Karunaharan** [comment]
Fixed now

**Comment by BaskarThambiayah** [comment]
Thanks @Karunaharan
