### ISSUE TITLE
Take a Tour of SAP BTP Trial

### ISSUE THREAD

**Issue by yoppieariesthio** [sap-tutorials/Tutorials#23299]
Tutorials: https://developers.sap.com/tutorials/cp-trial-quick-onboarding.html
--------------------------

On the step 5  : Navigate in the cockpit

I put the correct answer, but it's still response as false.
The question is pretty clear and easy to understand.
"Enter the first item in the left hand-side navigation of your trial Cloud Foundry global account:"

the answer is 'Account Explorer'

![2023-11-24 11_11_44-NVIDIA GeForce Overlay](https://github.com/sap-tutorials/Tutorials/assets/102799135/94cc59c5-fa84-47a3-95f3-6aaa667a161d)

**Comment by anz-sapfico** [comment]
@yoppieariesthio 
please try "subaccounts" 

The question is based on the previous version of SAP Cloud Platform. Check this image 

![image](https://github.com/sap-tutorials/Tutorials/assets/151246871/2266a72a-cac8-4f96-a28e-2dcce37c5799)

**Comment by jmmargo** [comment]
Thank you for the assist.
