### ISSUE TITLE
Build a House Price Predictor with SAP AI Core

### ISSUE THREAD

**Issue by Kai-Klatt** [sap-tutorials/Tutorials#23296]
> Tutorials: https://developers.sap.com/tutorials/ai-core-code.html
--------------------------

Hello! 

I've noticed in Step 13, the tutorial text mentions to use 

> docker upload docker.io/<YOUR_DOCKER_USERNAME>/house-price:02

However, this throws an error that upload is not a docker command. The correct version:

> docker push docker.io/<YOUR_DOCKER_USERNAME>/house-price:02 

can be seen corrected in the image right below this text. 

Hope this helps!

Cheers, Kai

**Comment by jmmargo** [comment]
Dhrubajyoti, can you please follow up on this issue?

**Comment by sharmaneeleshsap** [comment]
Hi @jmmargo , @Kai-Klatt ,

Thanks for the feedback. It has been fixed now.
Please note that it will take some time to reflect in the tutorials.

Regards,
Neelesh.

(cc: @dhrubpaul)
