### ISSUE TITLE
Consume the External Service in the UI of Your Application

### ISSUE THREAD

**Issue by gregorwolf** [sap-tutorials/Tutorials#23292]
Tutorials: https://developers.sap.com/tutorials/btp-app-ext-service-consume-ui.html

STEP 2 - Handle expands to remote entities
--------------------------

should be adjusted to make use of the new [Inferring Query Elements](https://cap.cloud.sap/docs/releases/nov23#inferring-query-elements) functionality.

**Comment by smahati** [comment]
Hello,

Sorry I didn't get back to you. As Risk Management was deprecated we don't make updates that aren't breaking changes. To prevent users from using it as a resource we added a deprecation notice to the tutorials.

Best regards,
Mahati
