### ISSUE TITLE
Add Views and Define Routes to Access Them 

### ISSUE THREAD

**Issue by anz-sapfico** [sap-tutorials/Tutorials#23301]
Tutorials: https://developers.sap.com/tutorials/sapui5-101-add-routing.html
--------------------------
@nicoschoenteich 
Write here how you think we can improve the tutorial ...
can you please provide test files and a display screensot of the folder structure. I tried to search Github for the raw tutorial files, but didn't find any. The test files help in providing a direction of the BAS generated files to the desired tutorial result.
receiving random error messages in the Google chrome console "cannot get following files"
Cannot Get appconfig/fioriSandboxconfig.json
Cannot Get test/i18n 
Cannot Get test/i18n/en_properties
Cannot GET /sap/bc/lrep/flex/settings

some screenshots below.

![image](https://github.com/sap-tutorials/Tutorials/assets/151246871/f58b74f4-a635-481b-87ea-ee1426773e0d)
![image](https://github.com/sap-tutorials/Tutorials/assets/151246871/be69050e-b536-45f0-9ef5-2df1183943da)
![image](https://github.com/sap-tutorials/Tutorials/assets/151246871/d01de0cf-4f7f-4da0-87ab-e97e788300f6)
![image](https://github.com/sap-tutorials/Tutorials/assets/151246871/ce91c327-3ed0-4ce8-a57f-cc327ebf9a55)

**Comment by nicoschoenteich** [comment]
Hi @anz-sapfico,

Thanks for providing feedback. I will add a section to the tutorial describing the generated project structure.

Regarding your errors, those are to be expected and nothing to worry about. You are missing optional configuration and translation (i18n) files (probably because you haven't added them). The flex service is only available once an application deployed and running in a productive launchpad.

Best, Nico

**Comment by nicoschoenteich** [comment]
Hi @cjbernal,
can we add a screen shot of the generated application files to this tutorial, which preceds the one this issue is referring to? https://developers.sap.com/tutorials/sapui5-101-create-project.html

**Comment by anz-sapfico** [comment]
@nicoschoenteich 
Hi Nico
Thank you for the response. The BAS is generating the below code for the i18n with a single properties file. 
I added a few empty files for fioriSandboxconfig.json and componentpreload.js files. The errors are eliminated, but I was still doubtful whether it would work. Thanks for the confirmation that these errors can be ignored.

Regarding the missing optional configuration and translation (i18n) files, are you able to add this to the tutorial as well?
The old Web IDE portal contains the screenshot and the files to validate, so it was a bit easier. Below is my structure.

![image](https://github.com/sap-tutorials/Tutorials/assets/151246871/22bf0d91-fff9-437a-a24d-d9d0c7bfa422)

**Comment by jmmargo** [comment]
Seems this was resolved.  Thank you.
