### ISSUE TITLE
Get to Know SAP Tutorials | Picture's missing Step 6

### ISSUE THREAD

**Issue by Mr-Solve** [sap-tutorials/Tutorials#23305]
Tutorials: https://developers.sap.com/tutorials/tutorial-first-steps.html
--------------------------

Picture's missing in step 6
<img width="1272" alt="Bildschirmfoto 2023-11-27 um 17 15 20" src="https://github.com/sap-tutorials/Tutorials/assets/152198163/e9406465-82ff-406c-92a6-b9b1df7577d0">

**Comment by jmmargo** [comment]
Picture has been restored.
