### ISSUE TITLE
Tutorial Page create-custom-theme.md Issue. PROD

### ISSUE THREAD

**Issue by DevRelations2** [sap-tutorials/Tutorials#23312]
Tutorial issue found: [https://github.com/sap-tutorials/Tutorials/blob/master/tutorials/create-custom-theme/create-custom-theme.md](https://github.com/sap-tutorials/Tutorials/blob/master/tutorials/create-custom-theme/create-custom-theme.md) contains invalid tags. Even though your tutorial was created, the invalid tags listed below were disregarded. Please double-check the following tags:
- tutorial:how-to

 Affected server: PROD

**Comment by jmmargo** [comment]
Issue resolved.
