### ISSUE TITLE
Prepare Your Kyma Development Environment

### ISSUE THREAD

**Issue by DanielKlt** [sap-tutorials/Tutorials#23311]
Tutorials: https://developers.sap.com/tutorials/btp-app-kyma-prepare-dev-environment.html
--------------------------

Outdated link: 
https://developers.sap.com/tutorials/btp-app-set-up-local-development.html
"In case you experience problems running the commands, check Step 2: Command Line Interpreters from [Set Up Local Development Using VS Code](https://developers.sap.com/tutorials/btp-app-set-up-local-development.html) for more details on recommended CLIs."

The link is in step 4.2

**Comment by jmmargo** [comment]
Mahati, can you please address this issue?

**Comment by smahati** [comment]
Hello,

The Kyma tutorials have been retired so I will close this issue. Sorry for the late reply, please create a new issue if you need support.

Best regards,
Mahati
