### ISSUE TITLE
Tutorial Page cp-portal-cloud-foundry-spaces-pages.md Issue. PROD

### ISSUE THREAD

**Issue by DevRelations2** [sap-tutorials/Tutorials#23316]
Tutorial issue found: [https://github.com/sap-tutorials/Tutorials/blob/master/tutorials/cp-portal-cloud-foundry-spaces-pages/cp-portal-cloud-foundry-spaces-pages.md](https://github.com/sap-tutorials/Tutorials/blob/master/tutorials/cp-portal-cloud-foundry-spaces-pages/cp-portal-cloud-foundry-spaces-pages.md) contains invalid tags. Even though your tutorial was created, the invalid tags listed below were disregarded. Please double-check the following tags:
- products>sap-business-technology-platform
- products>sap-fiori
- products>sap-build-work-zone--standard-edition

 Affected server: PROD

**Comment by jmmargo** [comment]
Issue resolved.
