### ISSUE TITLE
Use Redis in the Kyma Runtime to Store and Retrieve Data - missing Setup Mock Application prerequisite

### ISSUE THREAD

**Issue by ASRHARDING** [sap-tutorials/Tutorials#23323]
Tutorials: https://developers.sap.com/tutorials/cp-kyma-redis-function.html
--------------------------

The “[Setup Mock Application](https://developers.sap.com/tutorials/cp-kyma-mocks.html)” prerequisite link results in the message “Sorry, we couldn’t find that tutorial” from SAP Tutorials website.

There used to be a tutorial titled “Deploy Commerce Mock Application in the Kyma Runtime” (aka Setup Mock Application) which is no longer listed for mission “Build an Application in the Kyma Runtime”.

The tutorial “Deploy Commerce Mock Application in the Kyma Runtime” contents were old, screenshots and tutorial steps did not match actual BTP screens when I started the tutorial.

Is this mission still active, or is it being discontinued?

**Comment by jmmargo** [comment]
Jamie, can you please reassign this to whomever is the new owner?  Thank you.

**Comment by NHingerl** [comment]
Jamie transferred responsibility for the Kyma tutorials; assigning @grego952 instead.

**Comment by grego952** [comment]
The link works again
