### ISSUE TITLE
Set Up SAP Business Application Studio for Development

### ISSUE THREAD

**Issue by renejeglinsky** [sap-tutorials/Tutorials#23331]
Tutorials: https://developers.sap.com/tutorials/appstudio-onboarding.html
--------------------------

In the introduction, the Getting Started link seems to be outdated:

---
![image](https://github.com/sap-tutorials/Tutorials/assets/32062331/4a633be7-f12c-4669-b196-bbfe2d3c418a)
---

It just redirects to the root topic of the documentation.

**Comment by raz-korn** [comment]
Hi @ShiraManas ,
Please update the link to "[Set Up SAP Business Application Studio](https://help.sap.com/docs/bas/sap-business-application-studio/getting-started)".
Thanks - Raz
