### ISSUE TITLE
Error in Deploy Your Multi-Target Application (MTA)

### ISSUE THREAD

**Issue by SimonBurmer** [sap-tutorials/Tutorials#23340]
Tutorials: https://developers.sap.com/tutorials/btp-app-cap-mta-deployment.html
--------------------------

#### Step 4 says that users should add this to the package.json:   

"engines": {
    "node": "^16"
  }

#### But when deploying to BTP, I get the following error: 

[PollStageAppStatusExecution] [cpapp-srv] [2023-12-11T14:52:53.263526] [31;1m**ERROR**[0m Unable to install node: no match found for ^16 in [18.18.0 18.18.2 20.8.1 20.9.0] (STDOUT, STG)#

**Comment by smahati** [comment]
Hello, We have updated the minimum required version of node to be v18.

Best regards,
Maha
