### ISSUE TITLE
SAP Cloud ALM: Activate SAP Build Process Automation Monitoring

### ISSUE THREAD

**Issue by thomasalexneuhaus** [sap-tutorials/Tutorials#23349]
Tutorials: https://developers.sap.com/tutorials/sap-cloud-alm-sap-build-process-automation-1.html
--------------------------

Write here how you think we can improve the tutorial ...

Can please at this community comment, that was help full for the destination 
https://answers.sap.com/answers/13659231/view.html

**Comment by jmmargo** [comment]
The suggested content cannot be retrieved; the provided URL did not work.  If you can find the content, please reopen the issue.
