### ISSUE TITLE
Get an Account on SAP BTP to Try Out Free Tier Service Plans

### ISSUE THREAD

**Issue by mohamedyosufdeenjmh** [sap-tutorials/Tutorials#23358]
Tutorials: https://developers.sap.com/tutorials/btp-free-tier-account.html
--------------------------

In the prerequisites, there is a sentence as follows:
Note that the trial landscape offers different service plans than the free tier model for `SAP TP`, see: [Get an SAP BTP Account for Tutorials](https://developers.sap.com/tutorials/btp-cockpit-setup.html).

The letter "B" is missing from "BTP", and it must be:
Note that the trial landscape offers different service plans than the free tier model for `SAP BTP`, see: [Get an SAP BTP Account for Tutorials](https://developers.sap.com/tutorials/btp-cockpit-setup.html).

**Comment by jmmargo** [comment]
Thank you.  Spelling has been corrected.
