### ISSUE TITLE
Deploy CAP with SAP HANA Cloud project as MTA

### ISSUE THREAD

**Issue by swamyudayagiri** [sap-tutorials/Tutorials#23351]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-cap-deploy-mta.html
--------------------------

Please add the below instruction to update the xsuaa instance after adding the new redirect urls of deployed app

cf update-service MyHANAApp-auth -p application -c xs-security.json

**Comment by jung-thomas** [comment]
I don't see why we would add a manual update since deploying the MTA would update or create the service.
