### ISSUE TITLE
Get an Account on SAP BTP to Try Out Free Tier Service Plans

### ISSUE THREAD

**Issue by CimermanDenis** [sap-tutorials/Tutorials#23360]
Tutorials: https://developers.sap.com/tutorials/btp-free-tier-account.html
--------------------------

I am afraid the best you can do now is to retire the tutorial, because the Free tier for BTP is not available for individuals anymore.

**Comment by jmmargo** [comment]
@AnnikaGonnermann @Madeline-Schaefer 
Does this tutorial need to be retired based on the comment above?

**Comment by AnnikaGonnermann** [comment]
Hey @CimermanDenis - thank you for your feedback. We've added a note stating "This tutorial helps you to sign an enterprise account with SAP that includes services with free service plans." For now, we are going to keep it for enterprise accounts.

Best
Annika
