### ISSUE TITLE
Deploy a CAP Business Service to SAP Business Technology Platform

### ISSUE THREAD

**Issue by gregorwolf** [sap-tutorials/Tutorials#23369]
Tutorials: https://developers.sap.com/tutorials/cap-service-deploy.html
--------------------------

Hi @renejeglinsky,

the last sentence of [STEP 1 Enhance project configuration for production](https://developers.sap.com/tutorials/cap-service-deploy.html#e8e449ac-f6db-48ef-a51d-4d334d421800) reads:

> Don’t edit the gen/db/package.json file.

but as no mbt build was executed until this step the gen/db folder shouldn't exist. I would suggest to remove it or mention after the mbt build that nothing in the gen/ folder should be edited.

Best Regards
Gregor

**Comment by renejeglinsky** [comment]
Hi @gregorwolf ,

yes, you're absolutely right. Thanks a lot for your hint! :)
I'll remove this sentence.
