### ISSUE TITLE
Prepare User Authentication and Authorization (XSUAA) Setup

### ISSUE THREAD

**Issue by mohamedyosufdeenjmh** [sap-tutorials/Tutorials#23368]
Tutorials: https://developers.sap.com/tutorials/btp-app-prepare-xsuaa.html
--------------------------

### Step 2: Roles and scopes

**Existing sentence:**
For example, there could a role “Editor” consisting of the “Read” and “Write” scopes, while the role “Viewer” consists only of the “Read” scope.

**Proposed change:**
For example, there could `be` a role “Editor” consisting of the “Read” and “Write” scopes, while the role “Viewer” consists only of the “Read” scope.

**Comment by smahati** [comment]
Hey,

sorry for the late reply. I'll fix the typo, thanks!

Best regards,
Mahati

**Comment by mohamedyosufdeenjmh** [comment]
Thank you!

**Comment by smahati** [comment]
Hello,

closing as the tutorials are deprecated. please open a new issue if you need further support.

Best regards,
Mahati
