### ISSUE TITLE
VS Code Toolkit setup missing

### ISSUE THREAD

**Issue by karimmohraz** [sap-tutorials/Tutorials#23362]
Tutorials: https://developers.sap.com/tutorials/ai-core-vs-code-toolkit.html
--------------------------

Step 10 of Tutorial jumps right into VS Code Toolkit usage.
I am missing the VS Code setup part. Where to download, how to install and configure for AI Core.
If there is a separate tutorial, plz link it here.
thnx

**Comment by jmmargo** [comment]
Dhrub, can you please address this user's feedback?  Thank you.

**Comment by sharmaneeleshsap** [comment]
Hi @jmmargo, @karimmohraz 

Thanks for the feedback. The link to set up VS Code Toolkit has been hyperlinked in the prerequisites section of the tutorial.

Regards,
Neelesh
