### ISSUE TITLE
Feedback for Tutorial Deploy a Node.js Application in the Kyma Runtime

### ISSUE THREAD

**Issue by liangxusap** [sap-tutorials/Tutorials#23365]
Tutorials: https://developers.sap.com/tutorials/deploy-nodejs-application-kyma.html
--------------------------

Write here how you think we can improve the tutorial ...

Hello Tia

I am following the tutorial, and in step 7, in the yaml file, i use the same for below to create a network policy:
but app is not able to access, i cross checked and found in my kyma dashboard, the label of istio-system is kubernetes.io/metadata.name: istio-system, not name: istio-system, so is it possible to mention, user to check the label of namesapce and change accordingly?

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  labels:
    release: multitenancy
  name: multitenancy
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: istio-system
      podSelector:
        matchLabels:
          app: istio-ingressgateway
  podSelector:
    matchLabels:
      release: multitenancy
  policyTypes:
  - Ingress

**Comment by jmmargo** [comment]
Tia, can you please respond to the user's comments.  Thank you.

**Comment by TiaXu1122** [comment]
@liangxusap Thanks for your suggestion. I have create a pull request to adapt to kyma in trial account.
