### ISSUE TITLE
Set Up SAP Fiori Tools in Your Development Environment

### ISSUE THREAD

**Issue by matz3** [sap-tutorials/Tutorials#23361]
Tutorials: https://developers.sap.com/tutorials/fiori-tools-vscode-setup.html
--------------------------

In step 3, it is described to install the extension `SAP Fiori tools - Extensions Pack`.
However, it is called `SAP Fiori tools - Extension Pack` (without **s**).

**Comment by jmmargo** [comment]
Thank you.  This has been corrected.
