### ISSUE TITLE
Add Authentication and Authorization to the Application

### ISSUE THREAD

**Issue by darmiel** [sap-tutorials/Tutorials#23372]
Tutorials: https://developers.sap.com/tutorials/cp-cap-java-security-local.html
--------------------------

Hi! The quiz in Step 3:

> **Which user has the administrator role?**
> - [ ] Klaus Sussard
> - [ ] Mia Bonnellac
> - [ ] Sabine Autumnpi

Should be moved to Step 4 as the answer cannot be answered in Step 3 (the required information for this quiz is in step 4)

**Comment by renejeglinsky** [comment]
Thanks @darmiel ! You're totally right, I missed to move that. I'll fix that immediately. Thanks for caring about our content and opening this issue! :)
