### ISSUE TITLE
Create Database Artifacts Using Core Data Services (CDS) for SAP HANA Cloud

### ISSUE THREAD

**Issue by MissileRBM** [sap-tutorials/Tutorials#23387]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-cap-create-database-cds.html
--------------------------

Step 2 pint 2 ERROR, correct the I code snippet:

`using app.interactions from '../db/interactions';`

change it with

`using app.interactions from '../db/src/interactions';`

# the path is **./db/src**!!!

**Comment by jmmargo** [comment]
Thomas, can you please respond to this user's feedback?

**Comment by jung-thomas** [comment]
Actually not it shouldn't be ./db/src. it should be /db.  Look back at step 1.1.  We say to create the file in ./db not ./db/src.  ./db/src is for HANA native artifacts.  The CDS files should go into the /db folder.
