### ISSUE TITLE
Build a House Price Predictor with SAP AI Core

### ISSUE THREAD

**Issue by louenas** [sap-tutorials/Tutorials#23385]
Tutorials: https://developers.sap.com/tutorials/ai-core-code.html
--------------------------
Build a House Price Predictor with SAP AI Core
STEP 13

docker upload docker.io/<YOUR_DOCKER_USERNAME>/house-price:02

instead of upload it should be push as indicated in the screenshot

**Comment by jmmargo** [comment]
Dhrub, please respond to the user's feedback.

**Comment by sharmaneeleshsap** [comment]
Hi @jmmargo, @louenas 

The tutorial has been updated. The commands should work as per requirements now.

Regards,
Neelesh

(cc: @dhrubpaul)
