### ISSUE TITLE
Use Your SAP S/4HANA Cloud Service for Your Deployed CAP Application

### ISSUE THREAD

**Issue by dmartino** [sap-tutorials/Tutorials#23403]
Tutorials: https://developers.sap.com/tutorials/btp-app-ext-service-s4hc-use.html
--------------------------

Show how to create json representing the business partner service. In this example it is tutorial/templates/ext-service-s4hc-use-service/bupa-service-config.json. Unfortunately there is no information about where to get the list of outbound services dfined by the communication scenarios. The text in the tutorial states that "You can check the details of those scenarios in the SAP S/4HANA Cloud system." Where do I find this info?

**Comment by smahati** [comment]
Hello,

As we have discussed these issues I'll close this ticket now. Please create a new issue if you still need support.

Best regards,
Mahati
