### ISSUE TITLE
Tutorial Page hana-cloud-automation-pilot.md Issue. PROD

### ISSUE THREAD

**Issue by DevRelations2** [sap-tutorials/Tutorials#23402]
Tutorial issue found: [https://github.com/sap-tutorials/Tutorials/blob/master/tutorials/hana-cloud-automation-pilot/hana-cloud-automation-pilot.md](https://github.com/sap-tutorials/Tutorials/blob/master/tutorials/hana-cloud-automation-pilot/hana-cloud-automation-pilot.md) contains invalid tags. Even though your tutorial was created, the invalid tags listed below were disregarded. Please double-check the following tags:
- software-product-function>sap-automation-pilot

 Affected server: PROD

**Comment by danielva** [comment]
Thank you for mentioning this.  I will update the tag to software-product>sap-automation-pilot in my next pull request.
