### ISSUE TITLE
Build a House Price Predictor with SAP AI Core

### ISSUE THREAD

**Issue by gianfranco-s** [sap-tutorials/Tutorials#23418]
Tutorials: https://developers.sap.com/tutorials/ai-core-code.html
--------------------------

In step 13, the command used to upload the image is
```
docker upload docker.io/<YOUR_DOCKER_USERNAME>/house-price:02
```

It should be
```
docker push docker.io/<YOUR_DOCKER_USERNAME>/house-price:02
```

**Comment by jmmargo** [comment]
@dhrubpaul , please respond to the user's feedback.  Thank you.

**Comment by sharmaneeleshsap** [comment]
Hi @gianfranco-s , @jmmargo ,

Thanks for the feedback. The tutorial has been updated to incorporate the code changes, and is functional now.

Thanks.
