### ISSUE TITLE
Build a House Price Predictor with SAP AI Core using VS Code Toolkit

### ISSUE THREAD

**Issue by ivanmir** [sap-tutorials/Tutorials#23425]
Tutorials: https://developers.sap.com/tutorials/ai-core-vs-code-toolkit.html
--------------------------

I had to stop at step 16 as the created executable is not marked as deployable and the instructions do not clearly state how we are able to change it. 

Best regards,
Ivan

**Comment by sharmaneeleshsap** [comment]
Hi @ivanmir, @jmmargo 

Thanks for the feedback. The tutorial has been updated with clear instructions in each steps.

Thanks.
