### ISSUE TITLE
Ingest Live Data into your House Price Predictor with SAP AI Core

### ISSUE THREAD

**Issue by ivanmir** [sap-tutorials/Tutorials#23424]
Tutorials: https://developers.sap.com/tutorials/ai-core-data.html
--------------------------

I had to stop at the end of step 15 as it is really confusing. 
I was able to create the configuration, but after this is has a POSTMAN tag without any information on how to continue.
I guess the intention was to add an API consumption screen where you would learn how to create the execution.
However, there is no information and we cannot continue with the tutorial.

Best regards,
Ivan

**Comment by sharmaneeleshsap** [comment]
Hi @ivanmir, @jmmargo 

Thanks for the feedback. The tutorial has since been updated and all steps are now working fine.

Thanks,
Neelesh.
