### ISSUE TITLE
Ingest Live Data into your House Price Predictor with SAP AI Core

### ISSUE THREAD

**Issue by ivanmir** [sap-tutorials/Tutorials#23422]
Tutorials: https://developers.sap.com/tutorials/ai-core-data.html
--------------------------

On Step 12, the instructions are wrong. I cannot complete without the execution of the REST API to create the Artifact. The system always returns with the following error:

HTTP/1.1 404 Not Found
date: Thu, 01 Feb 2024 20:55:21 GMT
server: istio-envoy
connection: close
content-length: 0

The exercise that uses the VSCode Extension does work, but it doesn't request any labels to entered.

Here is the payload I'm sending:

POST https://api.ai.prod.us-east-1.aws.ml.hana.ondemand.com/lm/artifacts HTTP/1.1
Content-Type: application/json
Accept: application/json
AI-Resource-Group: 
DataServiceVersion: 2.0
Authorization: Bearer {{accessToken}}

{
    "kind": "dataset",
    "name": "House-Price-Dataset-101",
    "scenarioId": "learning-datalines",
    "url": "ai://mys3/data/jan",
    "labels": [
        {
            "key": "ext.ai.sap.com/month",
            "value": "Jan"
        }
    ],
    "description": "Prices in the month of Jan"
}

Please help.

Best regards,
Ivan

**Comment by sharmaneeleshsap** [comment]
Hi @ivanmir, @jmmargo,

Thanks for the feedback. The tutorial has since been updated, and all steps are now working fine.
The 404 error could be due to access issue, which can be resolved by generating a fresh token before new pull request.

Thanks,
Neelesh
