### ISSUE TITLE
Build a House Price Predictor with SAP AI Core

### ISSUE THREAD

**Issue by ivanmir** [sap-tutorials/Tutorials#23420]
Tutorials: https://developers.sap.com/tutorials/ai-core-code.html
--------------------------

On step 4: I was not able to build the docker image on Windows using the command from the tutorial. Instead I was able to use the following command:

`docker buildx build --output=type=docker --platform=linux/amd64 --tag docker.io/____my-docker-id____/house-price:01 .`

BTW: This could be due to the fact that I am not using Docker Desktop. Instead, I am using Rancher Desktop.

On step 13: The command should be:

`docker push` and not `docker upload`

Best regards,
Ivan

**Comment by thewiseg** [comment]
I see the same issue with step 13 using the docker desktop and the Mac command line.  Docker doesn't have an upload command, it should be push.

**Comment by jmmargo** [comment]
@Dhrub, please respond to the user's feedback.  Thank you.

**Comment by sharmaneeleshsap** [comment]
Hi @jmmargo , @thewiseg, @ivanmir,

Thanks for the feedback. The tutorial has been updated to accommodate the changes. The shared command should now work with windows (as demonstrated in the accompanying screenshot).

Regards,
Neelesh

(cc: @dhrubpaul)
