### ISSUE TITLE
Subscribe to the SAP Build Work Zone, Standard Edition - Step 4 - Mittigations and Risks App cannot be added 

### ISSUE THREAD

**Issue by octavonu** [sap-tutorials/Tutorials#23433]
Tutorials: https://developers.sap.com/tutorials/btp-app-work-zone-subscribe.html
--------------------------

Write here how you think we can improve the tutorial ...

Hello,
unfortunately the add button in Content-Explorer is not enabled. All steps before were implemented as written in documentation.

Thank you

![image](https://github.com/sap-tutorials/Tutorials/assets/50553626/98b91677-fec4-4f9d-9d41-44f6bd83e755)

**Comment by smahati** [comment]
Hello,

The tutorial was updated since the ticket was opened which I hope fixes your issue. Please create a new issue if you still need support.

Best regards,
Mahati
