### ISSUE TITLE
Use the SAP HANA Database Explorer Extension

### ISSUE THREAD

**Issue by VinceVega7** [sap-tutorials/Tutorials#23447]
Tutorials: https://developers.sap.com/tutorials/hana-dbx-extension.html
--------------------------

Please add how to connect to a trial account through vscode.
It says database added successfully, but this is not the case. No database is added.

Also, the workspace setting using cloud foundry doesnt work with trial.
Please update the documentation.

**Comment by danielva** [comment]
Thanks for the comments.  The tutorial has now been updated to use the trial account.
