### ISSUE TITLE
Tutorial Page cp-aibus-dox-ui-schema-custom.md Issue. PROD

### ISSUE THREAD

**Issue by DevRelations2** [sap-tutorials/Tutorials#23442]
Tutorial issue found: [https://github.com/sap-tutorials/Tutorials/blob/master/tutorials/cp-aibus-dox-ui-schema-custom/cp-aibus-dox-ui-schema-custom.md](https://github.com/sap-tutorials/Tutorials/blob/master/tutorials/cp-aibus-dox-ui-schema-custom/cp-aibus-dox-ui-schema-custom.md) Your tutorial was not created on the site. Please ensure there is an experience tag among the assigned tags.

 Affected server: PROD

**Comment by jmmargo** [comment]
Issue resolved.
