### ISSUE TITLE
Add the Consumption of an External Service to Your CAP Application

### ISSUE THREAD

**Issue by a-n-d-r-e-f-e-r-n-a-n-d-e-s** [sap-tutorials/Tutorials#23445]
Tutorials: https://developers.sap.com/tutorials/btp-app-ext-service-add-consumption.html
--------------------------

The tutorial will soon be phased out. However, it still being mentioned on the CAP documentation https://cap.cloud.sap/docs/guides/using-services#using-destinations and there is no explanation on why it's being phased out. Is it because some of the features will no longer be supported? Is it because consuming External Services in itself will not be supported? Or is it just because a better tutorial will be posted? 

At this point, I'm not even sure if I should follow this tutorial and risk implementing something that will soon be deprecated.

**Comment by smahati** [comment]
Hello,

Sorry for the delay, the deprecation note is to make people aware that the tutorials are being phased out. You do not need to worry about using it as this will have no impact on the features supported by CAP and we are aware of the links and will update them when the tutorials are removed. The tutorial is being phased out as there is a new set of tutorials which are linked in the note and cover most of the things that Risk Management covered. I will add a link to capire for this particular tutorial as it's not covered in any of the links we have already provided.

Hope this helps.

Best regards,
Maha
