### ISSUE TITLE
Import SAP SuccessFactors OData Services definitions. Tutorial step 5.

### ISSUE THREAD

**Issue by whocann** [sap-tutorials/Tutorials#23449]
Tutorials: https://developers.sap.com/tutorials/cap-extend-sfsf-import-services.html
--------------------------

Step5 is using default-env.json which seems to be deprecated in Capire documentation.
https://cap.cloud.sap/docs/node.js/cds-env#in-default-env-json

**Comment by ale-biagi** [comment]
Documentation recommends to use the new `cds bind` CLI command, but `default-env.json` still works and will keep working as `VCAP_SERVICES` is a Cloud Foundry standard. This also avoids the use of `cds watch --profile hybrid` and allows a simple `cds watch`.
