### ISSUE TITLE
Tutorial Page abap-websocket-rfc.md Issue. PROD

### ISSUE THREAD

**Issue by SAPDocs** [sap-tutorials/Tutorials#23443]
Tutorial issue found: [https://github.com/sap-tutorials/Tutorials/blob/master/tutorials/abap-websocket-rfc/abap-websocket-rfc.md](https://github.com/sap-tutorials/Tutorials/blob/master/tutorials/abap-websocket-rfc/abap-websocket-rfc.md)  - file path is not unique. Your tutorial was not created.

 Affected server: PROD

**Comment by jmmargo** [comment]
Tutorial moved to a new repository.
