### ISSUE TITLE
Mobiles cards are not getting downloaded

### ISSUE THREAD

**Issue by Akashbm964** [sap-tutorials/Tutorials#23451]
Hi colleagues,

We are testing **Get Started with SAP Mobile Cards Starter Scenario** for the February month cycle and we faced an issue 

Region: US

**Tutorial**: https://developers.sap.com/mission.mobile-cards-get-started.html

**Trial Cockpit**: https://cockpit.hanatrial.ondemand.com/trial/#/home/trial

Steps to re-produce the issue:

1. In the BTP trial account, click on boosters and search for 'Build a Micro App for SAP Mobile Cards'
2. Click on start on the tile that appears for 'Build a Micro App for SAP Mobile Cards'
3. Under Check Prerequisite, click 'Next'
4. Under 'Select Subaccount', choose 'trial' for Subaccount and 'dev' for Space from the respective dropdown lists.
5. Initialize the Mobile Card Kit if the same is not Initialized.
6. Click on 'Next'
7. Under 'Select Cards', search for 'Welcome Card' from the available templates.
8. Select the 'Welcome Card Template - Single Instance' template and click 'Next'
9. Under 'Configure Cards', provide a valid name for the card.
10. Click ' Next' and then 'Finish'
11. Select the tab 'Android' to see the QR codes for loading the mobile app and Registration
12. On your mobile phone, use the QR Code scanner and scan the QR Code to load the mobile app. This provides a link to take you to 
      the Google playstore from where the app can be downloaded. Download the app and open the same
13. Once the app is opened on the mobile phone, tap on 'Proceed' and then tap on 'I Agree' under the 'End User License Agreement'
14. Tap on the button ' Scan QR Code' and then scan the QR Code for 'Registration', that appeared at step 11
    After scanning QR code we are getting error as Registration failed

    
 Find the screenshot below for reference:

![Screenshot](https://github.com/sap-tutorials/Tutorials/assets/160128160/1fa66132-3ae3-4994-ad14-ee094a99ad35)

Thanks & regards,
Akash

**Comment by jmmargo** [comment]
This tutorial has been deprecated.
