### ISSUE TITLE
Prompt LLMs in the generative AI hub in SAP AI Core 

### ISSUE THREAD

**Issue by bradycale-taulia** [sap-tutorials/Tutorials#23459]
Tutorials: https://developers.sap.com/tutorials/ai-core-generative-ai.html
--------------------------

This tutorial appears to have a few mistakes or outdated references in it.

I used the python GENERATIVE AI HUB SDK client and I found that:
1. Under "Querying the LLM" section this article says to run "aicore-llm configure -k keys.txt", but it actually should be  "aicore configure -k keys.txt"
2. In all the examples this article states the python code to call a prompt should be "chat.invoke(xyz)" but it actually should be llm.invoke(xyz)"
3. In the "Querying the LLM" section, this article makes a reference/uses embeddings that aren't used anywhere else, running that line of code won't work.

**Comment by sharmaneeleshsap** [comment]
Hi @bradycale-taulia, @jmmargo ,

The issue has been resolved.

Thanks.
