### ISSUE TITLE
Build an Application End-to-End Using CAP, Node.js and VS Code

### ISSUE THREAD

**Issue by glaucodesouza** [sap-tutorials/Tutorials#23457]
Mission: https://developers.sap.com/mission.btp-application-cap-e2e.html
--------------------------

Hi. The course seems offline.

**Comment by smahati** [comment]
Hello, 

Thanks a lot for letting us know. The URL is now: https://developers.sap.com/mission.btp-application-cap-node-vs.html and you can always find our tutorials from the search in the [navigator](https://developers.sap.com/tutorial-navigator.html?tag=software-product-function:sap-cloud-application-programming-model&tag=programming-tool:node-js).

Best regards,
Maha

**Comment by jmmargo** [comment]
The URL is functioning as expected.
