### ISSUE TITLE
Add SAP HANA Support to Your Project

### ISSUE THREAD

**Issue by dreamagine-ai** [sap-tutorials/Tutorials#23468]
Tutorials: https://developers.sap.com/tutorials/btp-app-hana-app-setup.html
--------------------------

Write here how you think we can improve the tutorial ...

Replace first sentence "Run the following command in your project root folder:" with "Run the following command in your cpapp folder:"

**Comment by smahati** [comment]
Hi,

I'll make the change thank you for your feedback!

Best regards,
Maha

**Comment by smahati** [comment]
closing old issues
