### ISSUE TITLE
Tutorial Deploy CAP with SAP HANA Cloud project as MTA

### ISSUE THREAD

**Issue by yilmazozkan** [sap-tutorials/Tutorials#23465]
Tutorials: 
https://developers.sap.com/tutorials/hana-cloud-cap-create-ui.html
https://developers.sap.com/tutorials/hana-cloud-cap-deploy-mta.html
--------------------------
Hi @jung-thomas,
I followed your tutorials for CAPM and HANA Cloud, appreciate it.
Now I have CAPM project in my CF space and I can see my service there but can not see UI app(it is only possible to reach via direct link 
(https://.....hana.ondemand.com/app/interaction_items/webapp/index.html).
And I can not see this UI app under HTML5Apps in my Subaccount, so could not connect app to SAP Build Work Zone.
I would like to have a end to end development with MTA.
Could you please share or create a tutorial about SAP Build Work Zone connection of this MTA project? 
Thanks in advance!

**Comment by jung-thomas** [comment]
Work zone integration is outside the scope of this tutorial. I couldn't comment on what tutorials might cover Work Zone.
