### ISSUE TITLE
Use Pre-Trained Tensorflow Models with a GPU in SAP AI Core

### ISSUE THREAD

**Issue by gianfranco-s** [sap-tutorials/Tutorials#23462]
Tutorials: https://developers.sap.com/tutorials/ai-core-tensorflow-byod.html
--------------------------

I'm using the Free Tier. <s>I'm fairly certain that this tutorial cannot be completed with GPU nodes</s>
The tutorial can be completed without GPU nodes, although ATM I don't have any way to try it with GPU nodes.

<s>I haven't been able to complete this tutorial because there are multiple issues.</s>
I have solved all the issues with the tutorial. I'll fork the project, and create a PR.

The first issue appears when trying to register the artifact. It is my understanding (after having tried it multiple times) that the application must be created before registering the model.

Here are my proposed changes

| Order | Current | Proposed |
|--------|--------|--------|
| 1 | Step 1 | Step 1 |
| 2 | Step 2 | Step 2 |
| 3 | Step 3 | Step 3 |
| 4 | Step 4 | Step 6 |
| 5 | Step 5 | Step 7 |
| 6 | Step 6 | Step 4 |
| 7 | Step 7 | Step 5 |
| 8 | Step 8 | Step 8 | 
| 9 | Step 9 | Step 9 |

## Additional comments on current steps
- Step 6 says to set `resourcePlan` to `infer.s` which will enable GPU. Free tier only allows for `starter` resourcePlan. Maybe add this to the prerequisites?
- Step 7 has a typo:  `executables.ai.sap.com/name: "serve-executuable"` -> `executables.ai.sap.com/name: "serve-executable"`.

**Comment by gianfranco-s** [comment]
- Step 5: command `docker build -t` ends in error: `ERROR: failed to solve: process "/bin/sh -c pip3 install -r requirements.txt" did not complete successfully: exit code: 1`

I suggest leaving requirements.txt without versions (haven't tested it yet)
```
# requirements.txt
scikit-learn
Flask
gunicorn
```

And using flag '--ignore-installed' in dockerfile to avoid conflicts with base image packages
```
RUN pip3 install --ignore-installed -r requirements.txt
```

**Comment by gianfranco-s** [comment]
- Step 3: `Error: Could not connect to the endpoint URL`

Attribute `endpoint` is the problem. Should be `s3.` instead of `s3-`. [Source](https://docs.aws.amazon.com/general/latest/gr/s3.html)
- Original: `endpoint = "s3-eu-central-1.amazonaws.com", # Change this`
- Correct: `endpoint = "s3.eu-central-1.amazonaws.com", # Change this`

**Comment by gianfranco-s** [comment]
- Step 5: using latest tensor flow Docker image results in conflict while loading model.h5.

I suggest changing the Dockerfile to this:
```
FROM tensorflow/tensorflow:2.10.0-gpu-jupyter
```

**Comment by sharmaneeleshsap** [comment]
Hi @jmmargo, @gianfranco-s,

The latest version of the tutorial seems to be working fine.

Regards.

(cc: @dhrubpaul)
