### ISSUE TITLE
Add a List Report Interface to the CAP App (SAP HANA Cloud) - Update Auth strategy

### ISSUE THREAD

**Issue by Matthias-Adams** [sap-tutorials/Tutorials#23475]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-cap-add-list-report.html
--------------------------

Hi, in step 1 before you can start the server, the Auth strategy must be adjusted.
The auth property in package.json must be changed from "xsuaa" to "mocked". The default was changed in one of the CAP updates.

Best regards,
Matthias Adams

**Comment by jmmargo** [comment]
This tutorial has been removed.
