### ISSUE TITLE
Connect Using the Microsoft Entity Framework Core (EF Core)

### ISSUE THREAD

**Issue by bobsys-mfleischer** [sap-tutorials/Tutorials#23474]
Tutorials: https://developers.sap.com/tutorials/hana-clients-entity-framework.html
--------------------------

The tutorial does not work.
I have tested the whole thing on our On Premise version but EF Core simply does not create the tables!
I used the same driver versions and EF Core version as in the tutorial.

HANA DB Version: 2.00.059.04.1655794895 (fa/hana2sp05)

![image](https://github.com/sap-tutorials/Tutorials/assets/78475623/7f3efe42-23ef-42a4-9458-6a692e3b3796)

**Comment by bobsys-mfleischer** [comment]
@danielva 
Does the tutorial not work with On Premise ?

**Comment by MinghaiChang** [comment]
Hello,

Yes, On Premise version is supported. But HANA 1 isn't supported. Can you post you sample code?

**Comment by bobsys-mfleischer** [comment]
I followed the tutorial exactly, so you can find the corresponding code there.

After hours of analysis + reflection, I was able to find the problem and a solution.
After I added the value "CurrentSchema=*****" to the ConnectionString, it works.

**Comment by danielva** [comment]
Thank you for taking the time to comment and to post your solution.  I was not able to reproduce the issue but have added the CurrentSchema parameter.  It will appear in the next update to the tutorial.
