### ISSUE TITLE
Get to Know SAP Tutorials

### ISSUE THREAD

**Issue by Lujasogi** [sap-tutorials/Tutorials#23472]
Tutorials: https://developers.sap.com/tutorials/tutorial-first-steps.html
--------------------------

Link to Badges page not working in step 8 "You can also see all available badges – not just tutorials but also community missions – on the [badges](https://community.sap.com/resources/missions-badges) page."

**Comment by sandraros** [comment]
I suggest to change the issue title to "Get to Know SAP Tutorials > Step 8 > Link broken "badges".

**Comment by jmmargo** [comment]
The tutorial has been updated to show the new location of badges earned.  Thank you for the feedback.
