### ISSUE TITLE
Build a Micro App for SAP Mobile Cards tile is not visible after clicking on the boosters in navigation bar

### ISSUE THREAD

**Issue by Akashbm964** [sap-tutorials/Tutorials#23478]
Hi Colleagues,

We are testing **Get Started with SAP Mobile Cards** Starter Scenario for the March month cycle and we are facing an issue & it is blocker for us.

**Tutorial Link** : https://developers.sap.com/mission.mobile-cards-get-started.html

**Trail Cockpit** : https://cockpit.hanatrial.ondemand.com/trial/#/home/trial

**Region** : US & AP region

Steps to reproduce the issue:

1. In your web browser, open the above mentioned trail cockpit.
2. Provide the login details and click Log On.
3. Navigate to the trial global account by clicking Go To Your Trial Account.
4. In the side navigation bar, click on Boosters
5. Click on Build a Micro App for SAP Mobile Cards tile

Here **Build a Micro App for SAP Mobile Cards tile** tile is not visible.

Please find the Screen recording attahed to the ticket for your reference.

Thanks & regards,
Akash 

https://github.com/sap-tutorials/Tutorials/assets/160128160/4e9d85a9-2778-4753-8add-250d04d51941

**Comment by jmmargo** [comment]
This tutorial has been deprecated.
