### ISSUE TITLE
Use Redis in the Kyma Runtime to Store and Retrieve Data

### ISSUE THREAD

**Issue by maydeb** [sap-tutorials/Tutorials#23504]
Tutorials: https://developers.sap.com/tutorials/cp-kyma-redis-function.html
--------------------------

The setup mock application prerequisite is no longer available.

**Comment by NHingerl** [comment]
Jamie transferred responsibility for the Kyma tutorials; assigning @grego952 instead.

**Comment by grego952** [comment]
The link works again.
