### ISSUE TITLE
Setup SAP Build Code in SAP BTP

### ISSUE THREAD

**Issue by ajmaradiaga** [sap-tutorials/Tutorials#23506]
Tutorials: https://developers.sap.com/tutorials/build-code-setup.html
--------------------------

SAP Build Code is only available in the US trial environment. The tutorial can be improved by stating this.... it is not available if your subaccount is in the Singapore region. Also, additional screenshots can be added showing the set up of the booster, e.g. adding admin, developer accounts

**Comment by Paolaufer** [comment]
I added this information to the prerequisites and as a note. You will see this as soon as the changes are uploaded.
Sorry for the confusion and thank you for the contribution.
