### ISSUE TITLE
Retrieval Augmented Generation using generative-ai-hub-sdk and HANA vector search

### ISSUE THREAD

**Issue by obdi70** [sap-tutorials/Tutorials#23513]
Tutorials: https://developers.sap.com/tutorials/ai-core-genai-hana-vector.html
--------------------------

Hello,
thanks for the tutorial. 
May I kindly ask for some content in the file please?
File "GRAPH_DOCU_QRC3.csv" seems to be quite empty.

Thanks & Br.,
Obdi

**Comment by sharmaneeleshsap** [comment]
Hi @obdi70, @reginasheynblat,

Thanks for the feedback. The tutorial has been updated, and the file referred is populated with necessary data.

Regards.
