### ISSUE TITLE
Design and Deploy Your First Integration Flow

### ISSUE THREAD

**Issue by MissileRBM** [sap-tutorials/Tutorials#23523]
Tutorials: https://developers.sap.com/tutorials/cp-starter-integration-cpi-design-iflow.html
--------------------------

Can you kindly change https://refapp-espm-ui-cf.cfapps.eu10.hana.ondemand.com/espm-cloud-web/espm.svc the URL with the: https://services.odata.org/northwind/northwind.svc

**Comment by Karunaharan** [comment]
Hi @MissileRBM,
Why do you want to change the URL? The tutorial is designed for a specific scenario. Please let me know.
