### ISSUE TITLE
Entitlements UIs have changed

### ISSUE THREAD

**Issue by vilijana** [sap-tutorials/Tutorials#23527]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-mission-trial-2.html
--------------------------

The BTP Cockpit UIs for assigning entitlements have changed as of BTP takt release 2401b (Feb 22, 2024). Please, update the corresponding screenshots. 
For more information, see   [ BTP Cockpit - Entitlements UI Changes T2401B - UA Rollout.pptx](https://sap.sharepoint.com/:p:/r/teams/SAPBTPUserAssistance/Shared%20Documents/General/Meeting_BTP_T%26I%20UA%20Community/2024-04-03/BTP%20Cockpit%20-%20Entitlements%20UI%20Changes%20T2401B%20-%20UA%20Rollout.pptx?d=wef1a27f97d3c4cc1850040531cc32bf2&csf=1&web=1&e=KJ1xxMand) and the corresponding  [ BTP T&I UA community meeting recording](https://sap-my.sharepoint.com/:v:/p/aneta_peteva/EXzL0oS61INOqWhnQpSTUckBmuH1W38O8SbrRJ2ApSHeug?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D&e=cUlY4n).

**Comment by danielva** [comment]
Thank you for the feedback.  
I have updated the screenshots in this tutorial and in hana-cloud-mission-trial-2-ft.  I expect the update will be published next week.
