### ISSUE TITLE
Expose Integration Flow Endpoint as API and Test the Flow

### ISSUE THREAD

**Issue by FernanDoylet** [sap-tutorials/Tutorials#23537]
Tutorials: https://developers.sap.com/tutorials/cp-starter-isuite-api-management.html
--------------------------

On Step 2: Define the API
At 11. Choose RequestProductDetails and then the Resources tab.
the first line should be: choose Edit > Edit in API Designer.
( otherwise, the green POST button is not visible )

**Comment by Karunaharan** [comment]
Hi @FernanDoylet 
Thanks for noticing this. I'm looking into this feedback.

**Comment by FernanDoylet** [comment]
This is in Step 2 @Karunaharan 
Right after "11. Choose RequestProductDetails and then the Resources tab."
please add "Choose edit > Edit in API Designer"
because the previous 'Save' hides the green POST button shown on the graphic.
