### ISSUE TITLE
Connect Your SAP BTP Trial Account to SAP S/4HANA for Content Consumption

### ISSUE THREAD

**Issue by alagishetti** [sap-tutorials/Tutorials#23536]
Tutorials: https://developers.sap.com/tutorials/cp-launchpad-federation-connectivity.html
--------------------------

Write here how you think we can improve the tutorial ...

The runtime destination created has to be "principal propagation" which is the actual runtime user connecting to the back-end. which is missing in this tutorial.

**Comment by SibylleB** [comment]
Hi,
fully agree that for productive usage, principal propagation should be used. It is not used here to keep the tutorial simple and focus on SAP Build Work Zone capabilities. I will suggest the colleagues from the connectivity service to create a dedicated tutorial that shows how to set this up.
Regards,
Sibylle
