### ISSUE TITLE
Create an SAP Fiori App Using SAP Business Application Studio

### ISSUE THREAD

**Issue by FernanDoylet** [sap-tutorials/Tutorials#23541]
Tutorials: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html
--------------------------

Instead of the Run option, I have "Run and Debug" which stops at the URL line.
The mouse-over on the URL shows that I had to do Ctrl + click to follow the link.
The page shows folders and files. Clicking the index.html file opens the page with the header or list.
![directory](https://github.com/sap-tutorials/Tutorials/assets/6888398/c805794d-0c06-4ce6-9a8a-9709d1478dac)

**Comment by raz-korn** [comment]
Hi @FernanDoylet ,
Thanks for reaching out to us.
Kindly provide more details on this issue, eg which step exactly in the tutorial, screenshot before running the app, etc.
Regards - Raz

**Comment by FernanDoylet** [comment]
Good Day @raz-korn 
It happens in Step 4 #1 
and going back I found the option "Run Configurations" available after clicking the 3 dots at the end of the other options on the left side of the screen...

![Fiori](https://github.com/sap-tutorials/Tutorials/assets/6888398/ae0026e5-9a23-4801-8ac0-84efcc945257)

Now, when I try to "Run Configurations" the message "no configurations found" shows up.

So I went to EXPLORER, opened FIORIDEMO, selected 'businesspartners', and clicked the QUICK ACCESS option 'Run' at the end of the EXPLORER column. The option "Business Partners (Fiori Tools)" shows on the top middle of the screen, which I clicked. On the "File Name" field, I selected "index.html" from the drop-down list and clicked the 'Save' button below. Now "Run Configurations" is available on the screen with a 'businesspartners-config1' line and the option to 'Run' on the right side. It runs with the "Debugger attached" and stops at the URL line.

Following the link with Ctrl + click I obtained the screen with the folders and files I sent before.

![follow-link](https://github.com/sap-tutorials/Tutorials/assets/6888398/3222a7ee-5391-41e0-91b6-b995c1b649bc)

**Comment by raz-korn** [comment]
Hi @FernanDoylet ,

Thanks for the additional information.
I need to check if this is a known issue or not.
Anyway, I see two options:
1. Re-do the tutorial. This is the easiest path.
2. Add the run configuration manually.
    1. In the FioriDemo root folder add a folder named ".vscode". In your case it may already exist.
    2. In this folder create a new file called "launch.json". In your case it may already exist.
    3. The content of the file is the following:
{
  "configurations": [
    {
      "name": "Start businesspartners",
      "type": "node",
      "request": "launch",
      "runtimeExecutable": "npx",
      "cwd": "${workspaceFolder}/businesspartners",
      "windows": {
        "runtimeExecutable": "npx.cmd"
      },
      "runtimeArgs": [
        "fiori",
        "run"
      ],
      "args": [
        "--open",
        "test/flpSandbox.html#nsbusinesspartners-display"
      ],
      "console": "internalConsole",
      "internalConsoleOptions": "openOnSessionStart",
      "outputCapture": "std",
      "port": 9229,
      "env": {
        "DEBUG": "--inspect",
        "FIORI_TOOLS_URL_PARAMS": "sap-ui-xx-viewCache=false",
        "run.config": "{\"handlerId\":\"fiori_tools\",\"runnableId\":\"/home/user/projects/FioriDemo/businesspartners\"}"
      }
    }
 ]
}

Go to the Run Configuration pane and see that the run configuration exits and run it.
If it runs - perfect.
If not - there might be a lot of reasons. You can follow the errors and try to resolve.
That's why I mentioned that re-doing the tutorial is the easiest path.

Regards - Raz

**Comment by FernanDoylet** [comment]
Thank You @raz-korn

**Comment by raz-korn** [comment]
The issue seems to be resolved, so I am closing the issue.
If you still have questions, feel free to reopen the issue.
