### ISSUE TITLE
Use Redis in the Kyma Runtime to Store and Retrieve Data

### ISSUE THREAD

**Issue by s-razaq** [sap-tutorials/Tutorials#23546]
Tutorials: https://developers.sap.com/tutorials/cp-kyma-redis-function.html
--------------------------

Hi, 

the link in the prerequisite section [Setup Mock Application](https://developers.sap.com/tutorials/cp-kyma-mocks.html) is broken. It's returning a 404.

**Comment by NHingerl** [comment]
Jamie transferred resposibility for the Kyma tutorials; assigning @grego952 instead.

**Comment by grego952** [comment]
The link now working.
