### ISSUE TITLE
Build and Deploy Your SAP Fiori App to SAP Business Technology Platform

### ISSUE THREAD

**Issue by FernanDoylet** [sap-tutorials/Tutorials#23545]
Tutorials: https://developers.sap.com/tutorials/appstudio-fioriapps-mta-build-deploy.html
--------------------------
On Step 1 
In #1 there is no need to navigate to webapp > view > node_modules,
because mta.yaml is on the root of FIORIDEMO
And the question is in plural but the radiobuttons only allow to choose 1 option.

**Comment by raz-korn** [comment]
Hi @FernanDoylet ,
Thanks for your feedback.
You are correct - the mta.yaml is in the root of the project.
Regarding the English - I'll forward your comment to our User Assistance expert.
Regards - Raz
