### ISSUE TITLE
Download the Installer Files

### ISSUE THREAD

**Issue by RockyZzzzz** [sap-tutorials/Tutorials#23558]
Tutorials: https://developers.sap.com/tutorials/hxe-ua-download-binary.html
--------------------------
<img width="1394" alt="Screenshot 2024-05-10 at 10 52 34 AM" src="https://github.com/sap-tutorials/Tutorials/assets/169224256/1dfd6f48-daa4-4c51-9301-b990eccb5be3">
One extra "you will learn". The third phrase outlined in red should be "If you are NOT a Windows user".

**Comment by danielva** [comment]
Thank you for the feedback.  I have made adjustments to the tutorial that will appear in my next update.
