### ISSUE TITLE
Access a Classic Schema from SAP Business Application Studio

### ISSUE THREAD

**Issue by NiccoloPirani** [sap-tutorials/Tutorials#23554]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-access-cross-container-schema.html
--------------------------
At step 6 "Create a view", when we are requested to submit a sql statement in the blank space, i'm pretty sure that

SELECT TOP 1000
	"REGION",
	"DESCRIPTION"
FROM "DM_HDI_DB_1"."RegionTextsView"

is the correct answer, but once checked the output is "Technical Error". Cause to that i'm unable to complete the mission and obtain the badge, can you check if there is any bug or am i completely wrong about the answer? thank you

**Comment by jung-thomas** [comment]
Technical Error would not be a response if the answer were incorrect. That indicates an issue with the tutorial system itself when trying to validate your answer. I would suggest submitting again.
