### ISSUE TITLE
Download the Installer Files -  STEP 3 Familiarize yourself with the command syntax, and the command arguments

### ISSUE THREAD

**Issue by gregorwolf** [sap-tutorials/Tutorials#23562]
Tutorials: https://developers.sap.com/tutorials/hxe-ua-download-binary.html
--------------------------

In Step 3 of the Tutorial the option `-x` is mentioned for the extended help. But I think it should be corrected to `-X` which is the correct option.

**Comment by danielva** [comment]
Thanks for the reporting this.  I have made the change to this tutorial and to hxe-ua-download-binary-xsa and expect it will be published next week.
