### ISSUE TITLE
Get an Account on SAP BTP to Try Out Free Tier Service Plans

### ISSUE THREAD

**Issue by bufiku** [sap-tutorials/Tutorials#23563]
Tutorials: https://developers.sap.com/tutorials/btp-free-tier-account.html
--------------------------

Hi, 
It looks like the path to request a Free Tier Account has changed, and this tutorial describes an old path. Could you please update the tutorial with the current situation?
Thanks!

**Comment by Madeline-Schaefer** [comment]
Hi @bufiku,

Thanks for your feedback. We will update the tutorial with the new path and it will be available with the next tutorial release.

Kind regards,
Madeline
