### ISSUE TITLE
Prompt LLMs in the generative AI hub in SAP AI Core 

### ISSUE THREAD

**Issue by DamianLion** [sap-tutorials/Tutorials#23567]
Tutorials: https://developers.sap.com/tutorials/ai-core-generative-ai.html
--------------------------

During the "Step 6: Querying the LLMs" in the tab postman

there is the sentence "Note : with each inference request we need to pass the AI core JWT token and AI-Resource-Group in header with your resource group id as value. failing to pass same will throw and 404 Error. Refer step 1 on how to set Headers in Postman"

Please add a concrete header section with the real header name. Also Chat Completion is not part of the API Hub finding the correct header key should be part of the tutorial

```
AI-Resource-Group: default
```

**Comment by sharmaneeleshsap** [comment]
Hi @jmmargo, @DamianLion 

Thanks for the feedback.
The tutorial has now been updated.
