### ISSUE TITLE
Get to Know SAP Tutorials

### ISSUE THREAD

**Issue by HussienAdly** [sap-tutorials/Tutorials#23560]
Tutorials: https://developers.sap.com/tutorials/tutorial-first-steps.html
--------------------------

the link in step 3

More information on tags? See [Using Tags](https://community.sap.com/resources/using-tags).

the link doesn't work

**Comment by AmauryVanEspen** [comment]
May this link could be useful to replace the missing page : https://community.sap.com/t5/help/faqpage/title/Associated_Products

**Comment by sandraros** [comment]
I suggest to change the issue title to "Get to Know SAP Tutorials > Step 3 > Link broken "Using Tags".

**Comment by jmmargo** [comment]
Thank you.  The link has been updated accordingly.  Appreciate your feedback!
