### ISSUE TITLE
Get your Use Case Buddy started

### ISSUE THREAD

**Issue by AmauryVanEspen** [sap-tutorials/Tutorials#23568]
Tutorials: https://developers.sap.com/tutorials/build-use-case-buddy.html
STEP 3
Import the templates for SAP Build Apps & Process Automation
--------------------------
After downloading and unzipped the template, it is forbidden to import content in SAP Build with Trial Booster

Importing is forbidden
![image](https://github.com/sap-tutorials/Tutorials/assets/4487041/a25a0e9a-62f7-4117-bfe5-31a3c4dc739d)

**Comment by AmauryVanEspen** [comment]
For the file : use case buddy process..mtar in UseCaseBuddyTemplates_PleaseExtract.zip
there is a Correlation Id: 5295732a-b82b-4806-4a2b-ca44c37977ee

**Comment by jmmargo** [comment]
@FriederikeMa, can you please respond to the user's feedback?  Thank you.

**Comment by FriederikeMa** [comment]
Hi @AmauryVanEspen. The import could have failed due to your role setup in the BTP account you're using. A quick role assignment should fix it. Please use this guide and the mentioned roles https://help.sap.com/docs/build-apps/service-guide/configuring-user-roles. 

Hope this helps! :)

**Comment by AmauryVanEspen** [comment]
I've tried reviewing role without success. Does it work in free tier ?

**Comment by FriederikeMa** [comment]
Yes it works in free tier. 

Did you add all of the roles described in the guide?
Like these:
- BuildApps
- Registry
- BuildAppsAdministrator
- RegistryAdmin

**Comment by FriederikeMa** [comment]
Provided feedback for issue
