### ISSUE TITLE
The connection to the server localhost:8080 was refused - did you specify the right host or port?

### ISSUE THREAD

**Issue by Git-Nachi** [sap-tutorials/Tutorials#23571]
Tutorials: https://developers.sap.com/tutorials/btp-app-kyma-prepare-dev-environment.html
--------------------------

In Step 4: Log in to your Kyma cluster 

After downloading the .yaml file from KubeconfigURL, manual copy may not work properly as defined in the tutorial (MacOS). Because, its difficult to find .KUBE folder in mac & in many case it is not visible at all even with ls -A command in terminal. Any further commands like "kubectl create namespace risk-management" will throw following error message.

"The connection to the server localhost:8080 was refused - did you specify the right host or port?"

To over come this -> Easy way is to set the environment with EXPORT KUBECONFIG=<Downloaded .yaml file path>. 

This means, right after downloading the .yaml, in the VS Code terminal write ----> EXPORT KUBECONFIG=<URL>.

For ex, it should look like this -  EXPORT KUBECONFIG=/Users/abc/Downloads/config.yaml               

I feel, this is much easier to set the environment & this should work irrespective of OS. However, I'm submitting this for your review. Please check and add this hint too, it may help someone else who is puzzled with 8080 refusal error. 

Reference Blog / Tutorial : https://developers.sap.com/tutorials/btp-kyma-extension.html#d1e76efd-61f4-420c-a9db-12c4615ed635

**Comment by jmmargo** [comment]
@smahati please respond to the user's feedback.  Thank you.

**Comment by smahati** [comment]
Hello,

Sorry for the delay, unfortunately the Kyma tutorials have been retired please take a look at the new tutorial "Incident Management" for the latest tutorials.

Best regards,
Mahati
