### ISSUE TITLE
Set Up SAP HANA Cloud for Kyma

### ISSUE THREAD

**Issue by GregorMuenker** [sap-tutorials/Tutorials#23574]
Tutorials: https://developers.sap.com/tutorials/btp-app-kyma-hana-cloud-setup.html
--------------------------

The Tutorial list the connection to the Hana Cloud with cloudfoundry, there is also a way to connect the Hana via Kyma directly. 
As this is a full Kyma Tutorial, this part should also be a Kyma connection, not going back to cloudfoundry and showing the full capabilities of kyma.

Set Up SAP HANA Cloud for Kyma:
STEP 3 - Set Up SAP HANA Cloud

**Comment by jmmargo** [comment]
Mahati, can you please address the user's feedback?  Thank you.

**Comment by smahati** [comment]
Hello,

Sorry for the delay, unfortunately the Kyma tutorials have been retired please take a look at the new tutorial "Incident Management" for the latest tutorials.

Best regards,
Mahati
