### ISSUE TITLE
Secure Your Application on SAP Business Technology Platform Cloud Foundry

### ISSUE THREAD

**Issue by JHopmann** [sap-tutorials/Tutorials#23577]
Tutorials: https://developers.sap.com/tutorials/s4sdk-secure-cloudfoundry.html
--------------------------

Hi there, just in case somebody can improve the content of this tutorial:

In section 5: Protect your backend microservice.
The following text was found:

--------------------
Also enhance your manifest.yml file by adding an environment variable and a service binding for the XSUAA service instance:```diff env:TARGET_RUNTIME: mainSPRING_PROFILES_ACTIVE: ‘cloud’JBP_CONFIG_SAPJVM_MEMORY_SIZES: ‘metaspace:128m..’JBP_CONFIG_COMPONENTS: ‘jres: [‘‘com.sap.xs.java.buildpack.jre.SAPMachineJRE’’]’JBP_CONFIG_SAP_MACHINE_JRE: ‘{ use_offline_repository: false, version: 17.0.5 }’

xsuaa_connectivity_instance_name: my-xsuaa services:
my-xsuaa
my-destination```
--------------------

I was not able to identify what the author meant with this. It is somehow "corrupted" text. So I ignored and by following this tutorial step-by-step, I found it not working for some unknown reason.
(Sometimes I wonder: Did someone ever followed this tutorial step-by-step ever???, Well I did...Thank you for this..! Yes)

I think the author wanted to tell us: 
"Please make sure you have the following lines exactly indented as this in your manifest.yml:
(Because YAML get's it's syntax also by indentation. Feels like the 80s :-/ ... but tht's a different topic)

>   env:
>     TARGET_RUNTIME: main
>     SPRING_PROFILES_ACTIVE: 'cloud'
>     JBP_CONFIG_SAPJVM_MEMORY_SIZES: 'metaspace:128m..'
>     JBP_CONFIG_COMPONENTS: 'jres: [''com.sap.xs.java.buildpack.jre.SAPMachineJRE'']'
>     JBP_CONFIG_SAP_MACHINE_JRE: '{ use_offline_repository: false, version: 17.0.5 }'
>     xsuaa_connectivity_instance_name: 'my-xsuaa' 
>  
>   services:
>   - my-xsuaa
>   - my-destination

Remarks:
I had some trouble with the service my-destination while pushing it to the cloud:

>     env:
>       JBP_CONFIG_COMPONENTS: 'jres: [''com.sap.xs.java.buildpack.jre.SAPMachineJRE'']'
>       JBP_CONFIG_SAP_MACHINE_JRE: '{ use_offline_repository: false, version: 17.0.5 }'
>       JBP_CONFIG_SAPJVM_MEMORY_SIZES: metaspace:128m..
>       SPRING_PROFILES_ACTIVE: cloud
>       TARGET_RUNTIME: main
>       xsuaa_connectivity_instance_name: my-xsuaa
>     services:
>       my-xsuaa
> +   - my-destination
> For application 'BTPserver': Service instance 'my-destination' not found
> FAILED

I commented it again start searching what this service is all about. Maybe somebody can help?

Kindest regards Jörg Hopmann

**Comment by jmmargo** [comment]
Karsten, can you please address the user's feedback?  Thank you.

**Comment by CharlesDuboisSAP** [comment]
Hello @JHopmann,

We are fixing the corrupted code samples.
Also you could not use `my-destination` because you most likely skipped a prerequisite for this tutorial which is step 6 of [Connect to OData Service on Cloud Foundry Using SAP Cloud SDK](https://developers.sap.com/tutorials/s4sdk-odata-service-cloud-foundry.html).

Best, Charles

**Comment by JHopmann** [comment]
Thanks. Don’t worry.

I have it in place and described this issue, the solution in detail and overall – and much more – on my YT-channel already: https://www.youtube.com/watch?v=yXMKbHjD7_k <https://www.youtube.com/watch?v=yXMKbHjD7_k&t=1s&pp=ygUNasO2cmcgaG9wbWFubg%3D%3D> &t=1s&pp=ygUNasO2cmcgaG9wbWFubg%3D%3D

 

I think I am very deep in this technology and maybe tnhat ist he reason why it’s maybe only me sending you the detials.

But anyway, thank you for taking care.

 

Best regards Jörg

 

Von: Charles Dubois ***@***.***> 
Gesendet: Mittwoch, 7. August 2024 14:32
An: sap-tutorials/Tutorials ***@***.***>
Cc: JHopmann ***@***.***>; Mention ***@***.***>
Betreff: Re: [sap-tutorials/Tutorials] Secure Your Application on SAP Business Technology Platform Cloud Foundry (Issue #23577)

 

Hello @JHopmann <https://github.com/JHopmann> ,

We are fixing the corrupted code samples.
Also you could not use my-destination because you most likely skipped a prerequisite for this tutorial which is step 6 of Connect to OData Service on Cloud Foundry Using SAP Cloud SDK <https://developers.sap.com/tutorials/s4sdk-odata-service-cloud-foundry.html> .

Best, Charles
