### ISSUE TITLE
Screen change

### ISSUE THREAD

**Issue by FernanDoylet** [sap-tutorials/Tutorials#23584]
Tutorials: https://developers.sap.com/tutorials/hcp-apim-create-product.html
--------------------------
Please consider changing the screen in Step 2 with the following...

![product](https://github.com/sap-tutorials/Tutorials/assets/6888398/6d8a62d9-803c-44cc-a7cd-04594d4fc083)

It took me a while to figure that out ;)

**Comment by jmmargo** [comment]
Karunaharan, can you please address the user's feedback?  Thank you.

**Comment by Karunaharan** [comment]
hi @Kakabira 
looks like another outdated screenshot. can you please fix this? please let me know if you need help.

**Comment by Kakabira** [comment]
@FernanDoylet: Thank you for the feedback. I have updated the screenshots in this tutorial.
