### ISSUE TITLE
Sign up for an SAP HANA Cloud Trial account 

### ISSUE THREAD

**Issue by ceedee666** [sap-tutorials/Tutorials#23595]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-mission-trial-1.html
--------------------------
The link (https://www.sap.com/cmp/td/sap-hana-cloud-trial.html) in step two does not work anymore. The links needs to be updated.

**Comment by danielva** [comment]
Thanks for reporting this.  I believe the issue is now corrected.
