### ISSUE TITLE
Add Authentication and Authorization to the Application mistake

### ISSUE THREAD

**Issue by Denis-D-M** [sap-tutorials/Tutorials#23597]
Tutorials: https://developers.sap.com/tutorials/cp-cap-java-security-local.html
--------------------------

The app stops working on Step 4 with an DB-related exception:
"Table ... not found (this database is empty)"

The reason is application.yaml is missing "sql.init.schema-locations" property, although it's there on Step 3.

**Comment by renejeglinsky** [comment]
Thanks @Denis-D-M ,
this will be fixed with an update coming today.

**Comment by renejeglinsky** [comment]
Fix is shipped, therefore closing. Thanks a lot! :)
