### ISSUE TITLE
Install the Cloud Foundry Command Line Interface (CLI)

### ISSUE THREAD

**Issue by FernanDoylet** [sap-tutorials/Tutorials#23596]
Tutorials: https://developers.sap.com/tutorials/cp-cf-download-cli.html
--------------------------
After login, I received the answer: No org or space targeted, use 'cf target -o ORG -s SPACE'
The URL from the table was different than my endpoint.
I had to use the endpoint to target my organization and space.

**Comment by renejeglinsky** [comment]
Hi @FernanDoylet ,
the table can only show some examples. The tutorial then explains in the following how you find your individual API endpoint.
What is your proposal to improve this tutorial? Should we remove the table?

**Comment by renejeglinsky** [comment]
Closed due to inactivity.
