### ISSUE TITLE
Enable Services for Sales Tracker App

### ISSUE THREAD

**Issue by FernanDoylet** [sap-tutorials/Tutorials#23593]
Tutorials: https://developers.sap.com/tutorials/cp-apim-sales-tracker-services-enable.html
--------------------------
Please update the Prerequisite link to "Sign up for an account on SAP Cloud Platform" to learn how to access the "SAP Cloud Platform Cockpit" as shown in step 1.

**Comment by jmmargo** [comment]
This tutorial will soon be deprecated.  Thank you.
