### ISSUE TITLE
Introduce Resilience to your Application: Code snippet contains duplicate line.

### ISSUE THREAD

**Issue by AHaury** [sap-tutorials/Tutorials#23602]
Tutorials: https://developers.sap.com/tutorials/s4sdk-resilience.html
--------------------------

Write here how you think we can improve the tutorial ...

See attached screen copy.

![2024-06-20_17-24-59](https://github.com/sap-tutorials/Tutorials/assets/67156037/c43315cb-95df-412a-9f76-3f625150e2ff)

**Comment by jmmargo** [comment]
Thank you for the note.  This has been revised.
