### ISSUE TITLE
Connect to OData Service on Cloud Foundry Using SAP Cloud SDK

### ISSUE THREAD

**Issue by frank1302** [sap-tutorials/Tutorials#23600]
Tutorials: https://developers.sap.com/tutorials/s4sdk-odata-service-cloud-foundry.html
--------------------------
the section:
<plugin>
   <groupId>com.sap.cloud.sdk.datamodel</groupId>
   <artifactId>odata-generator-maven-plugin</artifactId>...

needs to be updated:

... <artifactId>odata-v4-generator-maven-plugin</artifactId>...
ciao Frank

**Comment by jmmargo** [comment]
Junjie, can you please respond to this user's feedback?

**Comment by CharlesDuboisSAP** [comment]
Hello @frank1302,

`odata-generator-maven-plugin` uses OData v2 which is not outdated.
Feel free to use OData v4
