### ISSUE TITLE
Tutorial: SAP HANA XS Advanced, Creating a Node.js Module

### ISSUE THREAD

**Issue by thiagofcs** [sap-tutorials/Tutorials#23618]
Tutorial link: https://developers.sap.com/tutorials/xsa-xsjs-xsodata.html

When trying to run the hdb.xsjs I`m getting the below issue:

**500 conn.executeQuery is not a function**

I`m using HANA 2.0 SP07 and followed the tutorial all good until this step. It seems that the Connection classe of $.hdb.getConnection is not having the executeQuery function or something like this.

What could it be?

 Best Regards,
Thiago

**Comment by jung-thomas** [comment]
For newer releases:
The @sap/xsjs library is being deprecated. XSJS supports Node.js runtime versions up to Node.js 14, which reached the end of support in April 2023. The successor for XSJS with Node.js 16 or later is the asynchronous library @sap/async-xsjs. For information about migrating from @sap/xsjs to @sap/async-xsjs, see Related Information below.
https://help.sap.com/docs/SAP_HANA_PLATFORM/d89d4595fae647eabc14002c0340a999/a6e9db6c7042477fa4c833e74c101485.html
