### ISSUE TITLE
Create a Full-Stack Application with SAP Fiori UI using Joule in SAP Build Code

### ISSUE THREAD

**Issue by ahmedkhan29789** [sap-tutorials/Tutorials#23622]
Tutorials: https://developers.sap.com/tutorials/build-code-test-drive.html
--------------------------

Write here how you think we can improve the tutorial ...

This tutorial is awesome, very detailed and step by step helping learners to learn, the most important part what i believe is missing is that after the last step is completed when developer able to see his 3 tiles there should be another tutorial where the developer can deploy these applications on SAP BUILD WORK ZONE, so that he can finally benefit the end user with this mission of developing apps using AI.

**Comment by Paolaufer** [comment]
Thank you for your comment and your suggestion. We will definitely look into it!
