### ISSUE TITLE
Get to Know SAP Tutorials > Step 8 > link broken "SAP profile" (#missions:earned)

### ISSUE THREAD

**Issue by sandraros** [sap-tutorials/Tutorials#23625]
Tutorials: https://developers.sap.com/tutorials/tutorial-first-steps.html
--------------------------

Link broken "SAP profile" (#missions:earned) in step 8:

> "The badges you earn appear in the Earned Missions tab of your [SAP profile](https://people.sap.com/#missions:earned)."

**EDIT July 30th: for information, two other broken links in Get to Know SAP Tutorials are reported in #23472 and #23560.**

**Comment by jmmargo** [comment]
Thanks for the feedback.  I am working on updating the link.

**Comment by jmmargo** [comment]
The tutorial has been updated to show the new location of badges earned.  Thank you for the feedback.
