### ISSUE TITLE
Jump start the SAP SuccessFactors Extension CAP Project

### ISSUE THREAD

**Issue by frankmeertens** [sap-tutorials/Tutorials#23630]
Tutorials: https://developers.sap.com/tutorials/cap-extend-sfsf-jumpstart.html
--------------------------

The instructions on how to open the Workspace do not seem to be in line with the current options within the studio. File -> Open Workspace is not available. Only File -> Open Workspace from file.

**Comment by jmmargo** [comment]
Alessandro, please respond to this user's feedback.  Thank you.

**Comment by ale-biagi** [comment]
Tutorial has been updated to reflect the current state of BAS.
