### ISSUE TITLE
CircleCI status badge - Readme.me

### ISSUE THREAD

**Issue by AmauryVanEspen** [sap-tutorials/Tutorials#23646]
Hi,
i've got an issue with loading the CircleCI badge status

![2024-07-30 05_46_47-sap-tutorials_Tutorials_ Tutorials on sap com ](https://github.com/user-attachments/assets/b54abba8-4c6d-4759-8ab2-4b146e75f853)

the link seems to be compliant according to [their doc](https://circleci.com/docs/status-badges/)

About DevDependency, i'm not sure.

Regards

Amaury

**Comment by jmmargo** [comment]
Without the tutorial name, I am unable to assist.  I am happy to reopen if more information is provided.
