### ISSUE TITLE
Create a Full-Stack Application with SAP Fiori UI using Joule in SAP Build Code

### ISSUE THREAD

**Issue by manoelfranklins** [sap-tutorials/Tutorials#23645]
Tutorials: https://developers.sap.com/tutorials/build-code-test-drive.html
--------------------------

Write here how you think we can improve the tutorial ...

Following the tutorials I get here and I don´t see "Open Guide". Is this because I have a trial account? Tutorial must cover this and what to do here.

![image](https://github.com/user-attachments/assets/4dab5994-6d08-45c7-b9a3-2724c55127bc)

**Comment by jmmargo** [comment]
Paola, can you please address this user's feedback?  Thank you!

**Comment by Paolaufer** [comment]
Hi @manoelfranklins,
I am sorry you are experiencing this. Let me look into it and get back to you.

**Comment by Paolaufer** [comment]
Hi @manoelfranklins ,
THere was a bug where it took a while for Joule to be enabled.
Did you try again? Is it working now?
It should definitely be working in Trial, in general, tutorials are built for the trial environment.
Please let me know if you can access joule now.

**Comment by Paolaufer** [comment]
HI,
I have updated the tutorial. 
Thank you for your feedback.
