### ISSUE TITLE
Deploy CAP Java App to SAP Business Technology Platform

### ISSUE THREAD

**Issue by zbroadwell** [sap-tutorials/Tutorials#23683]
Tutorials: https://developers.sap.com/tutorials/cp-cap-java-deploy-cf.html
--------------------------

In Step 7 of the tutorial:
- In item 4, an example URL should be `/odata/v4/BooksService/Books` if the user had followed the entire tutorial of [Build a Business Application Using CAP for Java](https://developers.sap.com/mission.cap-java-app.html), instead of `.../catalog/Books`
- In item 5, not sure what `routes` mean, there's no mention of `routes` in the previous step.

**Comment by jmmargo** [comment]
@renejeglinsky please respond to this user's feedback.

**Comment by renejeglinsky** [comment]
Hi @zbroadwell ,

thanks a lot for opening this issue. I'll provide a fix soon.

All the best,
René
