### ISSUE TITLE
Duplicate tags for SAP Cloud Application Programming Model 

### ISSUE THREAD

**Issue by hm23** [sap-tutorials/Tutorials#23693]
In the filter section of the tutorial navigator, I see multiple entries for "SAP Cloud Application Programming Model" (and also for some other tags, e.g. "SAP Business Application Studio" and "SAP Business Technology Platform"):

![image](https://github.com/user-attachments/assets/9b1a4807-ff3c-490b-b008-2f153179f2e7)

Selecting one or the other entry results in different search results:
- https://developers.sap.com/tutorial-navigator.html?tag=software-product%3Atechnology-platform%2Fsap-business-technology-platform%2Fsap-cloud-application-programming-model
- https://developers.sap.com/tutorial-navigator.html?tag=software-product-function%3Asap-cloud-application-programming-model

It would be good to merge the tags (`software-product-function>sap-cloud-application-programming-model` and `software-product>sap-cloud-application-programming-model`) in the tutorials.

Thanks a lot,
Heiko

**Comment by jmmargo** [comment]
Thank you for the feedback.  I have cleaned up the tags to remove the duplicates.  I also see other tags affected and will address those as well.
