### ISSUE TITLE
Create Your First App on Cloud Foundry

### ISSUE THREAD

**Issue by dsimov** [sap-tutorials/Tutorials#23699]
Group: https://developers.sap.com/group.scp-3-first-app.html
--------------------------

Hi,
Please change "SAP Cloud Platform cockpit" to "SAP BTP cockpit" in the introductory text of the tutorial. The name of the product changed a long time ago.

Regards
Jimmy

**Comment by jmmargo** [comment]
Thank you for the feedback.  The text has been updated.
