### ISSUE TITLE
Create an API Proxy

### ISSUE THREAD

**Issue by ceedee666** [sap-tutorials/Tutorials#23691]
Tutorials: https://developers.sap.com/tutorials/hcp-apim-create-api.html
--------------------------

In step 10 of the turoial the API Proxy is tested. this is not possible in the trial environment. In the trail environment the generated URL for the API proxy is wrong. In the trial environement it is necessary to manuyll adjust the URL in the test environment. 

I found the following question related to the issue: [https://community.sap.com/t5/sap-learning-q-a/developing-with-sap-integration-suite-how-to-modify-th...](https://community.sap.com/t5/sap-learning-q-a/developing-with-sap-integration-suite-how-to-modify-the-api-proxy-host-name/qaq-p/224504). This post shows that it is possible to invoke the API Proxy by manually adjusting the URL in the test environment.

**Comment by Karunaharan** [comment]
Dear @Kakabira - can you please assist this user?

**Comment by Kakabira** [comment]
@ceedee666: 
This tutorial is written for the production environment and doesn't cover the steps for trial environment. It's not possible to include a note about manually adjusting the URL in the test environment in this tutorial.
