### ISSUE TITLE
Create a Full-Stack Application with SAP Fiori UI using Joule in SAP Build Code

### ISSUE THREAD

**Issue by dirkelko** [sap-tutorials/Tutorials#23700]
Tutorials: https://developers.sap.com/tutorials/build-code-test-drive.html
--------------------------

Hi, I've started the tutorial with the SAP Build Code Booster in my Trial Account and created successfully a project for a full stack application. However when I want to do start Joule in step 2.1 it says:
**This feature is currently not enabled for you.
To use Joule, you must have configured SAP Build Code in your subaccount.
See [Initial Setup]**

I had to delete the BAS Subscription ans SAP Build subcription completely and restart the Booster which created a new BAS subscription that worked with Joule.

Maybe that should be included in the tutorial, otherwise more people will fall into that trap.

**Comment by jmmargo** [comment]
Paola, can you please respond to the user's feedback?

**Comment by Paolaufer** [comment]
Hi @dirkelko,
We have rechecked the tutorial and we can't reproduce the problem.
Would you please try again?

**Comment by dirkelko** [comment]
I deleted my old BAS and Build subscription and after that it works. I just proposed to include a hint into the tutorial that it might be necessary to delete old BAS/Build subscriptions first if you get this same error message.

**Comment by Paolaufer** [comment]
Thank you for you suggestion. I am glad it worked for you and sorry for the trouble.
