### ISSUE TITLE
[rl-code_scan_alerts-1] Code scan alerts are disabled.

### ISSUE THREAD

**Issue by Ulrike20** [sap-tutorials/Tutorials#23702]
This issue was generated by the SAP Repository Linter. It checks repositories for their compliance with the SAP open source project guidelines. As an SAP employee you can see further details at https://wiki.one.int.sap/wiki/display/ospodocs/Repository+Linter+Findings#RepositoryLinterFindings-CodeScanAlerts(rl-code_scan_alerts-XX)

**Comment by jmmargo** [comment]
Thank you for the notification.
