### ISSUE TITLE
Get to Know SAP Tutorials

### ISSUE THREAD

**Issue by ferces** [sap-tutorials/Tutorials#23712]
Tutorials: https://developers.sap.com/tutorials/tutorial-first-steps.html
--------------------------

In the step 7, there is no tip about where to find the "Feedback" option. Just an image of the window opened after clicking "feedback" button.
I've found it on the top of the tutorial in the bar, but i don't know if there's more ways of doing it.

![image](https://github.com/user-attachments/assets/2635b778-5289-42fa-b7ca-2daec27a5aeb)

**Comment by jmmargo** [comment]
Thank you for the feedback.  I updated the tutorial to explain this.
