### ISSUE TITLE
Deploy Your CAP Application on SAP BTP Kyma Runtime

### ISSUE THREAD

**Issue by nalcalde** [sap-tutorials/Tutorials#23713]
Mission: https://developers.sap.com/mission.btp-deploy-cap-kyma.html
--------------------------

Write here how you think we can improve the tutorial ...
Both links:
- Create a CAP Application and SAP Fiori UI
- Deploy Your CAP Application on SAP BTP Kyma Runtime
not work. Neither Chrome, Safari, nor Edge.
Regards,
Naldo Alcalde

**Comment by jmmargo** [comment]
This has been reported earlier and is being researched.  Thank you.

**Comment by jmmargo** [comment]
This issue has been resolved.  Thank you for your patience.
