### ISSUE TITLE
Expose Integration Flow Endpoint as API and Test the Flow

### ISSUE THREAD

**Issue by gregorwolf** [sap-tutorials/Tutorials#23726]
Tutorials: https://developers.sap.com/tutorials/cp-starter-isuite-api-management.html
--------------------------

Hello,

in "Step 4 - Assign policy template" the client credentials and token url are directly pasted into the policy. Even if this is a beginner tutorial I would expect that best practices are used and the credentials and token url is read from key value maps.

Best Regards
Gregor

**Comment by Karunaharan** [comment]
Hi @gregorwolf,
Thanks for that feedback. We will look into it and see how best we can improve the tutorial.
Since this is not feedback about something not working, I close the issue and take your inputs for further steps.
