### ISSUE TITLE
Issue in Set Up for the Mobile Development Kit (MDK) ( US & AP)

### ISSUE THREAD

**Issue by Akashbm964** [sap-tutorials/Tutorials#23724]
Hi Colleagues,

We are testing Starter scenarios for the September Month cycle.
Here, we are not able to create New Mobile app for both US & AP region.

Tutorial link : https://developers.sap.com/group.mobile-dev-kit-setup.html
Trail account link :  https://cockpit.hanatrial.ondemand.com/trial/#/home/trial

Steps to reproduce:

1.In your web browser, open the SAP BTP trail cockpit : https://cockpit.hanatrial.ondemand.com/trial/#/home/trial
2. Provide the login details to log on to your account.
3. Click subaccount available in your global account.
4. In the left pane, choose Services → Service Marketplace.
5. Search for Mobile, and click Mobile Services tile.
6. Choose Support to open SAP Mobile Services Cockpit.
7. The SAP mobile service cockpit dialog, Select API Endpoint, appears. Before you click on Login, make sure to provide the correct API endpoint belongs to your BTP subaccount.
8.  click on Login to continue.
9. The current API Endpoint value appears. Choose the relevant Organization and Space from the dropdown list, and then choose 
Open
10. Navigate to SAP Mobile Services cockpit.
11. On the home screen, click Create new app or navigate to Mobile Applications → Native/MDK → New.

Here, 
1. We are getting Type of the Application as No data , Click on next 
2. After entering ID & Name under Basic Info License type lite is disappearing  
3. After we are unable to proceed further steps as next button is not working.

Please find the screenshot & recordings for your reference.

![image](https://github.com/user-attachments/assets/e613675e-1adb-46c5-9d19-2b763a512096)

https://github.com/user-attachments/assets/9142c0a4-a2d9-4034-ba5a-40b8e4c21880

Thanks & regards,
Akash

**Comment by jitendrakansal** [comment]
@Akashbm964 Pls. check again. I am able to see the required information in my ap21 trial. See attachment.  
<img width="1579" alt="ap21_ms" src="https://github.com/user-attachments/assets/6bf17f51-c3c7-4226-8640-91eade6bebe0">

**Comment by Akashbm964** [comment]
Hi @jitendrakansal ,

I am able too see the type of Application page 

![image](https://github.com/user-attachments/assets/de84d990-3743-45ef-be79-d8437761ffaf)

**Comment by jitendrakansal** [comment]
@Akashbm964 are you now able to proceed and app creation works?

**Comment by Akashbm964** [comment]
Yes I could be able to create MDK Apps & it got created .

But, I got issue with SAP build code service in AP region
I am unable to start SAP Build code as I am getting error **Some entitlements are missing**

**Comment by jitendrakansal** [comment]
@Akashbm964 Is your trial in US10? or AP region?

Please note that The trial version of SAP Build Code is currently only available in the US10 region. See this information here https://developers.sap.com/tutorials/build-code-setup.html

**Comment by jitendrakansal** [comment]
The trial version of SAP Build Code is currently only available in the US10 region, it is not available in AP21, hence you see the entitlement missing message.

You can delete your current trial account and create a new one in US region to continue.

**Comment by Akashbm964** [comment]
Hi @jitendrakansal ,
Thanks for the update .
 SAP Build Code was available in AP region till last month.
 
 May I know, Is there any specific reason for removing it in AP region ?
