### ISSUE TITLE
Issue in Build a Business Application Using CAP for Node.js

### ISSUE THREAD

**Issue by c5291887** [sap-tutorials/Tutorials#23731]
Hi Colleagues,

We are testing  Starter Scenario for September month cycle in US region.

Tutorial link: https://developers.sap.com/tutorials/cap-service-deploy.html
Trial account link: https://cockpit.hanatrial.ondemand.com/trial/#/home/trial

Here in step no 3, deploy using CF deploy, this command "**mbt build -t gen --mtar mta.tar**" is giving error as below.

![image](https://github.com/user-attachments/assets/1f0e9fde-38fe-4ab5-bb4b-a8947633872f)

" **[2024-09-12 14:40:04] ERROR could not build the MTA project: could not execute the "make -f Makefile_20240912143957.mta p=cf mtar=mta.tar strict=true mode= t=\"gen\"" command: exit status 2
Error: could not build the MTA project: could not execute the "make -f Makefile_20240912143957.mta p=cf mtar=mta.tar strict=true mode= t=\"gen\"" command: exit status 2**"

Please find the attached screen shot for reference.
![image](https://github.com/user-attachments/assets/2c583d2a-ed66-4ed3-ae88-badbb5da0588)

Thanks & Regards,
Aruna J R

**Comment by jmmargo** [comment]
@renejeglinsky please respond to the user's feedback.  Thank you.

**Comment by renejeglinsky** [comment]
Hi @c5291887 ,

you're using Powershell. Could you please test it with another CLI?

**Comment by c5291887** [comment]
Hi Rene
we have verified in git bash and cmd but still the same error exists. kindly help us to proceed further.
![image](https://github.com/user-attachments/assets/5d5b6f50-e501-4ca2-a40f-f86f022639da)

**Comment by renejeglinsky** [comment]
As this is a different error and you closed the issue, I assume you executed the tutorial successfully. Thanks for testing and reaching out :)

**Comment by renejeglinsky** [comment]
For the current error, you need to create a DB, according to the error message.

**Comment by c5291887** [comment]
Hi Rene
Yesterday i did some work around n got some different error. 
But now i executed same scenario from scratch and got same error in Git Bash also. Kindly suggest me to proceed further. Thanks for your support.


![image](https://github.com/user-attachments/assets/4038d4d9-6769-4f48-84d8-3a355007eacc)

**Comment by renejeglinsky** [comment]
There seems to be a problem with the `nmp ci` command. Could you attach the whole error log? I'm not sure what causes this upstream conflict. I haven't seen this before

**Comment by renejeglinsky** [comment]
And please provide the versions you're using: `cds v -i`

**Comment by c5291887** [comment]
Hi Rene,
![image](https://github.com/user-attachments/assets/9f64f587-c7b1-4b0b-abcc-71654284ef2d)

**Comment by renejeglinsky** [comment]
Please do `cds v -i` inside the _my-bookshop_ project. I'm pretty sure you'll find `@sap/cds` with 8.1 or less there. I could reproduce your error when using `@sap/cds@8.1` and at the same time using `@cap-js/hana@1.2.0`. You log in the terminal (was not part of your screenshot) contains:

```
Error: npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: my-bookshop@1.0.0
npm ERR! Found: @sap/cds@8.1.1
npm ERR! node_modules/@sap/cds
npm ERR!   @sap/cds@"8.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @sap/cds@">=8.2" from @cap-js/hana@1.2.0
npm ERR! node_modules/@cap-js/hana
npm ERR!   @cap-js/hana@"^1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

Solution:
You dependencies in your _package.json_ should look as follows:

```
"dependencies": {
    "@sap/cds": "^8",
    "express": "^4",
    "@sap/xssec": "^4",
    "@cap-js/hana": "^1"
  },
```

After `npm install` you should find `@sap/cds@8.2` when doing `cds v -i`. And then also the MBT build works.

**Comment by c5291887** [comment]
We are able to create mta.tar file with cds version "@sap/cds": "^8" and while deploying i got this below error.

Creating service "my-bookshop-db" from MTA resource "my-bookshop-db"...
Error monitoring creation or update of services: Error creating service "my-bookshop-db" from offering "hana" and plan "hdi-shared": Service broker error: Service broker hana-broker failed with: Can not create service instance 'my-bookshop-db': There is no database available. Ensure that you have a database available in space 'dev' within organization 'd5e66d9btrial'.


![image](https://github.com/user-attachments/assets/595f0490-baba-4207-b67d-82101d8b3481)

**Comment by c5291887** [comment]
Am able to create database instance manually but from vs code its not happening "cf deploy gen/mta.tar".

![image](https://github.com/user-attachments/assets/3f4317e7-5a33-4627-9b7d-4eb28593feef)



The instance "abc1234" which we created manually.
![image](https://github.com/user-attachments/assets/c4e4b8fd-83b6-46db-aac3-0b0c8273e189)


Kindly suggest me to proceed further. Thanks

**Comment by renejeglinsky** [comment]
Hi,
I can't reproduce this. For me it works.

Please delete all service instances and app related to this tutorial and make a fresh deployment. I'm sure it will work then if the DB is running.

**Comment by renejeglinsky** [comment]
@c5291887 Can you confirm it worked?

**Comment by c5291887** [comment]
Hi Rene,
Yesterday i retested the scenario with new instance creation and deployed successfully and log file is generated as per the requirement.

![image](https://github.com/user-attachments/assets/1692fb07-ccf1-4d3e-9254-5c8f35026c43)

**The URL generated in log file is not launching as per requirnment.**
![image](https://github.com/user-attachments/assets/ed457201-7e6b-43cc-8e55-34ea8d21c7fc)

Kindly suggest me to proceed further. Thanks

**Comment by renejeglinsky** [comment]
Please use the other URL from the AppRouter (the one without `-srv`): 

>Application "my-bookshop" started and available ...

**Comment by c5291887** [comment]
I have launched this URL "fb2f4044trial-dev-my-bookshop.cfapps.us10-001.hana.ondemand.com" in different browsers and i got below response. 

Application "my-bookshop" started and available at "fb2f4044trial-dev-my-bookshop.cfapps.us10-001.hana.ondemand.com"

![image](https://github.com/user-attachments/assets/5a306fb4-8464-4cda-b34f-f56a5fea377b)

**Comment by renejeglinsky** [comment]
That looks as if this step is missing:
![image](https://github.com/user-attachments/assets/9dca9c6c-7ec8-49a6-a53d-9353e240cc6e)
Please check that your project contains this configuration.

**Comment by c5291887** [comment]
Hi Rene,
The scenario is working as expected. Thanks a lot for your support.

![image](https://github.com/user-attachments/assets/71037ecb-3d10-4a7b-a57c-523461e22377)


![image](https://github.com/user-attachments/assets/d3dfa7b1-1fc5-4cb4-b7eb-9e0bf921879d)
