### ISSUE TITLE
Tutorial 'Enhance Behavior With Action and Validation' talks about definition that was not created in the earlier steps. Please check.

### ISSUE THREAD

**Issue by sreejithppsap** [sap-tutorials/Tutorials#23732]
Tutorials: https://developers.sap.com/mission.cp-starter-extensions-abap.html
Tutorial : Enhance Behavior With Action and Validation (https://developers.sap.com/tutorials/abap-environment-behavior-action.html)
tutorial starts with the following statement: "Switch to your behavior definition ZR_TRAVELTP_### and add with draft to enable the draft concept.", but we are not creating any behavior definition with name 'ZR_TRAVELTP_###' in any of the earlier steps (Create Behavior Definition for Managed Scenario). Please check and update the tutorial accordingly.
Please refer the attached screenshot.

Thanks and Regards
Sreejith

<img width="960" alt="Screeshot" src="https://github.com/user-attachments/assets/637d8f5a-2b45-4a1c-84d8-511541306c5d">

**Comment by jmmargo** [comment]
@julieplummer20 can you please respond to the user's feedback?  Thank you.

**Comment by AnitaDixit** [comment]
Hi,
It is still not clear. Kindly update the tutorial at the earliest.

Thanks & Kind Regards,
Anita

**Comment by julieplummer20** [comment]
Hi Anita,
I apologise for the delay. It appears that the naming convention used in a previous tutorial in the mission is obsolete. I will update accordingly.
Best wishes,
Julie Plummer.

**Comment by julieplummer20** [comment]
Hi Baskar,
I will email you about this issue
I apologise for the inconvenience.

Best wishes,
Julie.

**Comment by Akashbm964** [comment]
Hi Colleagues,

I have completed the scenario as per link : https://developers.sap.com/tutorials/abap-environment-data-model.html

At last step , service definition got published as below

![image](https://github.com/user-attachments/assets/899a52f8-5093-494d-9a61-58ca6a6b2575)

After clicking on preview it is taking me to the following fiori application

![image](https://github.com/user-attachments/assets/181cbae9-6430-469f-8346-2d6765fed9ca)


Please let let us know is this correct or need to proceed any other steps.


Thanks & regards,
Akash

**Comment by BaskarThambiayah** [comment]
Hi Akash,
As per the email communication from Julie, the content of the tutorial “Create and Expose a CDS-Based Data Model With SAP BTP ABAP Environment” is covered in greater detail in the following mission:
[Build an SAP Fiori App Using the ABAP RESTful Application Programming Model [RAP100] | SAP Tutorials](https://developers.sap.com/mission.sap-fiori-abap-rap100.html)
Therefore, to avoid double maintenance, they have agreed to remove the group “Create and Expose a CDS-Based Data Model” from production, but It will remain in QA for now.

So kindly follow the new mission link:
[Build an SAP Fiori App Using the ABAP RESTful Application Programming Model [RAP100] | SAP Tutorials](https://developers.sap.com/mission.sap-fiori-abap-rap100.html)

Many thanks & regards,
Baskar

**Comment by Akashbm964** [comment]
Hi Colleagues,

I completed the scenario by using the link [Build an SAP Fiori App Using the ABAP RESTful Application Programming Model [RAP100] | SAP Tutorials](https://developers.sap.com/mission.sap-fiori-abap-rap100.html)

Deployment is done successfully.

![image](https://github.com/user-attachments/assets/a89f6700-e267-4fc7-8ce8-b975b5b8571d)


After this,
the next tutorial **Create SAP Fiori Launchpad Space and Page Templates** required _Requires Customer/Partner License_

![image](https://github.com/user-attachments/assets/b33a8433-c431-4799-90ea-d2de1a33ff2f)

Even though I tried further but I am getting error as **You don't have permission to access Manage launchpad pages app**

![image](https://github.com/user-attachments/assets/4a7ac8d0-ca83-44c5-bc99-bd0023eb355d)

Is this enough or do we need to get the access to continue further?

Kindly let us know ASAP.


Thanks & regards,
Akash
