### ISSUE TITLE
Take a Tour of SAP BTP Trial

### ISSUE THREAD

**Issue by Putzsch** [sap-tutorials/Tutorials#23736]
Tutorials: https://developers.sap.com/tutorials/cp-trial-quick-onboarding.html
--------------------------

Write here how you think we can improve the tutorial ...

well I was not able to answer the following question and I could not find any clues to fix it. I'd tried a lot of entries, 

**"Enter the first item in the left hand-side navigation of your trial Cloud Foundry global account: "**  

I mus be so d***.

Any help to compere screens?

thanks a lot,
Daniel

**Comment by jmmargo** [comment]
@Madeline-Schaefer can you please reply to this user's feedback?

**Comment by Madeline-Schaefer** [comment]
Hi @Putzsch, 

Thanks a lot for your feedback. 

On my screen, I can see this: 
![First item left hand](https://github.com/user-attachments/assets/1c626fb4-dec7-46a2-b865-d85653b38698)

Just for clarification, when you put in the answer, did it not accept the right answer, or did it not show the correct answer, or was there a different screen shown?

Best,
Madeline

**Comment by Putzsch** [comment]
Hey Madeline,
That's so great to get so fast a quick and clear feedback. 

I did a printscreen to show which reply I've got:

![2024_09_16_SAP_BTP_tutorial_bug](https://github.com/user-attachments/assets/d3fcd364-e7bd-411e-8b1a-b204d49fe68a)

I'd also tried again with the underlying item: Ressource Providers, it gave back the same result.

kr,
daniel

**Comment by Putzsch** [comment]
![2024_09_16_SAP_BTP_tutorial_bug_2](https://github.com/user-attachments/assets/9dc777f9-3ece-4ace-b48a-a4d8b437e3ff)   
Good morning Madeleine,
You've got it ! See attached print screen for confirmation.
Some times details make the difference :-) 
Kr,
Daniel

**Comment by Putzsch** [comment]
> Hey Daniel,
> 
> okay, I see. Can you try and put in "subaccounts" as the answer and let me know if it is shown as the correct answer then? Because "subaccounts" was the correct answer for the older version. If it is the right answer, I will update the tutorial again and make sure that it will be changed to "Account Explorer".
> 
> Thank you and kind regards, Madeline

**Comment by Madeline-Schaefer** [comment]
Perfect! I'm glad it worked :)

Thanks for bringing it to our attention, I will update the tutorial accordingly :)
