### ISSUE TITLE
Expose Integration Flow Endpoint as API and Test the Flow

### ISSUE THREAD

**Issue by Putzsch** [sap-tutorials/Tutorials#23740]
Tutorials: https://developers.sap.com/tutorials/cp-starter-isuite-api-management.html
--------------------------

Dear SAP Team,

I reprocessed at least twice all steps until "step 3" and I do not get the same reply as shown on the tutorial.

If it is my mistake, I apologize in advance.

Troubleshooting:
1) I do not receive an HTPP 401 error message, but an HTTP 404
2) There is no instances created on the BTP Subaccounts view, under: SERVICES \ "Instances and Subscription" under the "instances(0) " view.

![2024_09_17_SAP_BTP_tutorial_REST_API_STEP_3_pix_0](https://github.com/user-attachments/assets/851b78d1-8f5c-4336-8554-e842396217b4)
![2024_09_17_SAP_BTP_tutorial_REST_API_STEP_3_pix_1](https://github.com/user-attachments/assets/d679c352-d389-4453-9edd-fd7e9a5ef188)

Many thank in advance for your time and help.
Daniel

**Comment by Karunaharan** [comment]
Hi @Putzsch 
It could be that the webshop was down and you got the 404 error which is fine. Please try later.

With regards to this comment:
**_There is no instances created on the BTP Subaccounts view, under: SERVICES \ "Instances and Subscription" under the "instances(0) " view._**
The booster might not have been executed completely at this step: https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html#8a5e5cb1-4a39-445b-b9e4-1363df1eccc3
Please execute this step again.

I hope this helps!

Karuna
