### ISSUE TITLE
Expose Integration Flow Endpoint as API and Test the Flow

### ISSUE THREAD

**Issue by lgaaloul** [sap-tutorials/Tutorials#23749]
Tutorials: https://developers.sap.com/tutorials/cp-starter-isuite-api-management.html
--------------------------

Error When execute API : Cannot connect to host zeus.hana.prod.eu-central-1 

Hello

In step 4 "Execute API" of the tutorial "[Expose Integration Flow Endpoint as API and Test the Flow](https://developers.sap.com/tutorials/cp-starter-isuite-api-management.html)" I have the following error message

<?xml version='1.0' encoding='UTF-8'?><error xmlns="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"><code/><message xml:lang="en">

Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.8.v20201217-ecdf3c32c4): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: com.sap.db.jdbc.exceptions.JDBCDriverException: SAP DBTech JDBC: Cannot connect to jdbc:sap://zeus.hana.prod.eu-central-1.whitney.dbaas.ondemand.com:22716 [Cannot connect to host zeus.hana.prod.eu-central-1.whitney.dbaas.ondemand.com/18.196.126.43:22716 [java.net.ConnectException: error 111 - Connection refused], -813.].
Error Code: -813
Call: SELECT PRODUCT_ID, CATEGORY, CATEGORY_NAME, CURRENCY_CODE, DIMENSION_DEPTH, DIMENSION_HEIGHT, DIMENSION_UNIT, DIMENSION_WIDTH, LONG_DESCRIPTION, NAME, PICTURE_URL, PRICE, QUANTITY_UNIT, SHORT_DESCRIPTION, SUPPLIER_ID, WEIGHT, WEIGHT_UNIT, SUPPLIER_SUPPLIER_ID FROM ESPM_PRODUCT WHERE PRODUCT_ID LIKE ? ESCAPE '\'
bind => [1 parameter bound]
Query: ReadAllQuery(referenceClass=Product sql="SELECT PRODUCT_ID, CATEGORY, CATEGORY_NAME, CURRENCY_CODE, DIMENSION_DEPTH, DIMENSION_HEIGHT, DIMENSION_UNIT, DIMENSION_WIDTH, LONG_DESCRIPTION, NAME, PICTURE_URL, PRICE, QUANTITY_UNIT, SHORT_DESCRIPTION, SUPPLIER_ID, WEIGHT, WEIGHT_UNIT, SUPPLIER_SUPPLIER_ID FROM ESPM_PRODUCT WHERE PRODUCT_ID LIKE ? ESCAPE '\'")</message></error>

![Step_5](https://github.com/user-attachments/assets/9b22fda3-47ae-4fc8-8d28-334ee76ec704)

Thank You

**Comment by jmmargo** [comment]
@Karunaharan can you please respond to this user's feedback?  Thank you.

**Comment by Karunaharan** [comment]
Hi @lgaaloul, are you using a different receiver system to fetch details? It seems so to me. If it is different, I'll not be able to help. Please let me know.

**Comment by lgaaloul** [comment]
Hi @Karunaharan 

Thank you for your reply.
![Uploading step_receiver.jpg…]()
Attached is a screenshot of the integration process I have only one receiver.
