### ISSUE TITLE
Add an API Proxy to a Product

### ISSUE THREAD

**Issue by lgaaloul** [sap-tutorials/Tutorials#23748]
Tutorials: https://developers.sap.com/tutorials/hcp-apim-create-product.html
--------------------------
Hello

In step 7 when I click on publish I have the following error: 

Unable to publish Product
null
[Request ID: 15c271ae-a4ec-47be-91dc-e9fa5edaf402]
![step_7](https://github.com/user-attachments/assets/39287626-540d-49b4-9726-b69e9b7fa8a0)

thank you

**Comment by jmmargo** [comment]
@Karunaharan can you please respond to this user's feedback?  Thank you.

**Comment by Karunaharan** [comment]
Hi @lgaaloul - I tried to reproduce the scenario and I was able to publish the API. Could you please try again?

**Comment by lgaaloul** [comment]
> Hi @lgaaloul - I tried to reproduce the scenario and I was able to publish the API. Could you please try again?

Hi,
thanks for your answer
I tried again attached screen prints of the steps I have another error message

![step_1](https://github.com/user-attachments/assets/1932e282-050f-4372-910a-307448d5d822)
![step_2](https://github.com/user-attachments/assets/c12aca42-94bb-4200-be80-d03aa69fcfac)
![step_3](https://github.com/user-attachments/assets/fafa601b-15f5-40ce-8ec7-e5127bb16f21)
