### ISSUE TITLE
Installing SAP HANA, express edition with Docker

### ISSUE THREAD

**Issue by gregorwolf** [sap-tutorials/Tutorials#23743]
Tutorials: https://developers.sap.com/tutorials/hxe-ua-install-using-docker.html
--------------------------

I'm running the ABAP Developer Trial which comes with a built-in HANA DB on my Ubuntu 22.04.5 LTS without any issues. Today I've tried to run start [saplabs/hanaexpress](https://hub.docker.com/r/saplabs/hanaexpress) with the following (already adjusted command):

```
docker run -p 39013:39013 -p 39017:39017 -p 39041-39045:39041-39045 -p 1128-1129:1128-1129 \
-p 59013-59014:59013-59014 \
-v /home/gwolf/projects/hxe:/hana/mounts \
--ulimit nofile=1048576:1048576 \
--sysctl kernel.shmmax=1073741824 \
--sysctl net.ipv4.ip_local_port_range='40000 60999' \
--sysctl kernel.shmall=8388608 \
--name hxe \
saplabs/hanaexpress:latest \
--passwords-url file://hana/mounts/hxe.json \
--agree-to-sap-license
```

but I got this error:

```
======== Starting HANA container run script ========
Started at: Wed Sep 18 12:11:29 UTC 2024
Script parameters: --passwords-url file://hana/mounts/hxe.json --agree-to-sap-license
HANA version: 2.00.076.00.1705400033
WARNING: Unsupported Linux kernel version 5.15. Supported are 3.12 and 4.4+.
ERROR: Unknown host '45677630bc78'. The container must be started with one of these host names:
ERROR: 	2d54a5c2223f
```

I found also #4628 describing the same issue. Is there any hope that Ubuntu will be supported? It should not be an issue as the HANA for the ABAP Developer Trial works just fine.

**Comment by JCurrie27** [comment]
I haven't heard of any plans for Ubuntu support for HXE but I suggesting posting this question to the HANA Express community  page to take advantage of the community support model. The Q&A page receives much more traffic, and other users may be able to provide answers / workarounds immediately.

**Comment by gregorwolf** [comment]
Posted at https://community.sap.com/t5/technology-q-a/hana-express-docker-on-ubuntu/qaq-p/13870073#M4884359

**Comment by gregorwolf** [comment]
With the help of @se38 I discovered that adding:

```
-h b6557dacdfc6
```

in front of `--name hxe` fixes the issue and now the HXE is also running on my Ubuntu 22.04.5 LTS.
