### ISSUE TITLE
Broken link in Tutorial "Create a Full-Stack Application with SAP Fiori UI using Joule in SAP Build Code"

### ISSUE THREAD

**Issue by jascha-S** [sap-tutorials/Tutorials#23741]
Tutorials: https://developers.sap.com/tutorials/build-code-test-drive.html
--------------------------

In Step 7, the link in "See [Working in the Dev Space Manager]" is broken ("Sorry
We couldn't find that page.").
I assume it should point to this instead:
https://help.sap.com/docs/build_code/d0d8f5bfc3d640478854e6f4e7c7584a/ad40d52d0bea4d79baaf9626509caf33.html?q=Working%20in%20the%20Dev%20Space%20Manager&locale=en-US

**Comment by jmmargo** [comment]
@Paolaufer please respond to this user's feedback.  Thank you.

**Comment by ShiraManas** [comment]
Yes, you are correct. The link has been updated in the tutorial. Thank you for your feedback!

**Comment by jascha-S** [comment]
Thanks :)
