### ISSUE TITLE
Get Started with SAP API Management

### ISSUE THREAD

**Issue by sejopa80** [sap-tutorials/Tutorials#23745]
Group: https://developers.sap.com/group.cp-apim-code-1.html
--------------------------

I’ve been following a tutorial, and I noticed that the screenshots no longer match the current version of the product. Additionally, the automatic role assignment using boosters doesn’t seem to be working. Even after manually assigning all available roles, the process still doesn’t function as expected.

These tutorials are a fantastic resource for the community, and it would be incredibly helpful if they could be updated to reflect the latest changes. I appreciate the efforts of the authors and believe that updating this content would greatly benefit many users learning or working with these technologies. Thank you for your attention!

**Comment by jmmargo** [comment]
@Karunaharan can you please respond to this user's feedback?  Thank you.

**Comment by sejopa80** [comment]
Hello @jmmargo and @Karunaharan ,

I wanted to follow up on my previous feedback regarding the outdated screenshots and issues with role assignments. Since then, I’ve come across new tutorials that are up-to-date with the latest versions, and I was able to follow them without any issues.

I truly appreciate the effort that goes into maintaining and creating these tutorials. They have been incredibly beneficial for me and the community. 

Thank you once again for all the hard work!

Best regards,
