### ISSUE TITLE
Expose Integration Flow Endpoint as API and Test the Flow

### ISSUE THREAD

**Issue by lgaaloul** [sap-tutorials/Tutorials#23753]
Tutorials: https://developers.sap.com/tutorials/cp-starter-isuite-api-management.html
--------------------------

Error When execute API : Cannot connect to host zeus.hana.prod.eu-central-1

Hello

I created a ticket #23749 but it was closed without being resolved.

![Step_5](https://github.com/user-attachments/assets/f6a72d6f-0afd-494c-aef4-8192837666d7)
![step_receiver](https://github.com/user-attachments/assets/c2f45674-33bd-4d6d-8c32-4dd28cda1cf7)

In step 4 "Execute API" of the tutorial "[Expose Integration Flow Endpoint as API and Test the Flow](https://developers.sap.com/tutorials/cp-starter-isuite-api-management.html)" I have the following error message

Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.8.v20201217-ecdf3c32c4): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: com.sap.db.jdbc.exceptions.JDBCDriverException: SAP DBTech JDBC: Cannot connect to jdbc:sap://zeus.hana.prod.eu-central-1.whitney.dbaas.ondemand.com:22716 [Cannot connect to host zeus.hana.prod.eu-central-1.whitney.dbaas.ondemand.com/18.196.126.43:22716 [java.net.ConnectException: error 111 - Connection refused], -813.].
Error Code: -813
Call: SELECT PRODUCT_ID, CATEGORY, CATEGORY_NAME, CURRENCY_CODE, DIMENSION_DEPTH, DIMENSION_HEIGHT, DIMENSION_UNIT, DIMENSION_WIDTH, LONG_DESCRIPTION, NAME, PICTURE_URL, PRICE, QUANTITY_UNIT, SHORT_DESCRIPTION, SUPPLIER_ID, WEIGHT, WEIGHT_UNIT, SUPPLIER_SUPPLIER_ID FROM ESPM_PRODUCT WHERE PRODUCT_ID LIKE ? ESCAPE ''
bind => [1 parameter bound]
Query: ReadAllQuery(referenceClass=Product sql="SELECT PRODUCT_ID, CATEGORY, CATEGORY_NAME, CURRENCY_CODE, DIMENSION_DEPTH, DIMENSION_HEIGHT, DIMENSION_UNIT, DIMENSION_WIDTH, LONG_DESCRIPTION, NAME, PICTURE_URL, PRICE, QUANTITY_UNIT, SHORT_DESCRIPTION, SUPPLIER_ID, WEIGHT, WEIGHT_UNIT, SUPPLIER_SUPPLIER_ID FROM ESPM_PRODUCT WHERE PRODUCT_ID LIKE ? ESCAPE ''")

**Comment by jmmargo** [comment]
@Karunaharan please respond to this user's feedback.  Thank you.

**Comment by Karunaharan** [comment]
Hi @lgaaloul - what is the receiver system that you are connecting to? Please confirm.

**Comment by lgaaloul** [comment]
Hi @Karunaharan 

Below is my receiver configuration as shown in step 6 of the tutorial

![step_receiver_1](https://github.com/user-attachments/assets/838ae9a7-d17d-41a4-9f7d-702836149371)
![step_receiver_2](https://github.com/user-attachments/assets/95e23f13-8845-40c7-a2dd-2dfe2ce01dd5)
![step_receiver_def](https://github.com/user-attachments/assets/6d3d2f9f-e6b4-4c19-a40a-8091b23cccf8)

Thanks

**Comment by Karunaharan** [comment]
I'm not sure what you refer to by "**_Cannot connect to host zeus.hana.prod.eu-central-1.whitney.dbaas.ondemand.com_**"

It might be the case that the webshop application is intermittently down. Please try after some time. I'll check from my side as well.

**Comment by Karunaharan** [comment]
Hi @lgaaloul 
The webshop app didn't work with the mentioned URL. It is changed to https://refapps-espm-ui.cfapps.eu10.hana.ondemand.com.
The same is updated in the tutorial too. Please try now.

Karuna

**Comment by lgaaloul** [comment]
Hi @Karunaharan 

Thanks, it works.
