### ISSUE TITLE
Connect Your SAP Build Application to a Public API

### ISSUE THREAD

**Issue by jeffer9111** [sap-tutorials/Tutorials#23757]
Tutorials: https://developers.sap.com/tutorials/appgyver-connect-publicapi.html
--------------------------

Currently, this section is not updated. Today, I tried to set up the REST service https://world.openfoodfacts.org/api/v0 but the UI is different, and I couldn't find the "URL placeholder" section. I tried creating values both "Resource Schema" and" and "Additional Inputs" but the relative path "/product/{barcode}.json" didn't replace the "{barcode}".

**Picture from tutorial**
![image](https://github.com/user-attachments/assets/e641dcf8-26c8-471e-a786-204115c2209f)

**Picture from SAP Build right now**
![image](https://github.com/user-attachments/assets/c3aa5548-b6d5-43f2-8cf5-0d15171fb594)

**Comment by thecodester** [comment]
Dev says they recognize the serious of the changes, but I am not sure when they will "fix" ... I will check with them tomorrow and if will take a while I will update the tutorial with a workaround.

**Comment by thecodester** [comment]
The entire mission of 5 tutorials have been rewritten, including screenshots, and I hope you find it much improved. 

The data resource process in tutorial 3 has been updated to reflect changes in the product.

I will close the issue. But if you need anything else, feel free to comment here or even reppen.
