### ISSUE TITLE
Install the Cloud Foundry Command Line Interface (CLI) - outdated cli version for SAP BTP CF Environment

### ISSUE THREAD

**Issue by corporatemax** [sap-tutorials/Tutorials#23758]
Tutorials: https://developers.sap.com/tutorials/cp-cf-download-cli.html
--------------------------

Write here how you think we can improve the tutorial ...

... in exchanging the guide for the v7 cli version with the v8 cli version. 
See in [BTP SAP help documentation](https://help.sap.com/docs/btp/sap-business-technology-platform/cloud-foundry-environment#sap-btp-specific-configurations) regarding recommended cli version.

If you want to accept this issue, I can provide a patch / PR for this tutorial.

**Comment by jmmargo** [comment]
@nicoschoenteich can you please respond to this user's feedback?  Thank you.
