### ISSUE TITLE
Connect Your SAP Build Application to a Public API

### ISSUE THREAD

**Issue by Matthias-Adams** [sap-tutorials/Tutorials#23755]
Tutorials: https://developers.sap.com/tutorials/appgyver-connect-publicapi.html
--------------------------

Hi, there was a major UI update in SAP Build apps, so Step 1: Add data resources needs to be reworked.
I started to set it up but then I experienced issues with the open source API: https://world.openfoodfacts.org/api/v0/product/6416453061361
Server is not responding, seems there is high load on it. -> new backend needed.

**Comment by Matthias-Adams** [comment]
@thecodester FYI

**Comment by Matthias-Adams** [comment]
Instead of the .org server one can leverage the .net address, which is way faster:
https://world.openfoodfacts.net/api/v0/product/6416453061361

**Comment by jmmargo** [comment]
@thecodester can you please respond to this user's feedback?  Thank you.

**Comment by thecodester** [comment]
@Matthias-Adams  Thanks for bringing to my attention. There will be a significant UX redesign in a couple of weeks so I will wait to redo the tutorials until then, but will update the tutorials for the change in UI and provide the better URL. Thanks so much.

**Comment by thecodester** [comment]
I have rewritten the tutorial and hope it solves any issues. I did not change the URL since in my testing it worked. Note I also rewrote the tutorial assuming users are using the SAP BTP trial account.

I will close the issue. But if you need anything else, feel free to comment here or even reopen.
