### ISSUE TITLE
Deploy a CAP Business Service to SAP Business Technology Platform

### ISSUE THREAD

**Issue by J-saby** [sap-tutorials/Tutorials#23754]
Tutorials: https://developers.sap.com/tutorials/cap-service-deploy.html
--------------------------

Hi,
When I want to deploy MTA ( cf deploy gen/mta.tar), step3 of the tutorial, I am facing this error message:

Binding service instance "my-bookshop-db" to application "my-bookshop-db-deployer"...
Binding service instance "my-bookshop-auth" to application "my-bookshop"...
Binding service instance "my-bookshop-auth" to application "my-bookshop-srv"...
Error while binding service instance "my-bookshop-db" to application "my-bookshop-srv": Could not bind service "my-bookshop-db" to application "my-bookshop-srv": 422 Unprocessable Entity: CF-UnprocessableEntity(10008): Service instance not found 
Error while binding service instance "my-bookshop-db" to application "my-bookshop-db-deployer": Could not bind service "my-bookshop-db" to application "my-bookshop-db-deployer": 422 Unprocessable Entity: CF-UnprocessableEntity(10008): Service instance not found 

![image](https://github.com/user-attachments/assets/4b589eeb-71eb-4e38-af6c-ab6eefc89580)
![image](https://github.com/user-attachments/assets/4fd738f2-07c4-4716-a879-e8d4bd2c5216)

[my-bookshop.log](https://github.com/user-attachments/files/17111245/my-bookshop.log)
[my-bookshop-db-deployer.log](https://github.com/user-attachments/files/17111247/my-bookshop-db-deployer.log)
[my-bookshop-srv.log](https://github.com/user-attachments/files/17111248/my-bookshop-srv.log)
[OPERATION.log](https://github.com/user-attachments/files/17111249/OPERATION.log)

Do you have an idea of the root cause of this error?
Thanks,
Regards,
Jonathan

**Comment by renejeglinsky** [comment]
Hi Jonathan,
please check if your HANA DB is running. On trial landscapes it's stopped overnight.

**Comment by J-saby** [comment]
Hi René,
Finally I deleted the instance in error and redeployed it. The DB instance is now running but I still have an error:

```
Execution of task "deploy" on application "my-bookshop-db-deployer" failed.
Download the application logs via the dmol command and check them for more information.
A step of the process has failed. Retrying it may solve the issue.
Application "my-bookshop" started and available at "a49aae46trial-dev-my-bookshop.cfapps.us10-001.hana.ondemand.com"
Application "my-bookshop-srv" started and available at "a49aae46trial-dev-my-bookshop-srv.cfapps.us10-001.hana.ondemand.com"
Proceeding with automatic retry... (1 of 3 attempts left)
Executing task "deploy" on application "my-bookshop-db-deployer"...
Execution of task "deploy" on application "my-bookshop-db-deployer" failed.
Download the application logs via the dmol command and check them for more information.
A step of the process has failed. Retrying it may solve the issue.
Process failed.
```

 I can access to the application but I have an error and I opened it

![image](https://github.com/user-attachments/assets/6ba2d55c-70ee-411c-8f3b-99352097a716)
![image](https://github.com/user-attachments/assets/26199ec6-8932-45f1-8205-b48a2f97c1ee)

**Comment by renejeglinsky** [comment]
Hm, I can't really make sense out of it. I assume the error is based on infrastructure and would guess that everything runs smoothly tomorrow. Anyway, if you like , please attach the full logs (using the `dmol` command as the output proposes, there should as well we the proper command in the output to download the logs) and I'll have a look.

**Comment by J-saby** [comment]
Thanks René, find the attached logs 

[my-bookshop.log](https://github.com/user-attachments/files/17115149/my-bookshop.log)
[my-bookshop-db-deployer.log](https://github.com/user-attachments/files/17115150/my-bookshop-db-deployer.log)
[my-bookshop-srv.log](https://github.com/user-attachments/files/17115151/my-bookshop-srv.log)
[OPERATION.log](https://github.com/user-attachments/files/17115152/OPERATION.log)

**Comment by renejeglinsky** [comment]
Did you configure your HANA to allow all IP addresses?

**Comment by renejeglinsky** [comment]
The log doesn't seem to have a hint on an issue with your project. So either it's the IP thing or let's just wait and try again tomorrow.

**Comment by J-saby** [comment]
Hello René,
I clicked on the run button in the application space and it works fine now...

![image](https://github.com/user-attachments/assets/5e68fc28-d388-4c98-8e25-ce58e75e70e1)

**Comment by renejeglinsky** [comment]
Thanks a lot Jonathan! I'll have a look if the linked tutorials has changed. Previously that information was covered there. If that's not the case anymore, I'll enhance this tutorial.
