### ISSUE TITLE
Request Product Details with an Integration Scenario

### ISSUE THREAD

**Issue by JuergenMair** [sap-tutorials/Tutorials#23752]
Mission: https://developers.sap.com/mission.cp-starter-integration-cpi.html
--------------------------

Write here how you think we can improve the tutorial ...

The URL for the Web shop https://refapp-espm-ui-cf.cfapps.eu10.hana.ondemand.com/espm-cloud-web/espm.svc in the Tutorial "Design and Deploy Your First Integration Flow", Step 6 "Connect request reply to receiver" is not working. In the next step I get an connection error "Failed to connect to system.". See also screenshot. 

<img width="1489" alt="Screenshot 2024-09-23 at 23 05 47" src="https://github.com/user-attachments/assets/cc67b699-e821-4e27-8117-ec5d280e6bbf">

**Comment by jmmargo** [comment]
@Karunaharan please respond to this user's feedback.  Thank you .

**Comment by Karunaharan** [comment]
Hi @JuergenMair - this could have been an intermittent issue. It looks like the webshop application was down when you reported the issue. Could you please try later in the day?

**Comment by JuergenMair** [comment]
Hi @Karunaharan , I gave it another try but still get the same error message.

**Comment by Karunaharan** [comment]
Hi @JuergenMair  - thanks for noticing that. Yes, the app doesn't work with the mentioned URL. it is changed to https://refapps-espm-ui.cfapps.eu10.hana.ondemand.com. Apologies for the inconvenience. 
The same is updated in the tutorial too. Please try now.

Karuna
