### ISSUE TITLE
Create a CAP Business Service with Node.js Using Visual Studio Code

### ISSUE THREAD

**Issue by francisco-milan** [sap-tutorials/Tutorials#23762]
Tutorials: https://developers.sap.com/tutorials/cp-apm-nodejs-create-service.html
--------------------------

Write here how you think we can improve the tutorial ...

Hi there,

I am currently stuck at STEP 7 - Add Initial Data and have encountered an issue.

After executing the command cds add data, nothing seems to happen. The expected outcome was that the database tables would be created with initial data, and CSV files with a single header line for all entities would be added to the db/data folder. However, nothing has been generated in that directory.

It seems like there may be missing steps, or perhaps I have overlooked something. Could you please provide some guidance on what might be going wrong?

I've attached screenshots to illustrate the situation:

The step I'm stuck on.

![image](https://github.com/user-attachments/assets/254c2fc0-fedf-46da-8b51-85244183f3e8)

The empty db/data folder.

![image](https://github.com/user-attachments/assets/b8e192e2-b661-4647-be64-3b8e046f9334)

Thank you for your help!

Best regards,

Francisco Milan.

**Comment by jmmargo** [comment]
@renejeglinsky can you please assist this user?  Thank you.

**Comment by renejeglinsky** [comment]
Hi Francesco,
I can't reproduce this behavior, but I have questions:
- Has that db/data folder been generated and only the files are missing? 
- Have you done this step successfully before and are reusing an existing project? I'm asking, because at this step you normally  wouldn't have a `cat-service.js` file.
- What is the output when you execute `cds add data`? This is how it looks for me:
![image](https://github.com/user-attachments/assets/e341807c-498a-46c8-9d03-ec8fbc39fbae)

**Comment by francisco-milan** [comment]
Hi @renejeglinsky,

    Thanks a lot for your message!
To answer your questions:

- Has that db/data folder been generated and only the files are missing?_
The db/data folder has been generated, but it seems that some files are missing, which is what led me to this issue.

- Have you done this step successfully before and are reusing an existing project? I'm asking, because at this step you normally wouldn't have a cat-service.js file.
No, I haven't completed this step before with another project, and I'm not reusing an existing one. I started this project from scratch.

- What is the output when you execute cds add data? This is how it looks for me:
I have just executed the cds add data command again, and this time the files were generated with the initial data. To be honest, I can't reproduce the issue now, so I'm not sure how it was resolved. I might try going through the tutorial from scratch again to see if I can find any clues about what happened.
![image](https://github.com/user-attachments/assets/a31a1cb5-4eee-4d30-8b29-97c2f7d67132)

- Please provide the versions you're using (cds v -i).
![image](https://github.com/user-attachments/assets/3279ed83-1ec2-4ae2-84ab-562dcd59bc74)

In any case, the issue is now resolved, and I can proceed with the remaining steps. Thank you for your help—I really appreciate it!

Best regards,
Francisco.

**Comment by francisco-milan** [comment]
- _I'm asking, because at this step you normally wouldn't have a cat-service.js file._

oh... and I forgot to mention that I had the **"cat-service.js file"** file after executing STEP 5 of the Tutorial.

![image](https://github.com/user-attachments/assets/600d6bb5-307a-4feb-8f95-3cda789a888c)

**Comment by renejeglinsky** [comment]
Hi Francesco,
I'm glad it worked now and you can continue. Anyway it's odd that the folder has been generated and the files not. If you find any clues, please let us know about it :)

Thanks,
René
