### ISSUE TITLE
Design and Deploy Your First Integration Flow

### ISSUE THREAD

**Issue by marciofhome** [sap-tutorials/Tutorials#23768]
Tutorials: https://developers.sap.com/tutorials/cp-starter-integration-cpi-design-iflow.html
--------------------------

Write here how you think we can improve the tutorial ...

Hi, I think that the URL https://refapp-espm-ui-cf.cfapps.eu10.hana.ondemand.com/espm-cloud-web/espm.svc is not working anymore. 

When  try o consume , I receive the follow error:

404 Not Found: Requested route ('refapp-espm-ui-cf.cfapps.eu10.hana.ondemand.com') does not exist.

Regards,
Márcio

**Comment by jmmargo** [comment]
@Karunaharan can you please respond to this user's feedback?  Thank you.

**Comment by Karunaharan** [comment]
Hi @marciofhome - thanks for noticing that. Yes, the app doesn't work with the mentioned URL. it is changed to https://refapps-espm-ui.cfapps.eu10.hana.ondemand.com.
The same is updated in the tutorial too. Please try now.

Karuna

**Comment by marciofhome** [comment]
O have one more question, in my Trial version I can't find tokenurl as
mentioned in the tutorial Expose Integration Flow Endpoint as API and Test
the Flow | SAP Tutorials
<https://developers.sap.com/tutorials/cp-starter-isuite-api-management.html>

[image: image.png]
Do I need make something ?

Regards,
Márcio
