### ISSUE TITLE
Deploy a CAP Business Service to SAP Business Technology Platform

### ISSUE THREAD

**Issue by francisco-milan** [sap-tutorials/Tutorials#23766]
Tutorials: https://developers.sap.com/tutorials/cap-service-deploy.html
--------------------------

Write here how you think we can improve the tutorial ...

Hi there,

 I'm stuck at step 3.2 of this Tutorial, 

![image](https://github.com/user-attachments/assets/81b459a4-91c0-46b3-abb6-474941d4ccfa)

As you can see in the image above, the deployment failed, the step instructions briefly mentioned a workaround, but unfortunately I don't know how to make sure that my IP address is configured for connections to SAP HANA Cloud, or how to allow connections to all IP addresses, and how to revert that setting after completing the tutorial. Can you please elaborate on this?

![image](https://github.com/user-attachments/assets/43e1a63f-5c79-4f9b-b863-8424894c5042)

**Comment by jmmargo** [comment]
@renejeglinsky can you please respond to this user's feedback?  Thank you.

**Comment by renejeglinsky** [comment]
Hi @francisco-milan ,

wrt your question, here you can find the HANA tutorial that explains how to configure it: https://developers.sap.com/tutorials/hana-cloud-mission-trial-3.html#204264de-101c-4611-bbe0-88b26d3e8aad

But if that really is the issue, we can only find out of you provide the logs using the `dmol` command, as proposed in the CLI output. Could you please attach it?

Thanks,
René

**Comment by francisco-milan** [comment]
Hi René,

Thank you for the tutorial link. I’ve already generated the logs and attached them to the GitHub issue for your review.

[my-bookshop-logs.zip](https://github.com/user-attachments/files/17212655/my-bookshop-logs.zip)

Please let me know if you need anything else from my side.

Thanks again for your assistance!

Best regards,
Francisco.

**Comment by renejeglinsky** [comment]
Hi Francisco,
have you configured your SAP HANA to allow all OP addresses and tested it again? To me it really looks like this error. I can't find a hint that something is wrong with your project configuration.

All the best,
René
