### ISSUE TITLE
Overview of Cloud Foundry Application Container Metrics

### ISSUE THREAD

**Issue by wozjac** [sap-tutorials/Tutorials#23778]
Tutorials: https://developers.sap.com/tutorials/cp-cf-overview-application-metrics.html
--------------------------

Regarding the `cpu_entitlement` - the plugin is no longer needed.
My version: cf version 8.8.2+483578cb2.2024-09-20
Ouput:
![image](https://github.com/user-attachments/assets/fdc4b9c5-5b82-4b7e-ad70-3f96c316c653)

See: https://github.com/cloudfoundry/cli/issues/2812 and https://github.com/cloudfoundry/community/pull/988

Best Regards,
Jacek

**Comment by jmmargo** [comment]
@beyhan please consider the user's feedback for your tutorial.  Thank you.

**Comment by beyhan** [comment]
Thanks @wozjac for brining this up. I will update the tutorial.
