### ISSUE TITLE
Add the Consumption of an External Service to Your CAP Application

### ISSUE THREAD

**Issue by binpath** [sap-tutorials/Tutorials#23774]
Tutorials: https://developers.sap.com/tutorials/btp-app-ext-service-add-consumption.html
--------------------------

It would be really helpfull to try a deep insert or the CRUD for external service, al of the tutorials are simple doing the get o READ.

kind regards, 
Cesar

**Comment by smahati** [comment]
Hi Cesar,

Thank you for the feedback. These use cases are simple but these particular tutorials have been deprecated. I have noted your feedback and I am passing it on for use in other enablement materials, this tutorial however cannot be updated. For the documentation on this topic you can check [here](https://cap.cloud.sap/docs/guides/using-services#execute-queries-with-node-js). If you have more information that you would like to add such as, what you're trying to achieve or what is not covered in the documentation, then that would be helpful and I can add that to the feedback.

Best regards,
Mahati

**Comment by binpath** [comment]
Hi Mahati, 

Thanks for the feedback, when do you plan tu update this deprecated tutorial?
Regarding the [topic](https://cap.cloud.sap/docs/guides/using-services#building-custom-requests-with-node-js) you shared I did use it, but there are missing details, for example how should the destination in BTP should be created to avoid the 403 Forbidden because of x-csrf-token. 

I'm having that issue right now. The other issue is that since cds version 8.3 they have created a validation.js and now the deep insert, here is the community forum [link](https://community.sap.com/t5/technology-q-a/issue-with-deep-entity-request-in-cap-cds-validate-issue-cds-v-8-3-0/qaq-p/13884902/comment-id/4886392#M4886392)

kind regards, 
Cesar

**Comment by smahati** [comment]
@binpath Thank you for the details, I'll check and update the topic.

**Comment by smahati** [comment]
Hi Cesar,

I see that the topic already includes information to [create destinations on SAP BTP](https://cap.cloud.sap/docs/guides/using-services#btp-destinations). For bugs like the one you linked will have to be fixed by development teams.

Best regards,
Mahati

**Comment by jmmargo** [comment]
@smahati did you want to close this issue?

**Comment by binpath** [comment]
@smahati Thanks for your feedback!

Regarding the destination, I saw the link, the problem basically is the "Manually create destinations" where it doesn't specify in detail the use case based on additional parameters if needed for the x-csrf-token. I guess is not needed.

Thanks you very much I know that the CAP team on the developer side should fix it. Never the less the "Delegate requests to external services" section in this tutorial needs adjustment, for update and delete. It would be nicely appreciated and easier for the CRUD example.

kind regards, 
Cesar
