### ISSUE TITLE
can not expand the block

### ISSUE THREAD

**Issue by coderjinhui** [sap-tutorials/Tutorials#23784]
Tutorials: 
https://developers.sap.com/tutorials/btp-app-work-zone-setup.html
https://developers.sap.com/tutorials/btp-app-prepare-xsuaa.html
--------------------------

Write here how you think we can improve the tutorial ...

Hi there,

When I use the https://developers.sap.com/tutorials, I found that the expand in some pages not work when I click the "+" button.
The tutorial I found that can not expand is write above.

Could any one help to solve it?

**Comment by jmmargo** [comment]
@smahati these tutorials state that they will be phased out.  Can you please reply to the user's feedback with suggested alternatives?  Should we remove these from production?

**Comment by smahati** [comment]
Hi Josua, @coderjinhui ,

I would suggest these groups be used instead: 

[1. local development](https://developers.sap.com/group.cap-application-full-stack.html)
[2. deploy to cloud foundry](https://developers.sap.com/group.deploy-full-stack-cap-application.html)
[3. deploy to kyma](https://developers.sap.com/group.deploy-full-stack-cap-kyma-runtime.html)

@jmmargo The mission is used in other missions/tutorials too, so all of them should be hidden for now.

Best regards,
Mahati

**Comment by smahati** [comment]
Hi, 

I'm closing as an alternative has been provided, if you need further support please create another issue.

Best regards,
Mahati
