### ISSUE TITLE
Protect Your API Proxy by Adding Application Key Verification

### ISSUE THREAD

**Issue by lgaaloul** [sap-tutorials/Tutorials#23780]
Tutorials: https://developers.sap.com/tutorials/hcp-apim-verify-api.html
--------------------------

Hi,

I've done all the steps but I'm stuck at step 4 despite my several attempts to answer the system displays that it's wrong.
Thank you for your help.

**Comment by jmmargo** [comment]
@Karunaharan please respond to this user's feedback.  Thank you.

**Comment by lgaaloul** [comment]
Hi,
 I found the answer the property  is STREAM.
