### ISSUE TITLE
Issue in Set Up for the Mobile Development Kit (MDK) in AP region

### ISSUE THREAD

**Issue by Akashbm964** [sap-tutorials/Tutorials#23785]
Hi Colleagues,

We are testing Starter scenarios for the October month cycle.
Here, we are not able to start the service **Get Started with SAP Build Code** in AP region

Tutorial link : https://developers.sap.com/group.mobile-dev-kit-setup.html
Trail account link : https://cockpit.hanatrial.ondemand.com/trial/#/home/trial

Steps to reproduce :

In tutorial link provided above , first two tutorial runs smoothly without any issue.

In the 3rd tutorial **Setup SAP Build Code in SAP BTP**
1. Launch the URL : https://cockpit.hanatrial.ondemand.com/trial/#/home/trial
2. Click on Go To Your Trial Account.
3. In the navigation pane, click Boosters.
4. Search for SAP Build Code.
5. Open the booster to see the overview, components, and additional resources, and click Start, Get Started with SAP Build Code page will appear.
6. Under the Select Scenario choose Select Subaccount click next.
7. Here under Configure Subaccount we are getting error as **Some entitlements are missing**

Please see the attached screenshot below.

![image](https://github.com/user-attachments/assets/eda00f60-ce40-4e65-881a-95f5dbca96a6)

Note : I tried adding the SAP build code service under Entitlements in the Side Navigation of the Global account 
Here , I am getting message as **This service is not available for new assignments in this subaccount's region.**

Please see the attached screenshot below.

![image](https://github.com/user-attachments/assets/35fbddf5-ccd9-4159-8db4-eb3664fea7c4)

Thanks & regards,
Akash

**Comment by jmmargo** [comment]
@jitendrakansal can you please reply to the user's feedback?  Thank you.

**Comment by jitendrakansal** [comment]
@Akashbm964 @jmmargo 
The trial version of SAP Build Code is currently only available in the **US10** region, it is not available in AP21, hence you see the entitlement missing message.  

You can delete your current trial account and create a new one in US region to continue.

**Comment by jitendrakansal** [comment]
Closing, as this is working as expected. Pls. check my previous comment
