### ISSUE TITLE
Install the Cloud Foundry Command Line Interface (CLI)

### ISSUE THREAD

**Issue by horsemanjackyliu** [sap-tutorials/Tutorials#23788]
I think 80% of end users use MS Windows System.  Would you please also add the installation guide for MS Windows?

Tutorials: https://developers.sap.com/tutorials/cp-cf-download-cli.html
--------------------------

Write here how you think we can improve the tutorial ...

**Comment by jmmargo** [comment]
@nicoschoenteich can you please reply to this user's feedback?  Thank you.
