### ISSUE TITLE
Take a Tour of SAP BTP Trial - Navigation

### ISSUE THREAD

**Issue by ladenaw** [sap-tutorials/Tutorials#23792]
Tutorials: https://developers.sap.com/tutorials/cp-trial-quick-onboarding.html
--------------------------

**Problem Description**

This might be a silly one!

It seems to me, that the answer to this question:

"Enter the first item in the left hand-side navigation of your trial Cloud Foundry global account:"

should be: "Account Explorer". It is not accepted though.

Furthermore, I find the term "Cloud Foundry global account:" irritating. Is that the same as "global account" in this context? 

**Proposed Solution**

Update expected solution to "Account Explorer"

**Comment by jmmargo** [comment]
@Madeline-Schaefer can you please reply to this user's feedback?

**Comment by Madeline-Schaefer** [comment]
Hi Lennart,

Thank you for your valuable feedback!

We're in the process of updating the tutorial and will be changing the solution to "Account Explorer" soon. However, at the moment, the solution still reflects the older version with "subaccounts."

Regarding your second question, yes, the Cloud Foundry global account is indeed the same as the global account in this context. I hope this clears things up, but please feel free to reach out if you have any more questions or need further clarification!

Thanks again for your patience and understanding.

Best regards
Madeline

**Comment by ladenaw** [comment]
Hi Madeline, 

Thank you very much for your response and explanation. 

Best regards

Lennart
