### ISSUE TITLE
Setup SAP Build Code in SAP BTP

### ISSUE THREAD

**Issue by ceedee666** [sap-tutorials/Tutorials#23796]
Tutorials: https://developers.sap.com/tutorials/build-code-setup.html
--------------------------
When executing the booster in a trial account for an existing subaccount one needs to select the custom identity provider in step 3. The default selection is a Custom IAS tenant which did not work in my case. It lead to conflicts as I used the sam email address as I used for the SAP universal ID. As a result I was not able to sign in to SAP Build Code. 

I think one needs to select the default identity provider. This should be made clear in the tutorial.

![CleanShot 2024-10-22 at 08 52 06](https://github.com/user-attachments/assets/7e2bf5bd-1367-4f36-90b5-ac6bab980890)

Christian

**Comment by ceedee666** [comment]
Also in my case the boster failed because CF was already enabled in my account. AFAIK this is no problem but could be confusing for inexperienced users. 

![CleanShot 2024-10-22 at 08 56 25](https://github.com/user-attachments/assets/0d3b1549-9fcb-4715-b44d-ea5165dbe0ca)

**Comment by ceedee666** [comment]
> ## Tutorials: https://developers.sap.com/tutorials/build-code-setup.html
> 
> When executing the booster in a trial account for an existing subaccount one needs to select the custom identity provider in step 3. The default selection is a Custom IAS tenant which did not work in my case. It lead to conflicts as I used the sam email address as I used for the SAP universal ID. As a result I was not able to sign in to SAP Build Code.
> 
> I think one needs to select the default identity provider. This should be made clear in the tutorial.
> 
> ![CleanShot 2024-10-22 at 08 52 06](https://private-user-images.githubusercontent.com/235757/378715899-7e2bf5bd-1367-4f36-90b5-ac6bab980890.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1ODEyOTEsIm5iZiI6MTcyOTU4MDk5MSwicGF0aCI6Ii8yMzU3NTcvMzc4NzE1ODk5LTdlMmJmNWJkLTEzNjctNGYzNi05MGI1LWFjNmJhYjk4MDg5MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMlQwNzA5NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NTI2NTZjZDMxOWRiMjE3NGNiNDUyNzBhOTgwNzk0ZDNlN2I2NTZlNzhlZmYzYzVkOTRmM2VjMTA1MjdlYTRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wqV4oVzzRjOi-L7h9-hmE9gXeAEM5nHTloDtrNtSdcM)
> 
> Christian

I think my initial understanding here was wrong. The mistake I made was adding the email address of the logged in user again. I didn't read the text below the input field. I think it would be useful to add a hint to the tutorial.

**Comment by jmmargo** [comment]
@Paolaufer can you please respond to this user's feedback?  Thank you.

**Comment by Paolaufer** [comment]
Hi Christian,
Could you please resend the image?
I am unable to access it.
THanks,
Pao

**Comment by Paolaufer** [comment]
Hi Christian,
I cannot fix the note without seeing the image. I will close for the moment. Please reopen if you have the image.
