### ISSUE TITLE
Create a Full-Stack Application with SAP Fiori UI using Joule in SAP Build Code

### ISSUE THREAD

**Issue by fabiopagoti** [sap-tutorials/Tutorials#23800]
Tutorials: https://developers.sap.com/tutorials/build-code-test-drive.html
--------------------------

The following question has no correct answer which is accepted. 
_Follow the link above to the documentation "Working in the Dev Space Manager". There are 2 states your dev space can be in when you can download your dev space content. What are they?_

Because of that the tutorial cannot be completed.

**Comment by jmmargo** [comment]
@Paolaufer please respond to this user's feedback.  Thank you.

**Comment by Paolaufer** [comment]
Hi Fabio,
Thank you for your feedback.
I will fix this and let you know.

**Comment by ShiraManas** [comment]
Hi Fabio,
The question that you mentioned has been removed from the tutorial. Thanks for your feedback!
