### ISSUE TITLE
Failed to Open SAP HANA: Create SAP HANA Database Artifact

### ISSUE THREAD

**Issue by icesk127** [sap-tutorials/Tutorials#23817]
According to this tutorial
https://developers.sap.com/tutorials/hana-cloud-cap-calc-view.html

I'm on Step 1. I've tried to create a calculation view using the 'SAP HANA: Create SAP HANA Database Artifact'.
When I click on it, nothing happens. The Wizard doesn't show as expected.
Is there something wrong with the Wizard?

![image](https://github.com/user-attachments/assets/3af675f7-6534-486e-8492-8aa15cb2652a)

**Comment by icesk127** [comment]
I'm using Dev Space type 'Full-stack application with productivity tools'.

**Comment by jmmargo** [comment]
@jung-thomas can you please respond to this user's feedback?

Thank you.

**Comment by jung-thomas** [comment]
Can not recreate the problem.  The step is correct. If the wizard does not open, please enter a support ticket. 
Note from the screenshot it would appear you are using VSCode.  Try to perform the same operation in the SAP Business Application Studio. This tool is the only one in the scope of this tutorial.
