### ISSUE TITLE
Design and Deploy Your First Integration Flow

### ISSUE THREAD

**Issue by ajaysoreng** [sap-tutorials/Tutorials#23811]
Tutorials: https://developers.sap.com/tutorials/cp-starter-integration-cpi-design-iflow.html
--------------------------

Step 1.2 - The UI does not have any "OK" button - Please check and replace the latest screenshots

**Comment by Karunaharan** [comment]
hi @ajaysoreng 
The issue is fixed. You should be able to see the changes latest by tomorrow.
