### ISSUE TITLE
Set Up Integration Suite Trial

### ISSUE THREAD

**Issue by ajaysoreng** [sap-tutorials/Tutorials#23810]
Tutorials: https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html
--------------------------

The UI screenshots have changed for Step 3.1 Please update it. 
<img width="1504" alt="APIManagement" src="https://github.com/user-attachments/assets/4ce3dbf0-9bc0-4df2-94df-52995adc0ef1">

**Comment by Karunaharan** [comment]
Hi @ajaysoreng 
The issue is fixed. You will see the changes in a day's time.
