### ISSUE TITLE
Create a Full-Stack Application with SAP Fiori UI using Joule in SAP Build Code

### ISSUE THREAD

**Issue by rbrainey** [sap-tutorials/Tutorials#23820]
Tutorials: https://developers.sap.com/tutorials/build-code-test-drive.html
--------------------------

Joule is failing when I execute this tutorial.  I'm in the BTP Trial us10 region.  When I get to Step 3 Number 4 (Allowing Joule to enhance the sample Customer data table). I get the error "Cannot read properties of undefined (reading '0')"

Is this a known issue?

<img width="279" alt="Screenshot 2024-11-20 at 8 41 32 AM" src="https://github.com/user-attachments/assets/eb4faa63-2e14-41e5-ad10-2492c020ab13">

**Comment by Paolaufer** [comment]
Hi @rbrainey 
Thank you for contacting us.
I will look into your issue.

**Comment by Paolaufer** [comment]
HI, Please click the Regenerate button (the arrow cycle icon button) for another generation. That should solve the issue.
