### ISSUE TITLE
Implement a Business Add-in (BAdI) To Check a Purchase Requisition

### ISSUE THREAD

**Issue by GeorgeYu001** [sap-tutorials/Tutorials#7094]
Tutorials: https://developers.sap.com/tutorials/abap-s4hanacloud-procurement-purchasereq-checks.html
--------------------------

Write here how you think we can improve the tutorial ...

Hi Julie,
I enjoyed your tutorials very much. It is well written and organized. The new version of limit the quantity is better than the original flow control, more obvious to the users.

However, I have a suggestion to add a process flow to illustrate the concept better.  I created one for our SAP internal colleagues, and for your reference.

![image](https://user-images.githubusercontent.com/93267400/139077663-b625ba3e-9075-4513-8501-d97f47cc8386.png)

Best,
George

**Comment by julieplummer20** [comment]
Hi George, It has just occurred to me that this graphic would be useful, if we adapted it, in the other BADI tutorials. 
Since we are both internals, could you perhaps email me the original pptx file - for both speed and consistency?
I know this isn't your job ;-), but it would be really helpful.
Thanks a lot,
Julie.

**Comment by GeorgeYu001** [comment]
Hi Julie,
Sure. Here is my PPT.

By the way, Karl Kessler pointed me to your tutorial, because I am learning Steampunk.  If you have other new tutorials, I will be more than happy to test drive them 😊.

Best Regards,
George

**Comment by julieplummer20** [comment]
Hi George, I incorporated the graphic some time ago, so I am now closing this issue.
Please feel free to reopen it if you have any further questions or feedback.

Thanks a lot for these graphics; they were very useful. Best wishes, Julie.
