### ISSUE TITLE
tutorial cp-cf-security-xsuaa-create - npm.sap.com is not required anymore to run SAP packages locally

### ISSUE THREAD

**Issue by seVladimirs** [sap-tutorials/Tutorials#7100]
Tutorials: https://developers.sap.com/tutorials/cp-cf-security-xsuaa-create.html
--------------------------

Not sure but I think the usage of registry https://npm.sap.com is not required, and actually recommended to remove it - https://blogs.sap.com/2020/07/02/sap-npm-packages-now-on-npmjs.org/
![image](https://user-images.githubusercontent.com/9819889/139395371-f1785781-b065-448f-8a44-6c71ffc7edb9.png)

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
