### ISSUE TITLE
Access Protected SAP Analytics Cloud Resources with OAuth Two-Legged Flow

### ISSUE THREAD

**Issue by seVladimirs** [sap-tutorials/Tutorials#7101]
Tutorials: https://developers.sap.com/tutorials/sac-secure-oauth.html
--------------------------
SAP Cloud Platform is renamed to SAP Business Technology Platform ;) but not yet changed in the tutorial. 
![image](https://user-images.githubusercontent.com/9819889/139397037-15823629-ddc4-4021-bb90-e6308e1e42e3.png)

**Comment by mattschwarz-sap** [comment]
Hi @seVladimirs ,
Thanks for the feedback you provided for this tutorial. And: I'm very sorry for the late reply. We are currently reorganizing responsibilities so unfortunately it might take some further time to fix this issue.
Thanks & Best Regards,
Matthias

**Comment by MichaelCzcz** [comment]
@mattschwarz-sap what is the current status here? Has this been solved?

**Comment by Shrujit** [comment]
The issue is resolved. Please find the updated link: https://developers.sap.com/tutorials/sac-secure-oauth.html
