### ISSUE TITLE
Install the Kubernetes Command Line Tool

### ISSUE THREAD

**Issue by edwin7** [sap-tutorials/Tutorials#7102]
Tutorials: https://developers.sap.com/tutorials/cp-kyma-download-cli.html
--------------------------

add this to Prerequisites:
https://developers.sap.com/tutorials/cp-kyma-getting-started.html

**Comment by jcawley5** [comment]
Hello,

Thanks for the feedback. This change will be reflected in the next update which will be made available in the next coming weeks.

Regards,
Jamie
