### ISSUE TITLE
Tutorial Page cos-custom-rules.md Issue. PROD

### ISSUE THREAD

**Issue by SAPDocs** [sap-tutorials/Tutorials#7118]
Tutorial issue found: [https://github.com/SAPDocuments/Tutorials/blob/master/tutorials/cos-custom-rules/cos-custom-rules.md](https://github.com/SAPDocuments/Tutorials/blob/master/tutorials/cos-custom-rules/cos-custom-rules.md) contains invalid tags. Even though your tutorial was created, the invalid tags listed below were disregarded. Please double-check the following tags:
- topic>sap-api-business-hub

 Affected server: PROD

**Comment by mjeann** [comment]
Bug fix requested: https://github.com/sap-tutorials/Tutorials/pull/18074
