### ISSUE TITLE
enhancement - cp-aibus-dox-custom-schema : create custom schema and template for Document Information Extraction Trial UI

### ISSUE THREAD

**Issue by AmauryVanEspen** [sap-tutorials/Tutorials#7149]
Hello

please have a look to this contribution
[cp-aibus-dox-custom-schema](https://github.com/AmauryVanEspen/Tutorials/tree/patch-3/tutorials/cp-aibus-dox-custom-schema)

I've tried to start a feedback for the devtoberfest open source project and automatize my app with OpenSAP Certificates data from record of achivement documents

Regards

Amaury

**Comment by MichaelCzcz** [comment]
@AmauryVanEspen Thank you for your feedback. This channel is for issues regarding tutorials in the SAP Tutorial Navigator.
But if you could please provide the tutorial's author, I can assign this Github issue and your pull request to him/her. Thank you.

**Comment by AmauryVanEspen** [comment]
Hello @MichaelCzcz 
this was a "new submission" of tutorial. However, I've found this morning something quite similar here [Create Custom Schema for Custom Documents](https://developers.sap.com/tutorials/cp-aibus-dox-ui-schema-custom.html) from @Juliana-Morais 
I've started a [draft blog](https://blogs.sap.com/?p=1434371) about my own experience with Document Information Extraction thanks to this tutorials series.
Regards
Amaury

**Comment by Juliana-Morais** [comment]
Hi Amaury,

You're welcome! The tutorial missions have just been created:

- https://developers.sap.com/mission.btp-aibus-shape-ml.html
- https://developers.sap.com/mission.btp-aibus-shape-ml-custom.html

Let us know in case you have any feedback.

Best regards,
Juliana

**Comment by AmauryVanEspen** [comment]
Hello Juliana,

thank you for reaching me out.
I was looking for your linkedin profile and sap inbox =)
Great tutorial and mission,
would you be available for a short talk ?
Regards
Amaury

Le lun. 8 nov. 2021 à 09:10, Juliana Morais ***@***.***> a
écrit :

**Comment by MichaelCzcz** [comment]
@AmauryVanEspen I see. If you want to publish your new tutorial, please align with @Juliana-Morais and @thecodester. Thank you.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
