### ISSUE TITLE
Define a Validation Rule in an MDK App

### ISSUE THREAD

**Issue by Mark-Simunov** [sap-tutorials/Tutorials#7162]
Tutorials: https://developers.sap.com/tutorials/cp-mobile-dev-kit-add-validation.html
--------------------------

![image](https://user-images.githubusercontent.com/93543279/140783274-73500b14-3407-46f8-9437-2b811d893884.png)

In the emailValidation.js Rule file, the executeAction method is not returned, therefore it will not correctly function. This is not a major issue as typically the else statement is executed rather than the if statement and the rule functions as intended.

**Comment by jitendrakansal** [comment]
@Mark-Simunov  do you not see the line#5 (ValidationFailure.action) get executed in case email value doesn't contain @ ?

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
