### ISSUE TITLE
Set Up the SAP Launchpad Service

### ISSUE THREAD

**Issue by shivakumar-p-sap** [sap-tutorials/Tutorials#7178]
Tutorials: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-getting-started.html
--------------------------

Step 2: Add yourself to the Launchpad_Admin role

Please change the steps to add Launchpad_Admin role. Because in  Security > Trust Configuration Default Identity provider link is disabled as you can see in the below screenshot.
![image](https://user-images.githubusercontent.com/65213299/141088708-4d554d19-094d-4954-8634-2791a33361e4.png)

Change those step to Security > Users > Select your user > Scroll to Role Collections > Click on 3 dots > Click on Assign Role Collection > Select Launchpad_Admin > Click Assign Role Collection button.

Thanks and Regards
Shivakumar P

**Comment by PriyankaShivakumar** [comment]
This issue is fixed
