### ISSUE TITLE
Discover and Import the Live Process Package

### ISSUE THREAD

**Issue by bask-alur-gh** [sap-tutorials/Tutorials#7182]
Tutorials: https://developers.sap.com/tutorials/cp-cf-workflowmanagement-discover.html
--------------------------

Write here how you think we can improve the tutorial ...
The step1 doesn't work. The instruction "Ensure that the credentials of the trial user that are entered in the destination do not have Two Factor Authentication enabled." -- does it mean the UserID (say abc@yahoo.com) the user used does not have Two-factor authentication on Yahoo, or is there anywhere a 2-factor setup on this SAPID?  The error 'Not authorized' occurs when checking the Destination connection, regardless of turning OFF 2-factor at Yahoo (for example).  Please provide some clarity on what is needed exactly and how to get this resolved. Thank you!

**Comment by ArchanaShukla** [comment]
If you are using SAP Universal ID then please follow this SAP Note: https://launchpad.support.sap.com/#/notes/3085908. Check connection in Destination is bit faulty (we have informed the respective team). If you do check connection, and you get a green status which means that you connection is established. Ignore the error code.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
