### ISSUE TITLE
Create an ABAP Package - faulty prerequisite link

### ISSUE THREAD

**Issue by aliilkertopcu** [sap-tutorials/Tutorials#7183]
Tutorials: https://developers.sap.com/tutorials/abap-dev-create-package.html
--------------------------

Hi,
Prerequisite link is faulty, it navigates to the same site
https://developers.sap.com/tutorials/abap-dev-create-package.html

It must navigate to this I think:
https://developers.sap.com/tutorials/abap-create-project.html

BR
İlker

**Comment by julieplummer20** [comment]
Hi, 
Thank you for this.
I will fix this at once.
Best wishes,
Julie Plummer.

**Comment by julieplummer20** [comment]
Fixed

**Comment by aliilkertopcu** [comment]
Thank you!
Have a nice day.
