### ISSUE TITLE
Load Data into Standalone Data Lake in SAP HANA Cloud

### ISSUE THREAD

**Issue by CJSwift** [sap-tutorials/Tutorials#7188]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-hdl-getting-started-3.html
--------------------------

In Step 2 (the first SQL Code block in Step 2), there's an extra '*/' at the end of line 1. This causes the SQL to not work correctly and must be removed manually after it is copied

**Comment by VijayKrishnanSR** [comment]
Hi,

Thank you for letting us know. This error will be corrected soon. Hope the tutorial was helpful.

Regards,
Vijay

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
