### ISSUE TITLE
Run the Employee Onboarding Sample Scenario- Screenshot Update

### ISSUE THREAD

**Issue by PriyankaShivakumar** [sap-tutorials/Tutorials#7191]
Tutorials: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-5-run.html
--------------------------
**Step 3: View the process visibility workspace
Step 4: Execute the workflow sample application**

In Step 3- Point 1 and Step 4- Point 5, the screenshot of the Workflow Management Launchpad has to be changed. There is a new app-"Configure Workflow Intelligence Scenarios" under Productivity tools group as below:
![image](https://user-images.githubusercontent.com/65999547/141423027-666eef41-1730-4c3b-857b-8d815f3d98c9.png)

Best Regards,
Priyanka

**Comment by I559299** [comment]
Hi,
This issue still persists- screenshot yet to be updated!

**Comment by I559299** [comment]
The above issue didnt appear during this validation

**Comment by MichaelCzcz** [comment]
If this issue is solved, please close it.
