### ISSUE TITLE
Add Routing to a UI5 Web Components for React Project

### ISSUE THREAD

**Issue by axeladam** [sap-tutorials/Tutorials#7216]
Tutorials: https://developers.sap.com/tutorials/ui5-webcomponents-react-routing.html
--------------------------

Write here how you think we can improve the tutorial ...

https://stackoverflow.com/questions/69854011/matched-leaf-route-at-location-does-not-have-an-element
In V6, you can't use the component prop anymore. It was replaced in favor of element:
`<Route path="/" element={<Home />}></Route>`

Therefore in step 4 sub-step 2 the following does not work

```
<Routes>
      <Route path="/home" component={Home} />
      <Route path="/detail" component={Detail} />
      <Route path="/" element={<Navigate replace to="/home" />} />
    </Routes>
```

**Comment by Lukas742** [comment]
Hello @axeladam 

thanks for pointing this out! I have opened a [PR](https://github.com/SAPDocuments/Tutorials/pull/7218) that will fix this. It seems that this was overlooked during the last refactoring of the tutorial.
