### ISSUE TITLE
Get Started to Collaborate in SAP Business Application Studio

### ISSUE THREAD

**Issue by CJSwift** [sap-tutorials/Tutorials#7220]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-collaborative-database-development-1.html
--------------------------

Step 6 "SQL" is included at the start of the command, but to my knowledge is not needed for use, or for the question at the end of the tutorial

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
