### ISSUE TITLE
Basic Data Modeling with a Graphical View

### ISSUE THREAD

**Issue by ERibe3** [sap-tutorials/Tutorials#7224]
Group: https://developers.sap.com/group.data-warehouse-cloud-data-modeling.html
--------------------------

Write here how you think we can improve the tutorial ...

I would like to be able to download the same .csv tables that are being used in the tutorial so I can use them to perform the exercises.

Is there any way that you can send me these files or make them available in the tutorial just like in the [Get Ready for Your SAP Data Warehouse Cloud Trial Mission ](https://developers.sap.com/tutorials/data-warehouse-cloud-1-begin-trial.html) ?

**Comment by MichaelCzcz** [comment]
@ERibe3 Thanks for your feedback. Kindly specify the tutorial(s) in this group to which you are referring.

**Comment by ERibe3** [comment]
Hello Michael 

The tutorial which I was referring to is the [Basic Data Modeling with a Graphical View](https://developers.sap.com/group.data-warehouse-cloud-data-modeling.html) but it would be useful to have these files available in the following tutorials as well:

[Introduction to Data Preparation in SAP Data Warehouse Cloud](https://developers.sap.com/group.data-warehouse-cloud-data-preparation.html)
[Create Hierarchies with SAP Data Warehouse Cloud](https://developers.sap.com/group.data-warehouse-cloud-hierarchies.html)
[Data Modeling for Business with SAP Data Warehouse Cloud](https://developers.sap.com/group.data-warehouse-cloud-data-modeling-business.html)

**Comment by rashidabdulrahiman** [comment]
Hello @ERibe3. Thanks for your input!

The tutorials that you have mentioned aim to teach you the concept of how to perform the action with SAP Data Warehouse Cloud. It is sadly not possible to provide you with the very same datasets.

The [Get Ready for Your SAP Data Warehouse Cloud Mission](https://developers.sap.com/tutorials/data-warehouse-cloud-1-begin-trial.html) is a handheld tutorial group that is supposed to guide you through with the very same dataset.

What you could do is try the capabilities you mentioned with the [SAP Data Warehouse Cloud Sample Data](https://github.com/SAP-samples/data-warehouse-cloud-content) provided on the website.

I hope this helps. Thanks!

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
