### ISSUE TITLE
Subscribe to the Low-Code / No-Code Service in SAP BTP

### ISSUE THREAD

**Issue by AmauryVanEspen** [sap-tutorials/Tutorials#7227]
Tutorials: https://developers.sap.com/tutorials/appgyver-subscribe-service.html
--------------------------

Hello
according to [what's new](https://help.sap.com/doc/43b304f99a8145809c78f292bfc0bc58/Cloud/en-US/98bf747111574187a7c76f8ced51cfeb.html?from=2021-10-14&to=2021-10-14&search=SAP%2520BTP%2520Trial%2520Subaccounts%2520on%2520eu10)

eu10 is no longer available for SAP BTP
Could you please provide a workaround ?
Thank you
Amaury

**Comment by thecodester** [comment]
For now, you can do the same tutorial on the community edition: https://appgyver.com/

@heytombeck Can you comment about availability of AppGyver in BTP?
