### ISSUE TITLE
Add an API Proxy to a Product

### ISSUE THREAD

**Issue by spassaro80** [sap-tutorials/Tutorials#7231]
Tutorials: https://developers.sap.com/tutorials/hcp-apim-create-product.html
--------------------------

![image](https://user-images.githubusercontent.com/43064539/142869664-f8aecf6e-98cf-4cde-9636-fe52e62b7e11.png)

I perform all the steps but an "Unable to publish Product" message appears each time I try to publish the product.

**Comment by JosephLiuBin** [comment]
See https://answers.sap.com/questions/13426076/cant-publish-product-in-api-management.html which might help @spassaro80

**Comment by spassaro80** [comment]
Thank you so much!! I've been able to finally publish the product. Definitely, there's a missing step in the tutorial, it should warn to register as a developer in SAP API Business Hub before trying to publish the product.
