### ISSUE TITLE
Create a Resource Group and Connect AWS S3 Object Store to SAP AI Core (Postman)

### ISSUE THREAD

**Issue by SCHELLK** [sap-tutorials/Tutorials#7235]
Tutorials: https://developers.sap.com/tutorials/ai-core-aiapi-postman-resource.html
--------------------------
Hi,
Step 3 you consider that developers are using a windows machine, but what about Mac/Linux? They cannot use the S3 Browser and and need to find there own way of uploading data to s3. 

Would be great to improve it. 

Thanks and best regards,
Katharina

**Comment by LunaticMaestro** [comment]
@SCHELLK . Thanks for the request. We have update the tutorials. You may now find options for Mac/Linux OS as well. Please select the proper tab in the step in context.
![image](https://user-images.githubusercontent.com/38010046/145413440-59bb13bd-723c-4d3f-860f-ba5c25f305a9.png)

Lets us know if you are still facing any issues.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
