### ISSUE TITLE
Create a Resource Group and Connect AWS S3 Object Store to SAP AI Core (Postman)

### ISSUE THREAD

**Issue by SCHELLK** [sap-tutorials/Tutorials#7236]
Tutorials: https://developers.sap.com/tutorials/ai-core-aiapi-postman-resource.html
--------------------------

Hi,
Step 5 confuses me. You refer here to "COLLECTIONS>POST create objects store" which I cannot find in my AI API Postman collection. So I do not know which API call I should do here. 
 
![Screen Shot 2021-11-23 at 09 55 32](https://user-images.githubusercontent.com/20700614/142995067-b4fc51d0-8178-4f20-876a-d8d9d877dd87.png)

Best regards,
Katharina

**Comment by LunaticMaestro** [comment]
Hi Katharina,
Thanks for reaching out, below is the screenshot where you will find the endpoint in the collections.
![image](https://user-images.githubusercontent.com/38010046/143176285-c4973855-28f8-4c11-a5e1-ccb8a3cb7d3e.png)

We are sorry for the wrong directions out there. We will fix them.
Thank you again for pointing out the mistake. If encounter such error, you can always create you own REST API call with the endpoint provided in the same step.
