### ISSUE TITLE
Configure Object Pages Using SAP Fiori Tools

### ISSUE THREAD

**Issue by nicogeburek** [sap-tutorials/Tutorials#7241]
Tutorials: https://developers.sap.com/tutorials/fiori-tools-configure-object-pages.html
--------------------------

Hi there,
I just wanted to point out that https://sapes5.sapdevcenter.com/sap/opu/odata/sap/SEPMRA_PROD_MAN/ returns empty data for the `SEPMRA_C_PD_ProductSalesData` entity. Therefore, if users connect to the remote service (don't use the mockserver) the steps 3-7 don't really work / no data will be displayed.

**Comment by cjbernal** [comment]
Hi there,

Thank you for taking the time to point this out. I have taken the feedback to the team and am awaiting their recommendation for what to update it with. 

Kind regards,
Conrad

**Comment by MichaelCzcz** [comment]
@cjbernal Any updates?

**Comment by MichaelCzcz** [comment]
@nicogeburek Does this solve the issue for you?

**Comment by nicogeburek** [comment]
Well, the recommendation works and you can complete the tutorial, but still, that's not how it's meant to be. You could think about rewriting the tutorial to only use the mockserver to avoid any such problems.
I'm fine with closing this ticket as there is a workaround available, but still see an action item on updating the tutorial.

**Comment by MichaelCzcz** [comment]
@cjbernal It's up to you now.
