### ISSUE TITLE
Set Up and Generate a New SAP Fiori App Project

### ISSUE THREAD

**Issue by mperrrin** [sap-tutorials/Tutorials#7252]
Tutorials: https://developers.sap.com/tutorials/fiori-tools-generate-project.html
--------------------------
Hello,
I'm lock on step 2, I have 2 error message.

Panel "APPLICATION MODELER" : "Unable to find relevant SAP Fiori Tools project".
![image](https://user-images.githubusercontent.com/50703110/143596342-f11e4209-6c9f-4237-a1fd-a22cd63453be.png)
Panel "SAP SYSTEMS" : "No SAP systems found".
![image](https://user-images.githubusercontent.com/50703110/143596404-bd2d19c8-a424-4d3e-a169-7439963ed98e.png)

Some configuration missing but I don't where. I check again tuto but any information about that.
Thanks a lot for your help.
BR, Marc

**Comment by cjbernal** [comment]
Hi Marc,

Step 2 of that tutorial asks users to use the Application Generator, rather than the Application Modeler. Could you please try the `Fiori: Open Application Generator` command in the command palette and then follow the steps? That should allow you to create a project that you can later see in the Application Modeler if needed :-) 

Kind regards,
Conrad (SAP UX Engineering)

**Comment by mperrrin** [comment]
Hello Conrad,Thanks for answer.Unfortunately, nothing happen in Visual Studio when I choose option "Fiori: Open Application Generator".Attached : a video that show you the behavior.Hope it can help.BR, Marcenvoyé : 29 novembre 2021 à 19:52de : Conrad Bernal ***@***.***>à : SAPDocuments/Tutorials ***@***.***>cc : mperrrin ***@***.***>, Author ***@***.***>objet : Re: [SAPDocuments/Tutorials] Set Up and Generate a New SAP Fiori App Project (Issue #7252) Hi Marc,Step 2 of that tutorial asks users to use the Application Generator, rather than the Application Modeler. Could you please try the Fiori: Open Application Generator command in the command palette and then follow the steps? That should allow you to create a project that you can later see in the Application Modeler if needed :-)Kind regards, Conrad (SAP UX Engineering)—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cjbernal** [comment]
Hi Marc,

Unfortunately, I don't see a video attachment. Would you mind trying again? Perhaps directly in GitHub? There may have been an issue with the email response.

Thanks and regards,
Conrad

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
