### ISSUE TITLE
Connect SAP HANA Database in SAP HANA Cloud to Python

### ISSUE THREAD

**Issue by MartinStenzig** [sap-tutorials/Tutorials#7258]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-python-analysis-multimodel-1.html
--------------------------
In step 5 there is a typo: The current line to import ConnectionContext looks like this: 
from hana_ml.dataFrame import ConnectionContext

In order to work, the 'f' in dataFrame must be lowercase.

**Comment by VijayKrishnanSR** [comment]
Hi,
thank you for pointing out the typo. The corrections will soon be updated. I hope that the tutorial was helpful.

BR,
Vijay

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
