### ISSUE TITLE
Train Execution of ML Model (Postman)

### ISSUE THREAD

**Issue by kannankumar** [sap-tutorials/Tutorials#7263]
Tutorials: https://developers.sap.com/tutorials/ai-core-aiapi-postman-train.html
--------------------------

Write here how you think we can improve the tutorial ...

In Step 2: API to register train dataset as artifact:
Mentions this:
> IMPORTANT: DO NOT end url in the Body with forward slash.

However screenshot shows url ending with forward slash.
![Screenshot](https://developers.sap.com/tutorials/ai-core-aiapi-postman-train/_jcr_content.github-proxy.1637052320.file/img/postman/call-artifact.png)

Did I misunderstand something or does the screenshot need to be changed?

**Comment by LunaticMaestro** [comment]
@kannankumar 
Thanks for pointing out mistake. The problem lies with the screenshot. We will update the screenshot shortly.

Regards.

**Comment by LunaticMaestro** [comment]
@MichaelCzcz You may close this issue, the contents had been update in the PR https://github.com/SAPDocuments/Tutorials/pull/7295
