### ISSUE TITLE
Create Graph Workspace Visualization in SAP HANA Cloud, SAP HANA Database

### ISSUE THREAD

**Issue by MartinStenzig** [sap-tutorials/Tutorials#7265]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-python-analysis-multimodel-2.html
--------------------------
I like the tutorial and wish I could follow it through to the end, but I have major challenges getting the keppler python package to work on windows. Usually running everything in the linux sub system does work well, but keppler seems to be a special animal.   So even after 2 days of trying to to install the Jupyter notebooke extension, I am giving up now, unless you have a good idea. I assume you developed the scenario on a mac?

**Comment by VijayKrishnanSR** [comment]
Hi,
thank you for the feedback. I will get back to you on this after consulting with the products experts.

BR,
Vijay

**Comment by fath-markus** [comment]
Hej Martin,
the scenario was developed on windows and I can remember challenges when installing kepler in my environment. I think the whole stack was a little sensitive to installation order. What I did was: geopands (which includes shapely), kepler, hana-ml. Don't ask me why, but this worked for me. You may also want to look at the [hana-ml FAQs](https://help.sap.com/doc/1d0ebfe5e8dd44d09606814d83308d4b/2.0.05/en-US/html/hana_ml.faq.html), especially 3 and 4.
Hope that helps!
Regards, Markus

**Comment by MichaelCzcz** [comment]
@VijayKrishnanSR Any updates?

**Comment by VijayKrishnanSR** [comment]
No further updates from my side.

**Comment by MichaelCzcz** [comment]
@VijayKrishnanSR I have closed it, but you could also have closed it.
