### ISSUE TITLE
Set Up SAP Business Application Studio for Development

### ISSUE THREAD

**Issue by emildinchev** [sap-tutorials/Tutorials#7271]
Tutorials: https://developers.sap.com/tutorials/appstudio-onboarding.html
--------------------------
I think that there must be a new step between steps 2.1 and 2.2, showing the subscription for SAP Business Application Studio and "Go to Application" context menu, because some newcomers will wonder from where to launch it.

**Comment by raz-korn** [comment]
Hi @emildinchev ,

There are several ways to launch BAS.
In this tutorial we show the most friendly way for trial users.
Going through the cockpit > GA > space > subscription is outside the scope of this tutorial.

Regards - Raz

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
