### ISSUE TITLE
Improve User Experience of the List and Detail Page

### ISSUE THREAD

**Issue by emildinchev** [sap-tutorials/Tutorials#7279]
Tutorials: https://developers.sap.com/tutorials/sapui5-101-improve-user-experience.html
--------------------------
The tutorial itself is very useful. I tried to extend it and I have deployed the app to my trial account.
The problem is that the deployed app doesn't work as expected and the list of product is empty.
At the same time, when I test the app from the SAP Business Application Studio, everything is working fine.

Best regards,
Emil

**Comment by cjbernal** [comment]
@MichaelCzcz As Emil is an SAP colleague, I have connected him with our team to resolve the issue.
