### ISSUE TITLE
Add NativeScript Plugins in an MDK App

### ISSUE THREAD

**Issue by tobiashofmann** [sap-tutorials/Tutorials#7280]
Tutorials: https://developers.sap.com/tutorials/cp-mobile-dev-kit-nativescript-geolocation.html
--------------------------

Regardin step 3: "You will add this registered control in a Form Cell page"

Is it really a form cell page? I have created a new page using form cell and I cannot add the Static Key Value container control to it. In the container section I can only select "Section". 

Using a section page, I can add the static key value container.

**Comment by jitendrakansal** [comment]
@tobiashofmann  that is typo, will fix it. 
thanks.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
