### ISSUE TITLE
Create A New Welcome Card - Mobile card Not visible in Mobile App - US Region

### ISSUE THREAD

**Issue by i353590** [sap-tutorials/Tutorials#7296]
Tutorials: https://developers.sap.com/tutorials/cp-mobile-cards-welcome.html
--------------------------

The mobile card is not loading in the mobile app after creating the booster welcome card in the US region. (The card subscription was successful, tried again after unsubscribing and subscribing again).
In the activity log, it says failed to load the card.
Please check the issue.

Labels to be attached:
Sprint Label: SCPTest-2112A
Prio: high-prio
Scenario label: SCPTest-mcard
Landcape Label: SCPTest-trial2

Thanks,
Shubham

**Comment by SamiLechner** [comment]
this looks like a duplicate to https://github.com/sap-tutorials/Tutorials/issues/17985

**Comment by MichaelCzcz** [comment]
@SamiLechner If this issue really is a duplicate, please close it. Thank you.
