### ISSUE TITLE
Create A New Welcome Card - The Registration in Mobile app is failing after creating welcome card

### ISSUE THREAD

**Issue by i353590** [sap-tutorials/Tutorials#7297]
Tutorials: https://developers.sap.com/tutorials/cp-mobile-cards-welcome.html
--------------------------
Hello,

The registration of the mobile application is failing after creating the First Mobile card in AP Region
After scanning the QR generated for registering the mobile device, it gives the error: Registration Failed
Please refer to the screenshot:

![image](https://user-images.githubusercontent.com/66831161/145203340-98fb922b-0b6a-49a7-8cd8-ca4ed8e39b53.png)

Labels to be attached:
Sprint Label: SCPTest-2112A
Prio: high-prio
Scenario label: SCPTest-mcard
Landcape Label: SCPTest-trial3

Thanks,
Shubham

**Comment by SamiLechner** [comment]
this looks like a duplicate to https://github.com/sap-tutorials/Tutorials/issues/17985

**Comment by MichaelCzcz** [comment]
@SamiLechner If this issue really is a duplicate, please close it. Thank you.
