### ISSUE TITLE
Enhance Behavior With Action and Validation

### ISSUE THREAD

**Issue by VanitaDhanagar** [sap-tutorials/Tutorials#7298]
Tutorials: https://developers.sap.com/tutorials/abap-environment-behavior-action.html
--------------------------

The screenshot need to be updated as below ,
Step 9 ..point 2 :
Old:

![image](https://user-images.githubusercontent.com/80330660/145208798-3bd69d71-b771-4cf9-a128-26a93b218e33.png)

New ::
![image](https://user-images.githubusercontent.com/80330660/145208696-e8a42afe-33b0-4f0c-b1d4-87519a9c2161.png)

Lables ::
SCPTest-2112A
SCPTest-trial2
Low-Prio
SCPTest-fabap

Regards,
Vanita

**Comment by mervey45** [comment]
Hi @MichaelCzcz ,

I created following PR: #7809. Can you merge?

Thank you.

Best regards, 
Merve
