### ISSUE TITLE
Add Views and Define Routes to Access Them

### ISSUE THREAD

**Issue by JesperWessel** [sap-tutorials/Tutorials#7303]
Tutorials: https://developers.sap.com/tutorials/sapui5-101-add-routing.html
--------------------------

When following step 1.2 passing in the code I get a warning:
The "StandardListItem" class can't have an empty ID attribute when flexEnabled is "true".UI5 Language Assistant(1012)

If I add a id to it, and the rest of the code in the tutorial. The Web app failes in run.

**Comment by cjbernal** [comment]
Hi Jesper,

I'm sorry to see you're having an issue. I have forwarded this to my team to see who can potentially help you best. Thank you for your patience.

Kind regards,
Conrad

**Comment by nicogeburek** [comment]
Hi @JesperWessel & @cjbernal,
The Tutorial has been updated since and is now using stable IDs. I know should work as expected.
BR, Nico
