### ISSUE TITLE
Configure Business Rules, Workflow and Process Visibility

### ISSUE THREAD

**Issue by tschalcktwm** [sap-tutorials/Tutorials#7309]
Tutorials: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-2-configure.html
--------------------------

Hello,

I am stuck at step 2 of the tutorial when trying to import the Equipment Determination rules from SAP API Business Hub. I get a Bad Gateway when trying to import the rule. I checked the BUSINESSRULES_APIHUB destination and I am not using the 2 Factor Authentication but the basic one. I was also able to successfully log to api.sap.com with my user and password.

**Comment by ArchanaShukla** [comment]
Hello colleagues,
(a) Check if  you  have changed the password in this APIHub destination, (b) Login once to api.sap.com

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
