### ISSUE TITLE
Set Up SAP Fiori Tools in Your Development Environment

### ISSUE THREAD

**Issue by leinadavlis** [sap-tutorials/Tutorials#7310]
Tutorials: https://developers.sap.com/tutorials/fiori-tools-vscode-setup.html
--------------------------

In the Tutorial is missing the installation of NODE.JS to execute the next step. When I tried to execute the Application Generator, its cannot showed up because of this.

**Comment by cjbernal** [comment]
Hi Leina,

Sorry for any potential confusion. The installation of Node.js is mentioned as the 3rd bullet point in the prerequisites: https://developers.sap.com/tutorials/fiori-tools-vscode-setup.html

Were you able to get the installation done with no issues? If there is a cluster of learners struggling with the step, then we may add more detail. 

Kind regards,
Conrad

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
