### ISSUE TITLE
Configure Business Rules, Workflow and Process Visibility

### ISSUE THREAD

**Issue by MaxKuz52** [sap-tutorials/Tutorials#7311]
Tutorials: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-2-configure.html
--------------------------
Step 8
![Error](https://user-images.githubusercontent.com/95860511/145585833-99a16f56-e31d-40e7-9008-94f0151e6d2e.PNG)

**Comment by ArchanaShukla** [comment]
Hello MaxKuz,
Can you please explain the issue with error in English.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
