### ISSUE TITLE
Create Destination for SAP API Management Service

### ISSUE THREAD

**Issue by tschalcktwm** [sap-tutorials/Tutorials#7312]
Tutorials: https://developers.sap.com/tutorials/cp-apim-sales-tracker-create-destination.html
--------------------------

What does <yourP#> when creating the destination to https://<yourP#>trial-trial.apim1.hanatrial.ondemand.com ?
I tried with my SUser but it is returning the following error message when checking the connexion: 
Connection to "API_Portal_Trial" established. Response returned: "404: Not Found"
Also in the next tutorial when trying to set the API_Portal_Trial destination for SAP Mobile Cards, I cannot see the destination created before. 

I am running the tutorial on SAP BTP Trial and not on SAP Cloud Platform. Also this is the CF environment, not the Neo one. Maybe this is the reason why I cannot go further ? 

Thanks in advance

**Comment by jmmargo** [comment]
This tutorial will soon be deprecated.  Thank you.
