### ISSUE TITLE
Add Transactional Behavior to Your Core Data Services

### ISSUE THREAD

**Issue by Mupek** [sap-tutorials/Tutorials#7314]
Tutorials: https://developers.sap.com/tutorials/abap-environment-transactional-enablement.html
--------------------------

Step 4: Create behavior implementation
In this step eclipse context menu doesn't have the option you ask us to use .
Only option is from souce code to go on the class name and use quick fix.
SAP system is dock based 
Eclipse includes also latest updates 12.12.2021
SAP_BASIS	754
SAP_ABA	75E
SAP_GWFND	754
SAP_UI	754
ST-PI	740
SAP_BW	754
UIBAS001	500
MDG_FND	804
S4FND	104
DMIS	2011_1_731

**Comment by mervey45** [comment]
Hi @MichaelCzcz ,

I created following PR: #7809. Can you merge?

Thank you.

Best regards, 
Merve
