### ISSUE TITLE
Create an SAP Fiori Elements-Based UI

### ISSUE THREAD

**Issue by toddmfisher** [sap-tutorials/Tutorials#7325]
Tutorials: https://developers.sap.com/tutorials/btp-app-create-ui-fiori-elements.html
--------------------------

Instructions say to copy risk-service-ui.cds to get annotations, but error occurs because the Fiori app generator creates the @LineItem and @Facet annotations for the RiskService.Risk in the annotations.cds file.  I had to comment the annotations from the annotations.cds to get past the error
[issue.docx](https://github.com/SAPDocuments/Tutorials/files/7729824/issue.docx)
.

**Comment by manjuX** [comment]
Hi,

Could you share some information about the versions of the Fiori app generator and the output of `cds v`?
I worked on the tutorial and using the following versions doesn't produce this outcome.

```
@sap/cds: 5.7.4
@sap/cds-compiler: 2.11.4
@sap/cds-dk: 4.7.2
@sap/cds-foss: 3.0.0
Node.js: v16.13.1
cpapp: 1.0.0
```
I do have all the updates to VS Code applied.

Best Regards,
Manjunath

**Comment by iwonahahn** [comment]
Hi @toddmfisher, 

The issue is related to a change in the Template Wizard. See also my answer in the [community](https://answers.sap.com/answers/13557728/view.html). The tutorial is now updated to avoid this issue in the future.

Best regards,
Iwona
