### ISSUE TITLE
Get an Account on SAP BTP to Try Out Free Tier Service Plans

### ISSUE THREAD

**Issue by lineker** [sap-tutorials/Tutorials#7326]
Tutorials: https://developers.sap.com/tutorials/btp-free-tier-account.html
--------------------------

"Using Free Service Plans" link brings to a page that shows "403: You don’t have rights to view this page."

**Comment by AnnikaGonnermann** [comment]
Dear @lineker , thanks for your comment and apologies for the delay. Your comment got swallowed up by the Christmas break and has ever since been neglected by me! Nevertheless, we appreciate you taking the time to report the issue. It has been fixed now!

Best
Annika
