### ISSUE TITLE
Configure Business Rules, Workflow and Process Visibility

### ISSUE THREAD

**Issue by pjcools** [sap-tutorials/Tutorials#7345]
Tutorials: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-2-configure.html
--------------------------
Step 3: Import business rules from API Business Hub

Write here how you think we can improve the tutorial ...

When I try and deploy the Equipment Determination Rules I get the following error. Because the rules are coming from API Business Hub I cannot change the content but it does look like one of the fields (Employee.isFullTimeEmployee) is not compatible. 

![image](https://user-images.githubusercontent.com/38389079/147016341-e62efc21-ea6c-4dbe-a4fb-79d1cb9d9992.png)

Please fix so I can finish the tutorial. 

Kind Regards
Phil Cooley

**Comment by pjcools** [comment]
Hi

Just looking for an update on this issue so I can complete the tutorials as well as the openSAP workflow management course by the end of Jan 22. 

thanks
Phil

**Comment by ArchanaShukla** [comment]
Hello Phil,
This is already fixed and available, you can already import the updated version and deploy.
