### ISSUE TITLE
Set Up Integration Suite Trial

### ISSUE THREAD

**Issue by jpotts-sap** [sap-tutorials/Tutorials#7350]
Tutorials: https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html
--------------------------

At the end of Step 3: Provision the capabilities it says, "IMPORTANT: Before you proceed to Step 5, please wait for all the capabilities to be activated." This should be changed to "Before you proceed to Step **4**".  You can't run the booster until all the capabilities are provisioned. I found this out the hard way when my Integration Suite failed to complete the provisioning (it's been 24 hours). I thought, maybe I need to proceed with Step 4 and that will allow the provisioning to complete. Nope. Got an error message saying that it couldn't create the service instance because the capabilities weren't activated.

As an FYI, I can't even ask a question on the SAP Community page because it can't retrieve any of the SAP managed tags and you can't submit a question without at least one. So, right now, I'm screwed. I can't create the integration suite and I can't find out how to fix the problem.

**Comment by Karunaharan** [comment]
Hello @jpotts-sap,
Totally agree with your first part. I will update the tutorial to make the changes you suggested.

On the second part, I did check from my side. The SAP managed primary tags are retrievable. Users have posted questions in the community as latest as an hour back. Could have been an intermittent issue. Please try next time when you face an issue.

Regards,
Karuna
