### ISSUE TITLE
Develop and Run SAP Fiori Application With SAP Business Application Studio

### ISSUE THREAD

**Issue by i353590** [sap-tutorials/Tutorials#7351]
Tutorials: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html
--------------------------

https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html#:~:text=can%20o%20following%20steps

please note that the spelling of 'do' is mistyped as 'o' only. Also, there should be a space after colon .

Thanks,
Shubham

**Comment by mervey45** [comment]
Hi @MichaelCzcz ,

I created following PR: #7809. Can you merge?

Thank you.

Best regards, 
Merve
