### ISSUE TITLE
Develop and Run SAP Fiori Application With SAP Business Application Studio

### ISSUE THREAD

**Issue by mleeraar** [sap-tutorials/Tutorials#7354]
Tutorials: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html
--------------------------

The part in step 5.2 where I have to open the Fiori: Open Application Generator just shows a blank page instead of the floorplan selection.

**Comment by mleeraar** [comment]
I was using Safari first, now I tried Firefox but the problem still remains..

**Comment by mervey45** [comment]
Hi @mleeraar ,

did you type in  **Fiori: Open Application Generator**? If yes, can you send me a screenshot?

Thank you.

Best regards, 
Merve

**Comment by mleeraar** [comment]
Hi Merve,

Yes I did. The screen stays blank. This happens on my MacBook in Safari, Chrome and Firefox.
I later tried it in windows and in the Edge browser it works there. But I thought Chrome and Firefox were also supported?


Met vriendelijke groet,

Marcel Leeraar

**Comment by mervey45** [comment]
Hi @mleeraar ,

we support all browsers, normally this should not happen. And your browsers are up to date?

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
