### ISSUE TITLE
Subscribe to the Low-Code / No-Code Service in SAP BTP

### ISSUE THREAD

**Issue by goalset28** [sap-tutorials/Tutorials#7355]
Tutorials: https://developers.sap.com/tutorials/appgyver-subscribe-service.html
--------------------------

Write here how you think we can improve the tutorial ...

Your guide is based on EU10 Data center
But From Oct 10th, EU10 doesn't  not accept for new subscription .

**Comment by heytombeck** [comment]
Hello - sorry for the slow reply. The service is currently still only available on EU10, however you can create a free account on www.appgyver.com as a replacement. While the buttons and colors may differ in places, the barcode scanning app can still be created. I hope that helps.

**Comment by thecodester** [comment]
@heytombeck If you haven't already, can you add this comment to the tutorial at the start? Thanks.
