### ISSUE TITLE
Create Business Configuration for Factory Calendar

### ISSUE THREAD

**Issue by gregorwolf** [sap-tutorials/Tutorials#7356]
Tutorials: https://developers.sap.com/tutorials/abap-environment-service-binding.html
--------------------------

Step 4: Enable log changes

The screenshot shows the changelog to be set for ZCAL_HOLITXT_XXX. The instructions tell you that the settings needs to be done for ZCAL_HOLIDAY_XXX. What is correct?

**Comment by mervey45** [comment]
Hi @gregorwolf ,

the text and screenshot are missleading, we'll update it as soon as possible. You can select database table ZCAL_HOLITXT_XXX as databasetable and technical table setting to enable the log changes.
![image](https://user-images.githubusercontent.com/27953324/148242447-ac0d0a8b-febc-48b3-b474-44b312230ac8.png)


Best regards, 
Merve

**Comment by mervey45** [comment]
Hi @MichaelCzcz,

I created following PR: #7809. Can you merge?

Thank you.

Best regards,
Merve
