### ISSUE TITLE
Create a CAP Business Service with Node.js Using Visual Studio Code

### ISSUE THREAD

**Issue by VolkerSaggau** [sap-tutorials/Tutorials#7359]
Tutorials: https://developers.sap.com/tutorials/cp-apm-nodejs-create-service.html
--------------------------

Write here how you think we can improve the tutorial ...

Please update the respective libs:

(base) d055092@C02XT13BJGH6 ~ % npm i -g @sap/cds-dk    
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.

**Comment by iwonahahn** [comment]
Hi @VolkerSaggau,

Thank you for this feedback. The dev colleagues are already working on it. It should be fixed asap.

Best regards,
Iwona
