### ISSUE TITLE
Create Data Model and Lock Object in SAP BTP, ABAP Environment

### ISSUE THREAD

**Issue by monikaalis** [sap-tutorials/Tutorials#7360]
Tutorials: https://developers.sap.com/tutorials/abap-environment-lock-object.html
--------------------------

Hello,
I cannot save the data definition Z_I_ROOM_384 - Use of CDS ENTITY I_BUSINESSUSERBASIC is not permitted.
code (step 6 of this tutorial):
...
define root view Z_I_ROOM_384 as select from zroom_384 as room
association [0..1] to I_BusinessUserBasic as _SAPSysAdminDataChangeUser on _SAPSysAdminDataChangeUser.UserID = room.lastchangedbyuser
...
error:
Use of CDS ENTITY I_BUSINESSUSERBASIC is not permitted.
Use of element USERID of CDS ENTITY I_BUSINESSUSERBASIC is not permitted.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
