### ISSUE TITLE
Create Data Model and Lock Object in SAP BTP, ABAP Environment

### ISSUE THREAD

**Issue by ivanmir** [sap-tutorials/Tutorials#7361]
Tutorials: https://developers.sap.com/tutorials/abap-environment-lock-object.html
--------------------------

The Data Definition on step 6.5 contains an invalid association statement. It uses the I_BusinessUserBasic which is (according to the code validation) not permitted in cloud environment. 

Use of CDS Entity I_BusinessUserBasic is not permitted

I've removed the association definition and I was able to activate the code. 
However, I'm not sure if this association will be required later on the tutorial.

Best regards,
Ivan

**Comment by mervey45** [comment]
Hi @ivanmir ,

in which system are you doing this tutorial? Is it in the trial system? If yes, then it won't work, because the trial system is limited.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
