### ISSUE TITLE
Create Behavior and Service in SAP BTP, ABAP Environment

### ISSUE THREAD

**Issue by ivanmir** [sap-tutorials/Tutorials#7362]
Tutorials: https://developers.sap.com/tutorials/abap-environment-behavior-definition.html
--------------------------

On step 2.4 the class is named lcl_handler whereas the created class already comes with the same handler already defined as lhc_room.
The same applies to the class lcl_saver which is also already defined as lsc_Z_I_ROOM_XXX.

On step 3.1 the Data Definition named Z_ROOM_XX doesn't exist as it was created as Z_I_ROOM_XXX.

Best regards,
Ivan

**Comment by mervey45** [comment]
Hi @ivanmir ,

thank you for your feedback, we'll update Z_I_ROOM_XXX as data definition in step 3.1.

Best regards, 
Merve
