### ISSUE TITLE
Get an Account on SAP BTP to Try Out Free Tier Service Plans

### ISSUE THREAD

**Issue by luissismeiro** [sap-tutorials/Tutorials#7364]
Tutorials: https://developers.sap.com/tutorials/btp-free-tier-account.html
--------------------------

I didn't receive my credentials mentioned in Step 7: Welcome to SAP BTP. 
I think that we need a way to request them again.

**Comment by AnnikaGonnermann** [comment]
Dear @luissismeiro, thanks for reaching out and apologies for the delay. I've reached out to the respective team and will get back to you as soon as possible with my reply!
Best
Annika

**Comment by luissismeiro** [comment]
Hello @AnnikaGonnermann, I received the credentials on 05.01.2022, a few days after the registration.

BR,
Luís

**Comment by AnnikaGonnermann** [comment]
Hey @luissismeiro, what wonderful news, thanks for confirming. I'm closing this issue now! Enjoy exploring SAP Business Technology Platform!
