### ISSUE TITLE
Learn about SAP Event Mesh

### ISSUE THREAD

**Issue by fsebbane** [sap-tutorials/Tutorials#7366]
Tutorials: https://developers.sap.com/tutorials/cp-enterprisemessaging-learn-messaging-concepts.html
--------------------------
Issue:
The first question: 
    What communication options does SAP Business Technology Platform offer to connect applications, services and systems?
>> No combination answer fit

Write here how you think we can improve the tutorial ...
I just got through the Introduction and in my opinion it is very well done.

**Comment by pradeeppanda-sap** [comment]
Hi,
  First of all thanks for your opinion.
 Regarding your question on connection with SAP BTP, what we can convey here is, SAP Event Mesh which is a service in BTP provides MQTT, AMQP and REST based end points for services to connect to.  S/4 HANA for example connects with SAP Event Mesh using MQTT protocol.

Hope it answers your question.

**Comment by gregorwolf** [comment]
Dear @pradeeppanda-sap,

I've had the same issue as @fsebbane. I would suggest changing the question from:

> What communication options does SAP Business Technology Platform offer to connect applications, services and systems?

to

> What communication options does SAP Business Technology Platform Event Mesh offer to connect applications, services and systems?

Because as for the current state of the question also RFC and API Calls would be valid answers.

Best Regards
Gregor
