### ISSUE TITLE
Configure Business Rules, Workflow and Process Visibility

### ISSUE THREAD

**Issue by vjvats** [sap-tutorials/Tutorials#7367]
Tutorials: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-2-configure.html
--------------------------
Hi ,

In step 4 - Deploy business rules , I am getting the syntax error in rule when trying to deploy. I imported the rule from API hub, so was not expecting the error. Can you please help to resolve this?

![image](https://user-images.githubusercontent.com/49681932/147826742-3b208b43-3364-48e4-9c9e-e1f694d454e4.png)

![image](https://user-images.githubusercontent.com/49681932/147826872-355dd327-8647-4496-95b5-df2b2fe7d167.png)

Regards
Vijay

**Comment by ArchanaShukla** [comment]
Hello Vijay,
The issue is fixed, you can import the rules again and deploy
