### ISSUE TITLE
Implement the Transport for Your Factory Calendar

### ISSUE THREAD

**Issue by DerGuteWolf** [sap-tutorials/Tutorials#7371]
Tutorials: https://developers.sap.com/tutorials/abap-environment-transport.html
--------------------------

Method get_instance_features uses if_abap_behv=>mk-on / if_abap_behv=>mk-off while the documentation at https://help.sap.com/viewer/923180ddb98240829d935862025004d6/Cloud/en-US/9ee0a7073fef4f889e85862114b85fdd.html uses if_abap_behv=>fc-o-enabled / if_abap_behv=>fc-o-disabled . This is inconsistent.

In order to provide appropriate guidance and to avoid confusion this should be consistent.

**Comment by mervey45** [comment]
Hi @DerGuteWolf ,

thank you for your feedback. I will provide this to our development department.

Best regards, 
Merve
