### ISSUE TITLE
Set Up SAP Data Intelligence, Trial Edition

### ISSUE THREAD

**Issue by Ngugisenior** [sap-tutorials/Tutorials#7512]
Tutorials: https://developers.sap.com/tutorials/dataintelligence-trial-v2-setup.html
--------------------------

SAP Data Intelligence, Trial Edition is not available in SAP Cloud Appliance Library.

**Comment by NikhilD16** [comment]
We are working on it and we will have an update shortly. Thank you.

**Comment by NikhilD16** [comment]
Teams are still working on resolving the issue but I don't have a specific timeline. I will keep thread updated as we have an update.

**Comment by NikhilD16** [comment]
The team is testing the solution and we should have an update soon.

**Comment by NikhilD16** [comment]
As of January 31, 2023, the DI Trial CAL image is no longer available. Please contact your account executive to explore different options available to you.

Refer to the blog https://blogs.sap.com/2022/07/14/sap-data-intelligence-trial-edition-3.2/
