### ISSUE TITLE
Build Luigi App with React

### ISSUE THREAD

**Issue by dvankempen** [sap-tutorials/Tutorials#7517]
Tutorials: https://developers.sap.com/tutorials/luigi-app-react.html
--------------------------

Write here how you think we can improve the tutorial ...

Point 3

Next create a new file in react-core-mf/**views** called home.js and paste the following code into it

There is no directory called views. Add the command to create it

mkdir views

**Comment by alexandra-simeonova** [comment]
Hi, thank you for the feedback! The step will be added to the tutorial in the next 1-2 days.

**Comment by alexandra-simeonova** [comment]
Hi, the folder you're referring to in this issue is created here in step 6: https://developers.sap.com/tutorials/luigi-app-basic-setup.html
So it shouldn't be the case that there is no directory called views. 🤔 Maybe it was a different error? However, I can add a reminder in the tutorial about it.
