### ISSUE TITLE
Build Luigi App with React

### ISSUE THREAD

**Issue by dvankempen** [sap-tutorials/Tutorials#7518]
Tutorials: https://developers.sap.com/tutorials/luigi-app-react.html
--------------------------

Write here how you think we can improve the tutorial ...

Next create a new file in react-core-mf/views called home.js and paste the following code into it:

Should be 

Next create a new file in react-core-mf/**src**/views called home.js and paste the following code into it:

**Comment by alexandra-simeonova** [comment]
Hi,

Thank you for creating an issue. I updated the tutorial to say `react-core-mf/src/views `. It should be published today or tomorrow.
