### ISSUE TITLE
Add Rich Enterprise Controls to the User Interface

### ISSUE THREAD

**Issue by srochaudatsap** [sap-tutorials/Tutorials#7520]
Tutorials: https://developers.sap.com/tutorials/sapui5-fiori-cf-fiorify.html
--------------------------

Write here how you think we can improve the tutorial ...

hi, in Step 2: Use the smart filter bar , i found 77 items.
<img width="469" alt="bug" src="https://user-images.githubusercontent.com/64523205/148211022-aae73272-eff4-4f3f-b04b-e06ec6c68c7a.png">

but  you propose 12,18,60 and 3 as answer.

In fact, After click on OK button, we must click on GO button .

Best regards.

**Comment by nicogeburek** [comment]
Thanks for the feedback.
That's right, after clicking "OK" to close the filter window you have to click on "Go" to actually apply the filter. Only then the number of items changes. I will change the wording to hopefully make things clearer.
