### ISSUE TITLE
Connect Your On-Premise System with SAP Cloud Platform, ABAP Environment

### ISSUE THREAD

**Issue by gregorwolf** [sap-tutorials/Tutorials#7955]
Mission: https://developers.sap.com/mission.abap-env-connect-onpremise.html
--------------------------

Currently the subheading of this mission reads like:

> Retrieve data from an on-premise system using an existing BAPI, and OData service, then display it in SAP Fiori elements preview.

as the tutorial does not show how to consume an OData service I would suggest that OData should be removed from there. Maybe it would be worth to migrate the SAP TechEd 2020 Workshop [DEV268 - SAP BTP ABAP Environment Connectivity and Integration](https://github.com/SAP-samples/teched2020-DEV268) to the tutorial so it is kept up-to-date there.

**Comment by julieplummer20** [comment]
Hi Gregor,
Thanks for this heads-up. I will fix this at once.
Re DEV268: I am quite familiar with DEV268, and I think GitHub is a brilliant channel for TechEd workshops.
However, the person updating the text - whether on GitHub or Tutorial Navigator, would me, so it doesn't accelerate anything to migrate the tutorial to GitHub. I have already linked to DEV268 from the tutorial for trial users, so I am minded to leave it where it is.
Thanks for the feedback though.
Best wishes,
Julei.
