### ISSUE TITLE
Display Data from the Northwind Service

### ISSUE THREAD

**Issue by aliceqiou** [sap-tutorials/Tutorials#7957]
Tutorials: https://developers.sap.com/tutorials/sapui5-fiori-cf-display-data.html
--------------------------

In - Mission: Develop a Fiori Launchpad App with Your Own Dev Tools
      - Tutorial: Display Data from the Northwind Service
      - Step 3:
At the second step, the file to be modified should be Products.view.xml, but it states Mainview.view.xml instead which is already modified at step one.
![wrong_view_file](https://user-images.githubusercontent.com/38517866/148497586-a57aa0c1-7859-4f18-b1f7-3cacc7e5681a.PNG)

**Comment by nicogeburek** [comment]
Good catch. You are right. Will adapt it.
