### ISSUE TITLE
SAP HANA XS Advanced, Creating an OData Service with Create Operation and XSJS Exit

### ISSUE THREAD

**Issue by ahmedkhan29789** [sap-tutorials/Tutorials#7960]
Tutorials: https://developers.sap.com/tutorials/xsa-xsodata-create.html
--------------------------

Is it always mandatory to create xsjslib to POST data to xsOData?

**Comment by jung-thomas** [comment]
No not mandatory. But the feature allows you to perform addition validation before the update or control how the update is done. But as long as the target entity is a single table, the generic framework can perform the update/create/delete operation for you without an exit.

**Comment by ahmedkhan29789** [comment]
Thank you very much for your reply, I will try first simply post operation
without xsjslib through Postman using created xsodata service 😊
