### ISSUE TITLE
Create an SAP Cloud Application Programming Model Project for SAP HANA Cloud

### ISSUE THREAD

**Issue by ahmedkhan29789** [sap-tutorials/Tutorials#9461]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-cap-create-project.html
--------------------------

I followed the same steps and at the end when I am trying to run cds to see my JSON data I am getting this error "No or malformed db credentials" Is there any maintenance going in BTP from yesterday?
![image](https://user-images.githubusercontent.com/22063881/148653977-2e58bd59-aa12-4dc7-8c16-8636cc0e7161.png)

Although If I am changing back to sql in package.json( "kind": "sql") it is working and the service giving me the right data

**Comment by jung-thomas** [comment]
If you change the type to SQL then it uses a local SQLite database and doesn't connect to HANA Cloud.  The error says you credentials have a problem. So it would seem something is wrong with the default-env.json. 

The tutorial you mentioned doesn't have you testing the cds yet.  It only takes you up to creating the project.  Are you trying to test before the tutorial tells you to?  Or have you linked to the wrong tutorial and are actually further along? It would help to know how you are testing if not following the tutorial.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
